[cli] Tests
ray-project/ray pull request #10057
Opened 2020-08-12 00:55 UTC by maximsmol

## Why are these changes needed?
Currently the Ray CLI is mostly untested (some very weak tests are in `test_multi_node` and `test_output`). This PR adds tests that check both the old and the new style CLI for return codes and expected output.

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [X] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [X] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [X] This PR is not tested (please justify below)
This IS the tests.

2020-08-12 00:58 UTC, richardliaw commented on python/ray/tests/test_cli.py
> +        r"--------------------",
question - is it appropriate to do this or is it better to have this in a text file?

2020-08-13 17:21 UTC, maximsmol commented on python/ray/autoscaler/aws/node_provider.py
> +                    print('Done listing')
rm

2020-08-13 17:21 UTC, maximsmol commented on python/ray/tests/test_cli.py
> +            r"Done listing",
rm

2020-08-19 23:57 UTC, richardliaw commented on python/ray/tests/test_cli_patterns/test_ray_up_config.json
> +
I've had cases where I made broad changes to cluster YAML files across the code-base. Can we change this to a yaml file just to avoid missing this?

2020-08-20 00:22 UTC, richardliaw requested changes
Left a couple comments. Can you ping me once addressed?

2020-08-20 00:22 UTC, richardliaw commented on python/ray/autoscaler/commands.py
> +            "before bringing down the cluster.")
hm, why support this?

2020-08-20 00:22 UTC, richardliaw commented on python/ray/autoscaler/commands.py
> +            if not _printed_cached_config_warning:
let's use `ray.utils.debug.log_once`

2020-08-20 00:22 UTC, richardliaw commented on python/ray/autoscaler/commands.py
> +            if not _printed_cached_config_warning:
```
if log_once("printed_cached_config_warning"):
    ....

2020-08-20 00:22 UTC, richardliaw commented on python/ray/autoscaler/commands.py
> +    if dump_command_output is None:
this can be "False" too right? Maybe consider: `if not dump_command_output`

2020-08-20 00:22 UTC, richardliaw commented on python/ray/autoscaler/commands.py
> +    cmd_output_util.set_allow_interactive(True)
why set this always to True? how would the user disable this?

2020-08-20 00:22 UTC, richardliaw commented on python/ray/scripts/scripts.py
> +    default=None,
should default to `--dump` right?

2020-08-20 00:22 UTC, richardliaw commented on python/ray/tests/test_cli.py
> +def _unlink_test_shh_key():
can you turn this into a `pytest.fixture`?

2020-08-20 00:22 UTC, richardliaw commented on python/ray/tests/test_cli.py
> +def _setup_popen_mock(commands_mock):
`pytest.fixture`?

2020-08-20 23:03 UTC, richardliaw commented on python/ray/autoscaler/cli_logger.py
> +colorama.init(strip=False)
question - what does this do?

2020-08-20 23:06 UTC, richardliaw commented on python/ray/autoscaler/aws/node_provider.py
> +                            instance.state_reason = {"Message": "n/a"}
TODO: patch this instead

2020-08-21 04:12 UTC, richardliaw commented on python/ray/autoscaler/commands.py
> -
moved to scripts.py

2020-08-21 07:42 UTC, richardliaw commented on python/ray/autoscaler/commands.py
> +    cmd_output_util.set_allow_interactive(True)
nvm makes sense, left a note

2020-08-21 08:38 UTC, richardliaw approved these changes

2020-08-21 08:39 UTC, richardliaw commented on python/ray/autoscaler/commands.py
> +        cmd_output_util.set_allow_interactive(False)
there wasn't a place where we were disabling interactivity.

2020-08-21 08:41 UTC, richardliaw commented on python/ray/autoscaler/subprocess_output_util.py
>              stderr_file = subprocess.DEVNULL
I reverted these changes; I think the behavior as-is is correct and the adjusted version (where if stderr_file is None, stderr_file=stdout_file) is incorrect.

2020-08-21 08:41 UTC, richardliaw commented on python/ray/autoscaler/updater.py
> +            raise click.ClickException(msg)
moved this up here to avoid the `try-catch-all` in commandrunner

2020-08-22 20:29 UTC, merged