[RLlib] Unify GPU handling by RLlib (num_gpus; automate GPU testing).
ray-project/ray pull request #10242
Opened 2020-08-21 16:52 UTC by sven1977

This PR changes the default value of `num_gpus` in the Trainer's config to `None`.
Allowed values:

```
None: Use as many GPUs as are available (this used to be the default behavior anyways for TFPolicy, which never cared about e.g. 
num_gpus=0 and would still run on the GPU if one was available).
0: Do NOT use a GPU, even if one is available. TFPolicy and TorchPolicy used to violate this, causing some confusion amongst users who had force-set this to 0.
[some int]: Use this many GPUs. Error if less are available.
```

Also adds the option of setting an env variable (`RLLIB_FORCE_NUM_GPUS`) to some value to override `num_gpus` inside all RLlib's example scripts to use that many GPUs for upcoming daily GPU testing.
(TODO: Do the same for all test cases.)

## Related issue number

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

2020-08-28 12:05 UTC, sven1977 commented on rllib/utils/test_utils.py
> +FORCED_NUM_GPUS = int(os.environ.get("RAY_FORCE_NUM_GPUS", 0)) or None
+1

2020-09-04 15:34 UTC, sven1977 commented on rllib/agents/trainer.py
> +        # Resolve `num_gpus`=None (default): Set `num_gpus` to as many as we
This is the crux of this PR: How do we figure out, how many GPUs are available if `num_gpus: None`?

2020-09-04 15:35 UTC, sven1977 commented on rllib/policy/torch_policy.py
> +        if ray.get_gpu_ids():
In TorchPolicy: Decide inside Policy constructor, whether to place the Model on the GPU.

2020-09-04 15:36 UTC, sven1977 commented on rllib/examples/attention_net.py
> +from ray.rllib.utils.test_utils import check_learning_achieved, \
Fix all example scripts and Model classes in `examples/model` to work with env var RLLIB_FORCE_NUM_GPUS=[1|0|None].

2020-09-04 15:37 UTC, sven1977 commented on rllib/agents/trainer.py
> -        # Check and resolve DL framework settings.
Framework checks (installations vs config) moved to separate method.

2020-09-04 15:37 UTC, sven1977 commented on rllib/agents/trainer.py
> +    "num_gpus": None,
New default for num_gpus: None -> Figure out GPU placement based on what's available.
Also: num_gpus=0 means: Do NOT use any GPUs.

2020-09-04 18:43 UTC, ericl requested changes
This is a pretty major change. Why not instead simply raise a warning instead if a GPU is present but it is set to zero?

2020-09-04 18:45 UTC, ericl commented
Couple things:
(1) Can you split this into two PRs -- one for the GPU interface change, and the other for the GPU testing? We shouldn't be mixing major API changes with other big code changes.
(2) I was thinking the zero GPU case could be simply a warning in Trainer -- to let the user they had left num_gpus=0 if they didn't mean it. That would be just a couple lines and would not require any changes to the algorithms.

2020-09-09 21:53 UTC, closed without merging