Change default ip address for the dashboard to ipv4
ray-project/ray pull request #10287
Opened 2020-08-24 16:35 UTC by rkooo567

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

2020-08-24 19:28 UTC, wuisawesome approved these changes

2020-08-24 19:31 UTC, wuisawesome requested changes
Can you also change the default parameter in `ray.init` (I that's the most typical way to figure out the default argument in the docs)

2020-08-24 23:27 UTC, mfitton approved these changes

2020-08-24 23:34 UTC, wuisawesome approved these changes

2020-08-25 00:57 UTC, rkooo567 commented
`test_metrics` seems to fail. I will investigate it tomorrow.

2020-08-27 21:43 UTC, merged