[Autoscaler] Reload config
ray-project/ray pull request #10450
Opened 2020-08-31 17:54 UTC by wuisawesome

## Why are these changes needed?

This ensures that available node types is reloaded correctly, which involves moving the loading logic into reload and updating the launch hashes accordingly. 

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

2020-08-31 17:55 UTC, wuisawesome commented on python/ray/tests/test_autoscaler.py
> +        self.lock = threading.Lock()
In practice, this really reduces the amount of race conditions _especially_ when print statements/io are used.

2020-08-31 20:03 UTC, ericl requested changes

2020-08-31 20:03 UTC, ericl commented on python/ray/autoscaler/autoscaler.py
>          self.reload_config(errors_fatal=True)
Can we rename reload_config to `reset()` now that's it doing more stuff?

2020-08-31 20:03 UTC, ericl commented on python/ray/autoscaler/node_launcher.py
> +            available_node_types=config.get("available_node_types"))
We shouldn't include the entire config as part of the launch conf, or you need to relaunch if any config changes. Can you extract just the relevant one?

2020-08-31 20:03 UTC, ericl commented on python/ray/autoscaler/node_launcher.py
> +            available_node_types=config.get("available_node_types"))
Same comment for launch_hash in commands.py

2020-08-31 20:03 UTC, ericl commented
Can you also add unit tests covering the new reload behavior?

2020-09-01 21:36 UTC, ericl approved these changes

2020-09-01 21:37 UTC, merged