Dask-on-Ray: Add Dask-Ray scheduler callbacks.
ray-project/ray pull request #10519
Opened 2020-09-03 01:51 UTC by clarkzinzow

## Why are these changes needed?

This adds callback hooks to the Dask-Ray scheduler, allowing users to hook into the Ray task submission and execution lifecycle. This is very useful for implementing Dask-level progress reporting, diagnostics, caching, etc. See the [feature request](https://github.com/ray-project/ray/issues/10378) and the [Dask docs on custom callbacks](https://docs.dask.org/en/latest/diagnostics-local.html#custom-callbacks) for more details.

## Related issue number

Closes #10378 

## TODOs

- [ ] Add more tests that cover the other callback hooks? Given that those other hooks are primarily for creating side-effects, I'm not sure how to best test them. (They _have_ been tested manually)

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

2020-09-03 01:55 UTC, clarkzinzow commented on python/ray/tests/BUILD
> +        "test_dask_callback.py",
This file is the only actualy change to this file, the rest is due to my Bazel [buildifier](https://github.com/bazelbuild/buildtools/blob/master/buildifier/README.md) autoformatting [plugin](https://github.com/google/vim-codefmt). I was going to remove these formatting changes, but I wanted to gauge the interest in adding buildifier to Ray's formatting suite. We use it internally (at Descartes Labs) and really like it.

2020-09-03 20:37 UTC, clarkzinzow commented
All of the test failures appear to be transient and unrelated to this PR.

2020-09-03 22:52 UTC, stephanie-wang requested changes
This is pretty cool! I could see this being useful for Ray tasks in general too, although we would want to think about what sort of callbacks to allow.

Can you add some documentation for this to the doc/source/dask-on-ray.rst?

2020-09-03 22:52 UTC, stephanie-wang commented on python/ray/experimental/dask/callbacks.py
> +                Run before submitting a Ray task. If this callback returns a
Could you also document the args for these callbacks? Unless these are standard for Dask callbacks (I'm not familiar with that API).

2020-09-03 22:52 UTC, stephanie-wang commented on python/ray/experimental/dask/scheduler.py
> +        (
It might be nice to make this a namedtuple of callbacks, just to reduce verbosity and guard against future changes.

2020-09-06 23:43 UTC, clarkzinzow commented on python/ray/util/dask/callbacks.py
> +CB_FIELDS = tuple("_" + field for field in CBS)
I would really like to _not_ prefix the Ray-specific callbacks with an underscore and instead make the `RayDaskCallback` constructor kwargs (`RayDaskCallback(ray_presubmit=foo)`) and method implementations (`def ray_presubmit(...):`) have the same identifier, but I think that'd deviate too strongly from Dask's custom callback API.

2020-09-06 23:46 UTC, clarkzinzow commented on python/ray/util/dask/callbacks.py
> +                setattr(self, "_" + cb, cb_func)
I sacrificed some readability here to make the `CBS` tuple the source-of-truth for what Ray-specific callbacks exist.

2020-09-08 19:59 UTC, stephanie-wang approved these changes

2020-09-08 19:59 UTC, stephanie-wang commented on python/ray/util/dask/callbacks.py
> +                    deps (dict): The dependencies of this task.
Can you specify what the keys and values are in the dict?

2020-09-08 20:00 UTC, stephanie-wang commented
I'm merging this so that we can include it in Ray v1.0, but feel free to keep iterating in future PRs!

2020-09-08 20:00 UTC, merged

2020-09-09 01:17 UTC, clarkzinzow commented
Thanks @stephanie-wang! 😄