[Placement Group] Capture child tasks by default.
ray-project/ray pull request #11025
Opened 2020-09-25 05:24 UTC by rkooo567

## Why are these changes needed?

This PR does 2 things.
- Turn on the implicit pg capture by default.
- Support an option to turn off this option.

To enable the second option, this is how it works.

- If the capture child task is specified, the receiver configures this context to be true.
- When the receiver submits a new task, we check the worker context and decide whether or not if we want to configure this option.

Missing piece: Documentation (will create another PR since it is already pretty big).

## Related issue number

https://github.com/ray-project/ray/issues/9808

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2020-09-25 20:53 UTC, ericl commented on src/ray/core_worker/context.cc
> +  /// Whether or not if the current task should capture the parent's placement group
```suggestion
  /// Whether or not child tasks are captured in the parent's placement group
```

2020-09-25 20:53 UTC, ericl commented on src/ray/core_worker/context.cc
> +  /// implicilty.
```suggestion
  /// implicitly.
```

2020-09-25 20:53 UTC, ericl commented on src/ray/core_worker/context.cc
> +bool WorkerContext::PlacementGroupCaptureChildTasks() const {
```suggestion
bool WorkerContext::ShouldCaptureChildTasksInPlacementGroup() const {
```

2020-09-25 20:53 UTC, ericl commented on src/ray/core_worker/core_worker.h
> +  bool ShouldCaptureParentPlacementGroup() const {
```suggestion
  bool ShouldCaptureChildTasksInPlacementGroup() const {
```

2020-09-25 20:55 UTC, ericl requested changes
Mostly naming comments

2020-09-25 23:01 UTC, ericl approved these changes

2020-09-27 01:45 UTC, ffbin commented on src/ray/core_worker/context.cc
> +  // If the worker is an actor, we should return the actor's placement group id.
We do not return placement group id?

2020-09-27 01:48 UTC, ffbin commented
@rkooo567 Does Java API need to be modified?

2020-09-27 16:21 UTC, rkooo567 commented
@ffbin Yes. There are some parity to Java APIs from Python APIs, and we should unify them. I believe we also don't have ready API.

2020-09-27 16:22 UTC, rkooo567 commented on src/ray/core_worker/context.cc
> +  // If the worker is an actor, we should return the actor's placement group id.
ah, good catch. Let me fix.

2020-09-28 02:31 UTC, ffbin approved these changes

2020-09-28 02:33 UTC, merged