[Docker] Automagically add "runtime=nvidia"
ray-project/ray pull request #11125
Opened 2020-09-29 22:26 UTC by ijrsvt

## Why are these changes needed?
Users normally need to add `- --runtime=nvidia` to enable GPUs inside of their docker container. This PR makes that obsolete by checking if the nvidia runtime is available and opting to use that.

An alternate solution is to just always add the following to `run_options`:
```
--runtime=`docker info -f '{{.Runtimes.nvidia}}' | grep "nvidia-container-runtime" > /dev/null  && echo "nvidia" || docker info -f  '{{.DefaultRuntime}}'`
```

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2020-09-29 22:27 UTC, ijrsvt commented
cc @ray-project/ray-autoscaler

2020-09-29 22:36 UTC, ericl approved these changes

2020-09-29 22:39 UTC, wuisawesome reviewed
Can you also use the flag in `example-full.yaml` and explain that this sets the `--runtime` flag?

2020-09-29 23:41 UTC, ijrsvt commented
Sounds good @wuisawesome !

2020-09-30 15:23 UTC, wuisawesome approved these changes
lgtm

2020-10-01 01:11 UTC, ericl commented on python/ray/autoscaler/gcp/example-gpu-docker.yaml
> +    disable_automatic_runtime_detection: False
Can you leave this out of the examples? It should be an internal flag that users don't need to use.

2020-10-01 01:12 UTC, ericl commented on doc/source/cluster/autoscaling.rst
> +The ``worker_image`` and ``pull_before_run`` fields override the correpsonding field in the top level ``docker`` section for the node type. The ``worker_run_options`` field is combined with top level
```suggestion
The ``worker_image`` and ``pull_before_run`` fields override the correpsonding field in the top level ``docker`` section for the node type. The ``worker_run_options`` field is combined with top level ``docker: run_options`` field to produce the docker run command for the given node_type. The following configuration is for a GPU enabled node type. Ray will automatically select the Nvidia docker runtime if it is available.
```

2020-10-01 01:13 UTC, ericl requested changes
Just one comment to remove the internal flag.

2020-10-01 01:35 UTC, ijrsvt commented
Ahh, looks like you merged it :) Thanks @ericl

2020-10-01 17:06 UTC, ericl commented on python/ray/autoscaler/aws/example-full.yaml
> +    # Allow Ray to automatically detect GPUs
```suggestion
    # Allow Ray to automatically detect GPUs
```

2020-10-01 17:06 UTC, ericl commented on python/ray/autoscaler/aws/example-full.yaml
> +    # disable_automatic_runtime_detection: False
```suggestion
    # disable_automatic_runtime_detection: False
```

2020-10-01 17:06 UTC, ericl commented on python/ray/autoscaler/aws/example-gpu-docker.yaml
> +    disable_automatic_runtime_detection: False
```suggestion
    disable_automatic_runtime_detection: False
```

2020-10-01 17:06 UTC, ericl commented on python/ray/autoscaler/aws/example-ml.yaml
> +    disable_automatic_runtime_detection: False
```suggestion
    disable_automatic_runtime_detection: False
```

2020-10-01 17:06 UTC, ericl commented on python/ray/autoscaler/azure/example-gpu-docker.yaml
> +    disable_automatic_runtime_detection: False
```suggestion
    disable_automatic_runtime_detection: False
```

2020-10-01 17:06 UTC, ericl commented on python/ray/autoscaler/azure/example-gpu.yaml
> +    disable_automatic_runtime_detection: False
```suggestion
    disable_automatic_runtime_detection: False
```

2020-10-01 17:06 UTC, ericl commented on python/ray/autoscaler/gcp/example-gpu-docker.yaml
> +    disable_automatic_runtime_detection: False
```suggestion
    disable_automatic_runtime_detection: False
```

2020-10-01 17:06 UTC, ericl requested changes
Can you make the changes?

2020-10-01 18:04 UTC, ijrsvt commented
Oh, I didn't realize you wanted it changed from the YAMLs

2020-10-01 19:34 UTC, ericl requested changes
Did you commit the changes? I left the as comments only.

2020-10-01 20:07 UTC, ijrsvt commented
@ericl  🤦‍♂️ 🤦 🤦‍♂️ 🤦 🤦‍♂️ 🤦 🤦‍♂️ 🤦 🤦‍♂️ 🤦 🤦‍♂️ 🤦 🤦‍♂️ 🤦 🤦‍♂️ 🤦 🤦‍♂️ 🤦 🤦‍♂️ 🤦 
Yes i did, but I forgot to _**push**_.

2020-10-01 20:12 UTC, ericl approved these changes

2020-10-02 00:04 UTC, merged