[tune] Trial scheduler interface
ray-project/ray pull request #1160
Opened 2017-10-25 20:26 UTC by ericl

This pulls out an abstract trial scheduler interface for use with HyperBand and Median stopping rule.

@richardliaw

2017-10-25 20:57 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-10-25 20:57 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2204/
Test PASSed.

2017-10-26 16:29 UTC, richardliaw requested changes

2017-10-26 16:45 UTC, richardliaw commented
Multiple line overflow issues (lint) also

2017-10-27 18:05 UTC, ericl commented
Addressed comments.

2017-10-27 18:37 UTC, AmplabJenkins commented
Build finished. Test PASSed.

2017-10-27 18:37 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2214/
Test PASSed.

2017-10-27 20:27 UTC, richardliaw approved these changes

2017-10-27 20:29 UTC, merged

2017-10-27 20:29 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-10-27 20:29 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2217/
Test FAILed.