[rllib] wip: PyTorch Models for A3C
ray-project/ray pull request #1187
Opened 2017-11-07 01:44 UTC by richardliaw

- [ ] May need to refactor into modelcatalog

2017-11-07 02:17 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-11-07 02:17 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2279/
Test PASSed.

2017-11-07 07:20 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-07 07:20 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2282/
Test FAILed.

2017-11-07 07:25 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-07 07:25 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2283/
Test FAILed.

2017-11-07 08:33 UTC, richardliaw commented on python/ray/rllib/a3c/a3c.py
> +              "channel_major": False}
somehow this was defaulted incorrectly

2017-11-07 08:34 UTC, richardliaw commented on python/ray/rllib/models/preprocessors.py
> +        self._channel_major = self._options.get("channel_major", False)
this was also an incorrect residual

2017-11-07 08:50 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-07 08:50 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2284/
Test FAILed.

2017-11-07 23:00 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-07 23:00 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2285/
Test FAILed.

2017-11-07 23:50 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-07 23:50 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2286/
Test FAILed.

2017-11-08 00:30 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-08 00:30 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2289/
Test FAILed.

2017-11-08 06:50 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-08 06:50 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2298/
Test FAILed.

2017-11-08 07:05 UTC, ericl reviewed
Cool, so what's next? have you run any comparisons with the tensorflow model?

2017-11-08 07:05 UTC, ericl commented on python/ray/rllib/models/pytorch/visionnet.py
> +    def forward(self, inputs):
Should these be documented in the base model class?

2017-11-08 08:15 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-08 08:15 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2303/
Test FAILed.

2017-11-09 06:32 UTC, richardliaw commented on python/ray/rllib/models/pytorch/model.py
> +class Model(nn.Module):
Done.

2017-11-09 06:50 UTC, AmplabJenkins commented
Build finished. Test FAILed.

2017-11-09 06:50 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2322/
Test FAILed.

2017-11-09 06:59 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-09 06:59 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2323/
Test FAILed.

2017-11-09 07:17 UTC, richardliaw commented
Currently running a benchmark task on EC2 for both Linear and Conv models.

Next immediate steps are to (localized to the A3C/ModelCatalog):

1. Introduce the LSTM for PyTorch
2. Investigate and provide GPU support for PyTorch

2017-11-09 07:30 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-09 07:30 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2324/
Test FAILed.

2017-11-10 01:19 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-10 01:19 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2336/
Test FAILed.

2017-11-10 07:04 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-10 07:04 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2340/
Test FAILed.

2017-11-10 08:04 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-10 08:04 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2346/
Test FAILed.

2017-11-10 08:15 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-10 08:15 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2345/
Test FAILed.

2017-11-11 02:49 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-11 02:49 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2354/
Test FAILed.

2017-11-11 04:04 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-11 04:04 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2358/
Test FAILed.

2017-11-11 05:10 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-11 05:10 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2359/
Test FAILed.

2017-11-11 05:50 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-11 05:50 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2361/
Test FAILed.

2017-11-11 06:49 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-11 06:49 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2362/
Test FAILed.

2017-11-11 07:15 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-11 07:15 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2363/
Test FAILed.

2017-11-12 00:25 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-12 00:25 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2371/
Test FAILed.

2017-11-12 00:50 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-12 00:50 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2372/
Test FAILed.

2017-11-12 01:30 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-12 01:30 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2373/
Test FAILed.

2017-11-12 01:53 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-11-12 01:53 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2375/
Test PASSed.

2017-11-12 02:14 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-11-12 02:14 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2376/
Test PASSed.

2017-11-12 02:39 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-11-12 02:39 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2377/
Test PASSed.

2017-11-12 04:37 UTC, ericl requested changes
I think we should go ahead and merge this. Couple thing first though:

- Could we add a jenkins test that runs the pytorch a3c for a couple iterations?
- It would be nice if RLlib didn't acquire a hard dependency on pytorch. Can you make sure that things still run without torch installed (perhaps we should leave torch uninstalled on travis for this reason, and do a simple import test on rllib and check it doesn't crash?)

2017-11-12 04:45 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-11-12 04:45 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2378/
Test PASSed.

2017-11-12 04:56 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-11-12 04:56 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2379/
Test PASSed.

2017-11-12 04:56 UTC, ericl approved these changes

2017-11-12 05:00 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-11-12 05:00 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2380/
Test PASSed.

2017-11-12 05:21 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-12 05:21 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2385/
Test FAILed.

2017-11-12 05:27 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-11-12 05:27 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2388/
Test FAILed.

2017-11-12 07:00 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-11-12 07:00 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/2390/
Test PASSed.

2017-11-12 08:20 UTC, merged