[CLI] Fix ray commands when RAY_ADDRESS used
ray-project/ray pull request #11989
Opened 2020-11-12 21:21 UTC by ijrsvt

## Why are these changes needed?
* When `RAY_ADDRESS` is set, I cannot make calls like `ray status` because `ray.init()` is called with `address='auto'` and `RAY_ADDRESS=...`

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2020-11-13 01:27 UTC, ericl requested changes
IMO this fix is pretty confusing. Can we instead make the autodetect always return the specified address in RAY_ADDRESS if it's set?

2020-11-13 09:20 UTC, ijrsvt commented
@ericl What do you mean by "`autodetect`". I 💯  agree that the behavior here is confusing--this PR was to do the minimal delta, while fixing an obviously broken feature in the product.

2020-11-13 20:13 UTC, ericl commented
So is the core issue that "auto" doesn't respect RAY_ADDRESS? Can we have RAY_ADDRESS override autodetect?

2020-11-13 21:43 UTC, ijrsvt commented
> So is the core issue that "auto" doesn't respect RAY_ADDRESS? Can we have RAY_ADDRESS override autodetect?

No, it is that for most `scripts.py` commands we **manually** find the address by running `services.find_redis_address_or_die()` and then pass that into `ray.init()`

So ray sees the following situation:
```
os.environ()
 > RAY_ADDRESS='localhost:6379'

ray.init(address='172.31.201.164:6379')
```

2020-11-18 07:44 UTC, ericl approved these changes

2020-11-18 07:45 UTC, merged