[rllib] move evaluation to trainer.step() such that the result is properly logged
ray-project/ray pull request #12708
Opened 2020-12-09 11:48 UTC by Maltimore

Move evaluation to ```trainer.step()``` such that the result is properly logged even when training with ```trainer.train()``` instead of ```tune.run()```

## Why are these changes needed?
When training with ```trainer.train()``` instead of ```tune.run()```, the results of the evaluation (evaluation metrics) are not written to disk (e. g. to the progress.csv).

This moves the evaluation code to ```trainer.step()```, which ensures that the evaluation metrics are included in progress.csv and other output files.

## Related issue number

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR. --> yes but this errors with a flake8 error unrelated to the code
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/. --> no doc changes needed
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

I only tested this PR in my own experiments.

2020-12-21 17:12 UTC, sven1977 requested changes
Looks fine for me.
@Maltimore Could you fix the broken eval test case and run the ci/travis/format.sh (LINT) before pushing?
Thanks!

2021-01-07 14:42 UTC, Maltimore commented
I ran `ci/travis/format.sh` again and it works now (previously it failed with a flake8 error).
Can you tell me how to run the unit tests for rllib? Or, where can I find the information on how to run the unit tests?
I did (from the root directory of the ray repo):
```bash
python rllib/tests/test_evaluators.py
```
and it gave me 
```
ImportError while loading conftest '/home/maltimore/repos/ray/rllib/tests/conftest.py'.
rllib/tests/conftest.py:1: in <module>
    from ray.tests.conftest import ray_start_regular_shared  # noqa: F401
E   ModuleNotFoundError: No module named 'ray.tests'
```

2021-01-14 11:24 UTC, Maltimore commented
@sven1977 
could you take another look? I simplified the logic in the if condition a bit (I hope I didn't mess it up, maybe if you could check the if condition as well that would be good). The evaluation test case runs through now.

2021-01-25 11:55 UTC, sven1977 commented on rllib/agents/trainer_template.py
> +            # is over.
```suggestion
            # self._iteration gets incremented after this function returns,
            # meaning that e. g. the first time this function is called,
            # self._iteration will be 0. We check `self._iteration+1` in the
            # if-statement below to reflect that the first training iteration
            # is already over.
```

2021-01-25 11:55 UTC, sven1977 approved these changes
Thanks for this fix @Maltimore !
Looks good to me.

2021-01-25 11:56 UTC, merged