Remove unused file(object_manager_integration_test.cc)
ray-project/ray pull request #12989
Opened 2020-12-19 07:23 UTC by ffbin

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2020-12-19 09:54 UTC, kfstorm approved these changes

2020-12-19 14:57 UTC, WangTaoTheTonic approved these changes

2020-12-19 18:01 UTC, rkooo567 commented
I think this is still used?
<img width="1238" alt="Screen Shot 2020-12-19 at 10 00 58 AM" src="https://user-images.githubusercontent.com/18510752/102696157-1888d600-41e1-11eb-96da-7d3c908b6a33.png">

@ericl Can you confirm?

2020-12-19 18:01 UTC, rkooo567 requested changes
Temporary change request until the question is resolved.

2020-12-21 07:40 UTC, ffbin commented
Hi @ahbone , can you help review this PR, thanks.

2020-12-21 08:46 UTC, ahbone commented
Yes, object manager test is still useful.

2020-12-21 09:11 UTC, ffbin commented
> Yes, object manager test is still useful.

Is `src/ray/raylet/object_manager_integration_test.cc` still in use? It has compile errors.

2020-12-22 05:10 UTC, ahbone commented
> > Yes, object manager test is still useful.
> 
> Is `src/ray/raylet/object_manager_integration_test.cc` still in use? It has compile errors.

Sorry, I'm not quite sure about this one. :(

2020-12-27 20:35 UTC, rkooo567 commented
@ahbone @ffbin I think we should port this test to run with bazel instead of removing it? Any thought?

2020-12-28 06:07 UTC, ffbin commented
> @ahbone @ffbin I think we should port this test to run with bazel instead of removing it? Any thought?

Its test case been tested in `object_manager_test.cc` ?

2020-12-28 16:58 UTC, ahbone commented
I checked it and it looks like some of the test cases has been covered. I'm on vocation right now and I'll have another look tonight.

2020-12-29 06:57 UTC, ahbone commented
The only thing tested in `object_manager_integration_test.cc` is `Push` which has been covered here https://github.com/ray-project/ray/blob/7ad56826dbab8b718de47fbf2752ba0c81cbd843/src/ray/object_manager/test/object_manager_test.cc#L285

2020-12-29 09:28 UTC, ffbin commented
> The only thing tested in `object_manager_integration_test.cc` is `Push` which has been covered here
> 
> https://github.com/ray-project/ray/blob/7ad56826dbab8b718de47fbf2752ba0c81cbd843/src/ray/object_manager/test/object_manager_test.cc#L285

@ahbone @rkooo567 So we can delete `object_manager_integration_test.cc`?

2020-12-30 06:34 UTC, ahbone commented
I think so.

2021-01-04 02:44 UTC, raulchen approved these changes

2021-01-04 02:44 UTC, raulchen commented on src/ray/test/run_object_manager_tests.sh
>  sleep 1s
remove this line as well

2021-01-04 17:44 UTC, rkooo567 approved these changes

2021-01-05 03:09 UTC, merged