[RLlib] Env directory cleanup and tests.
ray-project/ray pull request #13082
Opened 2020-12-25 18:06 UTC by sven1977

- Move all wrappers (incl. 3rd party simulation wrappers) into env/wrappers sub-dir.
- Deprecate (backward-compatible w/ warning) all moved modules.
- Add test case for grouped_agents.
- Move `make_multiagent` helper from examples into env/multi_agent_env.py.

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2020-12-26 23:35 UTC, michaelzhiluo requested changes
Modifications to model_vec_env and Deepmind control suite will also change the dependencies (imports) for MBMPO and Dreamer. This also applies for other wrappers.

2020-12-27 01:28 UTC, sven1977 commented
I think, it's all ok. I made sure that everything stays backward-compatible (with warning). So you can still do
`from ray.rllib.env.model_vector_env import model_vector_env`.

I did change the import for mbmpo to not get this warning.
Didn't find anything in Dreamer regarding this, but please let me know, which exact import would be in danger of failing in case I missed something.

2021-01-18 13:12 UTC, sven1977 commented
@michaelzhiluo 
This is ready for review again.

2021-01-18 22:37 UTC, michaelzhiluo approved these changes

2021-01-19 04:22 UTC, michaelzhiluo approved these changes

2021-01-19 09:09 UTC, merged