[ray_client]: Add more retry logic
ray-project/ray pull request #13478
Opened 2021-01-15 01:57 UTC by barakmich

## Related issue number

Closes #13446 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-01-15 23:51 UTC, ericl commented on python/ray/util/client/worker.py
> +            ray_ready = self.is_initialized()
Do we need three different retry loops for the different stages? Why not have just a single one that tests this last condition?

2021-01-15 23:52 UTC, ericl requested changes
Comment on simplifying

2021-01-15 23:55 UTC, barakmich commented
Because it could fail at any one of these stages.

Now, one big retry loop would look like a finite state machine of ```
while retrying:
   if in step A:
   if in step B:
   if in step C:
```

But we can't "test this last condition" alone. If this is what you'd prefer, I'll go do that.

2021-01-16 00:08 UTC, ericl commented
Why can't we test the last condition alone? C implies {A, B} are fine right? I think a loop that just tests C would be sufficient. If it's for better error messages, we could also check {A, B} prior to C in the loop.

2021-01-16 02:10 UTC, ericl commented
Btw, it would be good to have a test here

2021-01-20 17:42 UTC, ericl commented on python/ray/util/client/worker.py
> +        connection_state = CONN_STATE_CHANNEL
Why do we need a FSM? Why not reset the state to the initial state on connection failure and retry end-to-end?

If the server is up, the connection should be instant so there isn't any benefit in keeping intermediate states around on failure.

2021-01-22 00:04 UTC, ericl commented on python/ray/tests/test_client.py
> +        server = ray_client_server.serve("localhost:50051")
Add a delay before the server starts?

2021-01-22 02:22 UTC, ericl approved these changes

2021-01-22 02:22 UTC, ericl commented
```
//python/ray/tests:test_client                                          TIMEOUT in 3 out of 3 in 75.0s
  Stats over 3 runs: max = 75.0s, min = 75.0s, avg = 75.0s, dev = 0.0s
  /home/travis/.cache/bazel/_bazel_travis/b88c129a127452fc94033a29d9f90e20/execroot/com_github_ray_project_ray/bazel-out/k8-opt/testlogs/python/ray/tests/test_client/test.log
  /home/travis/.cache/bazel/_bazel_travis/b88c129a127452fc94033a29d9f90e20/execroot/com_github_ray_project_ray/bazel-out/k8-opt/testlogs/python/ray/tests/test_client/test_attempts/attempt_1.log
  /home/travis/.cache/bazel/_bazel_travis/b88c129a127452fc94033a29d9f90e20/execroot/com_github_ray_project_ray/bazel-out/k8-opt/testlogs/python/ray/tests/test_client/test_attempts/attempt_2.log
```

2021-01-22 22:14 UTC, ericl commented
Tests / lint still failing

2021-01-23 00:23 UTC, barakmich commented
I'm starting to run out of ideas, but we'll see if this goes

2021-01-23 01:58 UTC, barakmich commented
I think I figured it out

2021-01-23 02:06 UTC, barakmich commented
This time for sure -- I got the reproduction locally and tracked it down

2021-01-24 07:11 UTC, merged