Make AWSNodeProvider.create_node return node config
ray-project/ray pull request #13498
Opened 2021-01-15 23:11 UTC by DmitriGekhtman

## Why are these changes needed?

@yifeif 

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-01-16 10:39 UTC, AmeerHajAli approved these changes
LGTM

2021-01-18 17:44 UTC, yifeif approved these changes
LGTM, thanks!

2021-01-18 23:54 UTC, AmeerHajAli commented
@ericl can you please merge this?
@wuisawesome, can we make sure it is in our next release?

2021-01-19 00:08 UTC, ericl requested changes
Isn't this breaking the node provider interface? We should at a minimum
- Document the return values in the base node_provider class
- Document that it's optional (not required for all node providers)?

Have you also considered alternatives to this change?

2021-01-19 00:10 UTC, AmeerHajAli commented
@ericl , gcp node provider already returns this config.

2021-01-19 00:38 UTC, wuisawesome commented
The `create_node` signature is 

```    
def create_node(self, node_config: Dict[str, Any], tags: Dict[str, str],
                    count: int) -> None:
```

2021-01-19 00:42 UTC, DmitriGekhtman commented
> The `create_node` signature is
> 
> ```
> def create_node(self, node_config: Dict[str, Any], tags: Dict[str, str],
>                     count: int) -> None:
> ```

Git blame tells me that I put in the type hints.
I could change it to Any. ¯\_(ツ)_/¯

2021-01-19 00:46 UTC, wuisawesome commented
That sounds reasonable since that's a backwards compatible change.

2021-01-19 01:03 UTC, AmeerHajAli commented
@DmitriGekhtman , I think what Eric meant is to make it Optional[Dict[str,Any]] in the parent class or something like that and to document that in the parent node provider class that this function can either return None or the configs of...
And in the AWS class (the son) to use Dict[str, Any] and explain what is that returned argument.

2021-01-19 01:06 UTC, DmitriGekhtman commented
@AmeerHajAli 
GCP node provider currently returns a list. I think it's fine to allow Any return type, though if anyone has objections, let me know.

2021-01-19 01:12 UTC, AmeerHajAli commented
I see, lets then just document that in the parent class(optional return values) and the son AWS class (what the return value is).

2021-01-19 01:54 UTC, ericl commented on python/ray/autoscaler/node_provider.py
> +        """
Can we specify the format of the metadata? E.g., can it always be Dict[NodeID, Any]?

2021-01-19 01:59 UTC, DmitriGekhtman commented
I think GCPNodeProvider currently returns a List.

On Mon, Jan 18, 2021 at 17:54 Eric Liang <notifications@github.com> wrote:

> *@ericl* commented on this pull request.
> ------------------------------
>
> In python/ray/autoscaler/node_provider.py
> <https://github.com/ray-project/ray/pull/13498#discussion_r559867596>:
>
> > @@ -110,8 +110,11 @@ def find_node_id():
>          return find_node_id()
>
>      def create_node(self, node_config: Dict[str, Any], tags: Dict[str, str],
> -                    count: int) -> None:
> -        """Creates a number of nodes within the namespace."""
> +                    count: int) -> Any:
> +        """Creates a number of nodes within the namespace.
> +
> +        Optionally returns information about the created nodes.
> +        """
>
> Can we specify the format of the metadata? E.g., can it always be
> Dict[NodeID, Any]?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ray-project/ray/pull/13498#pullrequestreview-570855111>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APAQTK5MEARHT2XFE7JSJALS2TQ5LANCNFSM4WEXOBRA>
> .
>

2021-01-19 02:06 UTC, ericl commented
> I think GCPNodeProvider currently returns a List.

Let's take the opportunity to fix this then, either (1) make it return None (just delete the return), or (2) change it to a dict.

2021-01-19 03:04 UTC, DmitriGekhtman commented
Deleted the return in GCPNodeProvider.create_node -- I hope the output wasn't used anywhere?

2021-01-19 03:14 UTC, ericl approved these changes

2021-01-19 15:50 UTC, DmitriGekhtman commented
@ericl
It's now good to merge.

2021-01-19 19:58 UTC, AmeerHajAli commented
@ericl , can you please merge?

2021-01-19 20:17 UTC, merged