[rllib][minor] Fix multiple Unity3DEnvs trying to connect to the same custom port
ray-project/ray pull request #13519
Opened 2021-01-18 10:25 UTC by yurirocha15

## Why are these changes needed?

When running the Unity3D env with several workers while using a custom port, every environment will try to connect to the same port.

The current logic increments the base_port while keeping the worker_id fixed. This works without issues if the default base port is used. However, if the user decides to use a custom port, this will override the base_port, trying to create several environments using the same custom port. The first environment will succeed, while the remaining environments will be trapped in an infinite loop.

This PR fixes that by keeping the base_port fixed and incrementing the worker_id instead. 

This PR also changed the base port value when calling a compiled app (to 5005, the same default as ml-agents uses internally. The editor port stays the same). There is a use case where the user might be running a distributed training in the background while debugging/prototyping/testing new features in the editor. If the first compiled environment is using the editor default port, the editor will fail to connect.

## Related issue number

## Checks

- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [X] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [X] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(
Added unit tests to check the default ports, and to check if two consecutive calls would have different base_port + worker_id (for either default and user-defined ports). 
Also tested using the rllib/examples/unity3d_env_local.py.

2021-01-25 11:41 UTC, sven1977 requested changes
Awesome! Thanks for the fix @yurirocha15 !
Could you do one more thing and add your new tests to the rllib/BUILD file?
Somewhere here?
```
py_test(
    name = "env/wrappers/tests/test_unity3d_env",
    tags = ["env"],
    size = "small",
    srcs = ["env/wrappers/tests/test_unity3d_env.py"]
)

# .... before this one here vv

py_test(
    name = "env/wrappers/tests/test_recsim_wrapper",
    tags = ["env"],
    size = "small",
    srcs = ["env/wrappers/tests/test_recsim_wrapper.py"]
)

```

2021-01-26 05:54 UTC, yurirocha15 commented
Travis is failing to find mlagents_envs (which is imported in the tests). I guess it might be necessary to add the mlagents requirements to python/requirements_rllib.txt.

2021-01-28 01:34 UTC, yurirocha15 commented
@sven1977 Would it be ok to add mlagents to rllib requirements?

2021-01-28 11:01 UTC, sven1977 commented
@yurirocha thanks a lot for adding the test.

Yes, you can add
```
mlagents
mlagents_env
```
to `ray/python/requirements_rllib.txt`. Then it should work.

2021-01-28 11:05 UTC, sven1977 commented
I added the two modules to the requirements_rllib.txt. Just waiting for tests now to pass. ...

2021-01-28 11:05 UTC, sven1977 approved these changes
Thanks for the fix @yurirocha15 ! Looks good now.

2021-01-28 11:18 UTC, yurirocha15 commented
@sven1977 Thank you!

2021-01-28 12:28 UTC, merged