Client convert registered things
ray-project/ray pull request #13639
Opened 2021-01-23 00:15 UTC by barakmich

TODO: Write tests

## Related issue number

Closes #13272 
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-01-30 00:15 UTC, ericl commented
One question I have is actor classes now are different depending on whether they were created before `ray.util.connect` vs after. Can we avoid this and always go through the conversion path? That seems like it will minimize changes for bugs due to divergence.

2021-01-30 00:17 UTC, ericl requested changes
See comment on unifying the paths to avoid two different class types.

2021-02-01 18:51 UTC, barakmich commented
Let's see if we can remove the other hooks for remote instantiation. We can't get rid of it from `ray.util.client` but anything outside the client that we're adapting may be viable

2021-02-01 21:11 UTC, ericl approved these changes

2021-02-01 21:11 UTC, ericl commented on python/ray/_private/client_mode_hook.py
> +RAY_CLIENT_MODE_ATTR = "__ray_client_mode_key__"
```suggestion
# This flag is set on function defs to mark they have been converted to client mode.
RAY_CLIENT_MODE_ATTR = "__ray_client_mode_key__"
```

2021-02-01 21:22 UTC, barakmich commented
Good comment :)

2021-02-02 23:07 UTC, ericl commented
python/ray/_private/client_mode_hook.py:5:80: E501 line too long (84 > 79 characters)

2021-02-03 21:30 UTC, merged

2021-02-03 21:31 UTC, ericl commented
Fixed lint and merged; please note you can check your pending PRs at github.com/pulls to see which ones are blocked on issues in the future.