[Placement Group] Make PlacementGroupID generate from JobID
ray-project/ray pull request #13830
Opened 2021-02-01 03:52 UTC by clay4444

## Why are these changes needed?
Now, `PlacementGroupID::FromRandom()` will generate duplicate IDs after a fork() call, we should replace it with `PlacementGroupID::Of(JobID)`

## Related issue number

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-02-01 05:19 UTC, rkooo567 commented
I think ray anyway doesn't work with fork()? Can you elaborate the exception case?

2021-02-02 02:15 UTC, ffbin commented on src/ray/common/id.h
> +  /// Length of `ActorID` in bytes.
```suggestion
  /// Length of `PlacementGroupID` in bytes.
```

2021-02-02 02:16 UTC, ffbin commented on src/ray/common/id.h
> +  /// Creates an `PlacementGroupID` by hashing the given information.
```suggestion
  /// Creates a `PlacementGroupID` by hashing the given information.
```

2021-02-02 02:20 UTC, ffbin commented
Hey @clay4444 Why `PlacementGroupID::Of(JobID)` will not generate duplicate IDs after a fork() call?

2021-02-02 03:39 UTC, clay4444 commented
> Hey @clay4444 Why `PlacementGroupID::Of(JobID)` will not generate duplicate IDs after a fork() call?

yeah, the reason why we make the `FromRandom` deleted is we want `PlacementGroupId` generate from `JobId` instead of from random, I have changed the comment.  cc @rkooo567

2021-02-02 03:43 UTC, clay4444 commented on src/ray/common/id.h
> +  /// Length of `ActorID` in bytes.
updated

2021-02-02 06:51 UTC, rkooo567 commented
Still didn't get answer for this question?

> I think ray anyway doesn't work with fork()? Can you elaborate the exception case?

Ray doesn't work with fork anyway. What's the use case, and adding this code will fix the whole issue?

2021-02-02 06:53 UTC, rkooo567 requested changes
So, there are 2 things.

1. Ray is not working with fork anyway. If we'd like to introduce this change, we should also add a python test that tests if it works with fork().
2. To do 1, we need a solid use case. There's no reason to fix this for a partial support without a use case.

2021-02-09 04:31 UTC, clay4444 commented
close temporarily.

2021-02-09 04:31 UTC, closed without merging