Minor fix to RayDP docs
ray-project/ray pull request #14309
Opened 2021-02-24 16:04 UTC by guykhazma

## Why are these changes needed?

The doc currently uses an incorrect parameter to set the memory per executer when calling the `init_spark` method.
The correct parameter should be `executor_memory` as can be seen [here](https://github.com/oap-project/raydp/blob/94aabf977903d9872e5428c8d5a1ddfae191c25a/python/raydp/context.py#L96). 

## Checks

No tests are needed. doc change.

2021-02-24 16:34 UTC, guykhazma commented
the examples are actually not runnable as well.
I will update the PR with a fix to them as well.

2021-02-24 18:26 UTC, guykhazma commented
Fixed the PyTorch and TensorFlow samples to have simple working examples based on the flow used in the [tests of RayDP](https://github.com/oap-project/raydp/tree/master/python/raydp/tests)

2021-02-24 19:40 UTC, richardliaw commented
@ConeyLiu can you please take a look?

2021-02-24 23:52 UTC, ConeyLiu requested changes

2021-02-24 23:52 UTC, ConeyLiu commented on doc/source/raydp.rst
> +  # Tensor Flow code
TensorFlow

2021-02-24 23:52 UTC, ConeyLiu commented on doc/source/raydp.rst
> +                              optimizer=optimizer,
indent

2021-02-24 23:53 UTC, ConeyLiu commented
thanks for the fixes. Others LGTM.

2021-02-25 02:49 UTC, wuisawesome reviewed
I defer to Coney on this. Happy to help merge when approved though.

2021-02-25 06:53 UTC, guykhazma commented
@ConeyLiu @wuisawesome thanks for the review. fixed according to the comments.

2021-02-25 13:31 UTC, ConeyLiu approved these changes

2021-02-25 19:22 UTC, wuisawesome approved these changes

2021-02-25 19:23 UTC, merged