[autoscaler] Converting assert False into useful exceptions.
ray-project/ray pull request #14481
Opened 2021-03-03 22:26 UTC by xcharleslin

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-03-03 22:29 UTC, AmeerHajAli commented on python/ray/autoscaler/_private/updater.py
> +                    if time.time() < deadline:
```suggestion
                    if time.time() > deadline:
```

2021-03-03 22:30 UTC, AmeerHajAli requested changes
Do you mind adding two pytest checks for this?
Is there a way to avoid "while True"?

2021-03-03 22:43 UTC, AmeerHajAli commented on python/ray/autoscaler/_private/updater.py
> +                    if self.provider.is_terminated(self.node_id):
immediately after create_node, is `is_terminated` set to false?

2021-03-04 00:19 UTC, ericl approved these changes
lgtm

2021-03-10 20:59 UTC, ericl commented
LINT is failing

2021-03-10 21:43 UTC, AmeerHajAli commented
> LINT is failing

I think we should add two pytest checks for this. What do you think?

2021-03-10 22:39 UTC, AmeerHajAli commented
> This should be covered by existing tests right? While adding tests is always nice, this PR is just clarifying an exception message and we shouldn't block it by overly expanding the scope to be adding more tests as well.

Can you please help me find where is this tested?
Expanding the scope? This is just 1 unit test with ~10 lines of code.

2021-03-10 23:26 UTC, AmeerHajAli approved these changes
It seems like this is tested here:
https://github.com/ray-project/ray/blob/153dcd3734719d68b0ab2c9c0d4bec1fa85eaf87/python/ray/tests/test_autoscaler.py#L479

2021-03-12 03:04 UTC, xcharleslin commented
@ericl @AmeerHajAli Heads up that I don't have merge permissions (also test results are unclear to me - first time in this repo - although I did run the linter).

2021-03-12 03:19 UTC, ericl commented
~/build/ray-project/tmp.8pIHIiMtRc
Thu Mar 11 04:23:30 UTC 2021 Flake8....
python/ray/autoscaler/_private/updater.py:244:80: E501 line too long (86 > 79 characters)

(you need to run scripts/format.sh)

2021-03-16 21:56 UTC, AmeerHajAli commented
Lint still fails @xcharleslin

2021-04-14 13:45 UTC, AmeerHajAli commented
@xcharleslin , can you please rebase + lint this?

2021-04-14 18:27 UTC, xcharleslin commented
I am no longer able to push to this PR's branch (due to new repo policies it seems). New PR here:
https://github.com/ray-project/ray/pull/15306

2021-04-14 18:27 UTC, closed without merging