[Java] Support getCurrentActorId in local mode
ray-project/ray pull request #14890
Opened 2021-03-24 06:16 UTC by kfstorm

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-03-26 13:42 UTC, jovany-wang approved these changes

2021-03-26 13:48 UTC, jovany-wang requested changes

2021-03-26 13:48 UTC, jovany-wang commented on java/runtime/src/main/java/io/ray/runtime/RayDevRuntime.java
> +    return new AsyncContext(((LocalModeWorkerContext) workerContext).getCurrentTask());
There is no definition of method getCurrentTask().

2021-03-31 13:05 UTC, kfstorm commented
@jovany-wang tests passed.

2021-03-31 13:31 UTC, jovany-wang approved these changes

2021-03-31 13:39 UTC, merged