Add implementation for get method
ray-project/ray pull request #1496
Opened 2018-01-31 23:58 UTC by HacksForHugs

Add tests for get method
Add implementation/tests for get_dtype_counts method
Add implementation/tests for get_ftype_counts method

## What do these changes do?

## Related issue number

2018-01-31 23:59 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-02-01 00:00 UTC, robertnishihara commented
ok to test

2018-02-01 00:55 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-02-01 00:55 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/3506/
Test PASSed.

2018-02-02 22:44 UTC, devin-petersohn requested changes
Great first pass! All changes requested should are minor.

2018-02-02 22:44 UTC, devin-petersohn commented on python/ray/dataframe/test/test_dataframe.py
> +
Please remove this line.

2018-02-02 22:44 UTC, devin-petersohn commented on python/ray/dataframe/test/test_dataframe.py
> +import sys
Please remove this line.

2018-02-02 22:44 UTC, devin-petersohn commented on python/ray/dataframe/test/test_dataframe.py
> +sys.path.insert(0, '../../')
Please remove this line.

2018-02-02 22:44 UTC, devin-petersohn commented on python/ray/dataframe/test/test_dataframe.py
> +import dataframe as rdf
Please revert to `import ray.dataframe as rdf`.

2018-02-02 22:44 UTC, devin-petersohn commented on python/ray/dataframe/test/test_dataframe.py
> +
Please remove this line.

2018-02-02 22:44 UTC, devin-petersohn commented on python/ray/dataframe/test/test_dataframe.py
> +    df = pd.DataFrame({'col1': [0, 1, 2, 3],
Prefer to convert test to `@pytest.fixture` and call from above. Feel free to create a new test with some string data if you would like.

2018-02-02 22:44 UTC, devin-petersohn commented on python/ray/dataframe/dataframe.py
> +        temp_df = self._map_partitions(lambda df: df.get(key, default=default))
Please add method-level docs.

2018-02-02 22:44 UTC, devin-petersohn commented on python/ray/dataframe/dataframe.py
> +        # print(ray.get(ray_df))
Please remove this code and the line above.

2018-02-02 22:44 UTC, devin-petersohn commented on python/ray/dataframe/dataframe.py
> +        return ray.get(_deploy_func.remote(lambda df: df.get_dtype_counts(), self._df[0]))
Please add method-level docs

2018-02-02 22:44 UTC, devin-petersohn commented on python/ray/dataframe/dataframe.py
> +        return ray.get(_deploy_func.remote(lambda df: df.get_ftype_counts(), self._df[0]))
Please add method-level docs

2018-02-02 22:44 UTC, devin-petersohn commented on python/ray/dataframe/test/test_dataframe.py
> +    df = pd.DataFrame({'col1': [0, 1, 2, 3],
Please add a test with the `default` optional parameter set to something.

2018-02-08 01:20 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/3638/
Test PASSed.

2018-02-08 01:24 UTC, devin-petersohn reviewed
This looks great! Just a couple of prints made it through, and I'd like to change something minor on the `get` test.

2018-02-08 01:24 UTC, devin-petersohn commented on python/ray/dataframe/test/test_dataframe.py
> +    print('ray sum', rdf.to_pandas(ray_df.sum()).sort_index())
Please remove print code.

2018-02-08 01:24 UTC, devin-petersohn commented on python/ray/dataframe/test/test_dataframe.py
> +    print('pandas sum', pandas_df.sum())
Please remove print code

2018-02-08 01:24 UTC, devin-petersohn commented on python/ray/dataframe/test/test_dataframe.py
> +def test_get(ray_df, pandas_df, key, default=None):
I prefer this test to be as follows:
```python
def test_get(ray_df, pandas_df, key):
    assert ray_df.get(key).equals(pandas_df.get(key))
    assert ray_df.get(key, default='default').equals(pandas_df.get(key, default='default'))
```
This way we can get a test with and without default but don't have to run multiple tests.

2018-02-08 09:37 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/3641/
Test PASSed.

2018-02-08 15:03 UTC, devin-petersohn approved these changes
Looks great! Thanks @HacksForHugs

2018-02-08 16:24 UTC, devin-petersohn commented
@robertnishihara @pcmoritz Is this ok to merge? There were test failures, but they seem unrelated.

2018-02-08 18:31 UTC, robertnishihara commented
@devin-petersohn yes the test failures look unrelated. The global scheduler valgrind test seems to be failing a lot these days.

2018-02-09 06:12 UTC, merged

2018-02-09 06:12 UTC, devin-petersohn commented
Thanks @HacksForHugs