Dataframe functions (max, min, notnull, notna)
ray-project/ray pull request #1500
Opened 2018-02-01 04:48 UTC by hsubbaraj

## What do these changes do?

Implement max, min, notnull, notna functions for dataframe

## Related issue number

2018-02-01 04:49 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-02-02 02:30 UTC, robertnishihara commented
ok to test

2018-02-02 03:23 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2018-02-02 03:23 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/3554/
Test PASSed.

2018-02-02 22:30 UTC, devin-petersohn commented
@robertnishihara This one failed because of an error that I'm not sure is related to the code changes:
```
======================================================================
ERROR: test_stresstest (__main__.TestPlasmaManager)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./python/ray/plasma/test/test.py", line 122, in setUp
    self.client1 = plasma.connect(store_name1, manager_name1, 64)
  File "plasma.pyx", line 678, in pyarrow.plasma.connect
  File "error.pxi", line 79, in pyarrow.lib.check_status
ArrowIOError: Could not connect to socket /tmp/plasma_manager56305384
----------------------------------------------------------------------
Ran 7 tests in 63.374s
FAILED (errors=1)
The command "python ./python/ray/plasma/test/test.py valgrind" exited with 1.
```

Is this a known issue?

2018-02-02 22:32 UTC, pcmoritz commented
This failure is unrelated, yeah!

2018-02-02 22:52 UTC, devin-petersohn requested changes
Great first pass! A few minor changes.

2018-02-02 22:52 UTC, devin-petersohn commented on python/ray/dataframe/dataframe.py
> +            return self.T.max(axis=1)
We probably also need to pass in `skipna`, `level`, etc.

2018-02-02 22:52 UTC, devin-petersohn commented on python/ray/dataframe/dataframe.py
> +            max_partitions = self._map_partitions(
I prefer to just have the `return` here instead of assigning it to a variable.

2018-02-02 22:52 UTC, devin-petersohn commented on python/ray/dataframe/dataframe.py
> +            return self.T.min(axis=1)
Same here for the other parameters.

2018-02-02 22:52 UTC, devin-petersohn commented on python/ray/dataframe/dataframe.py
> +            min_partitions = self._map_partitions(
Same here for the `return`.

2018-02-02 22:52 UTC, devin-petersohn commented on python/ray/dataframe/dataframe.py
> +        if(axis == 1):
Please add method-level docs.

2018-02-02 22:52 UTC, devin-petersohn commented on python/ray/dataframe/dataframe.py
> +        if(axis == 1):
Please add method-level docs.

2018-02-02 22:52 UTC, devin-petersohn commented on python/ray/dataframe/dataframe.py
> +        notna_partitions = self._map_partitions(lambda df: df.notna())
Sam here for the `return`. Also please add method-level docs.

2018-02-02 22:52 UTC, devin-petersohn commented on python/ray/dataframe/dataframe.py
> +        notnull_partitions = self._map_partitions(lambda df: df.notnull())
Sam here for the `return`. Also please add method-level docs.

2018-02-02 22:52 UTC, devin-petersohn commented on python/ray/dataframe/test/test_dataframe.py
> +        ray_df.median()
This should not have changed.

2018-02-02 22:52 UTC, devin-petersohn commented on python/ray/dataframe/test/test_dataframe.py
> +    pandas_df_nulls = pd.DataFrame({'col1': [np.NaN, np.NaN, np.NaN, np.NaN],
This test dataframe looks really useful! Could you instead move it above to its own test so all the test methods could run through it? Move to `test_nan_dataframe()`.

2018-02-11 08:14 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/3659/
Test PASSed.

2018-02-13 15:42 UTC, devin-petersohn requested changes
Please rebase and also add your tests to `test_mixed_dtype_dataframe`.

2018-02-14 06:28 UTC, devin-petersohn approved these changes
Great work, thanks @hsubbaraj!

2018-02-14 06:34 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/3713/
Test PASSed.

2018-02-16 22:00 UTC, merged