[autoscaler][aws] Update _configure_key_pair to available_node_types
ray-project/ray pull request #15108
Opened 2021-04-03 19:26 UTC by DmitriGekhtman

## Why are these changes needed?

Closes https://github.com/ray-project/ray/issues/15096 
Addresses key_pair part of https://github.com/ray-project/ray/issues/14856

## Related issue number

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

Added tests to check key-pair filling logic and assertion error on missing KeyName.

2021-04-05 15:31 UTC, ijrsvt reviewed
Can you modify [`log_to_cli`](https://github.com/ray-project/ray/blob/0d1b30620b27e2c65d5f51c33309e5269036efa5/python/ray/autoscaler/_private/aws/config.py#L166) to also check available node types?

2021-04-05 15:34 UTC, ijrsvt commented on python/ray/tests/aws/test_autoscaler_aws.py
> +
Could you add one more test to ensure the `UserData` configuration works correctly? i.e. having the `ssh_private_key` passed in and having `["node_config"]["UserData"]` set to a non-empty value

2021-04-05 15:36 UTC, ijrsvt reviewed
This overall looks good! Thanks for doing this. OOC, would this break for workflows where a user is using `available_node_types` and also setting data in `head_node` and `worker_nodes`?

2021-04-05 15:59 UTC, DmitriGekhtman commented
> This overall looks good! Thanks for doing this. OOC, would this break for workflows where a user is using `available_node_types` and also setting data in `head_node` and `worker_nodes`?

Eh, yeah, thanks -- need to consider this carefully, as that's way it currently has to be done... In an initial version, had a check for that, then got rid of it..

2021-04-05 16:12 UTC, ijrsvt commented
@DmitriGekhtman I think it might be good to support that workflow for a bit longer? 

What are your thoughts @AmeerHajAli

2021-04-05 19:46 UTC, DmitriGekhtman commented
> @DmitriGekhtman I think it might be good to support that workflow for a bit longer?
> 
> What are your thoughts @AmeerHajAli

Yes, for sure. No need to change things suddenly.
Shouldn't require too many more lines of code.

2021-04-14 13:22 UTC, AmeerHajAli commented on python/ray/autoscaler/_private/aws/config.py
> +                    _key_assert_msg(node_type))  # todo: err msg
what is this todo?

2021-04-14 13:22 UTC, AmeerHajAli commented on python/ray/autoscaler/_private/aws/config.py
> +                cli_logger.doassert(  # todo: verify schema beforehand?
what is this todo?

2021-04-14 13:28 UTC, AmeerHajAli commented on python/ray/tests/aws/test_autoscaler_aws.py
> +        node_config.pop("KeyName")
What are you trying to do?
I don't understand

2021-04-14 13:29 UTC, AmeerHajAli commented on python/ray/tests/aws/test_autoscaler_aws.py
> +
Lets explicitly unset the "ray.worker_default" to make it easier to read this code and understand that there is another key that does not have a KeyName.

2021-04-14 13:39 UTC, AmeerHajAli commented on python/ray/autoscaler/_private/aws/config.py
> +        node_config["KeyName"] = key_name
When doing something like this, we should explicitly raise a warning saying that KeyName in head_node/worker_nodes are deprecated and they must be passed in the node config.

2021-04-14 13:41 UTC, AmeerHajAli requested changes
Can we throw a warning for using worker_nodes and head_node and mention that they are deprecated and suggest using multi node types??

2021-05-25 06:35 UTC, AmeerHajAli commented
@DmitriGekhtman , closing this as it is no longer necessary, right?

2021-05-25 06:35 UTC, closed without merging

2021-05-25 15:50 UTC, DmitriGekhtman commented
> @DmitriGekhtman , closing this as it is no longer necessary, right?

Correct, superseded by https://github.com/ray-project/ray/pull/15584!