[azure] pin azure-mgmt-compute to 14.0.0
ray-project/ray pull request #15274
Opened 2021-04-13 15:02 UTC by AmeerHajAli

closes #13599
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-04-13 15:02 UTC, AmeerHajAli commented
cc @GiovanniGatti @gramhagen

2021-04-13 15:19 UTC, gramhagen commented
@AmeerHajAli those are all the right places. fwiw the versions have moved on a bit tho, current versions on pypi:
azure-mgmt-compute = 20.0.0
azure-mgmt-network = 18.0.0
azure-cli-core = 2.22.0

2021-04-13 15:30 UTC, AmeerHajAli commented
@gramhagen , if you do not mind, can you please check if this works for you? I don't have azure credentials.

2021-04-13 16:39 UTC, gramhagen commented
I will try to find some time, but it might not be until friday this week.

2021-04-15 01:24 UTC, AmeerHajAli commented
Sounds good. Yeah, I think if we get this merged this week it would be great!

2021-04-15 20:17 UTC, wuisawesome commented
The title says to pin to 14.0.0, but the code looks like it's pinning to 18.0.0?

2021-04-15 20:25 UTC, AmeerHajAli commented
@wuisawesome my previous reviewer suggesting updating it to the most recent version

2021-04-15 22:54 UTC, wuisawesome approved these changes
This looks good if 18.0 is ok. 

(A little confused because this comment suggests it shouldn't be this simple though? https://github.com/ray-project/ray/issues/13599#issuecomment-767101111)

2021-04-16 20:07 UTC, gramhagen commented
> This looks good if 18.0 is ok.
> 
> (A little confused because this comment suggests it shouldn't be this simple though? [#13599 (comment)](https://github.com/ray-project/ray/issues/13599#issuecomment-767101111))

I think #14787 should have addressed this, but I'll test now to see if anything is missing

2021-04-17 03:05 UTC, gramhagen commented
hmm, i take it back, there are still several commands in the node_provider which are not covered by #14787, so we should probably keep it at 14.0.0. sorry for the confusion.

I'll continue testing this weekend

2021-04-18 14:18 UTC, gramhagen requested changes
need to roll back azure versions, new sdks are still not fully supported

2021-04-18 14:18 UTC, gramhagen commented on docker/ray-deps/Dockerfile
> +        "azure-mgmt-network==18.0.0"; fi) \
need to roll back mgmt-compute and mgmt-network for all files to following verisions

```
    "azure-cli-core==2.22.0"
    "azure-mgmt-compute==14.0.0" 
    "azure-mgmt-msi==1.0.0"
    "azure-mgmt-network==10.2.0"
```

2021-04-21 15:04 UTC, AmeerHajAli commented
@gramhagen , can you please rereview this?

2021-04-22 00:26 UTC, gramhagen approved these changes
Looks good

2021-04-22 05:22 UTC, AmeerHajAli commented
the failing test is flakey and orthogonal to this change. Merging...

2021-04-22 05:23 UTC, merged