[runtime_env] Fix the some bugs related with runtime_env
ray-project/ray pull request #15286
Opened 2021-04-14 00:40 UTC by iycheng

## Why are these changes needed?
There are two issues reported related with runtime_env:
- empty dir doesn't work
- bad error message
This PR fixes them.

## Related issue number
Closes #15254 
Closes #15255 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-04-14 17:08 UTC, edoakes requested changes

2021-04-14 17:08 UTC, edoakes commented on python/ray/_private/runtime_env.py
> +        assert isinstance(working_dir, str), f"`working_dir` is not a string."
Please don't use `assert` statements for user-facing errors. Best practice here is to use `TypeError` for a type check and `ValueError` for a value check (e.g., an int must be >= 0 or the directory must exist)

2021-04-14 17:08 UTC, edoakes commented on python/ray/_private/runtime_env.py
> +            raise IOError(f"Invalid working dir {working_dir}.")
```suggestion
            raise ValueError(f"working_dir {working_dir} must be an existing directory.")
```

2021-04-14 17:08 UTC, edoakes commented on python/ray/_private/runtime_env.py
> +        assert isinstance(py_module, str), f"`py_module` is not a string."
TypeError

2021-04-14 17:08 UTC, edoakes commented on python/ray/_private/runtime_env.py
> +            raise IOError(f"Invalid py_module {py_module}.")
ValueError. Please also make the error more actionable:
```suggestion
            raise ValueError(f"py_module {py_module} must be a path to an existing directory.")
            raise IOError(f"Invalid py_module {py_module}.")
```

2021-04-14 17:08 UTC, edoakes commented on python/ray/_private/runtime_env.py
>      if working_dir:
Add some basic tests for these checks to avoid regressions please.

2021-04-14 17:08 UTC, edoakes commented on python/ray/_private/runtime_env.py
>      if working_dir:
You can use `with pytest.raises(ValueError): ...`

2021-04-19 21:05 UTC, ericl commented
//python/ray/tests:test_runtime_env                                      FAILED in 3 out of 3 in 393.4s
  Stats over 3 runs: max = 393.4s, min = 375.7s, avg = 382.2s, dev = 8.0s
  /private/var/tmp/_bazel_travis/7c557718f3877739c657a427203800b1/execroot/com_github_ray_project_ray/bazel-out/darwin-opt/testlogs/python/ray/tests/test_runtime_env/test.log
  /private/var/tmp/_bazel_travis/7c557718f3877739c657a427203800b1/execroot/com_github_ray_project_ray/bazel-out/darwin-opt/testlogs/python/ray/tests/test_runtime_env/test_attempts/attempt_1.log
  /private/var/tmp/_bazel_travis/7c557718f3877739c657a427203800b1/execroot/com_github_ray_project_ray/bazel-out/darwin-opt/testlogs/python/ray/tests/test_runtime_env/test_attempts/attempt_2.log
Executed 47 out of 47 tests: 46 tests pass and 1 fails locally.

2021-04-21 18:31 UTC, edoakes approved these changes

2021-04-21 18:31 UTC, edoakes commented
Trusting the tests-ok flag from @iycheng

2021-04-21 18:31 UTC, merged