[DataFrame] Implement loc, iloc
ray-project/ray pull request #1612
Opened 2018-02-26 21:45 UTC by simon-mo

## What do these changes do?

This PR implements basic `loc` and `iloc` for the dataframe. 

Out of five allowed inputs, this PR implements the most commonly used three:
- [x] A single label, e.g. 5 or 'a', (note that 5 is interpreted as a label of the index, and never as an integer position along the index).
- [x] A list or array of labels, e.g. ['a', 'b', 'c'].
- [x] A slice object with labels, e.g. 'a':'f' (note that contrary to usual python slices, both the start and the stop are included!).
- ~~A boolean array.~~
- ~~A callable function with one argument (the calling Series, DataFrame or Panel) and that returns valid output for indexing (one of the above)~~

## Related issue number

2018-02-26 21:46 UTC, simon-mo commented
This PR depends on commit 9b69cfc in PR #1599

2018-02-26 22:45 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/3976/
Test PASSed.

2018-02-27 04:12 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/3988/
Test PASSed.

2018-02-27 04:36 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/3989/
Test PASSed.

2018-02-27 05:32 UTC, devin-petersohn requested changes
A couple of minor changes. Looking good!

2018-02-27 05:32 UTC, devin-petersohn commented on python/ray/dataframe/indexing.py
> +        for partition, idx_to_lookup in lookup_dict.items():
I prefer to wrap this in list comprehension:
```python
retrieved_rows_remote = [_deploy_func.remote(retrieve_func, self.df._df[partition], idx_to_lookup, col_list) for partition, idx_to_lookup in lookup_dict.items()]
```

2018-02-27 05:32 UTC, devin-petersohn commented on python/ray/dataframe/indexing.py
> +def _row_tuples_to_dict(row_tuples):
Would it be faster to do a `self._index.groupby('partition')`?

2018-02-27 08:34 UTC, devin-petersohn approved these changes
This is great! Thanks @simon-mo !

2018-02-27 09:02 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/4002/
Test PASSed.

2018-02-27 09:57 UTC, merged