Add a callback for gcs table lookup failures.
ray-project/ray pull request #1702
Opened 2018-03-12 22:12 UTC by elibol

Adds a callback for GCS table lookup failures.

2018-03-12 23:10 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/4276/
Test PASSed.

2018-03-13 18:08 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/4302/
Test PASSed.

2018-03-13 18:54 UTC, pcmoritz approved these changes

2018-03-13 18:56 UTC, pcmoritz commented
Can be merged when the tests pass (the last one is failing at the moment and needs to be fixed).

2018-03-13 20:36 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/4305/
Test PASSed.

2018-03-14 18:22 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/4328/
Test PASSed.

2018-03-14 21:13 UTC, stephanie-wang requested changes

2018-03-14 21:13 UTC, stephanie-wang commented on src/ray/gcs/redis_context.h
> +  using RedisCallback = std::function<void(const std::string &, bool is_nil)>;
Does it make sense to add this parameter for all `RedisCallbacks`? I'm a little wary of adding this when it is only used by one of the table operations.

An alternative plan would be to call the failure callback if the response is empty in the `Lookup` call. Then we can keep the changes completely local to the `Lookup` operation. The only drawback I see here is that if we won't be able to support an entry that has an empty string as the value, but I think this is probably okay.

2018-03-15 23:06 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/4350/
Test PASSed.

2018-03-16 00:31 UTC, stephanie-wang approved these changes
Looks good!

2018-03-16 01:32 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/4352/
Test PASSed.

2018-03-16 04:45 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/4354/
Test PASSed.

2018-03-16 05:25 UTC, merged

2018-03-16 05:25 UTC, elibol commented
Tests on private travis passed.