[WIP][serve] Add Ray API stability annotations
ray-project/ray pull request #17295
Opened 2021-07-23 16:18 UTC by edoakes

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-07-23 16:18 UTC, edoakes commented
@ericl this looks pretty good. I don't think we have anything that fits into the `DeveloperAPI` category (yet)

2021-07-23 17:44 UTC, simon-mo approved these changes
LGTM looks great

2021-07-23 18:36 UTC, ericl commented on python/ray/serve/api.py
> +@ray.util.annotations.PublicAPI
`from ray.util.annotations import PublicAPI`

`@PublicAPI`

2021-07-23 18:37 UTC, ericl requested changes
Please remove `ray.util.annotations.` prefix for consistency with other uses of the annotation

2021-07-26 17:18 UTC, ericl approved these changes

2021-07-27 21:00 UTC, merged