[Core] Fix GRPC Server Back Pressure
ray-project/ray pull request #17427
Opened 2021-07-29 07:20 UTC by lixin-wei

## Why are these changes needed?

Prior to this PR, we create a ServerCall in HandleRequestImpl() and delete it when it is replied and pulled again from the completion queue.

However, it will cost some time from handling the request to deleting it. If request TPS is high, tons of ServerCall will be created during this time, which will cause a huge memory usage.

This PR fixes this issue, please have a look, thanks!

## Related issue number

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-07-29 15:31 UTC, edoakes commented
@clarkzinzow can you also take a look at this? I know you recently dove into the gRPC completion queue code.

2021-07-29 15:32 UTC, edoakes commented
@lixin-wei looks like this failed to compile in the Travis build.

2021-07-29 15:40 UTC, edoakes reviewed
If I understand correctly, the behavior change here is that we now create the new `server_call` _after_ the reply callback has been called, where previously we were creating the new call _before_ even invoking the RPC handler. Please correct me if I'm wrong.

What will happen if we drain the queue of `server_call`s in this case (e.g., we have a buffer of 100 `server_call`s and we have 100 RPCs that are all outstanding)? I would assume that this would block the RPC from being handled until one of the outstanding RPCs finishes. This may cause problems in the case of e.g., asyncio actors where there may be thousands of outstanding actor calls concurrently. If that's the case, we will probably need to either (1) warn users that there's a max number of outstanding actor calls and probably default to something quite high or (2) make the limit configurable.

If we're going to merge this, we should definitely run the full suite of nightly/release benchmarks and stress tests on it. A good start would be to post the microbenchmark results before and after the PR.

2021-07-29 16:23 UTC, lixin-wei commented
> I would assume that this would block the RPC from being handled until one of the outstanding RPCs finishes.

Yeah, that's exactly what 'back pressure' means.

> This may cause problems in the case of e.g., asyncio actors where there may be thousands of outstanding actor calls concurrently. 

In this case, user actors should put the requests into their own queues, and return immediately from GRPC's handling function. From an RPC framework's vision, back pressure is necessary.

2021-07-29 16:28 UTC, lixin-wei commented
And I agree with make the limit configurable,  I've committed it.

2021-07-29 17:57 UTC, ericl commented
@lixin-wei can you say more about what scenario triggers OOM on the raylet? AFAIK, all of Ray's components implement internal back-pressure, so it should not be possible to trigger such an overload because we have backpressure at higher levels.

I also share @edoakes 's concerns about this introducing distributed deadlocks. The unfortunate matter is that certain components require many active RPCs (e.g. async long-polling waiting for object locations). The number of async RPCs can scale with the number of workers in the cluster (e.g., up to tens of thousands).

What if we made this opt in--- each server/handler can request a max limit, and we can only enforce the limit on components that aren't handling async RPCs?

2021-07-29 17:58 UTC, ericl requested changes
[see comment]

2021-07-29 18:19 UTC, lixin-wei commented
> can you say more about what scenario triggers OOM on the raylet? 
@ericl  It's in GCS, not raylet. We have a job with 50k+ actors whose creation task's argument is 100+ ActorHandles. In ActorHandle's deserialization, a GetActorInfo RPC will be sent to GCS. When this job is starting, GCS will face a 50k/s TPS of  GetActorInfo RPC. And memory usage hit 64GB+, which caused OOM.

2021-07-29 18:19 UTC, lixin-wei commented
> can you say more about what scenario triggers OOM on the raylet? 

@ericl  It's in GCS, not raylet. We have a job with 50k+ actors whose creation task's argument is 100+ ActorHandles. In ActorHandle's deserialization, a GetActorInfo RPC will be sent to GCS. When this job is starting, GCS will face a 50k/s TPS of  GetActorInfo RPC. And memory usage hit 64GB+, which caused OOM.

2021-07-29 18:23 UTC, lixin-wei commented
> What if we made this opt in--- each server/handler can request a max limit, and we can only enforce the limit on components that aren't handling async RPCs?

I think it's a good idea. Actually, I just want to fix GCS's OOM, we can apply this to GCS first, leave other components as they are.

2021-07-29 19:02 UTC, ericl commented
I see, it makes sense to enable this by default for everything in GCS-- AFAIK, there are no long-running async calls to the GCS.

2021-07-29 19:09 UTC, rkooo567 commented
Actually, we have 1 RPC now PollActorOutOfScope (just lyk). And if we replace Redis pubsub, that will also the async long polling (though gcs server will be the receiver)

2021-07-30 04:26 UTC, lixin-wei commented
@rkooo567 I can't find PollActorOutOfScope in our code base, what is it?  Could you say more about it?

2021-07-30 04:30 UTC, lixin-wei commented
@ericl @edoakes @rkooo567  So do you agree with it if I make this configurable and only apply it to GCS? If you agree I'll proceed with my PR.

2021-07-30 04:42 UTC, rkooo567 commented
It's https://github.com/ray-project/ray/blob/58c4fe727c56ff7aff182db738e629fe1fe6d4b7/src/ray/gcs/gcs_server/gcs_actor_manager.cc#L509

This means we cannot apply this to gcs server right? unless we can remove this RPC

2021-07-30 04:50 UTC, lixin-wei commented
@rkooo567 If I understand correctly, this is an RPC from GCS to CoreWorker? Adding back pressure to GCS's gRPC server won't affect this.

>if we replace Redis pubsub, that will also the async long polling (though gcs server will be the receiver)

what did you mean with 'replace Redis pubsub'? Would you please say more about this? I don't know much about the context.

2021-07-30 05:01 UTC, rkooo567 commented
Ah, I see. it is only for the server. When I said replace Redis, I meant this PR; https://github.com/ray-project/ray/pull/16723 (this will use long polling from other components -> GCS for pubsub instead of Redis). I think this will be done in a couple month, so if you can make backpressure configurable, it should be fine (and default could be no backpressure for OSS).

But I also wonder if there's way to flagging each call somehow from the client side? If it is possible, we can probably only mark long-polling RPC to be not included for the backpressure (and we technically shouldn't have many long polling RPC because it causes memory leak if there are many)

2021-07-30 05:46 UTC, ericl commented
Applying to GCS sounds good to me!

On Thu, Jul 29, 2021, 10:01 PM SangBin Cho ***@***.***> wrote:

> Ah, I see. it is only for the server. When I said replace Redis, I meant
> this PR; #16723 <https://github.com/ray-project/ray/pull/16723> (this
> will use long polling from other components -> GCS for pubsub instead of
> Redis). I think this will be done in a couple month, so if you can make
> backpressure configurable, it should be fine (and default could be no
> backpressure for OSS).
>
> But I also wonder if there's way to flagging each call somehow from the
> client side? If it is possible, we can probably only mark long-polling RPC
> to be not included for the backpressure (and we technically shouldn't have
> many long polling RPC because it causes memory leak if there are many)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ray-project/ray/pull/17427#issuecomment-889629078>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAADUSVWVP7VO3HJR7O2L5LT2IW2VANCNFSM5BF3OLFQ>
> .
>

2021-07-30 06:16 UTC, lixin-wei commented
@rkooo567 Yeah, If we replace Redis with gRPC based pubsub, there will be a lot of long pollings to GCS.

> But I also wonder if there's way to flagging each call somehow from the client side? 

It's not easy to do this. But it's easy to make it configurable for every service(disabled by default). I'll add back pressure to all GCS's services now. @wuisawesome you don't need to worry about this in <https://github.com/ray-project/ray/pull/16723> because it's disabled by default, which won't affect the service you created in that PR.

2021-07-30 06:18 UTC, rkooo567 commented
SGTM!

2021-07-30 13:03 UTC, lixin-wei commented
I'm done. Would please have a look?

(BTW, the code of RPC part is pretty nasty, I've a hard time reading it. We should refactor it in the future.

2021-07-30 18:32 UTC, ericl requested changes
LGTM, only stylistic requests

2021-07-30 18:32 UTC, ericl commented on src/ray/common/ray_config_def.h
> +RAY_CONFIG(int64_t, gcs_default_back_pressure_limit_per_service, 100)
```suggestion
RAY_CONFIG(int64_t, gcs_max_active_rpcs_per_service, 100)
```

2021-07-30 18:32 UTC, ericl commented on src/ray/rpc/grpc_server.h
> +#define RPC_SERVICE_HANDLER_WITH_BACK_PRESSURE(SERVICE, HANDLER, BACK_PRESSURE_NUM) \
Consider consolidating this with the original, and explicitly passing a limit of -1 for services that don't support backpressure.

2021-07-30 18:32 UTC, ericl commented on src/ray/rpc/server_call.h
> +  virtual int64_t GetBackPressureLimit() const = 0;
```suggestion
  virtual int64_t GetMaxActiveRPCs() const = 0;
```

2021-07-30 18:32 UTC, ericl commented on src/ray/rpc/server_call.h
> +    if (factory.GetBackPressureLimit() == -1) {
```suggestion
    if (factory.GetMaxActiveRPCs() == -1) {
```

2021-07-30 18:32 UTC, ericl commented on src/ray/rpc/server_call.h
> +      int64_t back_pressure_limit = -1)
```suggestion
      int64_t max_active_rpcs = -1)
```

2021-07-30 18:32 UTC, ericl commented on src/ray/rpc/server_call.h
> +  uint64_t back_pressure_limit_;
```suggestion
  uint64_t max_active_rpcs_;
```

2021-08-03 09:03 UTC, rkooo567 commented
The failure from `tests:test_placement_group ` seems quite suspicious.

2021-08-03 09:06 UTC, lixin-wei commented
@rkooo567 Yeah, I'm trying to find out why.

2021-08-04 07:06 UTC, lixin-wei commented
I can't reproduce the failed test in my local machine, pull master and retry.

2021-08-04 12:30 UTC, lixin-wei commented
CI passed, would you please have a look? The streaming test failure is a known issue related to the CI framework.

You may take attention to this change:

https://github.com/ray-project/ray/pull/17427/files#diff-116723aef6c907367b1b8591aa9e2ad395e7e6a2e9a94c27ec16633c877236b7R180-R184

I add no limit to Register/Create actor handler because CreateActor is a long polling RPC. It will be replied to until raylet successfully schedules the creation task. If there are no resources, GCS will hold a lot of CreateActor RPCs, once it reaches the backpressure limit, GCS won't receive any CreateActor requests anymore. But the incoming actors might be schedulable(if the actor requires small resources).

2021-08-04 17:36 UTC, ericl approved these changes

2021-08-04 17:36 UTC, merged