[very WIP] Try adding tensor block support
ray-project/ray pull request #17439
Opened 2021-07-29 18:32 UTC by ericl

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-07-29 19:17 UTC, ericl commented
@clarkzinzow I'm hacking on this in spare time, feel free to push improvements

2021-08-02 04:11 UTC, wuisawesome commented on python/ray/experimental/data/datasource/datasource.py
> +                return np.ones(tensor_shape) * np.expand_dims(
`return np.arange(start, start+count, shape=tensor_shape`?

2021-08-02 04:12 UTC, wuisawesome commented on python/ray/experimental/data/datasource/datasource.py
> +                return np.ones(tensor_shape) * np.expand_dims(
I think we should be able to avoid matrix multiplication here.

2021-08-02 04:18 UTC, wuisawesome requested changes
Can you add a test that writes the tensor using `np.savefile` and then loads it using `ds.read_numpy()` (this type of test case wasn't actually trivial in the case of other data sources)?

2021-08-02 05:05 UTC, ericl reviewed
Test added

2021-08-02 05:38 UTC, wuisawesome approved these changes

2021-08-02 05:45 UTC, merged