[Serve] Add replica tag to request counter and error counter
ray-project/ray pull request #17613
Opened 2021-08-05 14:41 UTC by architkulkarni

## Why are these changes needed?
After looking at the implementation, the metrics `serve_backend_request_counter` and `serve_backend_error_counter` seem to be scoped to per-replica, not per-backend, but we just weren't tagging them with the replica.  This PR adds the replica tag to these metrics.  It might make sense to rename these metrics with `replica` instead of `backend` but I think we are changing them to `deployment` soon anyway.

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-08-05 17:58 UTC, edoakes approved these changes

2021-08-05 18:03 UTC, simon-mo requested changes

2021-08-05 18:03 UTC, simon-mo commented on python/ray/serve/backend_worker.py
>              tag_keys=("backend", ))
you need to specify the tag_keys here to include replica

2021-08-05 18:03 UTC, simon-mo commented on python/ray/serve/backend_worker.py
>              tag_keys=("backend", ))
add to tag_keys

2021-08-05 18:05 UTC, edoakes commented
@architkulkarni test is failing because the replica isn't added in the tag_keys:
https://buildkite.com/ray-project/ray-builders-pr/builds/10728#74d803bf-bdba-4be4-9a9f-7ac0c4931730/6-8366

2021-08-05 18:05 UTC, edoakes commented
Oh yeah what Simon said ^

2021-08-06 20:39 UTC, architkulkarni commented
The failing test is //python/ray/tests:test_kill_raylet_signal_log on windows, which is known flaky on master

2021-08-06 22:35 UTC, simon-mo approved these changes

2021-08-06 22:35 UTC, merged