[tune] Change tune resource request syntax to be less confusing
ray-project/ray pull request #1764
Opened 2018-03-21 22:22 UTC by ericl

## What do these changes do?

This renames resources => trial_resources, and cpu / driver_cpu_limit => cpu / extra_cpu.

## Related issue number

https://github.com/ray-project/ray/issues/1759

2018-03-21 23:17 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/4458/
Test PASSed.

2018-03-22 05:51 UTC, richardliaw commented on python/ray/tune/config_parser.py
>          "'{\"cpu\": 64, \"gpu\": 8}'. Note that GPUs will not be assigned "
I think this needs to be fixed

2018-03-22 05:56 UTC, richardliaw requested changes

2018-03-22 05:56 UTC, richardliaw commented on python/ray/tune/experiment.py
>              e.g. ``{"cpu": 64, "gpu": 8}``. Note that GPUs will not be
same with this

2018-03-22 05:56 UTC, richardliaw commented on python/ray/tune/config_parser.py
>          "'{\"cpu\": 64, \"gpu\": 8}'. Note that GPUs will not be assigned "
I think this needs to be fixed

2018-03-22 05:56 UTC, richardliaw commented on python/ray/rllib/train.py
> +                "trial_resources": resources_to_json(args.resources),
args.trial_resources?

2018-03-22 05:56 UTC, richardliaw commented on examples/carla/train_a3c.py
> +        "trial_resources": {"cpu": 5, "gpu": 2, "driver_gpu_limit": 0},
driver_gpu_limit deprecated

2018-03-22 17:56 UTC, ericl reviewed
Updated

2018-03-22 18:20 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/4470/
Test FAILed.

2018-03-22 18:40 UTC, richardliaw approved these changes

2018-03-22 18:51 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/4471/
Test PASSed.

2018-03-23 05:30 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/4480/
Test PASSed.

2018-03-23 13:25 UTC, merged