[usability] ray status show demand summary
ray-project/ray pull request #17892
Opened 2021-08-17 08:12 UTC by scv119

## Why are these changes needed?

## Related issue number

#15867

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-08-17 14:37 UTC, wuisawesome commented
This looks great to me. @richardliaw do you have any ux comments?

2021-08-17 17:41 UTC, rkooo567 commented
I think we should also format the usage?

2021-08-17 19:28 UTC, richardliaw commented
Usage formatting +1

On Tue, Aug 17, 2021 at 10:41 AM SangBin Cho ***@***.***>
wrote:

> I think we should also format the usage?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ray-project/ray/pull/17892#issuecomment-900502550>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABCRZZKAMKPLU7PLFBJYAT3T5KNLNANCNFSM5CJKBLNA>
> .
>

2021-08-17 23:03 UTC, scv119 commented
actually it's a bit confusing to show per replacement group resource usage; mostly because the capacity adds up exceeds the physical capacity.
so instead we just not showing per replacement group resource unless `ray status --verbose` is specified.

2021-08-17 23:09 UTC, richardliaw commented
That is really nice!

On Tue, Aug 17, 2021 at 4:03 PM Chen Shen ***@***.***> wrote:

> actually it's a bit confusing to show per replacement group resource
> usage; mostly because the capacity adds up exceeds the physical capacity.
> so instead we just not showing per replacement group resource unless ray
> status --verbose is specified.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ray-project/ray/pull/17892#issuecomment-900687515>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABCRZZNQH3ADLK6KSA7JRT3T5LTEBANCNFSM5CJKBLNA>
> .
>

2021-08-17 23:15 UTC, ericl requested changes
This is actually losing a lot of the important information right? Can we scope it to just to the placement groups or otherwise avoid losing info via aggregation?

2021-08-17 23:19 UTC, scv119 commented
@ericl  so with this PR if we run `ray status --verbose` it works as the same as the previous version. does that work or we should limit the change to placement group only?

2021-08-17 23:25 UTC, richardliaw commented
my 2c is that I like the direction of hiding those placement group names - it's quite hard to parse otherwise.

To avoid loss of info, we should at least have a summary indicator about placement groups usage (how many placements are created), and a hint for the user as to what they need to do to see the placement group usage.

2021-08-17 23:25 UTC, ericl commented
Hmm I was thinking the main fix would be to "handle placement groups" properly in the original display:

For example:
```
CPU: 16.0/16.0 (8.0 reserved in placement groups)
```

```
{"CPU": 1}: 10+ pending tasks/actors (3+ using placement groups)
```

2021-08-18 00:29 UTC, scv119 commented
just so that we are agree on the same design, is this the new output we are looking for? (in form of diff):

```
 Resources
 ------------------------------------------------------------
 Usage:
- 16.0/16.0 CPU
- 0.0/16.0 CPU_group_0_625ace126f848864c46f50dced5e0ef7
- 10.0/16.0 CPU_group_625ace126f848864c46f50dced5e0ef7
+ 16.0/16.0 CPU (10.0 reserved in placement groups)
  0.00/19.004 GiB memory
  0.00/9.502 GiB object_store_memory

 Demands:
- {'CPU_group_625ace126f848864c46f50dced5e0ef7': 10.0}: 1+ pending tasks/actors
- {'CPU': 100.0}: 1+ pending tasks/actors
+ {'CPU': 100.0}: 2+ pending tasks/actors (1+ using placement groups)
  {'memory': 2040588533900.0} * 1 (STRICT_PACK): 2+ pending placement groups
  {'GPU': 2.0} * 1, {'extra_resource': 2.0} * 1 (STRICT_PACK): 1+ pending placement groups
  {'CPU': 16.0} * 1, {'memory': 2040588533900.0} * 1 (STRICT_PACK): 1+ pending placement groups
```

2021-08-18 00:35 UTC, ericl commented
Diff LGTM

On Tue, Aug 17, 2021, 5:29 PM Chen Shen ***@***.***> wrote:

> just so that we are agree on the same design, is this the new output we
> are looking for? (in form of diff):
>
>  Resources
>  ------------------------------------------------------------
>  Usage:
> - 16.0/16.0 CPU
> - 0.0/16.0 CPU_group_0_625ace126f848864c46f50dced5e0ef7
> - 10.0/16.0 CPU_group_625ace126f848864c46f50dced5e0ef7
> + 16.0/16.0 CPU (10.0 reserved in placement groups)
>   0.00/19.004 GiB memory
>   0.00/9.502 GiB object_store_memory
>
>  Demands:
> - {'CPU_group_625ace126f848864c46f50dced5e0ef7': 10.0}: 1+ pending tasks/actors
> - {'CPU': 100.0}: 1+ pending tasks/actors
> + {'CPU': 100.0}: 2+ pending tasks/actors (1+ using placement groups)
>   {'memory': 2040588533900.0} * 1 (STRICT_PACK): 2+ pending placement groups
>   {'GPU': 2.0} * 1, {'extra_resource': 2.0} * 1 (STRICT_PACK): 1+ pending placement groups
>   {'CPU': 16.0} * 1, {'memory': 2040588533900.0} * 1 (STRICT_PACK): 1+ pending placement groups
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ray-project/ray/pull/17892#issuecomment-900721343>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAADUSTRUF4NOQ7VLHZ5KFLT5L5HTANCNFSM5CJKBLNA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-18 02:01 UTC, scv119 commented
actually the tasks/actors are not grouped so here is the diff after update:
```
 Resources
 ------------------------------------------------------------
 Usage:
- 16.0/16.0 CPU
- 0.0/16.0 CPU_group_0_625ace126f848864c46f50dced5e0ef7
- 10.0/16.0 CPU_group_625ace126f848864c46f50dced5e0ef7
+ 16.0/16.0 CPU (10.0 reserved in placement groups)
  0.00/19.004 GiB memory
  0.00/9.502 GiB object_store_memory

 Demands:
- {'memory_group_625ace126f848864c46f50dced5e0ef7': 10.0, 'CPU_group_625ace126f848864c46f50dced5e0ef7': 10000.0}: 1+ pending tasks/actors
- {'GPU_group_4a133bab2f93fe4a104533be2d51f85a': 10.0}: 5+ pending tasks/actors
+ {'memory': 10.0, 'CPU': 10000.0}: 1+ pending tasks/actors (using placement group 625ace126f848864c46f50dced5e0ef7)
+ {'GPU': 10.0}: 5+ pending tasks/actors (using placement group 4a133bab2f93fe4a104533be2d51f85a)
  {'CPU': 100.0}: 1+ pending tasks/actors
  {'CPU': 30.0, 'GPU': 2.0}: 3+ pending tasks/actors
  {'memory': 2040588533900.0} * 1 (STRICT_PACK): 2+ pending placement groups
  {'GPU': 2.0} * 1, {'extra_resource': 2.0} * 1 (STRICT_PACK): 1+ pending placement groups
  {'CPU': 16.0} * 1, {'memory': 2040588533900.0} * 1 (STRICT_PACK): 1+ pending placement groups
```

2021-08-18 05:48 UTC, ericl commented
> + {'memory': 10.0, 'CPU': 10000.0}: 1+ pending tasks/actors (using placement group 625ace126f848864c46f50dced5e0ef7)

Question for this, if there are many placement groups would the line get too long? Might be better to just have a count.

2021-08-18 19:53 UTC, scv119 commented
hmm currently if we have many placement groups they will be showed in different lines like following:
```
 {'memory': 10.0, 'CPU': 10.0}: 1+ pending tasks/actors (using placement group 625ace126f848864c46f50dced5e0ef7)
 {'memory': 12.0, 'CPU': 8.0}: 1+ pending tasks/actors (using placement group 4a133bab2f93fe4a104533be2d51f85a)
```
are you suggesting we showing this?
```
 {'memory': 10.0, 'CPU': 10.0}: 1+ pending tasks/actors (1+ using placement group)
 {'memory': 12.0, 'CPU': 8.0}: 1+ pending tasks/actors (1+ using placement group)
```

2021-08-18 20:31 UTC, ericl commented
If the two demand bundles are the same size (say 1 CPU each), which is the common case, I do expect them to be aggregated, for example:

bad:
```
 {'CPU': 1.0}: 7+ pending tasks
 {'CPU': 1.0}: 1+ pending tasks/actors (using placement group 625ace126f848864c46f50dced5e0ef7)
 {'CPU': 1.0}: 1+ pending tasks/actors (using placement group 4a133bab2f93fe4a104533be2d51f85a)
 {'CPU': 1.0}: 1+ pending tasks/actors (using placement group 123451234512342893472937498324)
```

good:
```
 {CPU': 1.0}: 10+ pending tasks/actors (3+ using placement groups)
```

2021-08-18 20:36 UTC, wuisawesome commented
Actually a higher level question about that: shouldn't we not show those demands at all? they're an implementation detail of placement groups (i.e. the autoscaler will never be able to fulfill those demands, they should only show up as demands if the placement group itself can't be placed).

2021-08-18 21:34 UTC, ericl commented
We are only showing demands if the placement group / task / actor isn't
placed (pending); if everything's placed the list should already be empty.

Eric


On Wed, Aug 18, 2021 at 1:36 PM Alex Wu ***@***.***> wrote:

> Actually a higher level question about that: shouldn't we not show those
> demands at all? they're an implementation detail of placement groups (i.e.
> the autoscaler will never be able to fulfill those demands, they should
> only show up as demands if the placement group itself can't be placed).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ray-project/ray/pull/17892#issuecomment-901413690>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAADUSVPW4I7TI3BE7WLETDT5QKVVANCNFSM5CJKBLNA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-19 18:25 UTC, ericl approved these changes
The output LGTM

2021-08-19 18:25 UTC, ericl commented on python/ray/autoscaler/_private/util.py
> +def get_demand_report(lm_summary):
Add types?

2021-08-19 18:25 UTC, ericl commented on python/ray/autoscaler/_private/util.py
> +    def filter_placement_group_from_bundle(bundle):
types?

2021-08-19 21:12 UTC, scv119 commented on python/ray/autoscaler/_private/load_metrics.py
> +def add_resources(dict1: Dict[str, float],
move from util to here to solve circular dependency when using the LoadMetricsSummary type

2021-08-20 22:29 UTC, merged