[Client] Skip object ref dealloc if client package has already been cleaned up
ray-project/ray pull request #17969
Opened 2021-08-19 22:36 UTC by ckw017

## Why are these changes needed?

Check is client package has already been set to None when deallocating object refs

## Related issue number

Closes #17968

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-08-19 23:21 UTC, ijrsvt approved these changes
LGTM!

2021-08-20 03:37 UTC, ckw017 commented
Failures (windows:test_advanced and windows:test_advanced_client) very likely unrelated (both at 20% failure rate, 100% over the last ~10 runs). Reviewers can merge at discretion.

2021-08-20 15:43 UTC, ijrsvt requested changes
Sorry for the last-minute change, but can you also modify the [ClientActorRef](https://github.com/ray-project/ray/blob/9416fce91b38d4a028be5ac97e3d0d271a7db378/python/ray/includes/unique_ids.pxi#L316)

2021-08-20 16:45 UTC, AmeerHajAli commented on python/ray/util/client/common.py
> +        if ray is None:
how about client?
Can you please add a comment here please?

2021-08-20 16:45 UTC, AmeerHajAli commented on python/ray/includes/unique_ids.pxi
> +        if client is None or client.ray is None:
Can you please add a comment here?

2021-08-20 21:08 UTC, AmeerHajAli approved these changes

2021-08-20 21:52 UTC, ckw017 commented
Windows failure unrelated

2021-08-20 22:17 UTC, ijrsvt approved these changes
LGTM! Thanks Chris!

2021-08-20 22:18 UTC, ijrsvt commented
Windows failure is unrelated (happening on master as well & on a non-client test): 
<img width="604" alt="Screen Shot 2021-08-20 at 3 18 23 PM" src="https://user-images.githubusercontent.com/21353794/130298655-89277103-29db-4ff0-b4a2-8d74ebca0987.png">

2021-08-20 22:18 UTC, merged