[tune] Update trial resources on resume.
ray-project/ray pull request #17975
Opened 2021-08-20 05:45 UTC by xwjiang2010

## Why are these changes needed?
Allow users to reconfigure trial resources, when tune job is resumed.

## Related issue number

Closes #15570

## Checks

- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [X] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-08-20 05:48 UTC, xwjiang2010 commented
Kai, I am curious to learn how two people can collaborate on a PR. I created a new one in this case but Antoni's comments are lost then :(

2021-08-20 07:57 UTC, krfricke reviewed
Very nice! Added a minor suggestion.

To collaborate on a PR, you would have to add my fork as a remote in git

```
git remote add krfricke git@github.com:krfricke/ray.git
```

Then fetch the PR branch

```
git fetch krfricke tune_restore_resources
```

And create a branch from there

```
git branch -d tune_restore_resources krfricke/tune_restore_resources
```

And you can then push your changes to the branch

```
git push krfricke tune_restore_resources
```

2021-08-20 07:57 UTC, krfricke commented on python/ray/tune/tests/test_tune_restore.py
> +                callbacks=[self.FailureInjectorCallback()],
Should we add a `self.CheckTrialResourcesCallback(1)` here as well?

2021-08-20 07:57 UTC, krfricke commented on python/ray/tune/tests/test_tune_restore.py
> +                self._checked = True
```suggestion
        def __init__(self, expected_new_cpu: int, check_after: int = 20):
            self._expected_new_cpu = expected_new_cpu
            self._check_after = check_after
            self._checked = False

        def on_step_begin(self, iteration: int, trials: List["Trial"], **info):
            if not self._checked and iteration >= self._check_after:
                for trial in trials:
                    if trial.status == Trial.PENDING:
                        assert trial.resources.cpu == self._expected_new_cpu
                    self._checked = True
```

This ensures that the code path is reached at least once, and only after a certain amount of step iterations. This shouldn't make a difference for the restored trial runner (as the Trial objects are recreated) but will make a difference if we add the callback to the first check (with the failure callback), as trials will not be generated, yet, on the first call of this callback.

2021-08-23 15:57 UTC, xwjiang2010 commented
> Very nice! Added a minor suggestion.
> 
> To collaborate on a PR, you would have to add my fork as a remote in git
> 
> ```
> git remote add krfricke git@github.com:krfricke/ray.git
> ```
> 
> Then fetch the PR branch
> 
> ```
> git fetch krfricke tune_restore_resources
> ```
> 
> And create a branch from there
> 
> ```
> git branch -d tune_restore_resources krfricke/tune_restore_resources
> ```
> 
> And you can then push your changes to the branch
> 
> ```
> git push krfricke tune_restore_resources
> ```

Got it, thanks!

2021-08-26 07:39 UTC, krfricke requested changes
We need one more change here - if you're happy with it you can just commit the suggestion directly in github.

2021-08-26 21:20 UTC, Yard1 reviewed
I've got nothing else to add to what @krfricke has said already :)

2021-08-27 07:11 UTC, krfricke approved these changes

2021-08-27 07:12 UTC, merged