Fix new serve api to retrive endpoints in benchmark
ray-project/ray pull request #18050
Opened 2021-08-24 19:04 UTC by jiaodong

## Why are these changes needed?

Current benchmark is broken on master since `list_endpoints` API is gone in serve's init. 

## Test plan

locally execute both single and multi deployment and ensure they pass.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-08-24 20:38 UTC, edoakes requested changes

2021-08-24 20:38 UTC, edoakes commented on release/serve_tests/workloads/multi_deployment_1k_noop_replica.py
> +        ray.get(serve_client._controller.get_all_endpoints.remote()).keys())
let's not use internal APIs or it'll break. use `serve.list_deployments()`

2021-08-24 20:58 UTC, simon-mo commented
to catch breakage easier, can you add a dry-run mode that runs through single iteration with small nodes and run add it to CI?

2021-08-24 20:59 UTC, simon-mo commented
actually, if you can't find a way to do it in short amount of time, I can do it as a follow up

2021-08-24 21:00 UTC, jiaodong commented
> actually, if you can't find a way to do it in short amount of time, I can do it as a follow up

happy to learn how to enable it but probably much faster if you have an example to follow :)

2021-08-24 21:08 UTC, simon-mo commented
So Ray tune's example directory is a great example, their script support `--smoke-test` flag and this flag is turned on for running in CI builds (prs and master builds) https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/pbt_example.py

2021-08-25 16:25 UTC, edoakes approved these changes

2021-08-25 16:27 UTC, edoakes commented on python/ray/serve/BUILD
> +    visibility = ["//python/ray/serve:__subpackages__", "//release:__pkg__"],
what's this for btw?

2021-08-25 16:28 UTC, edoakes commented
@jiaodong ping me when this is ready to merge please.

2021-08-25 17:26 UTC, merged