[tune] Conditional search space example using hyperopt
ray-project/ray pull request #18130
Opened 2021-08-26 19:45 UTC by ryanlmelvin

## Why are these changes needed?

Provides an example of conditional search spaces.

## Related issue number

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-08-26 21:22 UTC, Yard1 requested changes
Awesome, thanks! Could you also update the docs to include the example and ensure it runs in CI? You can follow this PR as a guide: https://github.com/ray-project/ray/pull/17464 

Also, please run the linting script in `scripts/format.sh` to make Lint CI pass!

2021-08-30 19:39 UTC, ryanlmelvin commented
@Yard1 I think I've made the changes you wanted: conf and doc files updated. CI ran without error locally. Please review.

2021-08-30 19:52 UTC, Yard1 commented on doc/source/tune/examples/hyperopt_conditional_search_space_example.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
hyperopt_conditional_search_space_example
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

2021-08-30 19:52 UTC, Yard1 commented on doc/source/tune/examples/hyperopt_conditional_search_space_example.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
hyperopt_conditional_search_space_example
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

2021-08-30 19:53 UTC, Yard1 approved these changes
Yep, looks good! Waiting for CI to pass.

2021-08-30 22:48 UTC, Yard1 commented on python/ray/tune/examples/hyperopt_conditional_search_space_example.py
> +    : unpacked dictionary
```suggestion
    Unpacks all sub-dictionaries in given dictionary recursively.
    There should be no duplicated keys across all nested
    subdictionaries, or some instances will be lost without warning

    Source: https://www.kaggle.com/fanvacoolt/tutorial-on-hyperopt

    Parameters:
    ----------------
    dct : dictionary to unpack

    Returns:
    ----------------
    : unpacked dictionary
```

2021-08-31 15:06 UTC, krfricke approved these changes
Thanks, this is great!

2021-08-31 15:06 UTC, merged