Retry application-level error by default for datasets
ray-project/ray pull request #18296
Opened 2021-09-02 03:40 UTC by jjyao

## Why are these changes needed?

## Related issue number

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-09-02 18:42 UTC, ericl requested changes

2021-09-02 18:42 UTC, ericl commented on python/ray/_raylet.pyx
> +                        logger.info("Application-level error was raised"
```suggestion
                        logger.info("Task failed with retryable exception: {}"
```

2021-09-02 18:42 UTC, ericl commented on python/ray/data/datasource/file_based_datasource.py
>          def write_block(write_path: str, block: Block):
Can you actually make this use cached_remote_fn, and move the retry exceptions flag into the cached_remote_fn fn?

2021-09-02 18:42 UTC, ericl commented on python/ray/data/impl/compute.py
> +        kwargs = {**{"retry_exceptions": True}, **remote_args}
Let's move this into cached_remote_fn.

2021-09-02 18:42 UTC, ericl commented on python/ray/data/read_api.py
> +        remote_read = ray.remote(**default_ray_remote_args)(remote_read)
Move to cached_remote_fn

2021-09-03 00:43 UTC, ericl approved these changes

2021-09-03 00:44 UTC, ericl commented
Oh one more thing, can you add a unit test?

2021-09-03 17:11 UTC, jjyao commented
> Oh one more thing, can you add a unit test?

Yea, added one.

2021-09-03 21:21 UTC, merged