Do not run RLlib learning and stress tests as smoke tests.
ray-project/ray pull request #18623
Opened 2021-09-15 06:14 UTC by gjoliver

## Why are these changes needed?

Looking at learning_tests, I noticed that these are currently being run as smoke tests.
These learning tests typically need more than an hour of time to finish/pass the critieria.
So all of them basically timeout right now.
I think they should not be run as smoke-test?

Also comment out a learning test that still errors out right now, due to incompatible tensorflow-probability version.

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [*] Release tests
   - [ ] This PR is not tested :(

2021-09-15 06:42 UTC, sven1977 commented
Hey, can we not disable the SmokeTest flag for these two? These are both really long running tests and they would otherwise run every day now for several hours. We should rather make sure that the SmokeTest wrapping works well inside the respective scripts, which are `release/rllib_tests/learning_tests/run.py` and `release/rllib_tests/stress_tests/run.py`. These two scripts take a --smoke-test arg and this should be properly forwarded to the `rllib/utils/test_utils.py::run_learning_tests_from_yaml()` function, which should probably just set the `time_total_s` to 300 (rather than 900 right now).
The hard timeout for this test is set in `release/rllib_tests/rllib_tests.yaml`:

```
  smoke_test:
      run:
        timeout: 900
      cluster:
        compute_template: 4gpus_64cpus.yaml

```

So I think this is where the actual conflict is right now. The entire test has a timeout of 15min, but the tune run alone is set to run for 15min.

2021-09-15 06:43 UTC, sven1977 commented
I'm not sure about tfp. It does run fine with tf=2.4.3, at least tfp==0.12 does. Let's upgrade to tf==2.5.0 and ftp==0.13.0 first, then we shouldn't need to uncomment this test.

2021-09-15 06:44 UTC, sven1977 requested changes
Left some comments on the SmokeTest and uncommenting the SAC learning test.
Thanks for looking into this @gjoliver !

2021-09-16 08:02 UTC, gjoliver commented
ok, I will revert this PR for now. we can discuss a bit after everything turns green :)

2021-09-16 08:02 UTC, closed without merging