[GCP] Add `conda` to the path when possible.
ray-project/ray pull request #18653
Opened 2021-09-15 20:28 UTC by ijrsvt

## Why are these changes needed?
* When not in Docker, conda is sometimes not properly configured
* This is similar to what we do on AWS https://github.com/ray-project/ray/blob/8a72824c63dbae9d8d189ce9c553c2e8c4299494/python/ray/autoscaler/aws/defaults.yaml#L126

## Related issue number

Closes https://github.com/ray-project/ray/issues/16539

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-09-15 20:29 UTC, richardliaw commented
@ijrsvt wow, nice work! 

Can you help me understand what the issue was/how you diagnosed this?

2021-09-15 22:28 UTC, ijrsvt commented
@richardliaw The main way that I debugged the issue was through:
1. Running `ray up repro.yaml -vvvvvv -y`
2. I found the failed SSH command (
)
3. I reran the failed SSH command  (
```
ssh -tt -i /home/ubuntu/.ssh/<redacted>.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_1d41c853af/009574a457/%C -o ControlPersist=10s -o ConnectTimeout=120s \
    ubuntu@34.127.87.64 bash --login -c -i \
    'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (which ray || pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl)'
```
)
4. The error was `ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl is not a supported wheel on this platform.`
5. I then modified the command to run `which python` and saw that it was using `/usr/bin/python`.
6. I ran `ray attach repro.yaml` and ran `which python` and saw it was `/opt/conda/bin/python`. I also saw that `/usr/bin/python` is **Python 2.7**

2021-09-15 23:15 UTC, DmitriGekhtman approved these changes
Thanks!
lgtm if it works

2021-09-17 08:12 UTC, richardliaw commented
Hey @ijrsvt this still doesn't fix it for me. 

```
    (1/3) which ray || pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
    Running `which ray || pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl`
      Full command is `ssh -tt -i /Users/rliaw/.ssh/ray-autoscaler_gcp_us-west1_loyal-oath-286321_ubuntu_0.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_97b4747bb8/c21f969b5f/%C -o ControlPersist=10s -o ConnectTimeout=120s ubuntu@35.233.175.3 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (which ray || pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl)'`
Collecting ray==2.0.0.dev0
  Downloading https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl (53.9 MB)
     |████████████████████████████████| 53.9 MB 170 kB/s
Collecting filelock
  Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)
Requirement already satisfied: attrs in /opt/conda/lib/python3.7/site-packages (from ray==2.0.0.dev0) (21.2.0)
Requirement already satisfied: grpcio>=1.28.1 in /opt/conda/lib/python3.7/site-packages (from ray==2.0.0.dev0) (1.38.1)
Requirement already satisfied: click>=7.0 in /opt/conda/lib/python3.7/site-packages (from ray==2.0.0.dev0) (8.0.1)
Collecting msgpack<2.0.0,>=1.0.0
  Downloading msgpack-1.0.2-cp37-cp37m-manylinux1_x86_64.whl (273 kB)
     |████████████████████████████████| 273 kB 7.0 MB/s
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.7/site-packages (from ray==2.0.0.dev0) (5.4.1)
Requirement already satisfied: protobuf>=3.15.3 in /opt/conda/lib/python3.7/site-packages (from ray==2.0.0.dev0) (3.16.0)
Collecting redis>=3.5.0
  Downloading redis-3.5.3-py2.py3-none-any.whl (72 kB)
     |████████████████████████████████| 72 kB 871 kB/s
Requirement already satisfied: numpy>=1.16 in /opt/conda/lib/python3.7/site-packages (from ray==2.0.0.dev0) (1.19.5)
Requirement already satisfied: importlib-metadata in /opt/conda/lib/python3.7/site-packages (from click>=7.0->ray==2.0.0.dev0) (4.8.1)
Requirement already satisfied: six>=1.5.2 in /opt/conda/lib/python3.7/site-packages (from grpcio>=1.28.1->ray==2.0.0.dev0) (1.16.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /opt/conda/lib/python3.7/site-packages (from importlib-metadata->click>=7.0->ray==2.0.0.dev0) (3.10.0.0)
Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.7/site-packages (from importlib-metadata->click>=7.0->ray==2.0.0.dev0) (3.5.0)
Shared connection to 35.233.175.3 closed.
2021-09-17 01:11:24,485	INFO node.py:295 -- wait_for_compute_zone_operation: Waiting for operation operation-1631866283897-5cc2c7a2c30b1-40acbd79-a7650d40 to finish...
2021-09-17 01:11:30,034	INFO node.py:307 -- wait_for_compute_zone_operation: Operation operation-1631866283897-5cc2c7a2c30b1-40acbd79-a7650d40 finished.
  New status: update-failed
  !!!
  {'message': 'SSH command failed.'}
  SSH command failed.
  !!!

  Failed to setup head node.
```

2021-09-17 08:17 UTC, richardliaw commented
Actually, @ijrsvt I think the fundamental issue of #16539 is not that the config is wrong, but rather that stderr from the command execution is not being piped properly.

For example, when I run `ray up`, I get no error message. However, when I run the pip install command via ssh manually, I actually get the error message.

2021-09-17 08:18 UTC, richardliaw requested changes
See above comment

2021-09-17 15:29 UTC, ijrsvt commented
@richardliaw Let me fix that as well, but conda is also a bug here.

2021-09-17 21:23 UTC, ijrsvt commented
@richardliaw I'm genuinely not sure why this message is getting swallowed. I think it is some weird race-y condition of it getting swallowed :(

Normal STDERR & STDOUT **do get printed correctly**, but not in this case 



Could you retry this PR, but using `--no-config-cache`?

2021-09-18 21:38 UTC, richardliaw commented
Got it; is it possible to reproduce in your side btw?

On Fri, Sep 17, 2021 at 2:23 PM Ian Rodney ***@***.***> wrote:

> @richardliaw <https://github.com/richardliaw> I'm genuinely not sure why
> this message is getting swallowed. I think it is some weird race-y
> condition of it getting swallowed :(
>
> Normal STDERR & STDOUT *do get printed correctly*, but not in this case
>
> Could you retry this PR, but using --no-config-cache?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/ray-project/ray/pull/18653#issuecomment-922089738>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABCRZZIIVWQF3LTFJDZWF5DUCOWVXANCNFSM5EDH5KAQ>
> .
>

2021-09-20 01:13 UTC, DmitriGekhtman commented
This fix works for me -- can we merge it and work on `ray up` error output as a separate issue?

2021-09-20 06:06 UTC, richardliaw approved these changes
approving for now

2021-09-20 06:06 UTC, merged

2021-09-20 06:06 UTC, richardliaw commented
Thanks a bunch for the fast fix, @ijrsvt !

2021-09-20 16:18 UTC, ijrsvt commented
@richardliaw yep, I can definitely repro this and it's pretty puzzling.

> This fix works for me (with no config cache) -- can we merge it and work on ray up error output as a separate issue?

I 100% agree with this, does this sound good @richardliaw ?