[rllib] Adding DDPG (adapted from baselines)
ray-project/ray pull request #1868
Opened 2018-04-10 10:20 UTC by qyccc

## What do these changes do?
Add the algorithm ddpg in rllib.
It can run using the same command as 'python ray/python/ray/rllib/train.py --run DDPG --env MountainCarContinuous-v0'.

## Related issue number

2018-04-10 10:52 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/4779/
Test FAILed.

2018-04-10 16:50 UTC, richardliaw commented
Thanks for contributing this! Do you have any performance numbers/charts?

2018-04-10 16:54 UTC, richardliaw requested changes
Thanks a bunch for contributing this! Do you mind running `flake8` on `rllib/ddpg/` and fixing the errors that show up?

2018-04-10 16:54 UTC, richardliaw commented on python/ray/rllib/__init__.py
> +                "__sigmoid_fake_data", "__parameter_tuning", "DDPG"]:
do you mind moving this before the private keys?

2018-04-10 16:54 UTC, richardliaw commented on python/ray/rllib/ddpg/models.py
> +        x = tf.layers.dense(x, 64)
can you use tf.slim instead? it would be great to avoid mixing higher level libraries

2018-04-10 16:54 UTC, richardliaw commented on python/ray/rllib/ddpg/ddpg.py
> +import tensorflow as tf
Would it be possible to move all of the TF code out of this file? We would like to keep the main algorithm framework agnostic

2018-04-11 01:48 UTC, ericl reviewed
Thanks for contributing this! I think this is good to merge after we add it to the test files mentioned below, and check that it passes those.

2018-04-11 01:48 UTC, ericl commented on python/ray/rllib/ddpg/ou_noise.py
> +# --------------------------------------
Shall we move this into rllib/utils ?

2018-04-11 01:48 UTC, ericl commented on python/ray/rllib/ddpg/models.py
> +def _huber_loss(x, delta=1.0):
Some of this seems duplicated with DQN, we should probably move it to a util file.

2018-04-11 01:48 UTC, ericl commented on python/ray/rllib/ddpg/ddpg_evaluator.py
> +    TODO(rliaw): Support observation/reward filters?"""
This comment seems out of date and could be removed.

2018-04-11 01:48 UTC, ericl commented on python/ray/rllib/ddpg/ddpg.py
> +    def _populate_replay_buffer(self):
Unused function.

2018-04-11 01:48 UTC, ericl commented on python/ray/rllib/agent.py
> +        return ddpg.DDPGAgent
Along with registering it here, could you also register DDPG in these automated tests?

1) The generic test for supported obs/action spaces:
https://github.com/ray-project/ray/blob/master/python/ray/rllib/test/test_supported_spaces.py#L132

2) The regression tests folder: https://github.com/ray-project/ray/tree/master/python/ray/rllib/tuned_examples/regression_tests

3) The checkpoint/restore test https://github.com/ray-project/ray/blob/master/python/ray/rllib/test/test_checkpoint_restore.py

You should be able to basically copy paste an existing entry for e.g., DQN in each of these cases.

2018-04-11 01:48 UTC, ericl commented on python/ray/rllib/ddpg/ddpg.py
> +    force_evaluators_remote=False)
Could we drop this config? It used to be used for Ape-X but it has been dropped due to improvements in Ray's actor scheduling.

2018-04-11 02:51 UTC, qyccc commented
![screenshot-2018-4-11 tensorboard](https://user-images.githubusercontent.com/17870083/38593886-3e80d5d2-3d76-11e8-91d1-0e4cf0e64f1b.png)

2018-04-11 16:52 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/4806/
Test PASSed.

2018-04-11 16:59 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/4807/
Test FAILed.

2018-04-11 19:50 UTC, ericl reviewed
Looks close. I just ran `./train.py -f tuned_examples/regression_tests/mountaincarcontinuous-ddpg.yaml` and got

```
Remote function __init__ failed with:

Traceback (most recent call last):
  File "/home/eric/Desktop/ray-private/python/ray/worker.py", line 832, in _process_task
    *arguments)
  File "/home/eric/Desktop/ray-private/python/ray/actor.py", line 212, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/eric/Desktop/ray-private/python/ray/rllib/agent.py", line 84, in __init__
    Trainable.__init__(self, config, registry, logger_creator)
  File "/home/eric/Desktop/ray-private/python/ray/tune/trainable.py", line 89, in __init__
    self._setup()
  File "/home/eric/Desktop/ray-private/python/ray/rllib/agent.py", line 107, in _setup
    self._init()
  File "/home/eric/Desktop/ray-private/python/ray/rllib/ddpg/ddpg.py", line 105, in _init
    for i in range(self.config["num_workers"])]
  File "/home/eric/Desktop/ray-private/python/ray/rllib/ddpg/ddpg.py", line 105, in <listcomp>
    for i in range(self.config["num_workers"])]
  File "/home/eric/Desktop/ray-private/python/ray/actor.py", line 822, in remote
    dependency=actor_cursor)
  File "/home/eric/Desktop/ray-private/python/ray/actor.py", line 646, in _actor_method_call
    args = signature.extend_args(function_signature, args, kwargs)
  File "/home/eric/Desktop/ray-private/python/ray/signature.py", line 212, in extend_args
    .format(function_name))
Exception: Too many arguments were passed to the function '__init__'
```

I think this is since the evaluator class doesn't take a logdir argument? Could you make sure that that example runs to -15 result?

2018-04-11 19:50 UTC, ericl commented on python/ray/rllib/ddpg/ddpg.py
> +    exploration_noise=0.2,
Comment for exploration_noise and action_noise?

2018-04-11 19:50 UTC, ericl commented on python/ray/rllib/ddpg/ddpg.py
> +
one newline

2018-04-11 19:50 UTC, ericl commented on python/ray/rllib/ddpg/ddpg.py
> +        self.local_evaluator.update_target()
Hm note that updating the target every time might be sub-optimal.

2018-04-11 19:50 UTC, ericl commented on python/ray/rllib/ddpg/ddpg.py
> +    # def _populate_replay_buffer(self):
Remove?

2018-04-11 19:50 UTC, ericl commented on python/ray/rllib/ddpg/ou_noise.py
> +class OUNoise:
I think you forgot to remove this file after moving it to rllib/utils

2018-04-11 19:50 UTC, ericl commented on python/ray/rllib/__init__.py
> +    for key in ["PPO", "ES", "DQN", "APEX", "A3C", "BC", "PG", "DDPG", "__fake",
Could we rename this to "DDPG_baselines", and change the directory to `rllib/ddpg_baselines` in order to not conflict with the other DDPG pr here https://github.com/ray-project/ray/pull/1877/files ?

The main feature of this PR is that it's adapted from the baselines code, so we should probably keep that in the naming (or, could also call it `DDPG2` and just leave the details in the README).

2018-04-12 04:13 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/4817/
Test FAILed.

2018-04-12 04:36 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/4819/
Test FAILed.

2018-04-12 22:11 UTC, ericl reviewed
Bunch of lint errors here: https://api.travis-ci.org/v3/job/365429239/log.txt

Could you also make sure the `HalfCheetah` environment trains, and add a tuned example for this env? This one should be fairly fast and so is a good sanity check for DDPG.

2018-04-12 22:11 UTC, ericl commented on python/ray/rllib/__init__.py
> +                "DDPG_beselines", "__fake", "__sigmoid_fake_data", "__parameter_tuning"]:
typo: `baselines`

2018-04-12 22:11 UTC, ericl commented on python/ray/rllib/ddpg_baselines/ddpg_evaluator.py
> +            """Changes self's filter to given and rebases any accumulated delta.
Indentation here is off

2018-05-06 03:42 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5232/
Test FAILed.

2018-05-06 10:56 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5237/
Test FAILed.

2018-05-07 13:17 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5255/
Test FAILed.

2018-05-08 15:43 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5272/
Test FAILed.

2018-05-09 02:44 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5278/
Test FAILed.

2018-05-09 05:50 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5282/
Test FAILed.

2018-05-09 08:31 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5286/
Test FAILed.

2018-05-09 09:43 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5289/
Test FAILed.

2018-05-09 10:41 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5292/
Test FAILed.

2018-05-09 15:59 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5293/
Test FAILed.

2018-05-11 04:04 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5329/
Test PASSed.

2018-05-12 02:48 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5347/
Test FAILed.

2018-05-13 02:33 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5356/
Test FAILed.

2018-05-13 02:56 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5357/
Test FAILed.

2018-05-14 01:38 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5366/
Test PASSed.

2018-05-14 13:02 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5376/
Test FAILed.

2018-05-15 01:31 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5395/
Test FAILed.

2018-05-16 03:11 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5411/
Test PASSed.

2018-05-17 01:34 UTC, qyccc commented
why does  continuous-integration/travis-ci/pr always fail ? I don‘t konw if my code is wrong

2018-05-17 03:44 UTC, robertnishihara commented
@qyccc unfortunately we have a bunch of flaky tests right now. Really need to address this.. Keeping track of them at https://github.com/ray-project/ray/issues?q=is%3Aissue+is%3Aopen+label%3A%22test+failure%22.

2018-07-19 12:31 UTC, closed without merging