[sgd/v1] Add API annotations
ray-project/ray pull request #18790
Opened 2021-09-21 19:44 UTC by krfricke

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-09-21 19:54 UTC, amogkam requested changes

2021-09-21 19:54 UTC, amogkam commented on python/ray/util/sgd/tf/tf_runner.py
> +@DeveloperAPI
I don't think we need annotations for this right?

```
Developer APIs are lower-level methods explicitly exposed to advanced Ray
    users and library developers. Their interfaces may change across minor
    Ray releases.
```

`TFRunner` is purely internal and not even exposed to advanced users.

2021-09-21 19:54 UTC, amogkam commented on python/ray/util/sgd/torch/torch_runner.py
> +@PublicAPI(stability="beta")
See comment above, we shouldn't need any annotations for this.

2021-09-21 19:54 UTC, amogkam commented on python/ray/util/sgd/torch/worker_group.py
> +@DeveloperAPI
Same as above, we shouldn't need any annotations for this. This is purely internal.

2021-09-21 20:03 UTC, amogkam commented on python/ray/util/sgd/data/dataset.py
> +@PublicAPI(stability="beta")
This is actually Deprecated fully and replaced by Rat Data

2021-09-22 10:08 UTC, krfricke commented
Thanks, take another look? :-)

2021-09-22 15:09 UTC, amogkam approved these changes
Thanks!

2021-09-22 15:10 UTC, merged