[SGDv2] Add Tune-Cifar-PyTorch-PBT example
ray-project/ray pull request #18860
Opened 2021-09-23 22:08 UTC by Yard1

## Why are these changes needed?

Adds an adapted SGDv1 example for SGDv2 & Tune.

The conversion was trivial, and I have not ran into any issues. The new API is intuitive and streamlined. I got it to work on the first try, without any issues.

## Related issue number

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-09-23 22:11 UTC, Yard1 commented on python/ray/util/sgd/v2/BUILD
> +
```suggestion

```

2021-09-24 20:23 UTC, amogkam requested changes
Thanks a lot @Yard1! It looks like the example is failing on CI though. Could you also add this example to the docs: https://docs.ray.io/en/master/raysgd/v2/examples.html

2021-09-24 20:50 UTC, Yard1 commented
@amogkam My bad! Updated the example. Also enabled it to work for GPU, please check if anything else is required!

2021-09-27 16:22 UTC, amogkam approved these changes
Thanks!

2021-09-27 16:22 UTC, merged