[nightly] update nightly test for many node test
ray-project/ray pull request #18975
Opened 2021-09-29 18:00 UTC by iycheng

## Why are these changes needed?

many node tests are really flaky now. But before we'd like to change the flags by default we need to test it to make sure it's working well. Due to k8s issues, thread number is reverted back.

- test gcs actor scheduler
- test gcs grpc mult-thread 

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-09-29 18:43 UTC, ericl requested changes
Can you make sure all non-trivial PRs have descriptions? Btw, shouldn't we fix this the proper way by putting the flag back in ray_config_def.h, and debugging the root cause of the k8s issue? Otherwise we are not testing what is deployed by users.

2021-09-30 00:00 UTC, iycheng commented
> Can you make sure all non-trivial PRs have descriptions? Btw, shouldn't we fix this the proper way by putting the flag back in ray_config_def.h, and debugging the root cause of the k8s issue? Otherwise we are not testing what is deployed by users.

I think what I actually want is to put it into a staging test. But since now we don't have it, I probably just want to test it in this way. At least we can verify it's working once we fix the k8s issues. 
Btw, it's also about testing the gcs actor scheduler which actually should also be put into staging testing I think. The goal for the staging test is to change the default values eventually when everything is stable.

2021-09-30 00:02 UTC, iycheng commented
We should fix the k8s issues and change the default value eventually. But I feel they probably are orthogonal since many nodes actor tests right now are flaky and we are testing nothing.

2021-09-30 00:28 UTC, ericl approved these changes
Alright--- let's try it then as a short term fix. I guess this has been quite tricky to resolve.

2021-09-30 00:28 UTC, merged