[runtime env] Move container related code to runtime env
ray-project/ray pull request #19067
Opened 2021-10-04 03:43 UTC by chenk008

## Why are these changes needed?

We will use runtime env to manager worker runtime. This pull request is trying to make the container related code as a runtime env plugin.  

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-10-04 17:20 UTC, simon-mo requested changes
Thanks for doing this!

2021-10-04 17:20 UTC, simon-mo commented on python/ray/_private/runtime_env/container.py
> +        logger.warning("start worker in container with prefix: {}".format(" ".join(container_command)))
```suggestion
        logger.info("start worker in container with prefix: {}".format(" ".join(container_command)))
```

2021-10-04 17:20 UTC, simon-mo commented on python/ray/_private/runtime_env/container.py
> +        logger.warning("start worker in container with prefix: {}".format(" ".join(container_command)))
add new line

2021-10-04 17:20 UTC, simon-mo commented on python/ray/_private/runtime_env/container.py
> +        self._tmp_dir = tmp_dir
rename this to mount dir? or ray_tmp_dir so it's more clear about what is it used for

2021-10-04 17:20 UTC, simon-mo commented on python/ray/_private/runtime_env/context.py
> +                 container_command_prefix: List[str] = None,
please don't change this. you can modify `self.py_exectuable` or `self.command_prefix` in ContainerManager.setup instead of adding a new entry.

2021-10-19 21:17 UTC, simon-mo commented
@chenk008 if you can turn on that test that would be greatly appreciated! I disabled it because one day podman just broke and I can't find a way fixing it.

2021-10-19 21:18 UTC, simon-mo approved these changes
LGTM

2021-10-19 21:18 UTC, simon-mo commented
Please fix the merge conflict when ping me when tests pass. Thanks!

2021-10-29 23:31 UTC, merged

2021-10-29 23:31 UTC, simon-mo commented
@chenk008 thanks! just to confirm, you will try to re-enable the work-in-container test as well right?

2021-10-31 11:23 UTC, chenk008 commented
> @chenk008 thanks! just to confirm, you will try to re-enable the work-in-container test as well right?

@simon-mo Yes, I will create a new PR to re-enable the work-in-container test.