Add serve ft nightly
ray-project/ray pull request #19125
Opened 2021-10-06 00:10 UTC by jiaodong

Create a serve FT test for nightly 

It uses s3://serve-nightly-tests/fault-tolerant-test-checkpoint/ as checkpoint path with 7 days TTL, each checkpoint is 260 Bytes in size. 

Passes locally now, need to check with product folks about configuring right bucket and permissions.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-10-06 00:12 UTC, jiaodong commented on python/ray/serve/storage/checkpoint_path.py
> +            prefix = parsed_url.path.lstrip("/")
this is needed since boto3 client don't take the first "/" in prefix as key.

2021-10-06 00:12 UTC, jiaodong commented on python/ray/serve/storage/kv_store.py
> +            aws_access_key_id=os.environ.get("AWS_ACCESS_KEY_ID", None),
i think previously we're not really getting these tokens in make_kv_store, so adding it at client level with actual s3 integration.

2021-10-06 16:01 UTC, edoakes requested changes

2021-10-06 16:35 UTC, edoakes commented on release/serve_tests/workloads/serve_cluster_fault_tolerance.py
> +with remote checkpoint.
cluster_utils will run much faster though and it'll be nice to be able to run it locally for testing. if possible maybe make one test with both "backends" and start with just cluster_utils?

2021-10-11 23:02 UTC, edoakes approved these changes

2021-10-12 01:33 UTC, simon-mo approved these changes
@jiaodong please make sure to add them to preset dashboard once they are running!

2021-10-12 01:33 UTC, merged