[DataFrame] Implementing write methods
ray-project/ray pull request #1918
Opened 2018-04-17 21:16 UTC by kunalgosar

This PR is rebased on #1712 

This PR implements the write IO functions by falling back on pandas. This is a temporary placeholder and throws a warning for performance degradation. 

Opening in favor of #1713

2018-04-17 22:09 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/4976/
Test PASSed.

2018-04-17 22:26 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/4978/
Test PASSed.

2018-04-18 05:26 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/4983/
Test FAILed.

2018-04-19 20:29 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5006/
Test FAILed.

2018-04-20 02:29 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5008/
Test FAILed.

2018-04-21 04:15 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5024/
Test PASSed.

2018-04-22 08:27 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5029/
Test FAILed.

2018-04-22 17:57 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5030/
Test FAILed.

2018-04-22 19:19 UTC, devin-petersohn requested changes
Looks great, just a quick formatting change.

2018-04-22 21:02 UTC, kunalgosar commented on python/ray/dataframe/test/test_io.py
>  import pandas as pd
Formatting done.

2018-04-22 22:08 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5031/
Test PASSed.

2018-04-22 22:37 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5032/
Test FAILed.

2018-04-22 22:39 UTC, devin-petersohn commented
Jenkins, retest this please.

2018-04-22 23:42 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5033/
Test PASSed.

2018-04-23 04:25 UTC, devin-petersohn approved these changes
Thanks @kunalgosar !

2018-04-23 04:25 UTC, merged

2018-04-23 04:44 UTC, devin-petersohn commented
Merged, thanks @kunalgosar!