[Core]Polling resource usages in lightweight way
ray-project/ray pull request #19316
Opened 2021-10-12 07:02 UTC by WangTaoTheTonic

## Why are these changes needed?
Now we use polling way to update resources of raylets in gcs but it didn't combine well with lightweight way, which cause lots cpu pressure in gcs(with 1000 nodes gcs cpu has reached 200%).
This PR does:
- Delete old code path `Async(Re)ReportResourceUsage` and related methods.
- Gcs polling resources in lightweight way
  - return Status::Invalid if raylet resource not changed
  - add changed flag for bool flag `object_pull_queued` and `cluster_full_of_actors`

## Related issue number
#19293

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-10-26 06:20 UTC, fishbone requested changes
I have one concern here. Have we handled the polling failure? What if one request is missed:

gcs -> raylet --- missed --> gcs

2021-10-28 02:54 UTC, rkooo567 reviewed
@iycheng please review it again! We can merge it once you are okay with the PR

2021-11-01 10:21 UTC, WangTaoTheTonic commented on src/ray/gcs/gcs_server/gcs_resource_report_poller.cc
> +  const bool &initial_report = state->next_pull_time == -1 ? true : false;
ok

2021-11-01 10:22 UTC, WangTaoTheTonic commented on src/ray/gcs/gcs_server/gcs_resource_manager.cc
> +    if (resources.cluster_full_of_actors_detected_changed()) {
ok

2021-11-02 20:26 UTC, iycheng commented
@WangTaoTheTonic  could you merge to the trunk we fixed the buildkite failure yesterday.

2021-11-04 05:34 UTC, rkooo567 commented
`test_output` fails. Maybe related? It never failed on master lately

2021-11-05 11:33 UTC, rkooo567 commented
seems to be very close (cpp tests are only thing that seems to fail). Can you remove the tag once tests are fixed? Also cc @iycheng

2021-11-07 09:00 UTC, WangTaoTheTonic commented
cpp failure seems fixed by https://github.com/ray-project/ray/pull/20118. let's revert the merge commit and see if it'd be ok

2021-11-08 02:04 UTC, WangTaoTheTonic commented
RLLib tests failed. Maybe something wrong with environment?

2021-11-09 08:13 UTC, WangTaoTheTonic commented
All tests except flakey one passed.

2021-11-09 08:17 UTC, rkooo567 approved these changes
Lgtm, but I haven’t looked into code in details, so I will let @iycheng to check the final pass

2021-11-16 06:05 UTC, closed without merging