[Core] Encode job ID in randomized task IDs for user-created threads
ray-project/ray pull request #19320
Opened 2021-10-12 13:25 UTC by kfstorm

## Why are these changes needed?

Currently, when `WorkerContext::GetCurrentTaskID()` returns a random task ID in user-created threads, and the returned task ID doesn't include the job ID. In this case, subsequent non-actor tasks and return values, and objects created by `ray.put()` don't include the job ID neither. This makes us hard to find the correct job ID from a task or object ID.

This PR updates the task ID generation code to always encode the job ID.

A side-effect of this PR is the change of possibility of task ID collision in user-created threads due to the fixed job ID part. w/o this PR: `sqrt(pi * 256 ^ 12 / 2)` ~= 352 trillion tasks. w/ this PR: `sqrt(pi * 256 ^ 8 / 2)` ~= 5 billion tasks. But this should be OK because the job ID part of task IDs in non-user-created threads are always fixed, so it won't be worse than non-user-created threads.

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-10-14 02:16 UTC, rkooo567 commented
I think this makes sense, but can you 

1. update https://github.com/ray-project/ray/blob/master/src/ray/design_docs/id_specification.md?
2. Fix broken tests?
3. What's the likelihood of collision with this mechanism? Can you calculate it?

2021-10-14 04:22 UTC, kfstorm commented
@rkooo567 I don't think we need to update the ID spec doc since I didn't change the structure of task ID.

Task ID consists of 8 unique bytes and a job ID of 4 bytes. After this PR, the job ID part is fixed. For a 50% collision possibility, we need about 5 billion randomized task IDs for the same job, if don't count non-randomized task IDs.

```
>>> import math
>>> n = 256 ** 8
>>> n
18446744073709551616
>>> math.sqrt(math.pi * n / 2)
5382943231.384526
```

2021-11-01 03:45 UTC, rkooo567 approved these changes
I think it makes sense, but do you know what it means by "fake task id"? Is there a better wording than this? (I was really confused what it means when I read it.. )

2021-11-01 03:45 UTC, rkooo567 commented on python/ray/includes/unique_ids.pxi
> +    def for_fake_task(cls, job_id):
What does it mean by "fake task" here? The naming seems very confusing to me.

2021-11-01 03:45 UTC, rkooo567 commented on src/ray/core_worker/context.h
> +  WorkerThreadContext &GetThreadContext() const;
nice!

2021-11-02 03:00 UTC, kfstorm commented
@rkooo567 The "fake task id" here means a random task ID. It's used for user-created threads to avoid object/task ID collision when a user calls Ray APIs in multiple threads. Renaming `ForFakeTask` to `FromRandom` sounds reasonable to me, so `FromRandom()` and `FromRandom(const JobID &)` are overloads. Actually, the existing implementation of `TaskID::ForFakeTask` is exactly the same as `BaseID::FromRandom()`.

2021-11-02 20:27 UTC, scv119 commented
agreed ForFake is very confusing; let's rename it to FromRandom

2021-11-02 20:29 UTC, scv119 commented
Also, can you suggest the possibility of collision and consequence of it in the PR summary?

2021-11-02 20:29 UTC, scv119 requested changes
wait for author's response.

2021-11-06 14:43 UTC, rkooo567 commented
cc @scv119

2021-11-07 04:07 UTC, scv119 approved these changes

2021-11-08 13:00 UTC, kfstorm commented
Windows CI failure is unrelated. Merging.

2021-11-08 13:00 UTC, merged