[Core][CoreWorker] increase the default port range
ray-project/ray pull request #19541
Opened 2021-10-20 05:58 UTC by scv119

## Why are these changes needed?

In the current logic of popping workers, we first select a free port and use that port to start Worker. There will be a race condition that the port was previously free being occupied when worker process starts.

In this PR, we increase the initial port selection range by 10x (from 1000 -> 10000) to reduce the likelihood of this race condition.

## Related issue number

Closes #19336

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-10-20 08:35 UTC, rkooo567 approved these changes

2021-10-20 17:22 UTC, edoakes requested changes
Please update all relevant docs too

e.g., https://github.com/ray-project/ray/blob/8c8b7770cbed506dff2e00e7b3fc7ded51404732/doc/source/configure.rst

2021-10-21 16:52 UTC, scv119 commented
ah this conflicts with node_manager's port (12345)

2021-11-04 19:30 UTC, scv119 commented
@rkooo567 take another look?

2021-11-04 20:41 UTC, edoakes approved these changes

2021-11-04 20:41 UTC, edoakes commented on doc/source/configure.rst
>  Port numbers are how Ray disambiguates input and output to and from multiple workers on a single node. Each worker will take input and give output on a single port number. Thus, for example, by defau
```suggestion
Port numbers are how Ray disambiguates input and output to and from multiple workers on a single node. Each worker will take input and give output on a single port number. Thus, for example, by default, there is a maximum of 10,000 workers on each node, irrespective of number of CPUs.
```

2021-11-04 21:45 UTC, rkooo567 approved these changes

2021-11-05 16:25 UTC, merged