[Core][CoreWorker][RFC] graceful shutdown if GetCoreWorker is null
ray-project/ray pull request #19598
Opened 2021-10-21 18:24 UTC by scv119

There are cases that the language frontend calls GetCoreWorker() after the worker has already been shutdown. Currently this results in a crash and causes confusions. 

```
pid=3714) [2021-10-21 10:50:23,596 C 3714 33544237] core_worker.cc:194:  Check failed: core_worker_process The core worker process is not initialized yet or already shutdown.
(pid=3714) *** StackTrace Information ***
(pid=3714)     ray::GetCallTrace()
(pid=3714)     ray::SpdLogMessage::Flush()
(pid=3714)     ray::SpdLogMessage::~SpdLogMessage()
(pid=3714)     ray::RayLog::~RayLog()
(pid=3714)     ray::core::CoreWorkerProcess::EnsureInitialized()
(pid=3714)     ray::core::CoreWorkerProcess::GetCoreWorker()
(pid=3714)     __pyx_pw_3ray_7_raylet_10CoreWorker_23get_worker_id()
(pid=3714)     _PyMethodDef_RawFastCallKeywords
(pid=3714)     _PyMethodDescr_FastCallKeywords
(pid=3714)     call_function
(pid=3714)     _PyEval_EvalFrameDefault
(pid=3714)     function_code_fastcall
(pid=3714)     property_descr_get
(pid=3714)     _PyObject_GenericGetAttrWithDict
(pid=3714)     _PyEval_EvalFrameDefault
(pid=3714)     _PyEval_EvalCodeWithName
(pid=3714)     _PyFunction_FastCallKeywords
(pid=3714)     call_function
(pid=3714)     _PyEval_EvalFrameDefault
(pid=3714)     function_code_fastcall
(pid=3714)     call_function
(pid=3714)     _PyEval_EvalFrameDefault
(pid=3714)     function_code_fastcall
(pid=3714)     method_call
(pid=3714)     PyObject_Call
(pid=3714)     _PyEval_EvalFrameDefault
(pid=3714)     function_code_fastcall
(pid=3714)     call_function
(pid=3714)     _PyEval_EvalFrameDefault
(pid=3714)     function_code_fastcall
(pid=3714)     call_function
(pid=3714)     _PyEval_EvalFrameDefault
(pid=3714)     function_code_fastcall
(pid=3714)     method_call
(pid=3714)     PyObject_Call
(pid=3714)     t_bootstrap
(pid=3714)     pythread_wrapper
(pid=3714)     _pthread_start
(pid=3714)     thread_start
```

## Related issue number

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-10-21 18:44 UTC, jovany-wang requested changes

2021-10-21 18:49 UTC, jovany-wang commented
Maybe I lost some info, feel free to add more.

2021-10-28 05:33 UTC, rkooo567 approved these changes

2021-10-28 06:10 UTC, jovany-wang approved these changes

2021-10-28 06:11 UTC, merged