[DataFrame] Implement df.merge
ray-project/ray pull request #1964
Opened 2018-04-28 21:11 UTC by devin-petersohn

Implement the `DataFrame.merge` method that does a Database style join on common columns. Depends on #1937.

2018-04-28 21:42 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5107/
Test FAILed.

2018-04-29 20:53 UTC, p-yang requested changes

2018-04-29 20:53 UTC, Veryku commented on python/ray/dataframe/dataframe.py
> +                "Columns must be passed without col_metadata"
"If col_metadata is None, columns must be passed in"

2018-04-29 20:53 UTC, Veryku commented on python/ray/dataframe/dataframe.py
> +        left_cols = ray.put(self.columns)
Put this before column merge

2018-04-30 06:03 UTC, Veryku commented on python/ray/dataframe/dataframe.py
> +        if on is not None:
Perform error checking before defining `new_columns` so users don't get a local error followed by a remote error.

2018-04-30 06:48 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5126/
Test PASSed.

2018-04-30 07:56 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5130/
Test FAILed.

2018-04-30 16:43 UTC, robertnishihara approved these changes

2018-04-30 18:02 UTC, devin-petersohn commented
Jenkins, test this please

2018-05-01 22:53 UTC, devin-petersohn commented
Jenkins, retest this please.

2018-05-01 23:56 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5137/
Test PASSed.

2018-05-02 01:40 UTC, merged