[Release/Horovod] Add user test for Horovod
ray-project/ray pull request #19661
Opened 2021-10-23 01:15 UTC by amogkam

Adds a "realistic" test for Horovod on Ray. The purpose of this test is to test the library in a particular environment setting that we care about.

This PR adds a new test suite for these realistic tests. All tests in this test suite must:
1. Be run in a distributed (multi-node) fashion
2. Use autoscaling/scale up (no wait_cluster.py)
3. Use GPUs if applicable
4. Have the `use_connect` flag set.

Tests run in this suite should also be located inside `ray/python/ray` so that they can be imported to other repos if needed.

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-10-27 15:13 UTC, krfricke approved these changes
LGTM do we have a nightly test output?

2021-10-27 15:28 UTC, krfricke submitted a review, later dismissed
Ah there seems to be an error:

https://buildkite.com/ray-project/periodic-ci/builds/1336#bcc1019f-d594-45dc-9e19-b65fa51d222c

2021-10-30 00:17 UTC, amogkam commented
Successful run: https://buildkite.com/ray-project/periodic-ci/builds/1421#b8935cf2-a733-43f2-922f-727acbfb76d4

2021-10-30 00:37 UTC, amogkam commented on release/horovod_tests/workloads/horovod_user_test.py
> +                                      "/tmp/horovod_releastic_test.json")
```suggestion
                                      "/tmp/horovod_user_test.json")
```

2021-11-01 17:44 UTC, amogkam commented
Final successful build: https://buildkite.com/ray-project/periodic-ci/builds/1460#fbc31d12-fc4d-4fd5-addb-1f6b2bb2b47f

2021-11-01 20:50 UTC, richardliaw requested changes

2021-11-01 20:50 UTC, richardliaw commented on python/ray/util/horovod/horovod_example.py
> +    kwargs = kwargs if kwargs else {}
nit, kwargs = kwargs or {}

2021-11-01 20:50 UTC, richardliaw approved these changes

2021-11-01 23:31 UTC, amogkam commented on release/.buildkite/build_pipeline.py
> -            + step_conf["commands"]
We want to do the necessary driver side setup before running the e2e script.

2021-11-01 23:33 UTC, amogkam commented on release/horovod_tests/driver_requirements.txt
> +git+https://github.com/horovod/horovod.git
that could lead to problems where the error is not uncovered until after the release is made, right?

2021-11-01 23:33 UTC, amogkam commented on release/horovod_tests/driver_requirements.txt
> +git+https://github.com/horovod/horovod.git
I think we might want to test both.

2021-11-02 01:28 UTC, merged