Add a simple node failure integration test + clean up spammy logs upon node failures
ray-project/ray pull request #19695
Opened 2021-10-25 12:06 UTC by rkooo567

## Why are these changes needed?

This PR is doing 2 things.

- Add a mini integration test to test retry (with nested tasks).
- Clean up spammy logs in the workload.

It cleans up spammy logs by
- First changing the log level to WARNING instead of ERROR if errors are handled by Ray. (e.g., task retry, or logs printed because the raylet is dead == expected death)
- Second, have more robust logic on raylet failure logs (e.g., capture raylet failures on local raylet RPCs and emit the quiet log messages instead of notifying the driver).

After this PR, there's no spammy logs from this workload. Here's the comparison.

before; (only captured like 5% of logs)
```python3
Chaos test sanity check:  13%|██████▊                                              | 128/1000 [00:26<02:07,  6.84it/s]2021-10-25 02:52:12,881	WARNING worker.py:1218 -- infinite retries left for task 8cf2e8c637825d7effffffffffffffffffffffff01000000, attempting to resubmit.
2021-10-25 02:52:12,881	WARNING worker.py:1218 -- infinite retries left for task 1d6583613d546c46ffffffffffffffffffffffff01000000, attempting to resubmit.
(invoke_nested_task pid=95217) [2021-10-25 02:52:12,853 E 95217 1100846] direct_task_transport.cc:588: The worker failed to receive a response from the local raylet. This is most likely because the local raylet has crashed.
(invoke_nested_task pid=95217) [2021-10-25 02:52:12,862 C 95217 1100846] direct_task_transport.cc:591: IOError: 14: Connection reset by peer
(invoke_nested_task pid=95217) *** StackTrace Information ***
(invoke_nested_task pid=95217)     ray::GetCallTrace()
(invoke_nested_task pid=95217)     ray::SpdLogMessage::Flush()
(invoke_nested_task pid=95217)     ray::SpdLogMessage::~SpdLogMessage()
(invoke_nested_task pid=95217)     ray::RayLog::~RayLog()
(invoke_nested_task pid=95217)     std::__1::__function::__func<>::operator()()
(invoke_nested_task pid=95217)     ray::rpc::ClientCallImpl<>::OnReplyReceived()
(invoke_nested_task pid=95217)     std::__1::__function::__func<>::operator()()
(invoke_nested_task pid=95217)     boost::asio::detail::completion_handler<>::do_complete()
(invoke_nested_task pid=95217)     boost::asio::detail::scheduler::do_run_one()
(invoke_nested_task pid=95217)     boost::asio::detail::scheduler::run()
(invoke_nested_task pid=95217)     boost::asio::io_context::run()
(invoke_nested_task pid=95217)     ray::core::CoreWorker::RunIOService()
(invoke_nested_task pid=95217)     std::__1::__thread_proxy<>()
(invoke_nested_task pid=95217)     _pthread_start
(invoke_nested_task pid=95217)     thread_start
(invoke_nested_task pid=95217) 
(invoke_nested_task pid=95268) [2021-10-25 02:52:12,864 E 95268 1102761] direct_task_transport.cc:588: The worker failed to receive a response from the local raylet. This is most likely because the local raylet has crashed.
(invoke_nested_task pid=95268) [2021-10-25 02:52:12,878 C 95268 1102761] direct_task_transport.cc:591: IOError: 14: failed to connect to all addresses
(invoke_nested_task pid=95268) *** StackTrace Information ***
(invoke_nested_task pid=95268)     ray::GetCallTrace()
(invoke_nested_task pid=95268)     ray::SpdLogMessage::Flush()
(invoke_nested_task pid=95268)     ray::SpdLogMessage::~SpdLogMessage()
(invoke_nested_task pid=95268)     ray::RayLog::~RayLog()
(invoke_nested_task pid=95268)     std::__1::__function::__func<>::operator()()
(invoke_nested_task pid=95268)     ray::rpc::ClientCallImpl<>::OnReplyReceived()
(invoke_nested_task pid=95268)     std::__1::__function::__func<>::operator()()
(invoke_nested_task pid=95268)     boost::asio::detail::completion_handler<>::do_complete()
(invoke_nested_task pid=95268)     boost::asio::detail::scheduler::do_run_one()
(invoke_nested_task pid=95268)     boost::asio::detail::scheduler::run()
(invoke_nested_task pid=95268)     boost::asio::io_context::run()
(invoke_nested_task pid=95268)     ray::core::CoreWorker::RunIOService()
(invoke_nested_task pid=95268)     std::__1::__thread_proxy<>()
(invoke_nested_task pid=95268)     _pthread_start
(invoke_nested_task pid=95268)     thread_start
(invoke_nested_task pid=95268) 
(invoke_nested_task pid=95301) [2021-10-25 02:52:12,858 E 95301 1103839] direct_task_transport.cc:588: The worker failed to receive a response from the local raylet. This is most likely because the local raylet has crashed.
(invoke_nested_task pid=95301) [2021-10-25 02:52:12,869 C 95301 1103839] direct_task_transport.cc:591: IOError: 14: failed to connect to all addresses
2021-10-25 02:52:12,893	WARNING worker.py:1218 -- infinite retries left for task ba71c1f69e4630bbffffffffffffffffffffffff01000000, attempting to resubmit.
(invoke_nested_task pid=95301) *** StackTrace Information ***
(invoke_nested_task pid=95301)     ray::GetCallTrace()
2021-10-25 02:52:12,893	WARNING worker.py:1218 -- infinite retries left for task 0c661fd25250731effffffffffffffffffffffff01000000, attempting to resubmit.
(invoke_nested_task pid=95301)     ray::SpdLogMessage::Flush()
(invoke_nested_task pid=95301)     ray::SpdLogMessage::~SpdLogMessage()
(invoke_nested_task pid=95301)     ray::RayLog::~RayLog()
(invoke_nested_task pid=95301)     std::__1::__function::__func<>::operator()()
2021-10-25 02:52:12,894	WARNING worker.py:1218 -- infinite retries left for task 3c0c8a320b4809a0ffffffffffffffffffffffff01000000, attempting to resubmit.
(invoke_nested_task pid=95301)     ray::rpc::ClientCallImpl<>::OnReplyReceived()
(invoke_nested_task pid=95301)     std::__1::__function::__func<>::operator()()
(invoke_nested_task pid=95301)     boost::asio::detail::completion_handler<>::do_complete()
(invoke_nested_task pid=95301)     boost::asio::detail::scheduler::do_run_one()
(invoke_nested_task pid=95301)     boost::asio::detail::scheduler::run()
(invoke_nested_task pid=95301)     boost::asio::io_context::run()
(invoke_nested_task pid=95301)     ray::core::CoreWorker::RunIOService()
(invoke_nested_task pid=95301)     std::__1::__thread_proxy<>()
(invoke_nested_task pid=95301)     _pthread_start
(invoke_nested_task pid=95301)     thread_start
(invoke_nested_task pid=95301) 
```

After (it is every log printed)

```python3
Chaos test sanity check:  24%|█████████████                                         | 121/500 [00:20<01:05,  5.75it/s](invoke_nested_task pid=42922) 
Chaos test sanity check:  25%|█████████████▍                                        | 124/500 [00:22<02:21,  2.65it/s](raylet) [2021-10-25 05:34:10,286 C 43098 1729504] plasma_store_provider.cc:73:  Check failed: _s.ok() Bad status: IOError: Broken pipe
(raylet) *** StackTrace Information ***
(raylet)     ray::GetCallTrace()
(raylet)     ray::SpdLogMessage::Flush()
(raylet)     ray::SpdLogMessage::~SpdLogMessage()
(raylet)     ray::RayLog::~RayLog()
(raylet)     ray::core::CoreWorkerPlasmaStoreProvider::CoreWorkerPlasmaStoreProvider()
(raylet)     ray::core::CoreWorker::CoreWorker()
(raylet)     ray::core::CoreWorkerProcess::CreateWorker()
(raylet)     ray::core::CoreWorkerProcess::CoreWorkerProcess()
(raylet)     ray::core::CoreWorkerProcess::Initialize()
(raylet)     __pyx_pw_3ray_7_raylet_10CoreWorker_1__cinit__()
(raylet)     __pyx_tp_new_3ray_7_raylet_CoreWorker()
(raylet)     type_call
(raylet)     _PyObject_FastCallKeywords
(raylet)     call_function
(raylet)     _PyEval_EvalFrameDefault
(raylet)     _PyEval_EvalCodeWithName
(raylet)     _PyFunction_FastCallKeywords
(raylet)     call_function
(raylet)     _PyEval_EvalFrameDefault
(raylet)     _PyEval_EvalCodeWithName
(raylet)     PyRun_FileExFlags
(raylet)     PyRun_SimpleFileExFlags
(raylet)     pymain_main
(raylet)     main
(raylet)     start
(raylet) 
Chaos test sanity check:  34%|██████████████████▏                                   | 168/500 [00:28<01:38,  3.39it/s]2021-10-25 05:34:16,579	WARNING worker.py:1218 -- The node with node id: 07925e6391ee940f5de0a5e3333f2022eca68c7e321e665a69d8915a and ip: 127.0.0.1 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a raylet crashes unexpectedly  [...]

2021-10-26 17:58 UTC, scv119 reviewed
I think it's moving the right direction. Added a few comments.

2021-10-26 19:00 UTC, stephanie-wang requested changes
Thanks, this looks good! A few comments:
1. Is there a test we can use to make sure that there won't be regressions in terms of surfacing remote raylet failure errors?
2. Can we write the failure testing as a pytest fixture? That way we can easily start applying it to other tests. I think we can do this with @ericl's suggestion to move raylet killing into a Ray task.

2021-10-29 22:42 UTC, stephanie-wang commented
Ah I think the idea behind the unit test was to just submit a Ray task to kill the raylet instead of killing the raylet from a different driver thread. But I think this is fine for now, we can revisit as we start to failure-test the distributed tests.

2021-10-29 22:42 UTC, stephanie-wang approved these changes

2021-10-29 22:42 UTC, merged