Rewrite YAPF scripts
ray-project/ray pull request #1971
Opened 2018-05-01 03:04 UTC by alok

## What do these changes do?

- Fixes YAPF to use existing `.style.yapf` config file
- Runs in parallel
- Easier to read `yapf.sh` (IMO)

## Related issue number

No.

2018-05-02 02:27 UTC, pcmoritz commented
@ericl @richardliaw Are these linting changes ok with you? They look good to me!

2018-05-02 02:30 UTC, alok commented
Personally, I'd tweak the `.style.yapf` file a bit. I set mine up to imitate Elm's style guide in the areas where Python has no clear rules, and I think it's easier to read. I just used the pep8 style in this PR because that was what was specified before. I think it's harder to read this way though since it has odd indentation at times.

2018-05-02 02:56 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5139/
Test FAILed.

2018-05-04 09:02 UTC, alok commented
Regardless of the particular style used, we should use this updated script since it shaves about 30s off Travis builds.

2018-05-08 06:46 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5269/
Test PASSed.

2018-05-09 10:11 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5290/
Test PASSed.

2018-05-09 23:35 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5299/
Test PASSed.

2018-05-10 04:04 UTC, richardliaw reviewed
Some comments

2018-05-10 04:04 UTC, richardliaw commented on test/actor_test.py
> +            for _ in range(num_local_schedulers * num_gpus_per_scheduler - 1 -
this one looks quite odd..

2018-05-10 04:04 UTC, richardliaw commented on python/ray/monitor.py
> +                      (len(self.live_plasma_managers) + len(
this one is also a little odd..

2018-05-10 04:04 UTC, richardliaw commented on python/ray/experimental/state.py
> +                        "id": (parent_info["worker_id"] + str(
not a big fan of these

2018-05-10 04:04 UTC, richardliaw commented on python/ray/experimental/state.py
> +                        "id": (parent_info["worker_id"] + str(
not a big fan of these

2018-05-10 06:50 UTC, alok commented
@richardliaw See the latest commit where I apply the style specified in the config file. I went in and manually tweaked some code by adding trailing commas so the formatter would do the right thing. I think it fixed all your comments and hopefully looks fine for the rest. If not, feel free to revert it.

2018-05-10 07:11 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5309/
Test FAILed.

2018-05-11 00:51 UTC, richardliaw commented
OK I think there's too much vertical space as of this most recent commit; would you be willing to revert?

2018-05-11 01:08 UTC, alok commented
Done.

2018-05-11 02:11 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5326/
Test PASSed.

2018-05-15 19:44 UTC, richardliaw requested changes
two requests to change; otherwise looks good overall.

2018-05-15 19:44 UTC, richardliaw commented on python/ray/experimental/state.py
> +                        "id": (parent_info["worker_id"] + str(
@alok can we revert this?

2018-05-15 19:44 UTC, richardliaw commented on python/ray/monitor.py
> +                      (len(self.live_plasma_managers) + len(
@alok can we revert this?

2018-05-16 17:25 UTC, alok commented
@richardliaw I'd rather tweak the formatting config until it ends up looking pretty to avoid ever having to worry about manual formatting. I want it to be reliable enough to become a git pre-push hook so no one ever has to comment about formatting again.

2018-05-16 18:16 UTC, alok commented
@richardliaw can you try out this style? i think it fixes (most) of your issues with the current one.

2018-05-16 18:47 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5425/
Test FAILed.

2018-05-16 21:10 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5432/
Test PASSed.

2018-05-17 06:06 UTC, richardliaw commented
Hey @alok how did this become a 4k line PR?

2018-05-17 06:10 UTC, alok commented
I made the mistake of actually committing the linting changes

2018-05-17 06:11 UTC, alok commented
Check out https://github.com/alok/ray/tree/yapf-take-2 for a clean version

2018-05-17 07:52 UTC, richardliaw commented
OK great `take-2` looks a lot better. Consider making a commit that reverts changes from 
6d2a24b onwards and then rebasing `take-2` onto this.

2018-05-17 18:11 UTC, alok commented
@richardliaw I ended up making a new branch from master and applying the necessary changes there. See #2083.

2018-05-19 00:51 UTC, closed without merging