Implemented prod, product, added test suite
ray-project/ray pull request #1994
Opened 2018-05-03 06:28 UTC by hsubbaraj

Implemented prod, product
pandas test suite for min, max, cumulative functions, sum, prod, product
added an additional missing parameter to sum

2018-05-03 06:32 UTC, devin-petersohn commented on python/ray/dataframe/test/test_analytics.py
> +from __future__ import absolute_import
We should remove this file.

2018-05-03 06:59 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5161/
Test FAILed.

2018-05-03 07:52 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5163/
Test PASSed.

2018-05-04 00:21 UTC, p-yang requested changes

2018-05-04 04:39 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5188/
Test PASSed.

2018-05-04 04:41 UTC, devin-petersohn reviewed
Looks great! Just a couple of minor changes.

2018-05-04 04:41 UTC, devin-petersohn commented on python/ray/dataframe/test/test_dataframe.py
> +    assert(ray_df_equals_pandas(ray_df.prod().sort_index(), pandas_df.prod().sort_index()))
Please remove `sort_index()` from each side of this. The index should come out the same.

2018-05-04 04:41 UTC, devin-petersohn commented on python/ray/dataframe/test/test_dataframe.py
> +    assert(ray_df_equals_pandas(ray_df.product().sort_index(), pandas_df.product().sort_index()))
Same as above regarding `sort_index()`.

2018-05-04 06:21 UTC, devin-petersohn reviewed
After you rebase and replace the newlines, looks good!

2018-05-04 06:46 UTC, devin-petersohn approved these changes

2018-05-04 07:15 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5204/
Test PASSed.

2018-05-04 07:35 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5205/
Test PASSed.

2018-05-04 16:50 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5215/
Test PASSed.

2018-05-04 19:43 UTC, hsubbaraj commented
Prod returns a Series, but I was using a dataframe check instead. This commit should resolve the issue

2018-05-04 20:47 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5224/
Test PASSed.

2018-05-06 04:25 UTC, merged

2018-05-06 04:25 UTC, devin-petersohn commented
Merged, thanks @hsubbaraj!