Implemented nunique, skew
ray-project/ray pull request #1995
Opened 2018-05-03 06:59 UTC by hsubbaraj

Implemented nunique, skew

2018-05-03 08:02 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5165/
Test PASSed.

2018-05-03 23:20 UTC, kunalgosar requested changes
Looks really good! Just a few minor comments.

2018-05-04 04:16 UTC, hsubbaraj commented
I took out the changes from #1994 as well

2018-05-04 05:18 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5192/
Test PASSed.

2018-05-04 05:26 UTC, kunalgosar approved these changes
Few minor testing comments; generally, looks really good! Many of the early comments were addressed in #1994 after code was moved over.

2018-05-04 05:26 UTC, kunalgosar commented on python/ray/dataframe/test/test_dataframe.py
> +def test_prod(ray_df, pandas_df):
These changes should be moved to #1994

2018-05-04 05:26 UTC, kunalgosar commented on python/ray/dataframe/test/test_dataframe.py
> +    assert(ray_df_equals_pandas(ray_df.nunique(), pandas_df.nunique()))
Test both axis here.

2018-05-04 06:12 UTC, kunalgosar approved these changes
Looks great, thanks!

2018-05-04 06:18 UTC, devin-petersohn approved these changes
Looks great! Thanks @hsubbaraj!

2018-05-04 06:25 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5202/
Test FAILed.

2018-05-04 07:14 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5203/
Test PASSed.

2018-05-04 08:29 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5207/
Test PASSed.

2018-05-04 18:56 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5219/
Test PASSed.

2018-05-04 19:22 UTC, merged