[DataFrame] Implement diff
ray-project/ray pull request #1996
Opened 2018-05-03 07:05 UTC by 11rohans

Implements `DataFrame.diff`

2018-05-03 07:38 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5166/
Test FAILed.

2018-05-03 21:42 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5176/
Test PASSed.

2018-05-03 22:56 UTC, kunalgosar commented
Dtypes PR was merged in so this can be rebased on master now.

2018-05-03 23:10 UTC, kunalgosar requested changes
Looks really good! Probably doesn't require the rebase on #1930 and #1956 though.

2018-05-03 23:10 UTC, kunalgosar commented on python/ray/dataframe/dataframe.py
> +        if (axis == 1 or axis == 'columns'):
Can use `axis = pd.DataFrame()._get_axis_number(axis)` here.

2018-05-03 23:10 UTC, kunalgosar commented on python/ray/dataframe/dataframe.py
> +            result = _map_partitions(lambda df:
Some code can be reused between the two functions here. There are examples that do similar things, eg: `mode`.

2018-05-03 23:10 UTC, kunalgosar commented on python/ray/dataframe/test/test_dataframe.py
> +def test_diff(ray_df, pandas_df):
Try different axis and period values in the tests.

2018-05-04 05:31 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5194/
Test PASSed.

2018-05-04 05:31 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5196/
Test PASSed.

2018-05-04 19:16 UTC, 11rohans commented
Comments resolved

2018-05-04 19:42 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5222/
Test FAILed.

2018-05-04 19:50 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5221/
Test PASSed.

2018-05-04 20:37 UTC, kunalgosar approved these changes
Looks great!

2018-05-04 20:38 UTC, kunalgosar commented
Can you resolve flake issues?

2018-05-04 22:19 UTC, 11rohans commented
resolved flake8

2018-05-04 22:39 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5226/
Test PASSed.

2018-05-05 07:44 UTC, devin-petersohn approved these changes

2018-05-05 07:44 UTC, merged

2018-05-05 07:44 UTC, devin-petersohn commented
Passes private-travis. Merged, thanks @11rohans