[DataFrame] Implements df.pipe
ray-project/ray pull request #1999
Opened 2018-05-03 10:01 UTC by SaladRaider

## What do these changes do?
Implements df.pipe

2018-05-03 11:05 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5170/
Test PASSed.

2018-05-03 21:59 UTC, kunalgosar requested changes
Looks really good! Just a small comment regarding testing.

2018-05-03 21:59 UTC, kunalgosar commented on python/ray/dataframe/test/test_dataframe.py
>  def test_pipe():
Can we continue to use the pytest fixtures here?

2018-05-04 00:50 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5179/
Test PASSed.

2018-05-04 06:57 UTC, devin-petersohn approved these changes

2018-05-04 07:00 UTC, kunalgosar approved these changes
Looks great!

2018-05-04 17:16 UTC, merged

2018-05-04 17:16 UTC, devin-petersohn commented
Passes private-travis. Merged, Thanks @SaladRaider!