[Java] Add isDetached Option
ray-project/ray pull request #20413
Opened 2021-11-16 08:38 UTC by lixin-wei

## Why are these changes needed?

Add isDetached actor creation option to Java API.

## Related issue number

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-11-16 12:11 UTC, jovany-wang approved these changes
LGTM

2021-11-16 12:26 UTC, kfstorm reviewed
LGTM overall, but we need to add a unit test.

2021-11-16 12:28 UTC, kfstorm commented
BTW, in Python we use `MyActor.options(lifetime="detached").remote()` to create a detached actor. Maybe we need to use a lifetime enum in Java as well.

2021-11-16 12:30 UTC, jovany-wang commented
> BTW, in Python we use `MyActor.options(lifetime="detached").remote()` to create a detached actor. Maybe we need to use a lifetime enum in Java as well.

Yes. But the value of the enum should be detached or extends from the parent right?

2021-11-17 03:11 UTC, kfstorm commented
@jovany-wang What do you mean by "extends from the parent"?

2021-11-17 03:21 UTC, jovany-wang commented
> @jovany-wang What do you mean by "extends from the parent"?

Sorry. I think what I'd like to mean is fate sharing with the parent actor.

2021-11-18 06:30 UTC, kfstorm commented
@jovany-wang We can just create an enum `ActorLifetime` with `Default` and `Detached` options. We can add some comments on the options about the detailed behaviors.

2021-11-18 06:51 UTC, jovany-wang commented
> @jovany-wang We can just create an enum `ActorLifetime` with `Default` and `Detached` options. We can add some comments on the options about the detailed behaviors.

I see.
@lixin-wei Do you intended to introduce ActorLifetime enum and add unit test for it?

2021-11-22 09:31 UTC, raulchen commented on java/api/src/main/java/io/ray/api/call/BaseActorCreator.java
> +  public T isDetached(boolean isDetached) {
better name this `setDetached`. `isDetached` sounds like a getter method.

2021-11-22 09:32 UTC, raulchen reviewed
please add a test

2021-11-22 09:35 UTC, raulchen requested changes
Right, to be aligned with Python, we should use `setLifetime(ActorLifetime.DETACHED)`. 
Also, please change the `actor.rst` doc file as well.

2022-01-06 14:23 UTC, closed without merging