[WIP] Change plasma_get take a timeout and multiple object IDs.
ray-project/ray pull request #206
Opened 2017-01-16 08:06 UTC by robertnishihara

2017-01-17 10:13 UTC, stephanie-wang requested changes

2017-01-17 10:13 UTC, stephanie-wang commented on src/plasma/plasma_store.c
> +  if (object_get_reqs != NULL) {
We could remove one indentation by returning if `object_get_reqs == NULL`.

2017-01-17 10:13 UTC, stephanie-wang commented on src/plasma/plasma_store.c
> +  /* If all of the objects are present already, return to the client. */
Might be worth it to also return immediately if `timeout_ms` is 0, since this will be a common pattern.

2017-01-18 02:29 UTC, robertnishihara commented on src/plasma/plasma_store.c
> +  /* If all of the objects are present already, return to the client. */
Good idea.

2017-01-18 02:32 UTC, pcmoritz commented on lib/python/ray/worker.py
> +  def get_object(self, object_ids):
can you rename this to get_objects and fix the docstring?

2017-01-18 03:49 UTC, robertnishihara commented on src/plasma/plasma_client.c
> +      plasma_object object_data;
Ok, good point.

2017-01-18 22:49 UTC, robertnishihara commented
Replaced by #212.

2017-01-18 22:49 UTC, closed without merging