[gcs] Fix can not resue actor name in the same namespace after be…
ray-project/ray pull request #20679
Opened 2021-11-23 18:14 UTC by newmanwang

…ing killed(#20611)

    Before this PR, `GcsActorManager::CreateActor()` would replace actor's namespace by
actors's owner job's namespace, even if actor is created by user with a user specified
namespace. But in named_actors_, actor is set to use user specified namespace by
`GcsActorManager::RegisterActor` before CreateActor() is called, So that
`GcsActorManager::DestroyActor` failed to find actor from named_actors_ by owner job's
namespace to remove, hence reuse actor name in same namespace failed for same name actor
 not removed by `GcsActorManager::DestroyActor` in named_actors_.

    ## Related issue number
    https://github.com/ray-project/ray/issues/20611

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-11-26 00:52 UTC, rkooo567 approved these changes

2021-11-26 00:55 UTC, rkooo567 commented
Lint failure!

2021-11-26 03:15 UTC, newmanwang commented
Sorry,  working on it

2021-11-26 03:44 UTC, rkooo567 commented
Can you also add a cpp unit test to gcs_actor_manager.cc?

2021-11-26 10:36 UTC, newmanwang commented
sure

2021-11-29 02:40 UTC, rkooo567 commented
Current status: Waiting for lint fix and cpp unit tests

2021-12-02 18:41 UTC, wuisawesome requested changes

2021-12-02 18:41 UTC, wuisawesome commented on src/ray/gcs/gcs_server/gcs_actor_manager.cc
> +      std::make_shared<GcsActor>(
Is it possible to add a c++ unit test for this? (`gcs_actor_manager_test.cc`)

2021-12-08 06:41 UTC, rkooo567 commented
Any progress on this?

2021-12-12 16:40 UTC, newmanwang commented
> Any progress on this?

Sorry for the delay, I have been busy as hell recently. Writing cpp test now, I am hoping to submit changes tomorrow.

2021-12-13 19:20 UTC, newmanwang commented
Could you please take a look at this clean pr https://github.com/ray-project/ray/pull/21053 and drop this one. @rkooo567

2021-12-14 04:45 UTC, closed without merging