Use pubsub instead of timeout for ObjectManager Pull.
ray-project/ray pull request #2079
Opened 2018-05-16 23:29 UTC by elibol

This PR removes the ObjectManager timeout for `Pull`. The ObjectDirectory interface method `Lookup` has been removed and replaced with methods `Subscribe` and `Unsubscribe`, which implement the existing GCS `Lookup` call followed by `RequestNotifications` whenever GCS `Lookup` fails to obtain object locations. This implementation eliminates the need to poll the GCS for object locations, which improves the performance of `Pull`.

2018-05-16 23:52 UTC, robertnishihara commented on src/ray/object_manager/object_directory.cc
> +    return ray::Status::Invalid("Cannot do things.");
I don't understand this message.

2018-05-17 00:02 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5439/
Test FAILed.

2018-05-17 01:11 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5442/
Test PASSed.

2018-05-17 01:53 UTC, eric-jj commented on src/ray/object_manager/object_directory.cc
> +                                             const std::vector<ObjectTableDataT> data) {
const std::vector<ObjectTableDataT>& data？

2018-05-17 01:54 UTC, eric-jj commented on src/ray/object_manager/object_directory.cc
> +    for (auto item : data) {
for (auto& item ：data)

2018-05-17 01:59 UTC, eric-jj commented on src/ray/object_manager/object_directory.cc
> +        for (auto entry : location_entries) {
for (auto& entry : location_entries) {

2018-05-17 02:44 UTC, eric-jj commented on src/ray/object_manager/object_directory.cc
> +        if (listeners_.count(object_id) > 0) {
Is the GetLocations is a sync call or async call?
If it is a sync call, we don't need the check here. If it is an async call, it means the listeners_ can be changed during the line, we must add lock to it.

2018-05-17 19:11 UTC, stephanie-wang requested changes
In general, let's try to think carefully about the places where we return `ray::Status` and what it means if we return a status that is not OK. If there are methods where we should always return OK, I think it's better to just return void and add fatal checks for non-OK situations. If there are places where we should return a status, we should document in the method what it means if the status is not OK.

2018-05-17 23:52 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5457/
Test PASSed.

2018-05-18 17:44 UTC, elibol commented on src/ray/object_manager/object_directory.cc
> +ray::Status ObjectDirectory::UnsubscribeObjectLocations(const ObjectID &object_id) {
This now returns status of `CancelNotifications`.

2018-05-18 18:07 UTC, stephanie-wang commented on src/ray/object_manager/object_directory.cc
> +  gcs_client_->object_table().Subscribe(UniqueID::nil(),
There is an unused return status here. Either return it or `RAY_CHECK_OK`.

2018-05-18 18:07 UTC, stephanie-wang commented on src/ray/object_manager/object_directory.cc
> +    entry->second.locations_found_callback(client_id_vec, object_id);
Do you want to call the callback if `client_id_vec` is empty?

2018-05-18 18:38 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5481/
Test PASSed.

2018-05-18 20:40 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5482/
Test PASSed.

2018-05-18 23:59 UTC, stephanie-wang approved these changes

2018-05-19 00:59 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5486/
Test PASSed.

2018-05-19 04:34 UTC, elibol commented
Tests look good: https://travis-ci.com/robertnishihara/ray-private-travis/builds/73884240

2018-05-19 04:35 UTC, merged