[Dask-on-Ray] Manually set global Dask scheduler config, along with task-based shuffle.
ray-project/ray pull request #21114
Opened 2021-12-15 19:09 UTC by clarkzinzow

Dask default's to a disk-based shuffle even thought we're using a distributed scheduler, which appears to be resulting in dropped data since the filesystem isn't shared across nodes. Dask Distributed manually sets the shuffle algorithm in the global config to the task-based shuffle, which the Dask-on-Ray scheduler should probably do as well.

This PR sets the global scheduler config at import time, along with changing the default shuffle to a task-based shuffle. This can still be overridden by the user by manually specifying `df.set_index(shuffle="disk")`.

## Related issue number

Closes #20108, closes #20992

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2021-12-15 19:11 UTC, ericl approved these changes
Looks good. I've always wanted this override to happen by default!

2021-12-15 19:20 UTC, clarkzinzow commented
@ericl Once I saw that Dask Distributed was doing it, I felt a lot better about it. 😄  Although they still have the option `Client(set_as_default=False)` to keep from setting the global config, but I think that we can wait to expose that hook until a user asks for it.

2021-12-15 23:46 UTC, rkooo567 approved these changes
Nice job finding this. Is there a way to add a test?

2021-12-15 23:58 UTC, ericl commented
//python/ray/util/dask:test_dask_optimization                            FAILED in 3 out of 3 in 9.9s

2021-12-16 06:29 UTC, rkooo567 requested changes
Request change to add test cases?

2021-12-16 07:35 UTC, clarkzinzow commented
@rkooo567 Sure, I guess I could remove the explicit setting of the scheduler in the scheduler tests now that it happens automatically at import time.

2021-12-16 08:59 UTC, rkooo567 commented
Does this mean we allow to disable this in some cases? If so, I think we should have a test for that (disabling case)

2021-12-17 07:42 UTC, clarkzinzow commented
@rkooo567 @ericl changed it to a config-setting helper, `enable_dask_on_ray`, which we can encourage Dask-on-Ray users to use.

2021-12-17 21:15 UTC, rkooo567 approved these changes

2021-12-17 21:15 UTC, rkooo567 commented
Lgtm!!

2021-12-17 21:16 UTC, ericl approved these changes
I'm also OK with this approach.

2021-12-17 21:16 UTC, merged