Lineage evict
ray-project/ray pull request #2196
Opened 2018-06-06 06:01 UTC by raulchen

=== Problem ===
Previously, when forwarding a task, we request a notification from GCS if the uncommitted lineage size is larger than `max_lineage_size` (configurable, 100 by default). The purpose of doing this is to evict these uncommitted lineage once is task's lineage is committed by a remote node.

However, this could have some perf issues in some cases. For example, if one worker forwards a large number (`N`) of tasks very quickly to an actor (this is common in streaming scenario). If the downstream actor doesn't process the tasks fast enough. We'll end up with requesting `N - max_lineage_size` notifications, which may bring significant workload to both local node manager and the GCS.

=== Solution ===
This RP resolves this issue by only request notifications for **every** `max_lineage_size` tasks. By doing this, we can reduce the number of requested notifications to at most `N / max_lineage_size`.

Also, it reduced the complexity of counting uncommitted lineage from `1 + 2 + ... + (N - max_lineage_size)` to `N`.

2018-06-06 07:12 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5886/
Test PASSed.

2018-06-06 07:14 UTC, raulchen commented
@stephanie-wang could you please take a look? thank you!

2018-06-06 17:58 UTC, stephanie-wang requested changes
Thanks a lot, this looks great! I left one small comment, but then we can merge this.

2018-06-06 17:58 UTC, stephanie-wang commented on src/ray/raylet/lineage_cache.h
> +  uint64_t CountUnsubscribedLineage(const UniqueID &task_id);
Can you make this `const`?

2018-06-06 18:08 UTC, robertnishihara commented
Looks like there are some linting errors https://travis-ci.com/ray-project/ray/jobs/127791187.

2018-06-07 02:59 UTC, raulchen commented
Comments are all fixed.
BTW, how do I locally run linter for c++ code? just `clang-format changed_files`?

2018-06-07 03:08 UTC, stephanie-wang approved these changes

2018-06-07 03:09 UTC, stephanie-wang commented
Thanks! I'll merge once the tests pass.

For linting, in the top-level directory, you can run `$ .travis/git-clang-format`

2018-06-07 03:39 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5904/
Test PASSed.

2018-06-07 03:48 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5905/
Test PASSed.

2018-06-07 04:04 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5906/
Test PASSed.

2018-06-07 04:09 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/5907/
Test PASSed.

2018-06-07 06:29 UTC, raulchen commented
CI errors seem unrelated

2018-06-07 07:35 UTC, merged