PoolActor now uses num_cpus=0 to avoid any deadlock
ray-project/ray pull request #22048
Opened 2022-02-02 06:55 UTC by czgdp1807

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-02-02 06:57 UTC, czgdp1807 commented
cc: @pcmoritz @wuisawesome

2022-02-02 18:50 UTC, wuisawesome requested changes
Can we add the repro from #21488 as a test case?

2022-02-03 17:11 UTC, wuisawesome commented on python/ray/tests/test_multiprocessing.py
> +    ray.init(num_cpus=1)
nit: can we initialize ray with a fixture if possible? Ideally we can use `ray_start_shared_local_modes`?

2022-02-03 17:11 UTC, wuisawesome approved these changes

2022-02-08 09:59 UTC, merged