[ray client] enable ray.get with >2 sec timeout (#21883)
ray-project/ray pull request #22165
Opened 2022-02-07 08:08 UTC by takeshi-yoshimura

Commit 2cf4c72 ("[ray client] Fix ctrl-c for ray.get() by setting a short-server side timeout") introduced a short server-side timeout not to block later operations.

However, the fix implicitly assumes that get() is complete within MAX_BLOCKING_OPERATION_TIME_S (two seconds). This becomes a problem when apps use heavy objects or limited network I/O bandwidth that require more than two seconds to push all chunks. The current retry logic needs to re-push from the beginning of chunks and block clients with the infinite re-push.

I updated the logic to directly pass timeout if it is explicitly given. Without timeout, it still uses MAX_BLOCKING_OPERATION_TIME_S for polling with the short server-side timeout.

Initially, I thought the fix should be exponential back-off, but that may change the behavior of many apps. So, this patch focuses on enabling bigger timeouts.

## Why are these changes needed?

## Related issue number

Closes #21883

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-03-25 00:47 UTC, ckw017 approved these changes
Looks good to me, can you merge with master? That should rerun CI and hopefully fix the failing tests.

2022-03-28 01:26 UTC, takeshi-yoshimura commented
@ckw017 
Thanks. I merged with master.

2022-03-30 21:21 UTC, ckw017 requested changes
Hmm, re-evaluating this, I think this overloads the meaning of `ray.get`'s timeout a bit too much. For example, users will have to explicitly add timeout to work in client, even though it would be unnecessary when attaching a driver directly.

@takeshi-yoshimura would being able to set an environment variable, i.e. something like `RAY_CLIENT_MAX_BLOCKING_OPERATION_TIME_S=20` to increase the timeout work for your usecase instead?

Alternatively we can try bumping `MAX_BLOCKING_OPERATION_TIME` to a higher value

cc @ericl (author of #14425)

2022-03-30 21:27 UTC, ckw017 commented
Hmm, re-evaluating this, I think this overloads the meaning of `ray.get`'s timeout a bit too much. For example, users will have to explicitly add timeout to work in client, even though it would be unnecessary when attaching a driver directly.

@takeshi-yoshimura would being able to set an environment variable, i.e. something like `RAY_CLIENT_MAX_BLOCKING_OPERATION_TIME_S=20` to increase the timeout work for your usecase instead?

cc @ericl (author of #14425)

2022-04-05 03:11 UTC, takeshi-yoshimura commented
@ckw017 
Updated the code to introduce a new environmental variable `RAY_CLIENT_MAX_BLOCKING_OPERATION_TIME_S` according to your request.

2022-04-05 16:58 UTC, ckw017 commented on python/ray/util/client/worker.py
> +        max_blocking_operation_time = MAX_BLOCKING_OPERATION_TIME_S
```suggestion
        if 'RAY_CLIENT_MAX_BLOCKING_OPERATION_TIME_S' in os.environ:
            max_blocking_operation_time = float(os.environ['RAY_CLIENT_MAX_BLOCKING_OPERATION_TIME_S'])
```

2022-04-05 16:59 UTC, ckw017 commented
Looks good, looks like the only thing failing is the [lint](https://buildkite.com/ray-project/ray-builders-pr/builds/28819#bac99b5f-5699-44cc-84b9-05de241c720a/1492-1578). Can you update to match what the linter is suggesting?

<img width="805" alt="Screen Shot 2022-04-05 at 9 59 15 AM" src="https://user-images.githubusercontent.com/14043490/161809423-dcc6fd0d-a05c-41a3-8595-df3c81644d80.png">

2022-04-07 02:01 UTC, takeshi-yoshimura commented
I fixed the format. thanks.

2022-04-07 18:01 UTC, ckw017 approved these changes

2022-04-21 17:17 UTC, ckw017 commented
Looks like we had a few problems with our testing infra when you first ran the PR, if you merge with master and push again it should be good to go!

2022-04-22 02:47 UTC, takeshi-yoshimura commented
Merged again. let's see...

2022-04-22 19:08 UTC, ckw017 commented
Okay, looks like failures are:
* LinkCheck (safe to ignore, failing on master as well)
* rllib:learning_tests_pendulum_ddppo (safe to ignore, failing on master)
* rllib:learning_tests_cartpole_ddppo (safe to ignore, failing on master at time of merge)
* mac tests (Looks like something in our infra dropped a bunch of mac agents around that time, IMO safe to ignore)

2022-04-22 19:09 UTC, ckw017 commented
cc @ijrsvt can you take a look/merge this when you get the chance

2022-04-22 20:48 UTC, ijrsvt approved these changes
LGTM

2022-04-25 20:06 UTC, ijrsvt commented
RLLIB Tests & OSX `test_shuffle` are failing on master at the point of rebase.

2022-04-25 20:06 UTC, merged