[runtime env] Add test for scheduling task after failed job env
ray-project/ray pull request #22224
Opened 2022-02-08 18:45 UTC by architkulkarni

## Why are these changes needed?
Adds a test to make sure a failed job runtime env creation doesn't hang the cluster (i.e. tasks can still be scheduled on the job, as long as the tasks' runtime env can be created.).  Test requested by @rkooo567, good idea!

## Related issue number

Closes #22218 
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-02-08 20:00 UTC, edoakes approved these changes

2022-02-09 06:07 UTC, rkooo567 requested changes
Can you add one more test ?

2022-02-09 06:07 UTC, rkooo567 commented on python/ray/tests/test_runtime_env.py
> +    assert ray.get(f.options(runtime_env={"pip": ["pip-install-test==0.5"]}).remote())
Actually I also would like to test the case where runtime env is not given (so it uses the default job runtime env).

Can you test this case?

2022-02-09 22:46 UTC, rkooo567 approved these changes

2022-02-10 22:30 UTC, architkulkarni commented
`//python/ray/data:tests/test_dataset` and `//python/ray/tests:test_dataclient_disconnect` flaky on master and unrelated

2022-02-11 17:01 UTC, merged