[core] Fix bug in fusion of spilled objects
ray-project/ray pull request #22750
Opened 2022-03-02 02:17 UTC by stephanie-wang

## Why are these changes needed?

Copied from #22571:

Whenever we spill, we try to spill all spillable objects. We also try to fuse small objects together to reduce total IOPS. If there aren't enough objects in the object store to meet the fusion threshold, we spill the objects anyway to avoid liveness issues.

However, the current logic always spills once we reach the end of the spillable objects or once we've reached the fusion threshold. This can produce lots of unfused objects if they are created concurrently with the spill.

This PR changes the spill logic: once we reach the end of the spillable objects, if the last batch of spilled objects is under the fusion threshold, we'll only spill it if we don't have other spills pending too. This gives the pending spills time to finish, and then we can re-evaluate whether it's necessary to spill the remaining objects. Liveness is also preserved.

Increases the test timeout in test_plasma_unlimited to allow tests to pass. I think this test was failing because the fix for fused objects can sometimes delay spilling when there are only a few objects in the store.

2022-03-02 14:17 UTC, rkooo567 approved these changes
Didn't review the PR, but I assume the bug was fixed..

2022-03-13 09:08 UTC, kfstorm commented
## :bangbang: ACTION REQUIRED :bangbang:

We've updated our formatting configuration for C++ code. (see #22725)

This PR includes C++ code change. To prevent issues with merging your code, here's what you'll need to do:

1. Merge the latest changes from upstream/master branch into your branch.

```bash
git pull upstream master
git merge upstream/master
```

2. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated C++ formatting configuration.

3. Format changed files.

```bash
scripts/format.sh
```

4. Commit your changes.

```bash
git add --all
git commit -m "Format C++ code"
```

2022-04-01 17:28 UTC, stephanie-wang commented
@rkooo567 I updated this PR a bit to address another issue I found where we're spilling at most the fusion size instead of at least. Can you take a look at the C++ changes and re-approve?

2022-04-01 23:55 UTC, rkooo567 requested changes
Temporarily request changed when I review the new change (will do this sun)

2022-04-04 05:31 UTC, rkooo567 approved these changes
I think we should update the docstring, but other than that, it lgtm

2022-04-04 05:31 UTC, rkooo567 commented on src/ray/raylet/local_object_manager.cc
> +  while (it != pinned_objects_.end() && counts < max_fused_object_count_) {
Can you update the docstring of `SpillObjectsOfSize` to explain semantic changes?

2022-04-05 17:57 UTC, merged