[ML] `TensorflowPredictor` implementation
ray-project/ray pull request #23146
Opened 2022-03-14 18:26 UTC by Yard1

## Why are these changes needed?

Implementation for `TensorflowPredictor`.

## Related issue number

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-03-14 19:13 UTC, amogkam approved these changes
LGTM! Just left one nit

2022-03-14 19:13 UTC, amogkam commented on python/ray/ml/predictors/integrations/tensorflow/tensorflow_predictor.py
> +        model = self.model_definition()
Can you leave a comment saying that the reason we are not doing this in __init__ is because this would make the predictor unserializable?

2022-03-14 20:16 UTC, ericl approved these changes

2022-03-14 20:20 UTC, xwjiang2010 approved these changes

2022-03-14 20:56 UTC, krfricke approved these changes
Great!

2022-03-14 21:11 UTC, amogkam requested changes

2022-03-14 21:11 UTC, amogkam commented on python/ray/ml/predictors/integrations/tensorflow/tensorflow_predictor.py
> +        data = self.preprocessor.transform_batch(data)
Same comment for this one- let's also support the case when `self.preprocessor` is None. Thanks!

2022-03-14 21:36 UTC, amogkam approved these changes
Thanks! Just one typo

2022-03-14 21:36 UTC, amogkam commented on python/ray/ml/predictors/integrations/tensorflow/tensorflow_predictor.py
> +                f"checkpoint in ``TorchTrainer``."
TensorflowTrainer?

2022-03-14 21:38 UTC, Yard1 commented on python/ray/ml/predictors/integrations/tensorflow/tensorflow_predictor.py
> +                f"checkpoint in ``TorchTrainer``."
whoops

2022-03-15 00:02 UTC, amogkam commented
Windows and mac tests are unrelated, going to merge

2022-03-15 00:02 UTC, merged