support hdfs at runtime env
ray-project/ray pull request #23273
Opened 2022-03-17 08:36 UTC by zkmn73

Change-Id: I4dcbbb7fdfe543ea1af67113b79d880cfa3fe411

## Why are these changes needed?

## Related issue number

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-06-24 20:23 UTC, shrekris-anyscale requested changes
Nice work! The change mostly looks good to me. @simon-mo Do you think we should add an integration test?

2022-06-24 20:23 UTC, shrekris-anyscale commented on python/ray/_private/runtime_env/packaging.py
> +    will be the adjusted path with 'gs_' prepended.
```suggestion
    will be the adjusted path with 'hdfs_' prepended.
```

2022-06-24 20:42 UTC, simon-mo commented on python/ray/_private/runtime_env/packaging.py
> +                    subprocess.check_call(["hdfs", "dfs", "-get", pkg_uri, pkg_file])
smart_open already support hdfs https://github.com/RaRe-Technologies/smart_open

2022-06-28 23:30 UTC, architkulkarni requested changes
I agree with Simon's comment, can we just use `smart_open` here as we do for the other URIs?

2022-08-13 23:18 UTC, closed without merging