[draft] raise_on_failed_trial=False
ray-project/ray pull request #23280
Opened 2022-03-17 16:03 UTC by xwjiang2010

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-03-18 00:57 UTC, xwjiang2010 commented
@amogkam Consider the timeline, I prefer to go down this route to unblock merging the rest of PRs. wdyt?

2022-03-18 01:05 UTC, amogkam commented
This sgtm. Should we add a test for this on the tuner side?

2022-03-18 03:28 UTC, xwjiang2010 commented
@amogkam Added some basic coverage. Will update it once settling on a long term plan with Kai.

2022-03-18 03:40 UTC, amogkam approved these changes
Lgtm, but I think you accidentally pushed over all the experiment result files

2022-03-18 05:08 UTC, amogkam commented
just fyi this currently doesn't work if `trial.checkpoint.value` is None. I had to patch in `if trial.checkpoint.value else None` into #23282.

btw, doesn't seem like Tuner is being tested right now? Should we slot that into beta?

2022-03-18 11:42 UTC, krfricke requested changes
The actual fix looks good to me, but I'm against committing quasi-binary checkpoints/states into CI. If we ever change the checkpoint format we will need to re-generate these, there are no instructions on how to do so and it is a test maintenance overhead we don't want to have.

Instead, please either construct an ExperimentAnalysis object and populate the trials manually, or if really required, construct a trial runner, add trials + their results, call the `trial_runner.checkpoint()` method to a temporary directory and use that checkpoint.

2022-03-21 15:31 UTC, krfricke approved these changes
Looks good - is the actual change already merged (since this is just a test)?

2022-03-21 17:09 UTC, xwjiang2010 commented on python/ray/tune/tuner.py
> +            run_config(name="my_tune_run")
fixed the typo.

2022-03-21 17:09 UTC, xwjiang2010 commented
> Looks good - is the actual change already merged (since this is just a test)?

Yes that's correct :)

2022-03-22 15:21 UTC, merged