[Datasets] Add basic data ecosystem overview, user guide links, other data processing options card.
ray-project/ray pull request #23346
Opened 2022-03-19 00:27 UTC by clarkzinzow

Tweaks the landing page for Datasets to give a (very brief) overview of the data ecosystem. Also includes misc. additions, e.g. to the new user guide pages.

Expanding the data ecosystem overview to include more content can be done in a future PR.

2022-03-19 00:41 UTC, ericl commented on doc/source/data/dataset.rst
> +Ray Data: Data Procesing on Ray
```suggestion
Ray Data: Data Processing on Ray
```

2022-03-19 00:41 UTC, ericl commented on doc/source/data/dataset.rst
> +The Ray ecosystem offers several great solutions for performant, large-scale data processing on Ray.
```suggestion
The Ray ecosystem offers several solutions for performant, large-scale data processing on Ray.
```

2022-03-19 00:44 UTC, ericl commented on doc/source/data/dataset.rst
> +For running super scalable ETL pipelines, check out :ref:`Spark-on-Ray<spark-on-ray>`. For scaling up your data science workloads, check out :ref:`Dask-on-Ray<dask-on-ray>`, :ref:`Modin<modin`, and :
```suggestion
For running ETL pipelines, check out :ref:`Spark-on-Ray<spark-on-ray>`. For scaling up your data science workloads, check out :ref:`Dask-on-Ray<dask-on-ray>`, :ref:`Modin<modin`, and :ref:`Mars-on-Ray<mars-on-ray>`.
```

2022-03-19 00:46 UTC, ericl requested changes
After thinking about this more, I don't think this change is desirable. Some of these integrations are not quite fully baked, so we shouldn't be recommending them in the front page.

Saying there are "several solutions" is also confusing the messaging here. We want to be clear that Datasets is the one standard way, and integrations can be introduced later.

For this PR, I think the changes to the front matter of dataset.rst should be reverted, but we can keep the changes further down in the page.

2022-04-18 03:08 UTC, clarkzinzow commented
Not stale

2022-04-22 20:13 UTC, jianoaix commented
> After thinking about this more, I don't think this change is desirable. Some of these integrations are not quite fully baked, so we shouldn't be recommending them in the front page.
> 
> Saying there are "several solutions" is also confusing the messaging here. We want to be clear that Datasets is the one standard way, and integrations can be introduced later.
> 
> For this PR, I think the changes to the front matter of dataset.rst should be reverted, but we can keep the changes further down in the page.

+1 not to feature alternative solutions at home page.
I think it's a good idea to having an overview of where Dataset fits / positioning, e.g. one reads this page should easily know that this is not for ETL.

2022-05-17 19:25 UTC, ericl commented
Stale.

2022-05-17 19:51 UTC, clarkzinzow commented
I'll be revisiting this PR today and implementing the above feedback.

2022-05-18 01:25 UTC, clarkzinzow commented
@ericl I implemented all feedback, including pushing all mentioning of third-party integrations to the integrations card. Can you and @jianoaix PTAL?

2022-05-18 02:00 UTC, ericl reviewed
I feel very strongly that we shouldn't introduce "Ray Data" or "broader ecosystem" in the frontmatter and the doc should focus purely on Datastes. I made a change to revert this change.

If it looks good to you, the rest of the PR is fine with me.

2022-05-18 03:27 UTC, clarkzinzow commented
@ericl Sure, if that commit makes this pass the bar, can you approve the PR so I can merge it?

2022-05-18 03:40 UTC, ericl approved these changes

2022-05-18 03:57 UTC, merged