[WIP] Ping Ray cluster
ray-project/ray pull request #23382
Opened 2022-03-21 18:20 UTC by mwtian

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-03-23 14:24 UTC, rkooo567 commented
Just curious, but how would this be different from https://github.com/ray-project/ray/blob/f91a134dc6d1bba8cd730cbcf4f9d4b629a08df9/dashboard/head.py#L60?

2022-03-23 22:40 UTC, rkooo567 commented
> They look very similar. The only difference is that ping_cluster() has the additional check for Python and Ray version compatibility. Should we update dashboard to use this utility or use CheckAliveRequest() here instead?

I don't have a strong opinion what to use, but I think we should unify to one (seems like both are for health checking the cluster).

cc @wuisawesome do you see any downsides of just using this util?

2022-03-23 23:46 UTC, wuisawesome requested changes
Please please add this functionality to `ray healthcheck` (which uses `CheckAliveRequest`). We shouldn't let this type of functionality deviate between components

2022-03-23 23:58 UTC, mwtian commented
How about using `CheckAliveRequest()` to check connectivity, and use cluster metadata to check Python & Ray versions? I'm not sure we want to add unnecessary data to the health check response.

2022-03-24 18:42 UTC, mwtian commented
I thought about the use case and only verifying Ray versions match should be sufficient.

2022-03-24 20:28 UTC, wuisawesome commented
Ok can we change the api name to make it clear that this is _not_ a healthcheck or way to ping the cluster? some form of cluster metadata that we can expose through the dashboard api seems reasonable.

2022-03-24 22:50 UTC, mwtian commented
@wuisawesome which API are you referring to, `ping_cluster()` or `CheckAlive`?

2022-04-04 08:00 UTC, rkooo567 commented
I will leave it up to @wuisawesome also cc @jon-chuang

2022-04-04 18:53 UTC, wuisawesome commented
> @wuisawesome which API are you referring to, ping_cluster() or CheckAlive?

`CheckAlive` is a grpc health check, and powers `ray health-check`. (I don't think the grpc endpoint is stable across versions since only `ray health-check` is). 

If you're trying to add a cluster metadata api and not a health check, I'm saying you should name it `GetClusterMetadata`. Calling it `ping` is extremely confusing since well known libraries like Redis use `ping` as a health check.

Btw it's also still not clear to me why you don't just add this in the health check. The main reason to separate them would be if we have some big metadata/expensive query that we didn't want to run in a health check (which we don't).

2022-04-14 04:23 UTC, mwtian commented
> Btw it's also still not clear to me why you don't just add this in the health check. The main reason to separate them would be if we have some big metadata/expensive query that we didn't want to run in a health check (which we don't).

Actually I'm using the `CheckAlive` rpc right now. Renaming the function to health check.

2022-04-14 04:46 UTC, mwtian commented
The plan is to add a public health check API in a subsequent PR.

2022-04-14 20:33 UTC, wuisawesome approved these changes

2022-04-14 20:33 UTC, wuisawesome commented on python/ray/_private/gcs_utils.py
> +def check_health(address: str, timeout=2):
```suggestion
def check_health(address: str, timeout=2) -> bool:
```

2022-04-18 16:58 UTC, merged