[Core] Add metadata to ray.remote keywords
ray-project/ray pull request #23884
Opened 2022-04-13 05:42 UTC by suquark

## Why are these changes needed?

We need `metadata` keyword for both Ray Workflow and Ray Serve. This is because after unification, Ray workflow and Ray serve are using remote function/remote actor API, we need to put extra options for them.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-04-13 20:07 UTC, suquark commented on python/ray/worker.py
> +        metadata (Dict[str, Any]): Extended options for Ray libraries. For example,
I think @iycheng @jiaodong both said (or TODOs) that we should use "metadata".

2022-04-14 17:59 UTC, jiaodong commented on python/ray/worker.py
> +        metadata (Dict[str, Any]): Extended options for Ray libraries. For example,
Yep for both workflow and serve deployment graph we uses the hidden "metadata" field at ray level, name looks good to me. cc: @ericl for a final quick look.

2022-04-14 18:43 UTC, ericl commented on python/ray/worker.py
> +        metadata (Dict[str, Any]): Extended options for Ray libraries. For example,
```suggestion
        _metadata: Opaque key-value pairs to attach to the task. This is used for internal library configurations.
```

(Keep it private, also our docstyle is to not have types (google style)).

2022-04-14 18:43 UTC, ericl requested changes
^

2022-04-14 20:54 UTC, suquark commented on python/ray/worker.py
> +        metadata (Dict[str, Any]): Extended options for Ray libraries. For example,
But I think the reason is that we should add type annotations instead? Here we do not have type annotations, so maybe type is better for UX? `*.pyi` could be an alternative, but it hardly works with IDE.

2022-04-14 20:57 UTC, suquark commented on python/ray/worker.py
> +        metadata (Dict[str, Any]): Extended options for Ray libraries. For example,
Also `_metadata` will be used quite frequently for user facing APIs. For example,

```python
@ray.remote(_metadata={"workflow.io/options": {"catch_exceptions": True}})
def foo(): ...
```

Should it still be a private field considering these use cases?

2022-04-14 21:02 UTC, ericl commented on python/ray/worker.py
> +        metadata (Dict[str, Any]): Extended options for Ray libraries. For example,
The type annotations are generated from the real types in the function signature---it's redundant to add them in the pydoc. In fact, people often forget to update it, so the pydoc gets out of sync with the real type signature.

2022-04-14 21:03 UTC, ericl commented on python/ray/worker.py
> +        metadata (Dict[str, Any]): Extended options for Ray libraries. For example,
> Should it still be a private field considering these use cases? @ericl

Yes. We'll be using syntax more like this in the public API (Serve is following this too):

```
@workflow.options(catch_exceptions=True)
@ray.remote
def foo():
```

2022-04-14 21:30 UTC, iycheng commented on python/ray/worker.py
> +        metadata (Dict[str, Any]): Extended options for Ray libraries. For example,
@suquark I think here the API got updated a little bit. And sorry I failed to sync it with you.

Here we'll use `_metadata` for the internal implementation, and for user-facing ones, we'll use a decorator for this as Eric mentioned.

```
@workflow.options(...)
@server(...)
@ray.remote
def foo():
   ...

```

2022-04-15 23:30 UTC, ericl approved these changes

2022-04-16 21:18 UTC, suquark commented
CI errors seem unrelated. I'll merge it.

2022-04-16 21:18 UTC, merged