[Release tests] Create compute config for new dataset shuffle tests
ray-project/ray pull request #24239
Opened 2022-04-26 23:00 UTC by mwtian

## Why are these changes needed?
Use a separate compute config that uses smaller instance types and no object store memory limit for the new shuffle implementation. I verified that the config works on `master` for `dataset_shuffle_*` tests.

## Related issue number
#24176: the added tests would verify the instance types which support the new shuffle implementations.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-04-26 23:49 UTC, jjyao approved these changes

2022-04-26 23:49 UTC, jjyao commented on release/release_tests.yaml
> +    cluster_compute: shuffle/large_scale.yaml
nit: maybe name it `dataset_large_scale_shuffle_compute.yaml`?

2022-04-26 23:49 UTC, stephanie-wang commented on release/nightly_tests/shuffle/large_scale.yaml
> +cloud_id: {{env["ANYSCALE_CLOUD_ID"]}}
Rename file to datasets_large_scale.yaml to differentiate from the other shuffle yaml?

2022-04-26 23:51 UTC, stephanie-wang requested changes
To avoid confusion with all the recent instance type changes, how about making this a separate test that's marked unstable for now? Once we see it passing several times, we can remove the old one.

I'm also kind of surprised this passes since the random_shuffle test was always failing with m5.4xlarge previously. Maybe it has to do with the Ray core changes or removing the object store memory limit, though?

2022-04-27 18:49 UTC, stephanie-wang approved these changes

2022-04-27 18:50 UTC, merged