[tune] add budgeted hyperparameter tuning algorithm
ray-project/ray pull request #2453
Opened 2018-07-22 10:23 UTC by zhiyun

## What do these changes do?

### add BudgetedScheduler to ray/tune
BudgetedScheduler suspends and resumes trials based on a budgeted hyperparameter
optimization algorithm. It uses a Bayesian belief model to predict the
future performance of a configuration, and selects the next trial based
on the future prediction and the remaining budget.
### tune_resnet_budget.py 
example to use the BudgetedScheduler.

cc @mitar

2018-07-22 11:43 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/6771/
Test PASSed.

2018-07-22 13:55 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/6773/
Test PASSed.

2018-07-22 18:54 UTC, richardliaw requested changes
This is really neat.

Here's a general list of TODOs/requests (in no particular order):

 - [ ] Can you rename helper functions so that they're more accessible?
 - [ ] Documenting helper functions in the util files
 - [ ] Removing leftover comments from testing
 - [ ] Linting
 - [ ] Adding docstrings for public classes (we follow [Google style](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html))

 - [ ] Adding unit tests for the Belief Model
 - [ ] Adding documentation in `ray/docs`

2018-07-22 18:54 UTC, richardliaw commented on python/ray/tune/budget/bayesian_util.py
> +import kernel_util as kernel
Generally, we import from the project (ie, `ray.tune.budget.kernel_util`).

2018-07-22 18:54 UTC, richardliaw commented on python/ray/tune/budget/budget.py
> +np.warnings.filterwarnings('ignore')
We can remove this, right?

2018-07-22 18:54 UTC, richardliaw commented on python/ray/tune/budget/tune_resnet_budget.py
> +#!/usr/bin/env python
Let's put this into `ray/tune/examples`

2018-07-22 18:54 UTC, richardliaw commented on python/ray/tune/budget/kernel_util.py
> +  assert t.ndim == 1 or (t.ndim == 2 and t.shape[1] == 1)
Can you make sure assertions have appropriate warning messages?

2018-07-22 18:54 UTC, richardliaw commented on python/ray/tune/budget/budget.py
> +        set according to the Hyperband algorithm.
This is left over from Hyperband right?

2018-07-22 18:54 UTC, richardliaw commented on python/ray/tune/budget/acqn_util.py
> +  if method is 'th1':
`method == "thi"`

2018-07-22 18:54 UTC, richardliaw commented on python/ray/tune/budget/bayesian_util.py
> +    """Freeze thaw posterior (predictive)
Is there some reference for the algorithm implemented here?

2018-07-22 18:54 UTC, richardliaw commented on python/ray/tune/budget/bayesian_util.py
> +  # Set up freeze thaw parameters
We can probably use this in unit tests

2018-07-22 18:54 UTC, richardliaw commented
@ericl What are thoughts on introducing a `contrib` module like in TF?

2018-07-22 19:36 UTC, mitar commented
(I have not looked at the code and I am basing this only on old  discussion with @zhiyun.)

@zhiyun, have you find a way to run this in parallel? If I understand correctly, your original algorithm/design assumed you are running only one thing at the time, and after each unit of work, deciding which one to do next? I think Ray Tune is great because it allows easy parallelism. So I think there are two questions to me here:

* How to make your algorithm parallel?
* Or, how to make sure Ray Tune does not try to parallelize it.

If anything of this is redundant or I am completely missing something, please ignore. :-)

2018-07-22 19:48 UTC, ericl commented
@richardliaw I think having this under a subdir is fine. Actually we can make an schedulers/ dir to clean things up so this can be under schedulers/budget/.

2018-08-11 01:26 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/7419/
Test PASSed.

2019-02-21 07:22 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/12190/
Test FAILed.

2019-02-22 05:49 UTC, ericl commented
[closing stale issue]

2019-02-22 05:49 UTC, closed without merging