[runtime env] URI reference refactor
ray-project/ray pull request #24538
Opened 2022-05-06 08:10 UTC by SongGuyang

## Why are these changes needed?

Recreate for the reverted PR for 2.0. 
https://github.com/ray-project/ray/pull/22828
https://github.com/ray-project/ray/pull/22620

2022-05-06 09:48 UTC, SongGuyang commented
Hey @xwjiang2010, we will make this change again.  Do you already have one UT for the issue https://github.com/ray-project/ray/issues/22595?

2022-05-06 09:53 UTC, SongGuyang commented
@edoakes @rkooo567 @architkulkarni please help to check if we can make this change for 2.0.

2022-05-06 14:25 UTC, rkooo567 commented
cc @edoakes Sorry that i forgot some context. did it pass the API review btw? Should we add an api-review-required tag?

2022-05-06 17:21 UTC, architkulkarni commented
> cc @edoakes Sorry that i forgot some context. did it pass the API review btw? Should we add an api-review-required tag?

This was the API review issue: https://github.com/ray-project/ray/issues/21818 There wasn't any pushback.  We also asked for opinions on OSS Slack and I think I remember there were a few thumbs up and no pushback (unfortunately I think the thread is lost because we have limited history.)

2022-05-06 17:32 UTC, architkulkarni approved these changes
The two PRs mentioned were already approved, so this PR should be approved too.  It includes the warning message for users in the case where the behavior is different.  The Ray 1.13 branch cut has already happened, so if I understand correctly, it's safe to merge this now and this will only appear in Ray 2.0.

I'll try to run `train_pytorch_linear_test` directly on this PR, since now we can run release tests for PRs on buildkite. (running [here](https://buildkite.com/ray-project/release-tests-pr/builds/2441))

2022-05-06 17:51 UTC, edoakes requested changes
According to @zhe-thoughts we should wait for the `branch-1` to be cut before merging breaking changes, so holding for that.

2022-05-12 11:49 UTC, rkooo567 approved these changes
Approving the PR assuming I already approved the same PR before!

2022-05-19 03:32 UTC, SongGuyang commented
We will merge this PR because the "ray-1.x" branch has been cut.

2022-05-19 09:17 UTC, rkooo567 commented on java/test/src/main/java/io/ray/test/RuntimeEnvTest.java
> +  public void testPerActorEnvVars() {
Let's merge this PR after addressing this? @jovany-wang we can just change the code this way here?

2022-05-19 10:10 UTC, jovany-wang commented on java/test/src/main/java/io/ray/test/RuntimeEnvTest.java
> +  public void testPerActorEnvVars() {
This change had been committed at [867ef68](https://github.com/ray-project/ray/pull/24538/commits/867ef6825597c6b1c62449519727c0c271f6f5de)

So feel free to merge this PR

2022-05-19 10:14 UTC, jovany-wang approved these changes

2022-05-19 16:38 UTC, edoakes approved these changes

2022-05-20 02:53 UTC, merged

2022-06-04 21:33 UTC, ericl commented
This PR has caused a P0 regression in master for Tune: https://github.com/ray-project/ray/issues/25484

Thinking about the new behavior, it's also fundamentally inconsistent with how Jobs works. When the user specifies a working_dir, it's very surprising that overriding env_vars also deletes the working dir.

I think we need to change this to either:
1. Raise an *exception* if any fields are dropped (such as working_dir), or
2. Revert to the previous behavior.

The user should have to explicitly set `{"working_dir": None}` to unset the working_dir.