[Release Test] Add smoke_test field to release test report
ray-project/ray pull request #24749
Opened 2022-05-12 20:34 UTC by jjyao

## Why are these changes needed?
Distinguish smoke test and normal test.

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-05-12 21:50 UTC, jianoaix approved these changes

2022-05-13 11:41 UTC, krfricke requested changes
The current implementation is not great because you alter the test configuration and add a hidden field that wouldn't pass validation. Instead of cluttering the test configuration, the correct way is to add a `smoke_test` field to the `Result` class (in `result.py`, maybe below the `stable` field), populate it in `run_release_test()` (in `glue.py`, maybe below `result.stable`) and then pass that in `db.py`.

2022-05-13 19:03 UTC, jjyao commented
> The current implementation is not great because you alter the test configuration and add a hidden field that wouldn't pass validation. Instead of cluttering the test configuration, the correct way is to add a `smoke_test` field to the `Result` class (in `result.py`, maybe below the `stable` field), populate it in `run_release_test()` (in `glue.py`, maybe below `result.stable`) and then pass that in `db.py`.

I actually want to add it to the `Test` class:
```
class Test(dict):
   def __init__(self):
      self.smoke_test=False
```

2022-05-16 09:38 UTC, krfricke approved these changes
Great, thanks!

2022-05-16 09:38 UTC, merged