[Core] Use newly pushed actor for existing pending tasks
ray-project/ray pull request #24980
Opened 2022-05-19 19:00 UTC by siavash119

## Why are these changes needed?
Newly pushed actors will never be used with existing pending submits, so the worker will not be used to speed up existing tasks. If _return_actor is called at the end of push instead, the actor is pushed to _idle_actors and immediately used if there are pending submits.

## Related issue number
Closes #24921

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-05-19 19:03 UTC, siavash119 commented
I'm wondering if the docstring should be updated. Also, does the name _return_actor still make sense if it's now being used to add a new actor?

2022-05-19 21:48 UTC, zhe-thoughts commented
Thanks for the contribution @siavash119 !

2022-05-19 21:54 UTC, mwtian commented
Yeah `_add_actor()` may be more suitable than `_return_actor()` now. Which update do you want to make to the docstring?

2022-05-19 22:34 UTC, wuisawesome requested changes
Thanks for the contribution, do you mind adding the repro in the issue as a unit test for this? 

(/python/ray/tests/test_actor_pool.py)

2022-05-19 22:58 UTC, siavash119 commented
@mwtian 
Maybe now is a good time I mention I implemented another feature `_pending_pops`. It's a counter incremented in `pop_idle` if there are no idle_workers. Then in the currently named `_return_actor`, if there are pending pops, I don't add the actor back to the _idle_worker list and instead terminate it gracefully i.e. remove that actor from the pool. This is so I can reduce the number of actors during currently running jobs without waiting for the entire job to finish. So `_return_actor` will add new actors, submit pending tasks, and remove actors if pending pops.

So _add_actor might make sense for just this current change, but I think I'd immediately change it again. How about `_handle_idle_actor` or `_process_idle_actor` instead? Or should I change it to `_add_actor` for now then leave further changes for later?

I was thinking I should change something about pushing to _idle_actors in the push function docstring, since that's done by `_return_actor` instead, but I guess it's okay as it is now.

@wuisawesome
Sure, I'll add a test.

2022-05-23 02:14 UTC, siavash119 commented
I just kept it as _return_actor and didn't touch the docstring for now. It can be changed later.

@wuisawesome i updated the existing test_push function in /python/ray/tests/test_actor_pool.py to check using new actors for pending submits.

2022-05-23 18:53 UTC, wuisawesome approved these changes
thanks

2022-05-23 18:56 UTC, wuisawesome commented
@siavash119 actually, it looks like lint is still broken, can you fix that? the other tests are flakey i think. 

```


Sun 22 May 2022 07:54:02 PM PDT Flake8....
--
  | Sun 22 May 2022 07:55:22 PM PDT shellcheck scripts....
  | diff --git a/python/ray/tests/test_actor_pool.py b/python/ray/tests/test_actor_pool.py
  | index 23d3fcdae..bc8e044cb 100644
  | --- a/python/ray/tests/test_actor_pool.py
  | +++ b/python/ray/tests/test_actor_pool.py
  | @@ -234,7 +234,7 @@ def test_push(init):
  | assert pool.has_free() is False
  | assert len(pool._pending_submits) == 1
  | pool.push(a3)
  | -    assert pool.has_free() is False # a3 is used for pending submit
  | +    assert pool.has_free() is False  # a3 is used for pending submit
  | assert len(pool._pending_submits) == 0
  |  
  |  
  | Reformatted changed files. Please review and stage the changes.
  | Files updated:
  |  
  | python/ray/tests/test_actor_pool.py


```

2022-05-23 18:57 UTC, mwtian commented
@siavash119 waiting for the next change to rename sounds good.

2022-05-25 02:28 UTC, siavash119 commented
not sure if I should do anything for this PR for the remaining failing tests

2022-06-01 14:50 UTC, wuisawesome commented
Remaining test failures look unrelated. Merging.

2022-06-01 14:51 UTC, merged