Point to latest contributing doc
ray-project/ray pull request #25149
Opened 2022-05-24 11:21 UTC by tupui

## Why are these changes needed?

Pointing to the latest documentation for contributor is important as the workflow is always evolving. E.g. the installation instructions for bazel are not representatives of the current state on release vs master. Hence, I propose to update contribution links in the documentation to point to the latest state on master.

## Related issue number

Closes #11687 (linked and could already be closed)

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

2022-05-24 12:14 UTC, maxpumperla requested changes

2022-05-24 12:14 UTC, maxpumperla commented on doc/source/_toc.yml
> +      - url: https://docs.ray.io/en/master/ray-contribute/getting-involved.html
I don't think we can make these TOC changes.

2022-05-24 12:16 UTC, maxpumperla commented
@tupui thank you! I think your analysis is correct,  and we should definitely work on the underlying issue. The question is how we address it. The concern I have is that your proposed change breaks with a fundamental principle: don't magically redirect users to a different version of the docs without telling them.

I made a quick suggestion that instead adds an additional link with some context. Let me know what you think and if that could work for you? Thanks again for your contribution.

2022-05-24 12:46 UTC, tupui commented
Thank you for the quick review @maxpumperla. I understand your concern indeed. Your suggestion would have worked for me because when I first opened your documentation, I did not see the TOC on the left and when through following the links. I will do this now.

Another possibility is, in addition to your suggestion, to add a note/warning (with the same message you are suggesting now) on the top level pages of the contributing doc (https://docs.ray.io/en/master/ray-contribute/getting-involved.html at least). But that might be too much.

2022-05-24 13:06 UTC, maxpumperla commented
@tupui right, reuse the mechanism that we have, please. We just need to make sure there aren't too many boxes there. Not sure where to put things best.

I don't know, do you think we _should_ have it on all those pages? Maybe first create a proper `_include/` and add it to one page, and we can discuss a follow-up?

No worries, we need to run CI, but it's our job to take care of it. Your first commit broke the linter, but we're likely fine now.

2022-05-30 14:08 UTC, maxpumperla approved these changes
@tupui thank you, looking good!

2022-05-31 08:13 UTC, merged