Clean up docstyle in data, ml, and tune packages
ray-project/ray pull request #25188
Opened 2022-05-25 20:42 UTC by ericl

## Why are these changes needed?

Move these modules to fully following our style guide: https://docs.ray.io/en/latest/ray-contribute/getting-involved.html#code-style

Ideally this would be programmatically enforced (not sure the best way).

2022-05-25 21:10 UTC, bveeramani commented
> Ideally this would be programmatically enforced (not sure the best way).

There's a tool called [pydocstyle](https://github.com/PyCQA/pydocstyle) by PyCQA, although I'm not sure if it can enforce no-type-in-docstring.

2022-05-25 21:30 UTC, ericl commented
I've also come up with a pretty good regex, might try tackling this programatically in other modules when I have some spare time.

2022-05-26 05:01 UTC, ericl commented
Ping for review.

2022-05-26 07:45 UTC, richardliaw approved these changes
lgtm, cc @xwjiang2010 @Yard1

2022-05-26 08:39 UTC, Yard1 approved these changes
lgtm to me too

2022-05-26 09:41 UTC, krfricke requested changes, later dismissed
Thanks, generally LGTM, but we should move the type annotations to the function definition if possible, otherwise we'll lose information.

2022-05-26 09:41 UTC, krfricke commented on python/ray/tune/automl/search_space.py
> +            name: Name of the parameter. Name can be dot separated,
In the cases where we remove the type annotation in the docstring, we should add it to the function definition instead, e.g. `def __init__(self, name: str):`

2022-05-26 14:12 UTC, xwjiang2010 approved these changes

2022-05-26 21:26 UTC, scv119 approved these changes

2022-05-26 21:27 UTC, merged