[air] add to_air_checkpoint method for inference only workload.
ray-project/ray pull request #25444
Opened 2022-06-03 15:05 UTC by xwjiang2010

## Why are these changes needed?

Follow up on our last discussion for supporting piecemeal fashion air users.
Only did for tensorflow for now, want to collect some feedback on API naming etc and I will add others.

## Related issue number

#25224

## Checks

- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-06-03 23:30 UTC, richardliaw requested changes
Add to package ref and mention it in key concepts?

2022-06-06 19:11 UTC, xwjiang2010 commented on python/ray/ml/predictors/integrations/tensorflow/utils.py
> +        preprocessor: Stateless preprocessor only. The preprocessing logic will
Rephrased..

2022-06-06 19:12 UTC, xwjiang2010 commented
> Add to package ref and mention it in key concepts?

Added a session in key concepts

2022-06-06 23:38 UTC, richardliaw commented on doc/source/ray-air/use-pretrained-model.rst
> +========================
```suggestion
Use a pretrained model for batch inference
===============================
```

2022-06-06 23:38 UTC, richardliaw commented on python/ray/air/predictors/integrations/tensorflow/utils.py
> +    Args:
add Returns:

2022-06-06 23:39 UTC, richardliaw commented on doc/source/_toc.yml
> +              - file: ray-air/use-pretrained-model
rebase => move to User Guide

2022-06-07 15:29 UTC, richardliaw approved these changes
Looks good, did not review new models very carefully -- ping when tests pass

2022-06-07 21:48 UTC, amogkam approved these changes

2022-06-07 21:50 UTC, merged