[WIP] [air] Allow users to use instances of `ScalingConfig`
ray-project/ray pull request #25607
Opened 2022-06-09 00:11 UTC by sumanthratna

CC @amogkam @xwjiang2010 @richardliaw 

## Why are these changes needed?

Makes `ScalingConfig` the single way to configure scaling configurations for Tune

## Related issue number

n/a

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-06-10 04:08 UTC, ericl requested changes
Can you ensure we have a test with a tune.grid_search on num_workers and that it is working the same as the {"num_workers": tune.grid_search()}?

2022-06-10 04:09 UTC, ericl commented on python/ray/tune/tests/test_tuner.py
> +            "scaling_config": ScalingConfig(num_workers=tune.grid_search([1, 2])),
Can we document this capability in Tune and in Train docs?

2022-06-10 15:09 UTC, sumanthratna commented
> Can you ensure we have a test with a tune.grid_search on num_workers and that it is working the same as the {"num_workers": tune.grid_search()}?

@ericl Not sure I understand -- don't we already have a unit test to verify that this works? (the same test that you commented on in your PR review)
```python
Tuner(
    param_space={
        "scaling_config": ScalingConfig(num_workers=tune.grid_search())
    }
)
```

2022-06-12 02:52 UTC, closed without merging

2022-06-13 06:13 UTC, sumanthratna commented
superseded by https://github.com/ray-project/ray/pull/25712