[RLlib] CRR documentation
ray-project/ray pull request #25667
Opened 2022-06-10 17:45 UTC by kouroshHakha

## Why are these changes needed?

## Related issue number

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-06-10 18:30 UTC, christy requested changes
Nice work, Kourosh!

Need to also add link refs to crr from:
- Github readme: https://github.com/ray-project/ray/blob/master/rllib/README.rst
- RLlib docs index > Algorithms pull-down: https://docs.ray.io/en/master/rllib/index.html 

New Algo Org:
Offline RL (put Off-policy Eval here): **CRR**, BC, MARWIL, CQL, OPE ("importance sampling" and "weighted importance sampling")
Model-free RL (split into off/on policy):
On-policy: APPO, PPO, IMPALA, A2C, A3C, PG
Off-policy: DQN, DDPG, TD3, SAC
Model-based RL: MBMPO, Dreamer
Derivative-free Algos: ES & ARS
RecSys and Bandits (or separate categories): LinUCB, LinTS, SlateQ
Multi-agent: QMIX, AlphaStar, MA-DDPG

2022-06-10 22:36 UTC, christy approved these changes

2022-06-10 22:42 UTC, avnishn approved these changes

2022-06-14 10:44 UTC, sven1977 commented on doc/source/rllib/rllib-algorithms.rst
> +The later become increasingly important during bootstrapping the bellman equation, where the Q-function queried for next state does not have support in the observed data.
```suggestion
The latter becomes increasingly important during bootstrapping in the bellman equation, where the Q-function queried for the next state's Q-value(s) does not have support in the observed data.
```

2022-06-14 10:44 UTC, sven1977 commented on doc/source/rllib/rllib-algorithms.rst
> +To mitigate these issues, CRR, implements a simple and yet powerful idea of value-filtered regression.
```suggestion
To mitigate these issues, CRR implements a simple and yet powerful idea of "value-filtered regression".
```

2022-06-14 10:45 UTC, sven1977 commented on doc/source/rllib/rllib-algorithms.rst
> +Basically the key idea is to use a learned critic to filter-out the non-promising transitions from the replay dataset. For more details, please refer to the paper.
```suggestion
The key idea is to use a learned critic to filter-out the non-promising transitions from the replay dataset. For more details, please refer to the paper (see link above).
```

2022-06-14 10:45 UTC, sven1977 approved these changes
Great work @kouroshHakha , thanks for the PR.

2022-06-14 10:45 UTC, merged