[KubeRay] Warn explicitly against using kubectl apply to create RayCluster CRD.
ray-project/ray pull request #25685
Opened 2022-06-10 23:02 UTC by DmitriGekhtman

## Why are these changes needed?

This PR adds a warning about a known issue to the KubeRay section of the Ray docs.

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-06-12 07:46 UTC, richardliaw approved these changes

2022-06-13 17:32 UTC, wuisawesome requested changes
Can you use `.. note` or `.. warning` syntax? It doesn't seem to be formatted the same as other notes/warnings

<img width="801" alt="image" src="https://user-images.githubusercontent.com/3980609/173411327-5b453b84-8485-42fb-95e9-f3421f8a90d5.png">

2022-06-27 03:42 UTC, DmitriGekhtman commented
Switched to use boxed admonitions for notes.
Updated the description of feature state of KubeRay integration.
Added some links to the docs hosted in the KubeRay repo.

2022-06-27 21:02 UTC, wuisawesome approved these changes

2022-06-27 21:11 UTC, merged