Windows gpu detection workaround with GPUtil
ray-project/ray pull request #25701
Opened 2022-06-11 12:35 UTC by juliusfrost

## Why are these changes needed?

Because [WMIC is now deprecated](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-deprecated-features), #9300 may stop working on recent Windows systems. As a workaround this PR extends GPUtil to do GPU detection when installed on Windows systems.

## Related issue number

Workaround for #9166

This builds on #18938

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-06-11 15:56 UTC, mehrdadn commented
I'm not responsible for reviewing these - you'll want someone else to review.

2022-06-13 17:30 UTC, wuisawesome requested changes
Thanks for the contribution, can you write a unit test for this and also remove the TODO in the docstring?

2022-07-13 20:13 UTC, wuisawesome commented
@juliusfrost do you have the bandwidth to write finish this off?

2022-07-14 13:50 UTC, mattip commented
> remove the TODO in the docstring 

I reworked the docstrings.

Is the DCO signoff absolutely required? This PR now has commits from two contributors, so I don't think the missing signoffs can be remedied.

2022-07-14 17:40 UTC, wuisawesome commented
> Is the request to add tests for ResourceSpec.resolves on windows specifically or in general to make sure ResourceSpec.resolves still works, in which case current tests should be sufficient.

The test I had in mind was to hopefully test that we try GPUtil first before falling back on other logic. It may need to be reworked with a little [inversion of control ](https://en.wikipedia.org/wiki/Inversion_of_control), but as we try to support more types of machines and the logic becomes more complicated, IMO it's worth doing (I don't think this should be too much work?). 

Note we also have a gpu string parsing test here: https://sourcegraph.com/github.com/ray-project/ray/-/blob/python/ray/tests/test_advanced_8.py?L188

2022-07-18 10:05 UTC, mattip commented
> we try GPUtil first before falling back on other logic

That is what is being tested in the tune [GPUTest](https://github.com/ray-project/ray/blob/8f74e1f3ae8bf1d6f9126492004ca75c1d699073/python/ray/tune/tests/test_trainable_util.py#L224) tests, since it expects the results from the `GPUUtilMock`, no?

2022-07-18 10:09 UTC, mattip commented
@juliusfrost something seems off here. I want to rebase off master and then force-push to your repo since the PR started there. Is that OK?

2022-07-18 12:17 UTC, juliusfrost commented
> @juliusfrost something seems off here. I want to rebase off master and then force-push to your repo since the PR started there. Is that OK?

Sounds good

2022-07-19 04:16 UTC, mattip commented
CI is happy now, only the DCO problem remains.

2022-07-19 16:31 UTC, pcmoritz approved these changes

2022-07-19 22:11 UTC, wuisawesome approved these changes
@juliusfrost Can you add the DCO? (You can do it by clicking the "failing test" button for it)

2022-07-20 00:04 UTC, merged

2022-07-20 00:23 UTC, juliusfrost commented
I added the DCO. Thanks for finishing this up!

2022-07-20 00:32 UTC, pcmoritz commented
Thanks for your contribution :)