[docs] Update docs for building from source
ray-project/ray pull request #26045
Opened 2022-06-23 17:11 UTC by wuisawesome

## Why are these changes needed?

The existing docs didn't work for me and these updates did. 🤷‍♀️ 

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-06-23 21:04 UTC, scv119 commented on doc/source/ray-contribute/development.rst
> +  sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 \
on ubuntu 18.04, you need add 
```
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
```
 before `sudo apt-get update`.

2022-06-23 21:08 UTC, scv119 requested changes
need support 18.04

2022-06-28 21:40 UTC, scv119 commented
friendly ping!

2022-06-28 21:59 UTC, wuisawesome commented
I've pushed your comment but haven't had time to spin up 18.04 vm for manual testing (i'm using 22.04 these days)

2022-07-06 19:11 UTC, scv119 approved these changes

2022-07-06 19:11 UTC, scv119 commented
Thanks for the fix!

2022-07-06 19:12 UTC, richardliaw approved these changes
stamp

2022-07-06 19:17 UTC, merged