[C++ API] Hide other symbols in libray_api.so only keep ray*
ray-project/ray pull request #26069
Opened 2022-06-24 07:23 UTC by larrylian

## Why are these changes needed?

Users may rely on other libraries such as boost/bssl, and then the symbols of these libraries are exposed in libray_api.so, which will eventually lead to double symbols, which will lead to some problems.
So hide other symbols in libray_api.so only keep ray-related symbols.

## Related issue number
#25304 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-06-24 08:04 UTC, SongGuyang commented
Can we rename the two files to `ray_api_exported_symbols_mac.lds` and `ray_api_exported_symbols_linux.lds`, and move it to a separate directory `cpp/symbols`?

2022-06-24 08:10 UTC, SongGuyang requested changes
Is it easy to add a test for it?

2022-06-24 08:10 UTC, SongGuyang commented on cpp/BUILD.bazel
> +        "@bazel_tools//src/conditions:windows": [
Add a TODO here for windows.

2022-06-24 08:10 UTC, SongGuyang commented on cpp/ray_api_version_script.lds
> +        *[0-9]ray[0-9]*;
Do we need to hit `ray::core::` and `ray::internal`?
`

2022-06-24 08:36 UTC, WangTaoTheTonic commented
I think it satisfies basic requirement for avoiding conflicts between third party symbols imported by users and us.
If we wanna export minimum symbols set, there's a lot more accurate work to do.

2022-06-29 09:45 UTC, WangTaoTheTonic approved these changes
LGTM

2022-06-30 02:16 UTC, SongGuyang commented on cpp/BUILD.bazel
> +            #TODO
```suggestion
            #TODO(larry): Hide the symbols when we make it work on Windows.
```

2022-06-30 02:19 UTC, larrylian commented
> Is it easy to add a test for it?

Now simple_kv_store and cluster_mode_test is test。

2022-06-30 03:39 UTC, SongGuyang approved these changes
LGTM.

2022-07-01 03:51 UTC, raulchen approved these changes

2022-07-01 03:51 UTC, merged

2022-07-06 16:42 UTC, simon-mo commented
HI @larrylian  @raulchen @SongGuyang @WangTaoTheTonic 
This PR broke compilation on m1 macOS, which block future releases because we need to release m1 wheels. See https://github.com/ray-project/ray/issues/26324

Can you please try to fix it? In the meantime we will revert this PR so developers can build ray locally.