[air] Do not warn of `checkpoint_dir` if it's coming from us (base_trainer).
ray-project/ray pull request #26259
Opened 2022-07-01 18:21 UTC by xwjiang2010

## Why are these changes needed?
This will be removed once internally we migrate to use `session` API.

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-07-02 01:49 UTC, Yard1 approved these changes

2022-07-02 13:51 UTC, krfricke requested changes
This is a bit hacky. Can we just add a flag to `wrap_function` to not warn or alternatively just trigger `log_once("tune_checkpoint_dir_deprecation")` in our trainers?

2022-07-02 15:06 UTC, xwjiang2010 commented
> This is a bit hacky. Can we just add a flag to `wrap_function` to not warn or alternatively just trigger `log_once("tune_checkpoint_dir_deprecation")` in our trainers?

Good point! Updated to `warn=False` in `base_trainer`

2022-07-04 00:28 UTC, krfricke approved these changes

2022-07-04 00:29 UTC, merged