[RLlib] WorkerSet dataset loading minor fix
ray-project/ray pull request #26369
Opened 2022-07-07 21:46 UTC by charlesjsun

## Why are these changes needed?

The ShuffledInput for module input didn't have a window size parameter passed in.

## Related issue number

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-07-07 21:49 UTC, avnishn approved these changes

2022-07-18 22:39 UTC, richardliaw requested changes
how did you find the bug? Can we have a test?

2022-07-19 00:31 UTC, charlesjsun commented
I found the bug when I was reading worker_set to understand how it works. I added a test as well (and found another bug while doing it)

2022-07-19 00:45 UTC, avnishn approved these changes
This looks good to me. The test is the minimal to ensure that the integration works, which is what this pr fixes.

2022-09-24 02:47 UTC, closed without merging