[RLlib]: Fix FQE Policy
ray-project/ray pull request #26671
Opened 2022-07-18 19:11 UTC by Rohan138

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-07-18 22:08 UTC, kouroshHakha approved these changes
LGTM.

2022-07-18 22:43 UTC, richardliaw requested changes
what's the reason for not having a unit test here?

2022-07-19 00:03 UTC, kouroshHakha commented on rllib/offline/estimators/tests/test_ope.py
> +        # Miscellaneous tests for FQETorchModel
write a docstring on what this function is testing?

2022-07-19 00:03 UTC, kouroshHakha approved these changes
Tests are added. Reviewed again and approved @richardliaw

2022-07-19 07:58 UTC, richardliaw approved these changes

2022-07-19 07:58 UTC, merged