Raise error when histogram boundaries <= 0
ray-project/ray pull request #26728
Opened 2022-07-19 18:22 UTC by danielwen002

## Why are these changes needed?

Raises error when histogram has boundaries that includes 0.

Closes #26698 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-07-19 20:10 UTC, ckw017 commented on python/ray/util/metrics.py
> +        for bound in self.boundaries:
Can you move this up to before `self.boundaries = boundaries`

2022-07-19 20:35 UTC, ckw017 commented
^bad merge, accidentally pulled in codeowners

2022-07-19 20:53 UTC, ckw017 approved these changes

2022-07-21 01:45 UTC, rkooo567 requested changes

2022-07-21 01:45 UTC, rkooo567 commented on python/ray/util/metrics.py
> +                raise ValueError("boundaries arguments should be positive values")
Can you update the error message? Following this guideline; https://spark.apache.org/error-message-guidelines.html

```
for i, boundary in enumerate(boundaries):
    if boundary <= 0:
        raise ValueError(`Invalid `boundaries` argument at index {i}, {boundaries}. Use positive values for the arguments.)
```

2022-07-21 22:32 UTC, rkooo567 approved these changes

2022-07-21 22:33 UTC, merged