Use compress observations where replay buffers and image obs are used  in tuned examples
ray-project/ray pull request #26735
Opened 2022-07-19 20:07 UTC by avnishn

Many of our tuned examples using replay and atari wouldn't be able to run on clusters or single node machines because they'll oom without enabling this compression. 

Signed-off-by: avnish <avnish@anyscale.com>

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-07-19 21:49 UTC, gjoliver requested changes
nit nit nit
can we write the comments more formally, like:
```Compress observations to make sure the size of the ReplayBuffer fits most computers. ```
something like that? not really good at wording, but you get the idea.
thanks.

2022-07-19 22:44 UTC, avnishn commented
could I change 
"we should set this because few machines would be able to contain the replay buffers in memory otherwise" to 

"we should **set compress_observations to True** because few machines would be able to contain the replay buffers in memory otherwise"

is that descriptive enough?

2022-07-22 02:55 UTC, avnishn commented
I addressed the comments, but during today's experiments realized that only pong examples need obs compression so I turned off the compression in the non pong examples that I changed before.

2022-07-22 02:55 UTC, avnishn commented on rllib/tuned_examples/apex_dqn/atari-apex-dqn.yaml
> +        min_sample_timesteps_per_iteration: 25000
just needed a newline

2022-07-22 03:24 UTC, gjoliver approved these changes
this is good trick.

2022-07-22 03:24 UTC, gjoliver commented
@richardliaw please merge

2022-07-22 17:10 UTC, merged