[aws] Added more cluster configurations including GPUs, cleaned up CloudWatch, added more AWS tips and integrations
ray-project/ray pull request #26990
Opened 2022-07-25 23:56 UTC by cfregly

## Why are these changes needed?

Added more cluster configurations including GPUs, cleaned up CloudWatch, added more AWS tips and integrations

## Related issue number

## Checks

- [X ] I've run `scripts/format.sh` to lint the changes in this PR.
- [X] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [X] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
   - [X] Release tests
   - [X] This PR is not tested :(

2022-07-25 23:57 UTC, cfregly commented
@pdames Please review.

2022-07-26 01:00 UTC, wuisawesome requested changes

2022-07-26 01:00 UTC, wuisawesome commented on doc/source/cluster/cloud.rst
> +        Refer to the `ray/python/ray/autoscaler/aws/example-gpu-docker.yaml <https://github.com/ray-project/ray/tree/master/python/ray/autoscaler/aws/example-gpu-docker.yaml>`__ cluster config file t
```suggestion
```

Seems a bit weird that we're providing a docker specific example here, redirecting them to the aws cluster page should be enough.

2022-07-26 01:00 UTC, wuisawesome commented on doc/source/cluster/aws-tips.rst
> +
Can you include the cluster name and provider fields so this becomes a fully copy/pastable example? (it should only add 3 lines to the config)

2022-07-26 01:00 UTC, wuisawesome commented on doc/source/cluster/aws-tips.rst
> +
Same here, fully copy/pastable pls

2022-07-26 01:00 UTC, wuisawesome commented on doc/source/cluster/aws-tips.rst
> +To use Amazon EFS, install some utilities and mount the EFS in ``setup_commands``. Note that these instructions only work if you are using the AWS Autoscaler.
Is there some EFS documentation we can link to here about what utilities we're installing and why? maybe this page? https://docs.aws.amazon.com/efs/latest/ug/installing-amazon-efs-utils.html#installing-other-distro

2022-07-26 01:00 UTC, wuisawesome commented on doc/source/cluster/aws-tips.rst
> +Amazon EMR
Can you remove this and the following sagemaker section? These are different deployment models. 

It's not enough for these examples to just work at a given point in time. Adding them to the docs creates an implication of supporting those deployment models, which is a rather large decision.

AWS can provide its own support for running Ray on EMR, but Ray's would only be providing first-class support via the manual cluster setup steps (e.g. the public `ray start`/`ray stop` apis). 

If you feel strongly about trying to get first class support for EMR, I think the right next steps would be to open up a [REP (ray enhancement proposal) ](https://github.com/ray-project/enhancements)

2022-07-26 01:02 UTC, wuisawesome requested changes
Thanks for the contribution @cfregly!

Left a couple of comments that fall under 3 categories.
1. The EMR and SageMaker sections are different deployment models with large implications and we need to go through a more thorough process for those.
2. In general, users should ideally be able to copy/paste the examples and they should be fully working.
3. A few other minor formatting comments.

2022-10-01 18:40 UTC, closed without merging