[Core][fix] Increasing timeout on non-windows for waiting workers in test_metrics
ray-project/ray pull request #27379
Opened 2022-08-02 19:05 UTC by rickyyx

## Why are these changes needed?
The test was timing out.
<img width="971" alt="image" src="https://user-images.githubusercontent.com/11676094/182452306-cf3b12d6-64a6-4a8a-ba61-752d57893127.png">

 A normal pass was ~17secs. 
<img width="781" alt="image" src="https://user-images.githubusercontent.com/11676094/182452647-2a929739-3326-4501-8c38-2a3e4c2e2ce9.png">

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-08-02 20:00 UTC, scv119 approved these changes

2022-08-02 20:23 UTC, stephanie-wang approved these changes

2022-08-02 21:43 UTC, scv119 commented
looks  it's still failing...
```


//python/ray/tests:test_metrics                                          FAILED in 3 out of 3 in 46.9s
--
  | Stats over 3 runs: max = 46.9s, min = 46.6s, avg = 46.7s, dev = 0.1s
  | /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/testlogs/python/ray/tests/test_metrics/test.log
  | /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/testlogs/python/ray/tests/test_metrics/test_attempts/attempt_1.log
  | /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/testlogs/python/ray/tests/test_metrics/test_attempts/attempt_2.log



//python/ray/tests:test_metrics                                          FAILED in 3 out of 3 in 46.9s
--
  | Stats over 3 runs: max = 46.9s, min = 46.6s, avg = 46.7s, dev = 0.1s
  | /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/testlogs/python/ray/tests/test_metrics/test.log
  | /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/testlogs/python/ray/tests/test_metrics/test_attempts/attempt_1.log
  | /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/testlogs/python/ray/tests/test_metrics/test_attempts/attempt_2.log


```

2022-08-03 16:17 UTC, rkooo567 requested changes

2022-08-03 16:17 UTC, rkooo567 commented on python/ray/tests/test_worker_capping.py
> +    def verify():
Can you revert this? I will take it over

2022-08-03 22:21 UTC, rkooo567 approved these changes

2022-08-03 22:22 UTC, merged