[air/docs] fix trainer documentation
ray-project/ray pull request #27481
Opened 2022-08-04 01:14 UTC by richardliaw

## Why are these changes needed?
This is stacked on https://github.com/ray-project/ray/pull/27389/files.

This PR adds the following sections:

* a new landing page
* key concepts
* getting started

to the Train section, bringing it in line with the rest of the Ray ecosystem libraries.

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-08-04 23:28 UTC, ericl requested changes
I made an editing pass over the intro, key concepts, and guides. I think it's OK.

The main thing that seems off right now is the "API Reference" section-- is it just redundant with the AIR API reference? Maybe we should just clarify that and just have two sections:
- Link to AIR API reference
- Deprecated APIs

2022-08-04 23:59 UTC, dmatrix commented on doc/source/train/dl_guide.rst
How do I ...  to use Ray Train?

2022-08-05 08:38 UTC, richardliaw commented
@ericl I deduped and addressed comments. Though to me it still feels more natural to just move all the trainer stuff into Ray Train instead of leaving it hanging in Ray AIR package ref.

2022-08-05 17:12 UTC, ericl approved these changes

2022-08-05 18:08 UTC, xwjiang2010 approved these changes

2022-08-05 18:21 UTC, merged