[Java] Fix methods' signatures for JNI.
ray-project/ray pull request #2756
Opened 2018-08-28 10:04 UTC by jovan-wong

## What do these changes do?
1. I fixed native methods' signatures in this small PR.
2. Fixed some native JNI methods' naming.

## Related issue number
N/A

2018-08-28 11:17 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/7822/
Test FAILed.

2018-08-28 14:22 UTC, raulchen reviewed
Thanks, looks good to me.

Most of the function parameters in `org_ray_spi_impl_DefaultLocalSchedulerClient.cc` don't have meaningful names. Could you also improve that with this PR? thanks.

2018-08-28 20:16 UTC, robertnishihara approved these changes
Looks good to me, though we should still get rid of the autogenerated files at some point.

2018-08-29 07:55 UTC, jovan-wong commented
I have updated some code.

In conclusion, it contains 3 changes:
1) Renamed the native JNI methods and some parameters of JNI methods. 
2) Fixed native JNI methods' signatures by `javah` tool.
3) Removed some useless native methods.

@robertnishihara  @raulchen  Could u plz review this again?

2018-08-29 08:44 UTC, jovan-wong commented
@eric-jj cc

2018-08-29 08:57 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/7852/
Test PASSed.

2018-08-29 10:18 UTC, raulchen requested changes
There's lint error in `org_ray_spi_impl_DefaultLocalSchedulerClient.cc`. Otherwise looks good.

2018-08-29 12:41 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/7856/
Test FAILed.

2018-08-29 12:54 UTC, raulchen approved these changes

2018-08-29 14:03 UTC, jovan-wong commented
I didn't change any py file, and just changed `org_ray_spi_impl_DefaultLocalSchedulerClient.h` and `org_ray_spi_impl_DefaultLocalSchedulerClient.cc` which are used for Java. 
But in many times, the CI job `#1` and `#2` can't pass.

```shell
=============== 1 failed, 47 passed, 8 skipped in 218.85 seconds ===============
The command "python -m pytest -v test/actor_test.py" exited with 1.
```
@robertnishihara  Do u guys have any idea about it?

2018-08-29 20:47 UTC, robertnishihara commented on src/local_scheduler/lib/java/org_ray_spi_impl_DefaultLocalSchedulerClient.cc
> +        (jbyteArray) env->GetObjectArrayElement(objectIds, i);
We should not use C style casts here

2018-08-29 20:47 UTC, robertnishihara commented on src/local_scheduler/lib/java/org_ray_spi_impl_DefaultLocalSchedulerClient.cc
> +        (jbyteArray) env->GetObjectArrayElement(objectIds, i);
C style cast

2018-08-29 20:48 UTC, robertnishihara commented
@jovan-wong I think those test failures are unrelated. Can you remove the C-style casts? Then I think we can merge it.

2018-08-30 05:34 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/7883/
Test PASSed.

2018-08-30 09:59 UTC, merged