[ray misc] adding the placement by id
ray-project/ray pull request #27861
Opened 2022-08-15 06:44 UTC by JiahaoYao

It would be also good to get the placement by id because the users usually use the `ray.state` to get all the placement info, and usually the name is not set but there is always id. 

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-08-15 06:45 UTC, JiahaoYao commented
maybe i should check the `placement_id` is valid? @rkooo567

2022-08-15 06:54 UTC, JiahaoYao commented
not sure whether this works?

2022-09-01 02:12 UTC, rkooo567 requested changes

2022-09-01 02:12 UTC, rkooo567 commented on python/ray/util/placement_group.py
> +        if placement_group_id:
I think we want to run 

```
    worker = ray._private.worker.global_worker
    worker.check_connected()
```
for the id case as well? Can you add if/else based on a given input in line 269? 

Also we need to add an unit test

2022-10-15 17:59 UTC, closed without merging