[cli] Add flags to start gcs only or dashboard only.
ray-project/ray pull request #28322
Opened 2022-09-07 05:38 UTC by iycheng

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-09-07 07:52 UTC, iycheng commented on python/ray/tests/test_ray_deploy.py
> +def test_ray_deploy_e2e(docker_cluster, tmp_path):
@allenyin55  @yiranwang52  please check this script to see what and how.

2022-09-07 16:24 UTC, yiranwang52 approved these changes

2022-09-07 17:07 UTC, allenyin55 approved these changes

2022-09-07 17:49 UTC, scv119 commented
currently we have following options for `ray start`
1. `ray start` start worker node, including raylet and agent
2. `ray start --head` start header node, including gcs, raylet, agent and dashboard
3. `ray start --head --include-dashboard` start api server on **head node only**; this has to be 

in this case, does it make sense make following changes?

1. `ray start --gcs-only` only start gcs.
2. `ray start --include-dashboard` now allows to be call on worker node as well

2022-09-07 17:52 UTC, iycheng commented
It seems the client setup got messed up. I'm looking.

2022-09-07 18:12 UTC, jjyao commented
I'm most curious how this should work with existing flags, especially with `--head`:
* Should `--gcs` always come with `--head` indicating that it starts on the head node?
* Should `--api-server` always come with `--head`?
* Should `--raylet` always come with `--head`, is it sensible to use this option to start raylet on the worker node?
* What about other processes like agent, log monitor, are they started with `--raylet`?

2022-09-07 18:17 UTC, iycheng commented
@scv119 
> ray start --include-dashboard now allows to be call on worker node as well

include-dashboard means the UI, not means the api server. I think we start the api server anyway. So what's why I use `--api-server`.

2022-09-07 18:19 UTC, iycheng commented
@jjyao it's not allowed. `--head` starts several things. `--gcs/--raylet/...` starts the component by themselves. No need to allow the combination.

2022-09-07 18:22 UTC, iycheng commented
@jjyao  log-monitor should always come with raylet, otherwise, log streaming will fail. (we always start log-monitor with raylet right now, no change in the behavior).

2022-09-07 18:24 UTC, iycheng commented
@jjyao in summary, nothing changed with existing flags their semantics are the same as before.

2022-09-07 18:30 UTC, jjyao commented
What's the difference between using `ray start` vs `ray start --raylet` to start a worker node?

2022-09-07 18:42 UTC, iycheng commented
@jjyao  no difference.

2022-09-07 18:52 UTC, ericl requested changes
I don't think this is an API we should expose to developers. Ray internals should not be something infra engineers should be aware of. For this change to proceed, I'd have to see proof that there is no other way to achieve the goals besides this.

As I understand, the goal is prioritization of the GCS process over other internal Ray processes. There are other ways of achieving this that don't require exposing a public API.

2022-09-07 23:36 UTC, rkooo567 commented
Btw, I want to make sure "log_monitor" and "dashboard_agent" is deployed together when they are started standalone. Without that we will lose error logs from GCS and all metrics emitted to dashboard + gcs

2022-09-08 01:20 UTC, SongGuyang commented
In Ant, our requirement is no raylet in head node.  The worker processes which is brought by raylet will affect the stability of GCS and dashboard, e.g. cpu, memory, disk, network and so on.

2022-09-08 01:23 UTC, ericl commented
@SongGuyang , the goal makes sense. How about adding a --disable-scheduling flag for the head node? The implementation detail can either be not starting raylet or starting it with scheduling disabled.

2022-09-08 01:28 UTC, SongGuyang commented
So, can we support a way as follows:
- start a head node in which doesn't contain raylet by default: `ray start --head`
- start a worker node: `ray start`
- start a standalone cluster which contains all the core processes(raylet, gcs, dashboard, agent...): `ray start --standalone`

2022-09-08 01:30 UTC, SongGuyang commented
> --disable-scheduling

This flag seems also good for us.

2022-09-08 01:32 UTC, ericl commented
The reason to have a new flag is backwards compatibility... we'd break all existing ray deployments otherwise.

2022-09-08 01:34 UTC, SongGuyang commented
I see. Keeping backwards compatibility makes sense.

2022-10-03 18:53 UTC, closed without merging