Dataset pytest modularization 6
ray-project/ray pull request #28638
Opened 2022-09-20 13:30 UTC by PaulFenton

## Why are these changes needed?

Solves the "good first issue" task suggested by @bveeramani: https://github.com/ray-project/ray/issues/28398#issuecomment-1251762583

**Note:** This PR is primarily just moving tests into more specific files without changing them. The only exception is a workaround that was added to fix an issue with the test `test_image_folder_reader_estimate_data_size` by adding `shutdown_only` fixture to the previously run test (`test_image_folder_datasource_e2e`)

## Related issue number
Closes #28398 

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-09-20 14:34 UTC, bveeramani reviewed
Thanks for opening this PR! I skimmed it and it looks reasonable to me. 

Would it make sense to move the binary and text tests to separates modules?

Will perform a more thorough review later this week.

2022-09-23 18:15 UTC, PaulFenton commented
@bveeramani I believe I have just resolved the "binary and text tests to separate modules" suggestion with the most recent commits.

2022-09-26 22:01 UTC, bveeramani requested changes
Sorry for the delayed review, and thanks again! This'll be helpful.

LGTM except couple minor things:
* I think `test_read_text_remote_args` might be in the wrong module.
* Could you merge master in and make sure `test_read_tfrecords` is here?

2022-09-26 22:01 UTC, bveeramani commented on python/ray/data/tests/test_dataset_formats.py
> -import shutil
There's a recently-added `test_read_tfrecords`. Could you merge master in and check that it's here? Want to make sure no tests go missing.

2022-09-26 22:18 UTC, bveeramani commented
@clarkzinzow @c21 could you take a look and let me know if this is okay with you? I checked and all of the tests on master are there except for `test_read_tfrecords`.

2022-09-27 13:58 UTC, clarkzinzow approved these changes
Thank you for doing this @PaulFenton, this has been a long-standing TODO that will greatly improve the Datasets developer experience!

2022-09-27 17:47 UTC, c21 approved these changes
Thanks for the work!

2022-09-28 21:15 UTC, bveeramani approved these changes
Sweet! LGTM 🚀

2022-09-29 17:14 UTC, merged

2022-09-29 17:14 UTC, clarkzinzow commented
Thanks again @PaulFenton for the contribution! 🎉