refactor: cost-saving with AMD instances
ray-project/ray pull request #28793
Opened 2022-09-26 23:13 UTC by csivanich

## Why are these changes needed?

Improves cost of test execution by switching from Intel to AMD backed instances.

Saves ~10% on all `m5.*` instance types with similar baseline performance and full binary compatibility.

## Related issue number

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [x] Release tests
   - [ ] This PR is not tested :(

2022-09-27 00:59 UTC, DmitriGekhtman commented
Looks like this modifies the example configurations in `python/ray/autoscaler/aws` too. These aren't used for tests, but I imagine users who are trying out Ray for the first time wouldn't mind the cost improvement.

Does anyone else mind this change in the example files?

2022-09-27 08:14 UTC, krfricke requested changes
The main thing I'm concerned about is instance availability and quota. If @thomasdesr can confirm we have enough quota for m5a.xlarge/2xlarge instances I'm happy to go ahead.

We need to run a suite of release tests on these instances to make sure they are still pasisng. I can kick these off once the quota is confirmed.

For the buildkite `pipeline.ml.yml` tests, they currently hang as our aws cloudformation stack does not have these instances defined. We are currently looking into changing the queues anyway, until then I'd suggest we revert that specific change.

2022-09-27 20:54 UTC, thomasdesr commented
You should have access to go check the quotas in the test account, but in this case I believe they share the same quota family! So we should be good to go here.

2022-09-28 22:26 UTC, csivanich commented
@DmitriGekhtman I'm actually curious about your thoughts on changing examples/demos in the codebase. I tried to leave _most_ of the docs/examples untouched since the behavior/perf should be roughly the same. I can certainly take another pass and update them too.

2022-09-28 22:29 UTC, csivanich commented
@krfricke 

> For the buildkite pipeline.ml.yml tests, they currently hang as our aws cloudformation stack does not have these instances defined. We are currently looking into changing the queues anyway, until then I'd suggest we revert that specific change.

For my knowledge can you point me to where the CF stack is defined? I can pull that file out of the changes in the meantime.

2022-09-28 22:48 UTC, DmitriGekhtman commented
> @DmitriGekhtman I'm actually curious about your thoughts on changing examples/demos in the codebase. I tried to leave _most_ of the docs/examples untouched since the behavior/perf should be roughly the same. I can certainly take another pass and update them too.

I'm leaning conservative -- it's preferable if the examples are untouched, since at the moment we don't have any tests for them. 
...These examples have a tendency to break spontaneously even without us changing the configs.

2022-09-29 10:32 UTC, krfricke commented
@csivanich it's here: https://github.com/ray-project/buildkite-ci-stack/blob/master/ci-stack-module/main.tf#L59

Let's keep the changes just for the release tests then, kick them off, and see if everything passes.

2022-09-30 19:09 UTC, wuisawesome requested changes
May not want to change the microbenchmarks. Not sure if the other ones should be changed or not.

2022-09-30 19:09 UTC, wuisawesome commented on release/microbenchmark/tpl_64.yaml
> +    instance_type: m5a.16xlarge
Probably don't want to change this (consistent benchmarks are pretty useful)

2022-11-19 18:59 UTC, closed without merging