[wip][ci/air] Update ML/DL dependencies to latest releases
ray-project/ray pull request #28808
Opened 2022-09-27 10:16 UTC by krfricke

## Why are these changes needed?

This PR upgrades torch and tensorflow to the latest releases.

Additionally, this PR adds a new CI job that installs the previous CI versions and runs a number of tests on them. This is to make sure that we remain compatible with a specified lower bound version of the dependencies. We can update these lower bounds as we see fit.

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-10-11 16:26 UTC, krfricke commented
Tests are passing except for some in RLlib - I will work with the rllib team to resolve this.

But the rest is ready for review

cc @pcmoritz @richardliaw  for general testing infrastructure
cc @gjoliver @sven1977 for rllib compatibility
cc @amogkam for air compatibility and dependencies

The base CI GPU image has been updated to support CUDA 11.6 already.

2022-10-11 17:45 UTC, amogkam requested changes

2022-10-11 17:45 UTC, amogkam commented on docker/ray-ml/Dockerfile
> +    && $HOME/anaconda3/bin/pip --no-cache-dir install --use-deprecated=legacy-resolver -U \
can we not use the legacy resolver? what are the conflicts we are getting if we remove this?

2022-10-18 17:21 UTC, sven1977 commented on python/requirements/ml/requirements_tune.txt
> -gym>=0.21.0,<0.24.0; python_version >= '3.7'
Oh, got it. Already in RLlib.

2022-10-18 17:22 UTC, sven1977 approved these changes
LGTM.

2022-10-19 14:16 UTC, krfricke commented
Deferring this until https://github.com/ray-project/ray/pull/29375 is merged

2022-10-19 22:45 UTC, ddelange commented
I guess this PR could incorporate, supercede and close #26072?

2022-10-20 03:33 UTC, ddelange commented
totally fine by me :)

2022-10-21 22:00 UTC, amogkam approved these changes
Thanks @krfricke, lgtm!

2022-10-26 18:19 UTC, richardliaw approved these changes

2022-10-27 20:51 UTC, ArturNiederfahrenhorst commented on rllib/algorithms/a3c/tests/test_a3c.py
> +        for _ in framework_iterator(config, with_eager_tracing=False):
@gjoliver @kouroshHakha Not sure why this test did not fail initially, but A3C seems error with eager tracing as well, right @krfricke ?

2022-10-27 22:39 UTC, merged