[docs/core] Batch training on Core example (SSML)
ray-project/ray pull request #28863
Opened 2022-09-28 18:59 UTC by Yard1

Signed-off-by: Antoni Baum <antoni.baum@protonmail.com>

## Why are these changes needed?

This PR adds a notebook showcasing how to conduct batch training & tuning on Ray Core. This is a common SSML use case we see with users. While this is possible using higher-level APIs, a self contained example like this is helpful for:
* Use cases not covered by our higher level APIs
* Use cases requiring higher performance than what we currently provide with higher-level APIs
* Showcasing the correct usage patterns of Ray Core primitives

A notebook solving the exact same problem but with Ray Data & AIR will be added in a followup and linked from this notebook later.

One callout - the notebook uses an [external S3 bucket](https://ursalabs.org/arrow-r-nightly/articles/dataset.html). While we have a copy of the NYC taxi dataset in our bucket, it's partitioned differently and doesn't posses the necessary columns. I am happy to upload a copy to our bucket if considered necessary, please let me know!

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-09-28 19:46 UTC, Yard1 commented
Currently failing in CI due to an S3 authentication error, working on it

2022-09-28 20:26 UTC, jjyao commented on doc/source/ray-core/tips-for-first-time.rst
> +.. _tip-avoid-same-object-in-remote:
This has been converted to an anti-pattern (https://docs.ray.io/en/master/ray-core/patterns/pass-large-arg-by-value.html), could you reference that instead.

2022-09-29 17:47 UTC, Yard1 commented
CI now passes.

2022-09-30 01:03 UTC, richardliaw requested changes
A couple things:

1. Can we add some diagrams in the beginning to show exactly what is the workload that you're about to demonstrate? Batch training isn't a very common term (afaik some people use "partitioned training" too)
2. Why use pyarrow instead of pandas? the pyarrow API is not as commonly used
3. for run(), can you bring out the dataset construction so it looks like:

```
dataset = ...
models = []
generator = task_generator(dataset, models)
run(generator)
```

otherwise it's just not apparent where the dataset is constructed.

4. instead of the long output, do you think you could just show a tqdm output?

2022-10-03 12:50 UTC, Yard1 commented
@richardliaw Applied feedback

Re. 2 - pyarrow has push-down predicates which allows us to load only the rows necessary into memory. Clarified that in the notebook
Re. 4 - we can't use tqdm as we do not know ahead of time how many tasks will be ran. I made the output shorter instead.

2022-10-03 15:58 UTC, richardliaw approved these changes

2022-10-03 21:14 UTC, merged