[core] actors are not retried when OOM killed. Switch to system exit
ray-project/ray pull request #28943
Opened 2022-09-30 22:51 UTC by clarng

Signed-off-by: Clarence Ng <clarence.wyng@gmail.com>

## Why are these changes needed?

Right now actors that are restartable don't restart when OOM killed. GCS does not retry actor if the failure reason is INTENDED_USER_EXIT or USER_ERROR.

This PR changes the OOM killer exit to be system error so that GCS can retry the actor.

## Related issue number

https://github.com/ray-project/ray/issues/28920

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-10-03 02:29 UTC, scv119 commented on src/ray/raylet/node_manager.cc
> +                        rpc::WorkerExitType::INTENDED_SYSTEM_EXIT,
should `SYSTEM_ERROR` be better here?

2022-10-03 10:41 UTC, clarng commented
looks like redis / tune tests are failing, but not related to this PR

2022-10-03 16:03 UTC, stephanie-wang commented
Do we need to add the OOM-specific retry/error reporting logic for actor restart, like what #28714 did for tasks? Or do you plan to do this in a follow-up PR?

2022-10-03 17:21 UTC, clarng commented
> Do we need to add the OOM-specific retry/error reporting logic for actor restart, like what #28714 did for tasks? Or do you plan to do this in a follow-up PR?

This PR blocks release test as it affects workload stability.

We have a separate issue tracked for actor error conversion https://github.com/ray-project/ray/issues/28937 
It doesn't affect retry logic its just cosmetic

2022-10-04 14:11 UTC, rkooo567 requested changes
Lmk when you address the comment! I will merge the PR..

2022-10-04 14:11 UTC, rkooo567 commented on release/ray_release/cluster_manager/cluster_manager.py
> +        self.cluster_env["env_vars"]["RAY_task_oom_retries"] = "15"
Can we avoid this? It's ideal we are using the default configuration if possible (I prefer not to have retries 15 only for nightly tests)

2022-10-05 00:53 UTC, rkooo567 approved these changes

2022-10-05 01:07 UTC, merged