[core] telemetry for when memory monitor is enabled
ray-project/ray pull request #29152
Opened 2022-10-07 04:14 UTC by clarng

Signed-off-by: Clarence Ng <clarence.wyng@gmail.com>

## Why are these changes needed?

Add telemetry to record at worker init time whether the ray cluster is using memory monitor

## Related issue number

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

Manual test per https://docs.google.com/document/d/1XSWzx9ZatnlttsurCXzvV4vVsb2g1KxJ2T4zpf33bI8/edit
`
{"usage_stats": {"ray_version": "3.0.0.dev0", "python_version": "3.7.7", "schema_version": "0.1", "source": "OSS", "session_id": "330fafc5-718b-48c5-92d0-dbe8dbc784a5", "git_commit": "{{RAY_COMMIT_SHA}}", "os": "linux", "collect_timestamp_ms": 1665116028212, "session_start_timestamp_ms": 1665115658078, "cloud_provider": null, "min_workers": null, "max_workers": null, "head_node_instance_type": null, "worker_node_instance_types": null, "total_num_cpus": 12, "total_num_gpus": null, "total_memory_gb": 10.672229005023837, "total_object_store_memory_gb": 5.336114501580596, "library_usages": ["dataset", "train", "tune"], "total_success": 302, "total_failed": 0, "seq_number": 302, "extra_usage_tags": {"gcs_storage": "memory", "memory_monitor_enabled": "false"}, "total_num_nodes": 1, "total_num_running_jobs": 1}, "success": true, "error": null}
`

2022-10-07 04:38 UTC, scv119 approved these changes

2022-10-07 04:40 UTC, scv119 commented
need fix CI though

2022-10-07 15:18 UTC, rkooo567 requested changes
Can we update this from usage_lib.py? I think we can do this way;

1. Generate a method that gets all internal config from `GetInternalConfigRequest`. 
2. When the dashboard first starts, we get internal config and update only relevant fields only once (in this case memory monitor config)

2022-10-07 17:02 UTC, jjyao commented on python/ray/_private/worker.py
> +        "true" if ray._raylet.Config.memory_monitor_interval_ms() > 0 else "false",
Should we use the actual ms as the value, seems it provides more information while it's also not sensitive?

2022-10-13 08:46 UTC, rkooo567 commented
Hmm I think it is not going to work if you do ray start --head. Can you add a test with this case?

2022-10-13 17:15 UTC, clarng commented
> I'd love to talk in person to talk about how I'd approach this

sounds good, should be back on this very soon

2022-11-23 01:42 UTC, clarng commented
Fixed in https://github.com/ray-project/ray/pull/30472

2022-11-23 01:42 UTC, closed without merging