[ci] Add release branch reporting
ray-project/ray pull request #29265
Opened 2022-10-12 17:59 UTC by rickyyx

Signed-off-by: rickyx <rickyx@anyscale.com>

## Why are these changes needed?
So we have test results from release branch as well. 

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-10-12 18:01 UTC, krfricke approved these changes

2022-10-12 18:45 UTC, krfricke requested changes

2022-10-12 18:45 UTC, krfricke commented on release/ray_release/scripts/build_pipeline.py
> +        or branch.startswith("releases")
Hm actually we may need to use `get_buildkite_repo_branch()` instead to get the wheels branch and not the test branch. Basically we should only report if both the test branch and the wheels branch are `releases/*`

2022-10-12 20:00 UTC, rickyyx commented on release/ray_release/scripts/build_pipeline.py
> +        or branch.startswith("releases")
Sounds right to me - I wasn't sure what this test branch means tho. 

So test branch is the branch name we give to the buildkite pipeline? And the repo branch is the actual wheel branch name?

2022-10-12 20:23 UTC, jjyao commented on release/ray_release/scripts/build_pipeline.py
> +        or branch.startswith("releases")
@rickyyx how do we run release tests for release branch now? Do we provide wheel url directly?

2022-10-17 23:50 UTC, rickyyx commented on release/ray_release/scripts/build_pipeline.py
> +        or branch.startswith("releases")
> @rickyyx how do we run release tests for release branch now? Do we provide wheel url directly?

No, we are just using the latest commit (HEAD). See this pipeline https://buildkite.com/ray-project/release-tests-branch/builds/1129

2022-10-17 23:53 UTC, rickyyx commented
Addressed comments. cc @krfricke

2022-10-18 20:23 UTC, krfricke approved these changes

2022-10-18 20:23 UTC, merged