[AIR] Use recommended Pandas APIs
ray-project/ray pull request #29269
Opened 2022-10-12 19:25 UTC by amogkam

Signed-off-by: Amog Kamsetty <amogkamsetty@yahoo.com>

Pandas APIs we were previously using for data batch conversions will have its behavior changed soon. We switch to using the recommended APIs instead.

Gets rid of this FutureWarning in newer Pandas versions
```
/Users/amog/dev/ray/python/ray/air/util/data_batch_conversion.py:221: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
    df.loc[:, col_name] = TensorArray(col)
```

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-10-13 01:29 UTC, amogkam commented
there actually seem to be significant differences in behavior between `df.loc` API and directly setting the column. https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

@clarkzinzow do you have more context on this?

2022-10-13 16:13 UTC, clarkzinzow requested changes
We should only be using the `iloc` and `loc` APIs, since we nearly always want to be setting these in-place. The recommendation in that warning is only if you're wanting a copy to be returned, which we typically do _not_ want. If we need a copy, that should be done upstream from these mutations.

2022-10-13 18:22 UTC, amogkam commented
@clarkzinzow can you clarify what the recommended change should be then?

From the Pandas changelog, `df.iloc` will no longer work as we are currently using it in future Pandas versions. https://pandas.pydata.org/docs/dev/whatsnew/v1.5.0.html#inplace-operation-when-setting-values-with-loc-and-iloc.

2022-10-13 18:39 UTC, clarkzinzow commented
@amogkam When we want to mutate the underlying DataFrame instead of creating an entirely new copy (which is nearly always the case), we want to use `.iloc[]` and `.loc[]`, and AFAICT those are the semantics we want in these three cases.

2022-10-13 18:39 UTC, clarkzinzow commented on python/ray/air/util/data_batch_conversion.py
> +            return data[data.columns[0]].to_numpy()
This is just returning an rvalue, we're not mutating here, so `data.iloc[:, 0].to_numpy()` should be fine.

2022-10-13 18:41 UTC, clarkzinzow commented on python/ray/air/util/data_batch_conversion.py
> +                    df[col_name] = TensorArray(col)
We want to mutate (overwrite) the column in-place, so `df.loc[:, col_name] = TensorArray(col)` is preferred.

2022-10-13 18:41 UTC, clarkzinzow commented on python/ray/air/util/data_batch_conversion.py
> +                df[col_name] = pd.Series(list(col.to_numpy()))
Same here, we want to mutate (overwrite) the column in-place, so `df.loc[:, col_name] = pd.Series(list(col.to_numpy()))` seems correct to me.

2022-11-15 21:52 UTC, clarkzinzow approved these changes
LGTM!

2022-11-15 22:08 UTC, amogkam commented on python/ray/air/util/data_batch_conversion.py
> +                    # Surpress Pandas warnings:
```suggestion
                    # Suppress Pandas warnings:
```

2022-11-15 22:08 UTC, amogkam commented on python/ray/air/util/data_batch_conversion.py
> +                # Surpress Pandas warnings:
```suggestion
                # Suppress Pandas warnings:
```

2022-11-16 00:17 UTC, merged