Upgrade tensorflow
ray-project/ray pull request #29368
Opened 2022-10-14 18:14 UTC by sihanwang41

Signed-off-by: Sihan Wang <sihanwang41@gmail.com>

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-10-14 18:20 UTC, amogkam requested changes

2022-10-14 18:20 UTC, amogkam commented on python/requirements/ml/requirements_dl.txt
> +tensorflow==2.10.0
lets keep this as 2.6.3. It will introduce the least amount of changes.

2022-10-14 18:20 UTC, amogkam commented on python/requirements/ml/requirements_dl.txt
> +tensorflow==2.10.0
only tensorflow 2.6.2 has the typing extensions restriction. 2.6.3 does not.

2022-10-17 17:20 UTC, amogkam approved these changes
Thanks, lgtm!

2022-10-17 18:08 UTC, krfricke approved these changes

2022-10-17 18:09 UTC, krfricke commented
@sihanwang41 can you update the PR description?

2022-10-17 18:38 UTC, sihanwang41 commented
> @sihanwang41 can you update the PR description?

Updated!

2022-10-19 21:47 UTC, amogkam commented
Closing this as it breaks rllib tests. Will have to revisit this later cc @ArturNiederfahrenhorst

2022-10-19 21:47 UTC, closed without merging