[Docker] Pin `fastapi` in a separate requirements file
ray-project/ray pull request #29441
Opened 2022-10-18 20:23 UTC by amogkam

Signed-off-by: Amog Kamsetty <amogkamsetty@yahoo.com>

The ML Docker image does not pick up changes in `requirements.txt` due to a bug. This is being fixed here https://github.com/ray-project/ray/pull/29375.

We pin `fastapi` in a separate file as a stopgap solution to immediately resolve https://github.com/ray-project/ray/issues/29396

Closes https://github.com/ray-project/ray/issues/29396

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-10-18 20:25 UTC, krfricke commented on python/requirements/requirements_extra.txt
> +fastapi==0.84.0
```suggestion
fastapi==0.84.0
protobuf==3.20.1
```

2022-10-18 20:29 UTC, krfricke approved these changes

2022-10-18 20:32 UTC, sihanwang41 requested changes
This will break the serve release test until https://github.com/ray-project/ray/blob/master/release/serve_tests/gpu_app_config.yaml#L13 remove.

2022-10-19 17:44 UTC, sihanwang41 reviewed
The unit tests looks failing

2022-10-19 21:41 UTC, sihanwang41 approved these changes

2022-10-19 21:51 UTC, merged