[core] Reduce log spam in task_manager when nodes newly fail
ray-project/ray pull request #29594
Opened 2022-10-24 03:19 UTC by clarng

Signed-off-by: Clarence Ng <clarence.wyng@gmail.com>

## Why are these changes needed?

Reduce log spam in task_manager when nodes newly fail

## Related issue number

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-10-24 23:24 UTC, ericl commented on src/ray/core_worker/transport/direct_task_transport.cc
> +            RAY_LOG_EVERY_MS(INFO, 2 * 1000)
How about every 30s?

2022-10-25 03:28 UTC, ericl approved these changes

2022-10-25 12:30 UTC, rkooo567 requested changes
nit !

2022-10-25 12:30 UTC, rkooo567 commented on src/ray/core_worker/transport/direct_task_transport.cc
> +            RAY_LOG_EVERY_MS(INFO, 30 * 1000)
it'd be great if we can handle it in this PR..

2022-11-17 04:02 UTC, clarng commented
@rkooo567  ptal?

2022-11-17 04:03 UTC, ericl approved these changes

2022-11-17 04:04 UTC, rkooo567 approved these changes

2022-11-17 04:04 UTC, merged