[Log monitor] Handle Process lookup error for log monitor
ray-project/ray pull request #29754
Opened 2022-10-27 11:14 UTC by rkooo567

Signed-off-by: SangBin Cho <rkooo567@gmail.com>

## Why are these changes needed?

Looks like `ProcessLookupError ` can be raised when the proc doesn't exist. We should handle this. 

https://github.com/ray-project/ray/issues/29452

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-10-28 20:38 UTC, scv119 approved these changes

2022-10-28 20:40 UTC, scv119 commented on python/ray/_private/log_monitor.py
> +        except OSError, ProcessLookupError:
any other errors we should expect as well?

2022-10-28 20:41 UTC, scv119 commented on python/ray/_private/log_monitor.py
> +        except OSError, ProcessLookupError:
hmm. https://docs.python.org/3/library/exceptions.html#OSError looks ProcessLookupError is already subclass of OSError?

2022-10-28 20:47 UTC, scv119 requested changes
request change

2022-10-29 00:24 UTC, rkooo567 commented
seems like ProcessLookupError should be caught. Not sure why the user has this error not caught by OSError...

2022-10-29 00:24 UTC, closed without merging