Make ray.get(timeout=0) to throw timeout error
ray-project/ray pull request #30210
Opened 2022-11-11 14:09 UTC by vitrioil

## Why are these changes needed?
As mentioned in the issue it makes it consistent with other `.get` call.

However, I wonder if this change might be unexpected for existing code where 0 is already used without expecting an error.

## Related issue number
Closes #28465

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-11-23 14:24 UTC, vitrioil commented
@krfricke any idea who can review this? (I think the build failures are unrelated?)

2022-12-14 17:06 UTC, krfricke commented
I think the main question is if this was intended API before or not. But yes, this will effectively be an API change and it will be hard to provide a graceful transition.

2022-12-14 20:58 UTC, krfricke approved these changes
Looks good to me, thanks!

2022-12-14 20:59 UTC, krfricke commented
After internal discussion, it seems like this was a bug and we should fix it. cc @rickyyx to take a look from Ray core side

2022-12-14 21:14 UTC, rickyyx reviewed
<div><img src="https://media2.giphy.com/media/10uEX5kfeodYgo/200.gif?cid=5a38a5a27f17d0eei6ug6uq3ee0eid5dt4y63daoelnla3fm&amp;rid=200.gif&amp;ct=g" style="border:0;height:239px;width:300px"/><br/>via <a href="https://giphy.com/gifs/share-very-discover-10uEX5kfeodYgo">GIPHY</a></div>


Should we also piggyback doc improvmeent?
https://github.com/ray-project/ray/blob/e1a879605d840c4e634dc18eb28c72541dcd3e53/python/ray/_private/worker.py#L2272-L2285


I feel the current documentation is not explicit in the behaviour of timeout=0 vs timeout=None, which could be better. 

Also, does it make sense to change these as well now we have a proper `timeout=0` behaviour: 
https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/ray-project/ray%24+ray.get.*timeout%3D0.1&patternType=standard&sm=1

2022-12-14 23:01 UTC, rkooo567 commented
We shouldn't always raise an error? I think it should get the object if the object is ready. Is this covered?

2022-12-14 23:48 UTC, rkooo567 requested changes
request change on the comment ^

2022-12-15 00:35 UTC, krfricke commented
@vitrioil let me know if you want to take these changes, otherwise I'm happy to add them to this PR later this week

2022-12-15 02:25 UTC, rickyyx commented
An update on this - since this change will be breaking backward compatibility (there might be users who have code depends on this "buggy" behaviour), we will take a slower migration approach. 

1. We will collect some signals on existing  usage of `ray.get(timeout=0)`
   a. telemetry data 
   b. Ask in slack and OSS community 
2. [Optional] add warnings of changes in the future release. 
   a. This step will depend on if there's significant usage of the `timeout=0` behaviour. 
3. Perform the migration (this PR) in future releases.

2023-01-17 17:39 UTC, krfricke commented
This is still relevant. Can we make the stale bot less aggressive?

2023-02-22 00:01 UTC, rickyyx commented
Keep.

2023-04-11 10:27 UTC, closed without merging

2023-04-12 01:15 UTC, rkooo567 commented
This will be done by https://github.com/ray-project/ray/issues/28465 in ray 2.5