AIR batch forecasting Prophet example
ray-project/ray pull request #30430
Opened 2022-11-17 20:30 UTC by christy

## Why are these changes needed?

This example follows the same AIR pattern as [Batch training & tuning on Ray Tune](https://github.com/ray-project/ray/blob/master/doc/source/ray-air/examples/batch_tuning.ipynb).  Also used the same NYC Taxi data.  However we use Prophet time series forecasting models instead of Scikit-learn regression models.

Things still left to do IMHO:
- Still need to polish notebook explanatory texts.
- I noticed some inconsistency restoring my inference pandas df from checkpoint.  (Prophet outputs a nice pandas df that includes confidence intervals).  I will double check my code.  I often had to re-inference the restored-from-checkpoint model again in order to see a correct plot at end of notebook.
- The example of tuning a seasonality hyperparameter in Prophet might not be that useful?  Since Prophet is good at automatically trying and using the right seasonalities.  
- Maybe a better tuning example would be comparing 2 different Prophet algorithm flavors? Original [Prophet](https://github.com/facebook/prophet) vs research team maintained [Prophet] (https://github.com/facebookresearch/Kats/blob/main/kats/models/prophet.py) and let both algorithms do their thing to automatically detect the right seasonal effects.  Another option is ARIMA vs Prophet as a Tune experiment.

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-11-17 21:03 UTC, Yard1 commented
I'd try both flavors of prophet and autoarmia from statsforecast.

2022-11-21 16:35 UTC, christy commented
Latest commit:
- Updated notebook explanatory texts.
- Fixed restoring Prophet forecast pandas dataframes from checkpoint, now I see correct plots at end of notebook.
- Replaced Tune experiment so it uses 2 flavors of Prophet seasonality + ARIMA
- One more example that might be useful is replace the PyArrow data step with Ray Datasets

2022-11-21 23:14 UTC, Yard1 approved these changes
LGTM, thanks!

2022-11-22 01:36 UTC, richardliaw requested changes
Awesome work! some changes requested. Can we rename this to something like "parallel demand forecasting"?

2022-11-22 01:36 UTC, richardliaw commented on doc/source/ray-air/examples/batch_forecasting.ipynb
> +    "> The typical use case for Tune search spaces are for hypterparameter tuning. In our case, we are defining a Tune search space in a way to allow for training jobs to be conducted automatically.
```suggestion
    "> The typical use case for Tune search spaces are for hyperparameter tuning. In our case, we are defining a Tune search space in a way to allow for training jobs to be conducted automatically. Each training job will run on a different data partition (taxi pickup location) and use a different model.\n",
```

2022-11-22 01:36 UTC, richardliaw commented on doc/source/ray-air/examples/batch_forecasting.ipynb
> +    "- Grid search.\n",
this seems a bit weird

2022-11-22 01:36 UTC, richardliaw commented on doc/source/ray-air/examples/batch_forecasting.ipynb
> +   ]
We can skip this section (or put it in the bottom); it's not critical path for the user to know

2022-11-22 01:36 UTC, richardliaw commented on doc/source/ray-air/examples/batch_forecasting.ipynb
> +    "[checkpoints.append(i.checkpoint) for i in results]\n",
```suggestion
    "checkpoints = [i.checkpoint for i in results]\n",
```

2022-11-22 01:36 UTC, richardliaw commented on doc/source/ray-air/examples/batch_forecasting.ipynb
> +    "[model_type.append(i.config[\"model_type\"]) for i in results]\n",
let's make this more idiomatic (see suggested change above)

2022-11-22 01:42 UTC, christy commented
I'll pull again, and re-work those sections.

2022-11-22 19:06 UTC, richardliaw commented
@christy the changes haven't been fixed yet; can you take a look?

2022-11-22 23:16 UTC, christy commented
Made changes for comments https://github.com/ray-project/ray/pull/30430#pullrequestreview-1189141567

One thing that had me puzzled for a while, `train_test_split()` was switched out to scikit-learn's method. That does not work on time series. So another change in this latest commit was to sort the data by date, then manually split data into train, test.

2022-11-22 23:37 UTC, richardliaw approved these changes

2022-11-29 00:04 UTC, merged