[AIR] Ensure GBDT PGFs match passed ScalingConfig
ray-project/ray pull request #30470
Opened 2022-11-18 12:39 UTC by Yard1

## Why are these changes needed?

Depends on https://github.com/ray-project/ray/pull/30304

This PR fixes an issue with the special case from `GBDTTrainer`, where the `ScalingConfig` would be converted to `xgboost_ray.RayParams` first before being converted to a PGF for purposes of determining trial resources. This however results in dropping of strategy, args and kwargs from `ScalingConfig`, as `RayParams` doesn't support them. This PR introduces backwards compatible logic to deal with this issue. The changes introduced here will be upstreamed to `xgboost_ray`. 

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-11-18 18:59 UTC, amogkam reviewed
thanks @Yard1 lgtm. can we add a small test?

2022-11-18 19:12 UTC, Yard1 commented
This is tested by ensuring that the strategy is not dropped from PGF in the resource changing test, but I can add another one

2022-11-18 19:18 UTC, Yard1 commented
@amogkam added, PTAL

2022-11-18 19:20 UTC, amogkam approved these changes
Thanks!

2022-11-19 01:25 UTC, krfricke requested changes
Good catch, but a couple of small requests

2022-11-19 01:25 UTC, krfricke commented on python/ray/train/gbdt_trainer.py
> +            placement_strategy: Optional[str] = None
```suggestion
            placement_strategy: str = "PACK"
```
it currently defaults to PACK in xgboost-ray, so this should probably be reflected here

2022-11-19 01:25 UTC, krfricke commented on python/ray/train/gbdt_trainer.py
> +            pgf_kwargs: Optional[Dict[str, Any]] = None
Can we just have a single option `placement_options` that contains kwargs to pass to PGF? If we want to upstream this, we should try to keep the `RayParams` dataclass clean as it is also used without Tune

2022-11-19 01:25 UTC, krfricke commented on python/ray/train/gbdt_trainer.py
> +    ray_params.pgf_kwargs = scaling_config_pgf._kwargs
IMO it's not great to convert the scaling config into a PGF here and then cherry-pick specific attributes to pass into the PGF.

I understand that this ensures other arguments (e.g. cpu fraction per node) are automatically caught, but maybe for now we can just build the `placement_options` above manually. Feel free to add a comment into `ScalingConfig.as_placement_group` to keep in sync with GBDT RayParams

2022-11-22 01:39 UTC, krfricke approved these changes
Thanks! Can you open a PR upstream at XGBoost-Ray for these changes?

2022-11-22 01:40 UTC, merged