[Java] Support dynamic resources required when submitting task.
ray-project/ray pull request #3070
Opened 2018-10-16 09:56 UTC by jovan-wong

## What do these changes do?
Before this PR, if we want to specify some resources, we must do as following codes:
```java
@RayRemote(Resources={ResourceItem("CPU", 10)})
public static void f1() {
// do sth
}

@RayRemote(Resources={ResourceItem("CPU", 10)})
class Demo {
// sth
}
```
Unfortunately, it's no way for us to create another actor or task with different resources required.

After this PR, the thing will be:
```java
RayResources resource = new RayResources(); 
resource.add("CPU", 4.0);
RayActor<Echo> echo1 = Ray.createActor(Echo::new, resource);
resource.add("Res-A", 4.0);
RayActor<Echo> echo2 = Ray.createActor(Echo::new, resource);

//or
Ray.call(Echo::echo, echo2, 100,  resource);

//if we don't specify resource, it's `{"cpu":0.0}` by default.
Ray.call(Echo::echo, echo2, 100);
```

## Related issue number
N/A

2018-10-16 10:00 UTC, jovan-wong commented
@chuxi  cc

2018-10-16 11:31 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/8678/
Test PASSed.

2018-10-17 03:04 UTC, raulchen requested changes
A few comments:
1) Better change the extra argument from `RayResource` to `CallOptions` (for `Ray.call`) and `ActorCreationOptions` (for `Ray.createActor`). For now, `CallOptions` only has a `resources` field. But in the future, we can add more options to it.
2) I think it's not necessary to define resources as a class. We can simply use a map. The logic of adding default CPU field should be in the runtime module, not in api module.
3) Change `RayCallGenerator.java`, do not modify `RayCall.java` directly. `

2018-10-17 06:11 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/8696/
Test PASSed.

2018-10-17 08:39 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/8699/
Test PASSed.

2018-10-17 08:49 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/8700/
Test PASSed.

2018-10-18 04:55 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/8719/
Test PASSed.

2018-10-18 05:25 UTC, raulchen approved these changes

2018-10-18 05:31 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/8720/
Test PASSed.

2018-10-18 05:34 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/8721/
Test PASSed.

2018-10-19 13:22 UTC, merged