unit testing
ray-project/ray pull request #30775
Opened 2022-11-30 02:41 UTC by rickyyx

Signed-off-by: rickyyx <rickyx@anyscale.com>

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-11-30 02:47 UTC, rickyyx commented on src/ray/core_worker/core_worker.cc
> -  if (request.include_task_info()) {
todo: this needs to be reverted.

2022-11-30 21:22 UTC, rickyyx commented on src/ray/common/task/task_spec.h
> +  TaskSpecification() { ComputeResources(); }
Used only in test.

2022-11-30 21:22 UTC, rickyyx commented on src/ray/core_worker/profiling.h
>  #include "ray/common/asio/instrumented_io_context.h"
Profiling frontend porting will be in the next PR.

2022-12-01 01:34 UTC, rickyyx commented on src/ray/common/ray_config_def.h
> +/// TODO(rickyx): Turn this off before merging
to be turned off - turning on now for runnign release tests and CI.

2022-12-01 01:44 UTC, ericl requested changes
Per our general policy to keep PRs <500 lines when possible, could we split this PR into a few chunks? Perhaps the utility data structures could be reviewed first, prior to the code plumbing.

2022-12-01 01:53 UTC, rickyyx commented
> Per our general policy to keep PRs <500 lines when possible, could we split this PR into a few chunks? Perhaps the utility data structures could be reviewed first, prior to the code plumbing.

Ah Ok, let me do that instead. Thought I could try merging something working more end to end in. I think I could probably do the below: 
1. the RPC changes 
2. The `TaskEventBuffer` code and its unittests 
3. The GCS side changes. 

Each of the above should be small enough for an easier review I believe.

2022-12-01 17:28 UTC, closed without merging