Enable to specify driver id by user.
ray-project/ray pull request #3084
Opened 2018-10-18 07:00 UTC by jovan-wong

## What do these changes do?
It's very useful for us to specify driver id to a driver.
In Java, we could specify it by `ray.conf`, and in Python, we should do it by `def init()`:
```python
ray.init(worker_id="01234567")
```
If we don't specify one, it will generate a random for us.

## Related issue number
N/A

2018-10-18 07:04 UTC, robertnishihara commented on python/ray/worker.py
> +         worker_id=None,
If this is the `driver_id` then it needs to be called `driver_i`.

2018-10-18 07:05 UTC, robertnishihara commented on python/ray/worker.py
> +    if worker_id is None:
We should do some type checking. I think we want to assert that it is a Ray ObjectID or that it is 20 bytes or something like that. All of that is a bit ugly unfortunately.

2018-10-18 07:07 UTC, robertnishihara commented
I have mixed feelings about this. I think we want to restrict driver_id's to have type `ray.DriverID`, but we don't have that, so it would need to be `ray.ObjectID`, which feels weird because it's a driver, not an object. You're code example seems to use a short string, which doesn't make sense to me. Doesn't it need to be 20 bytes?

2018-10-18 09:03 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/8729/
Test PASSed.

2018-10-18 11:38 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/8732/
Test PASSed.

2018-10-18 15:53 UTC, jovan-wong commented
@robertnishihara  Thanks a lot for your comments about it.

I have addressed some comments: 
adding type checking and renaming `worker_id` to `driver_id`.

Of course, it's too awkward for me to do type checking for these codes. As you mentioned, which type should `driver_id` should be? Maybe we should add an `UniqueID` type.

Another question I found is `worker.worker_id`'s type. I guess we assume that it's a string or bytes. One problem that comes with this is :
```python
    # Initialize some fields.
    if mode is WORKER_MODE:
        worker.worker_id = random_string()
    else:
        # This is the code path of driver mode.
        if driver_id is None:
            driver_id = ray.ObjectID(random_string())

        elif isinstance(driver_id, (bytes, str)):
            if len(driver_id) is not ray_constants.ID_SIZE:
                raise Exception("The length of given driver id str must be 20.")
            driver_id = ray.ObjectID(driver_id)

        elif not isinstance(driver_id, ray.ObjectID):
            raise Exception("The type of given driver id must be str or ray.ObjectID.")

        worker.worker_id = driver_id.id()
```
We should assume `driver_id` is a `ray.ObjectID` because we should cast from a str or a `ray.ObjectID`, And the next we should cast `driver_id` to str(or bytes) to match `worker.worker_id`.

I think the better way to solve it is to use `worker_id` as `ray.ObjectID` instead of `str(or bytes)`. And we needn't worry about the length of `worker_id` any more, right?

2018-10-18 16:01 UTC, jovan-wong commented
@guoyuhong  cc

2018-10-19 05:49 UTC, robertnishihara commented
@guoyuhong @jovan-wong what is the use case for specifying the driver ID?

2018-10-22 07:17 UTC, raulchen commented
Another purpose is that we want to have an external 'job manager' that runs all drivers with pre-defined driver ids, so it can manage the drivers by the ids.

@robertnishihara do you have any other questions? This PR looks good to me.

2018-10-22 09:52 UTC, raulchen commented
Another purpose is that we want to have an external 'job manager' that runs all drivers with pre-defined driver ids, so it can manage the drivers by the ids.

@robertnishihara do you have any other questions? This PR looks good to me.

2018-10-22 09:52 UTC, raulchen commented
Another purpose is that we want to have an external 'job manager' that runs all drivers with pre-defined driver ids, so it can manage the drivers by the ids.

@robertnishihara do you have any other questions? This PR looks good to me.

2018-10-22 10:53 UTC, raulchen commented
Another purpose is that we want to have an external 'job manager' that runs all drivers with pre-defined driver ids, so it can manage the drivers by the ids.

@robertnishihara do you have any other questions? This PR looks good to me.

2018-10-22 10:54 UTC, raulchen approved these changes

2018-10-22 10:55 UTC, raulchen approved these changes

2018-10-22 13:57 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/8795/
Test FAILed.

2018-10-22 14:41 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/8797/
Test FAILed.

2018-10-29 01:50 UTC, robertnishihara commented on python/ray/worker.py
> +        elif isinstance(driver_id, (bytes, str)):
Let's check that it is `bytes` for Python 2 and `str` for Python 3.

2018-10-29 01:51 UTC, robertnishihara commented on python/ray/worker.py
> +        driver_id: The id of driver, and it will be ignored in non-driver mode.
id -> ID

remove the stuff after the `,`, there is no such thing as "non-driver" mode.

2018-10-29 01:52 UTC, robertnishihara commented on python/ray/worker.py
> +        driver_id: The id of driver, and it will be ignored in non-driver mode.
at least from the perspective of the user and `ray.init`, there is no such thing as "non-driver" mode.

2018-10-29 01:53 UTC, robertnishihara commented on python/ray/worker.py
> +        elif isinstance(driver_id, (bytes, str)):
actually, for now, let's require it to be an `ObjectID`. I think the more restrictive we make it the better since it makes it easier to change later.

2018-10-29 01:53 UTC, robertnishihara requested changes
Thanks! I left some comments.

2018-11-02 09:18 UTC, jovan-wong commented
@robertnishihara  Tks 4 ur comments.
I have addressed them, and could u plz c it again?

2018-11-02 10:29 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/9000/
Test FAILed.

2018-11-02 10:40 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/9001/
Test PASSed.

2018-11-02 10:41 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/9002/
Test PASSed.

2018-11-02 22:25 UTC, robertnishihara approved these changes

2018-11-03 00:00 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/9014/
Test PASSed.

2018-11-03 02:01 UTC, merged