[ci] Raise exception when db put failure when uploading release results.
ray-project/ray pull request #30933
Opened 2022-12-06 23:22 UTC by rickyyx

Signed-off-by: rickyyx <rickyx@anyscale.com>

## Why are these changes needed?

We have not had release test results being reported for a month when they ran but failed to report results to DB. 
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/11676094/206046444-d3ba57aa-8064-4943-b908-981ae64da010.png">

But there are successful runs which failed to upload results, and are not recorded silently: 
<img width="998" alt="image" src="https://user-images.githubusercontent.com/11676094/206046585-0f40122c-9e00-412c-afb1-bb0b77978490.png">

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-12-06 23:30 UTC, rickyyx commented
Ah I guess this is the root-cause: https://github.com/ray-project/ray/pull/30849

2022-12-06 23:35 UTC, rkooo567 approved these changes
I will wait @krfricke for the approval (not sure if the change is controversial, but I think it is the right thing to do)

2022-12-07 06:29 UTC, krfricke requested changes
Wait, what is the actual root cause for logs not being persisted? After #30849 the length should always be short enough?

The `raise e` change won't do much as we catch everything in the outer loop in `glue.py`:

```
    for reporter in reporters:
        try:
            reporter.report_result(test, result)
        except Exception as e:
            logger.error(f"Error reporting results via {type(reporter)}: {e}")
```

I'm open to raising an error, but if we do, let's please raise an exception that inherits `ReleaseTestError` and is associated to a proper exit code. IMO it should be a new exit code in the "hard infra error (non-retryable)" section

2022-12-07 18:07 UTC, rickyyx commented
Right - The root cause is https://github.com/ray-project/ray/pull/30849

Oh I see - should we be reporting any reporter failure in this case? E.g. not catching all exceptions at `glue.py`?

2023-01-07 19:56 UTC, closed without merging