Make pandas dataframe keep the index when concat them
ray-project/ray pull request #30939
Opened 2022-12-07 01:16 UTC by jianoaix

Signed-off-by: jianoaix <iamjianxiao@gmail.com>

## Why are these changes needed?
The dataframe index is lost when having a roundtrip with `.from_pandas()` and then `.to_pandas()`.

## Related issue number
#30261

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-12-07 22:05 UTC, c21 approved these changes
@jianoaix - have you checked why we reset index in the first place?

2022-12-08 01:08 UTC, jianoaix commented
> @jianoaix - have you checked why we reset index in the first place?

It's unclear why: no comment in code, no tests failures.

2022-12-09 18:29 UTC, ericl reviewed
What was the historical reason we dropped the index?

2022-12-09 19:05 UTC, clarkzinzow requested changes
@ericl @jianoaix In general, consistently resetting the index was a very early design decision, where we decided that a block's index should represent the dataset record order. This means that we need to reset the index whenever we slice, concatenate, or shuffle blocks, with the end-result being that each block is locally ordered, and if all blocks are concatenated together (e.g. via `ds.to_pandas()`), the resulting index would give the global dataset order. This was under the assumption that the user would _not_ be encoding application-level identifiers into the index, since we hadn't encountered that use case at the time, and this was a bit of a pragmatic choice, since trying to maintain a sensible index on a distributed DataFrame is a bit difficult, and would require a lot of care to ensure that accidentally-aligned indices wouldn't yield unintended outputs on certain Pandas operations.

@jianoaix This particular index drop was added because of this issue: https://github.com/ray-project/ray/pull/27019/commits/a48e34d25477f4d0f90b7bb7ac4909c8a042b696#r931308133.

If we're going to try to maintain the index, we can't only make the change on concatenation; we would need to do a global audit of all other places we reset the index, i.e. slicing, taking, shuffling:
- https://github.com/ray-project/ray/blob/055c2e4a962ab6afd418886eb55b5992a59dd25b/python/ray/data/_internal/pandas_block.py#L147
- https://github.com/ray-project/ray/blob/055c2e4a962ab6afd418886eb55b5992a59dd25b/python/ray/data/_internal/pandas_block.py#L154
- https://github.com/ray-project/ray/blob/055c2e4a962ab6afd418886eb55b5992a59dd25b/python/ray/data/_internal/pandas_block.py#L167

And before we decide to try to maintain the index, we need to ensure that index-aware operations (i.e. operations that automatically align on indices) will not now give incorrect results, and we might want to only preserve the original index if the index is not the default sequential ordering index (assuming there's an easy way to check that).

2022-12-09 22:09 UTC, ericl commented
Hmm, another obstacle I see is whether this would void our ability to transparently manage the block format conversions--- for example, to numpy or arrow and back. It seems like those would be destructive operations to the index, and if we supported index preservation, we'd need to integrate that into future logical optimization rules.

2022-12-09 22:20 UTC, clarkzinzow commented
@ericl Yep, although the Arrow <--> Pandas integration already preserves the index by default, where the (default) `RangeIndex` is encoded into the Arrow schema as custom metadata, and any other indices are encoded as columns in the Arrow table; converting back to a Pandas DataFrame automatically reinstates the index.

We'd need to implement something similar for the NumPy batch format, though.

2022-12-09 22:29 UTC, ericl commented
Hm was that the original reason why we disabled it? I'm vaguely remembering something about excessive memory overhead.

2022-12-09 22:31 UTC, jianoaix commented
Thanks for context @clarkzinzow. Also the block conversion is a good point.

2022-12-09 22:33 UTC, clarkzinzow commented
>Hm was that the original reason why we disabled it? I'm vaguely remembering something about excessive memory overhead.

>In particular, storing the index in the schema sounds like it could break our assumption of Schema being small.

@ericl The default `RangeIndex` can be represented with constant space per block (I think it's just start, stop, and step ints), and that's the only one that's represented in the schema (all other index types are explicitly represented as a column), so I don't think that was it.

2022-12-10 00:26 UTC, jianoaix commented
In just this rotation of oncall, I saw three different users looking to adding index to a Ray Dataset. All of them ended up doing it in a very inefficient way, i.e. sequentially scan the Dataset to maintain a count and then add it to a new column. I think there are some emerging signals now to support index at Dataset natively.

This looks more complex than it seems. We can start a doc to scope the issue before getting back to here.

2022-12-10 00:37 UTC, ericl commented
Spark has this API for what sounds like these users want: https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.RDD.zipWithIndex.html

2022-12-10 00:50 UTC, clarkzinzow commented
It's a very reasonable feature request, +1 for scoping out the feature
before digging into the implementation. I'm not sure how we'd handle e.g.
maintaining a sidecar index for a NumPy batch format UDF that filters out
rows, since we won't know which index elements correspond to the filtered
rows (same goes for a UDF that adds rows). And there are risks around added
complexity in adding index handling for batch UDFs, and possible changes in
behavior of existing Pandas-based workloads.

It will probably be easier to discuss those concerns in a one-pager or RFC
issue!

On Fri, Dec 9, 2022, 6:38 PM Eric Liang ***@***.***> wrote:

> Spark has this API for what sounds like these users want:
> https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.RDD.zipWithIndex.html
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ray-project/ray/pull/30939#issuecomment-1344947163>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB2X3TYUTOPP3PTM5FCHKE3WMPGHFANCNFSM6AAAAAASWGFJME>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-12 22:34 UTC, ericl commented
Let's close this for now then. It sounds like the issue is more complex than anticipated, and it is not high priority.

2022-12-12 22:34 UTC, closed without merging