[Datasets] Fix `to_tf` when the input feature_columns is a list.
ray-project/ray pull request #31228
Opened 2022-12-20 04:01 UTC by n30111

## Why are these changes needed?

This fixes a bug in `dataset.to_tf` method. This method should returns a dictionary when input  feature_columns is a list, but in the current release 2.2 and master branch it is returning a set, which also fails due to unhashable type. 

## Related issue number

https://github.com/ray-project/ray/issues/31229

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-12-20 05:40 UTC, bveeramani requested changes
Thanks for the contribution! The patch looks good to me.

Could you also add a unit test?

2022-12-20 12:25 UTC, n30111 commented
@bveeramani thanks, I have added a test to verify the above change.

2022-12-21 21:40 UTC, bveeramani approved these changes
LGTM

2022-12-21 21:53 UTC, clarkzinzow approved these changes

2022-12-21 21:53 UTC, merged