Task backend disable status
ray-project/ray pull request #31287
Opened 2022-12-22 01:22 UTC by rickyyx

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2022-12-22 01:32 UTC, rickyyx commented
Local benchmark showing perf improvement: 
|    | name        |   report_interval | enable_status_event   |   multi_client_tasks_async |   n_n_actor_async |
|---:|:----------|------------------:|:----------------------|---------------------------:|------------------:|
|  0 | master  |              1000 | True                  |                    29728.2 |           26801   |
|  1 | no-status (this PR) |              1000 | False                 |                    33125.3 |           29763.3 |
|  2 | off      |                 0 | True                  |                    34821.5 |           30928.5 |

Running e2e release tests: https://buildkite.com/ray-project/release-tests-pr/builds/24231#0185376d-2abe-4776-a305-4f304a567ae2

2022-12-22 01:37 UTC, ericl commented
Hmm what is the implication for this? Seems like we should at least keep the start/failed/finished events?

2022-12-22 01:47 UTC, rickyyx commented
Ah - yeah maybe we could do that. I am planning to do some trial and errors to see at which/how many callsites we will see the regression.

2022-12-22 04:34 UTC, rkooo567 approved these changes
I believe it is a temporary disablement so that we can prioritize state API integration first (which can unblock others). 

Btw is this expected? IIRC we didn't see this regression when we prototyped it first right? What's been changed?

2022-12-22 04:34 UTC, rkooo567 commented
(also there's a test failure )

2022-12-22 18:05 UTC, rickyyx commented
> I believe it is a temporary disablement so that we can prioritize state API integration first (which can unblock others).
> 
> Btw is this expected? IIRC we didn't see this regression when we prototyped it first right? What's been changed?

The regression was probably there - but I guess I focused more on the task related and microbenchmark which is more reproducible locally.

2022-12-22 20:29 UTC, ericl requested changes
I'm against adding this flag / merging this change--- if we want to optimize the backend, I think we should do it in a way that doesn't involve flags. For example, only recording certain events, or deciding that we don't need these status events altogether.

2022-12-23 01:07 UTC, rickyyx commented
I think the regression actually happened before this PR. Closing the PR.

2022-12-23 01:07 UTC, closed without merging

2022-12-23 01:07 UTC, rickyyx commented
I think the regression actually happened before this PR. Closing the PR.