[release][tune] [build_base] Fix `tune_scalability_durable_trainable` configuration to force experiment syncs less often
ray-project/ray pull request #31649
Opened 2023-01-12 21:38 UTC by justinvyu

Deflakes `tune_scalability_durable_trainable` release test by configuring it so that forced experiment checkpoint syncs happen less frequently, cutting down on the test runtime.

## Why are these changes needed?

The `tune_scalability_durable_trainable` test had a performance regression (running for ~300s longer) and is flaky. This was due to experiment checkpoint syncing to cloud being forced more often due to a fix by https://github.com/ray-project/ray/pull/31131. Each forced sync causes the driver to wait until that sync is finished before launching a new one, which accounts for the drastically increased runtime. This PR fixes the issue by increasing the number of checkpoints to keep, which in turn reduces the frequency of forced cloud syncs.

**Question:** How can we provide a better default for users? Can we provide a maximum amount of time spent waiting on cloud syncs? So that even if the user configures `keep_checkpoints_num` in such a way that syncs are getting forced very frequently, their script runtime doesn't get affected past a certain amount.
- Tracking this here: https://github.com/ray-project/ray/issues/31613, to be addressed in a followup.

## Related issue number

Closes https://github.com/ray-project/ray/issues/31506

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [x] Release tests
   - [ ] This PR is not tested :(

2023-01-13 01:03 UTC, krfricke requested changes
Instead of increasing the number of checkpoints to keep, can we just increase the fake training time? This will also increase the time between checkpoint syncs, correct?

2023-01-13 18:11 UTC, justinvyu commented
> Instead of increasing the number of checkpoints to keep, can we just increase the fake training time? This will also increase the time between checkpoint syncs, correct?

@krfricke Yes, we could increase the training time and increase the test pass threshold. Currently, the fake training time per iteration is 6s.

2023-01-16 20:18 UTC, krfricke commented
@justinvyu I'd prefer that option then, could you update the PR? Thanks!

2023-01-17 17:35 UTC, krfricke approved these changes

2023-01-17 17:37 UTC, merged