[core] clean up queued task submitted by the worker when the worker dies
ray-project/ray pull request #32029
Opened 2023-01-28 22:37 UTC by clarng

Signed-off-by: Clarence Ng <clarence.wyng@gmail.com>

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-01-30 19:47 UTC, rkooo567 requested changes

2023-01-30 19:47 UTC, rkooo567 commented on src/ray/raylet/node_manager.cc
> +  cluster_task_manager_->CancelTaskForOwner(worker->GetAssignedTaskId());
I think it doesn't clean up if the tasks are queued on other nodes? Can you add a test case?

2023-01-30 19:47 UTC, rkooo567 commented on src/ray/raylet/scheduling/cluster_task_manager.h
> +  /// Attempt to cancel already queued tasks submitted by the owner.
We shouldn't apply this if the task is a detached actor creation task (it doesn't fate share with the owner). Can you also add a test case for this one?

2023-01-31 20:47 UTC, clarng commented
Moved to https://github.com/ray-project/ray/pull/32127/files

2023-01-31 20:47 UTC, closed without merging