[Doc] Move actor checkpointing to actor fault tolerance page
ray-project/ray pull request #32153
Opened 2023-02-01 02:06 UTC by jjyao

## Why are these changes needed?

Actor fault tolerance page is a better place for actor checkpointing. Also make the code example testable.
## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-02-01 05:07 UTC, angelinalg commented on doc/source/ray-core/fault_tolerance/actors.rst
> +Although ``max_restarts`` will restart the crashed actor automatically,
```suggestion
``max_restarts`` automatically restarts the crashed actor,
```

2023-02-01 05:08 UTC, angelinalg commented on doc/source/ray-core/fault_tolerance/actors.rst
> +it doesn't provide ways for you to restore application level state in your actor.
```suggestion
but it doesn't allow you to restore application level state in your actor.
```

2023-02-01 05:09 UTC, angelinalg commented on doc/source/ray-core/fault_tolerance/actors.rst
> +For this, you can checkpoint your actor's state and recover from the checkpoint upon actor restart.
```suggestion
You can checkpoint your actor's state and recover from the checkpoint with an actor restart.
```

2023-02-01 05:10 UTC, angelinalg commented on doc/source/ray-core/fault_tolerance/actors.rst
> +One way of doing this is letting the actor creator manage the checkpoint and manually restart and recover the actor upon failure:
```suggestion
Let the actor creator manage the checkpoint and manually restart and recover the actor upon failure:
```

2023-02-01 05:11 UTC, angelinalg commented on doc/source/ray-core/fault_tolerance/actors.rst
> +Or the actor can checkpoint and restore automatically:
```suggestion
Alternatively, the actor can checkpoint and restore automatically:
```

2023-02-01 05:11 UTC, angelinalg commented on doc/source/ray-core/fault_tolerance/actors.rst
> +  If the checkpoint is saved to an external storage, you need to make sure
```suggestion
  If the checkpoint is saved to external storage, make sure
```

2023-02-01 05:12 UTC, angelinalg commented on doc/source/ray-core/fault_tolerance/actors.rst
> +  it's accessible to the entire cluster since the actor might be restarted
```suggestion
  it's accessible to the entire cluster, since the actor might be restarted
```

2023-02-01 05:13 UTC, angelinalg commented on doc/source/ray-core/fault_tolerance/actors.rst
> +  You can save the checkpoint to a cloud storage (e.g. S3) or a shared directory (e.g. via NFS).
```suggestion
  Save the checkpoint to cloud storage (e.g., S3) or a shared directory (e.g., via NFS).
```

2023-02-03 21:15 UTC, stephanie-wang requested changes

2023-02-03 21:15 UTC, stephanie-wang commented on doc/source/ray-core/fault_tolerance/actors.rst
> +but it doesn't allow you to restore application level state in your actor.
```suggestion
but it doesn't automatically restore application level state in your actor.
```

2023-02-03 21:15 UTC, stephanie-wang commented on doc/source/ray-core/fault_tolerance/actors.rst
> +You can checkpoint your actor's state and recover from the checkpoint with an actor restart.
```suggestion
Instead, you should manually checkpoint your actor's state and recover upon actor restart.
```

2023-02-03 21:15 UTC, stephanie-wang commented on doc/source/ray-core/fault_tolerance/actors.rst
> +Let the actor creator manage the checkpoint and manually restart and recover the actor upon failure:
```suggestion
For actors that are restarted manually, the actor's creator should manage the checkpoint and manually restart and recover the actor upon failure. This is recommended if you want the creator to decide when the actor should be restarted and/or if the creator is coordinating actor checkpoints with other execution:
```

2023-02-03 21:15 UTC, stephanie-wang commented on doc/source/ray-core/fault_tolerance/actors.rst
> +Alternatively, the actor can checkpoint and restore automatically:
```suggestion
Alternatively, if you are using Ray's automatic actor restart, the actor can checkpoint itself manually and restore from a checkpoint in the constructor:
```

2023-02-03 21:15 UTC, stephanie-wang commented on doc/source/ray-core/fault_tolerance/actors.rst
> +  Save the checkpoint to cloud storage (e.g., S3) or a shared directory (e.g., via NFS).
```suggestion
  For example, save the checkpoint to cloud storage (e.g., S3) or a shared directory (e.g., via NFS).
```

2023-02-03 21:15 UTC, stephanie-wang commented on doc/source/ray-core/doc_code/actor_checkpointing.py
> +            # Heavy init
I don't understand what this comment means.

Also this example seems kind of odd; if the state is immutable, why would you need to save it? Wouldn't it make more sense to have mutable state and write to the checkpoint after each update?

2023-02-03 21:15 UTC, stephanie-wang commented
(mainly comments to provide more context on use cases)

2023-02-09 21:40 UTC, stephanie-wang approved these changes

2023-02-09 22:00 UTC, merged