[RLlib] Change scope of PPO tests to comply with corrently supported set of spaces in RLModules for PPO
ray-project/ray pull request #32940
Opened 2023-03-01 16:32 UTC by ArturNiederfahrenhorst

## Why are these changes needed?

This PR changes the scope of the PPO test_supported_spaces test.
As we not yet support all previously supported spaces, this PR makes it so that we skip the tests that we don't "want".

2023-03-08 15:54 UTC, ArturNiederfahrenhorst commented on rllib/core/models/base.py
> +    by also inheriting from a framework-specific model base-class, s.a. TorchModel.
This is more feedback from Jun - we were missing this hint.

2023-03-08 20:50 UTC, kouroshHakha requested changes
dude this is super hacky, and not approvable.
My suggestion (the general sketch):
```
LEARNER_ENABLED_OBS_SPACES = [...]
LEARNER_ENABLED_ACTION_SPACES = [...]
def _do_check(algo, config, a_name, o_name):
     config_copy = config.copy()
     config_copy.validate()
     if config_copy.enable_api:
              obs_space_list = LEARNER_ENABLED_OBS_SPACES
              act_space_list = LEARNER_ENABLED_ACTION_SPACES
     else: ...
     
     if o_name not in obs_space_list:
            warn(message)
            return
      if a_name not in act_space_list:
            warn(message)
            return 
```

2023-03-08 22:19 UTC, ArturNiederfahrenhorst commented
@kouroshHakha I understand that it looks hacky. But the code you propose makes it so that hitting an unsupported action space OR and unsupported observations space simply skips the test. Thereby omitting tests that would have a supported space.

2023-03-08 22:20 UTC, ArturNiederfahrenhorst commented
This test works by zipping the spaces together. I don't think it is worth restructuring the rest of the test around your code.

2023-03-08 22:51 UTC, ArturNiederfahrenhorst commented
As per our offline discussion, we are restructuring the test itself.

2023-03-09 22:33 UTC, kouroshHakha commented on rllib/tests/test_supported_spaces.py
> +        if alg == "PPO":
We decided to not have this algo == "PPO" specialization, right? 
We should check for which obs / action space to choose based on whether the enable_rl_module_api is set or not.

2023-03-22 02:20 UTC, kouroshHakha approved these changes

2023-03-22 02:20 UTC, kouroshHakha commented on rllib/tests/test_supported_spaces.py
>      "vector1d": Box(-1.0, 1.0, (5,), dtype=np.float32),
rename: vector1d --> continuous

2023-03-24 16:11 UTC, merged