[runtime env] Add environment variable to skip parsing `.gitignore` file into `"excludes"`
ray-project/ray pull request #33149
Opened 2023-03-08 22:46 UTC by architkulkarni

## Why are these changes needed?
Currently, if a user specifies a local `working_dir`, any `.gitignore` file in the directory will be parsed and the specified files will be excluded from the uploaded `working_dir` package.  This is an issue if the user wants to have some files in `.gitignore` (e.g. because they are very large) but still wants to upload them as part of the `working_dir`.  Previously, there was no way to override this behavior.

This PR adds an environment variable `RAY_RUNTIME_ENV_SKIP_GITIGNORE` which if set to `1`, skips all parsing of `gitignore` files.  

## Related issue number

Closes #18279 
## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-03-08 22:47 UTC, architkulkarni commented
@dmatrix I'm assigning you for docs codeowner review since you have some context on the `runtime_env` docs, but feel free to reassign to another codeowner!

2023-03-08 22:51 UTC, architkulkarni commented
(cc @gvspraveen )

2023-03-09 22:52 UTC, edoakes approved these changes
super nit: `IGNORE_GITIGNORE` is more fitting to me than `SKIP_GITIGNORE`

code changes LGTM

2023-03-10 21:39 UTC, angelinalg commented on doc/source/ray-core/handling-dependencies.rst
> +  Note: If your local directory contains a ``.gitignore`` file, the files and paths specified therein will not be uploaded to the cluster.  This can be disabled by setting the environment variable `R
```suggestion
  Note: If the local directory contains a ``.gitignore`` file, the files and paths specified there are not uploaded to the cluster.  You can disable this by setting the environment variable `RAY_RUNTIME_ENV_IGNORE_GITIGNORE=1` on the machine doing the uploading.
```

2023-03-10 21:40 UTC, angelinalg commented on doc/source/ray-core/handling-dependencies.rst
> +  Note: For option (1), if your local directory contains a ``.gitignore`` file, the files and paths specified therein will not be uploaded to the cluster.  This can be disabled by setting the environ
```suggestion
  Note: For option (1), if the local directory contains a ``.gitignore`` file, the files and paths specified there are not uploaded to the cluster.  You can disable this by setting the environment variable `RAY_RUNTIME_ENV_IGNORE_GITIGNORE=1` on the machine doing the uploading.
```

2023-03-10 21:40 UTC, angelinalg requested changes
Left a couple of copy edits. Otherwise,
LGTM

2023-03-10 22:24 UTC, architkulkarni commented
@angelinalg Thanks, I incorporated them! Please take another look

2023-03-10 22:28 UTC, angelinalg approved these changes
LGTM

2023-03-11 00:47 UTC, architkulkarni commented
Doc build failing on master, error unrelated: /ray/doc/source/ray-air/examples/index.rst:29: WARNING: unknown document: /ray-air/examples/serving
RLlib cartpole tests flaky on master, unrelated
Debug wheels and Arm64 linux wheels flaky on master with error "Error: Observed wheel commit () is not expected commit (bda5766defb095ff370271648b3e8589685e39ce). Aborting.", unrelated
Tune `test_commands` flaky on master, unrelated

2023-03-11 00:48 UTC, merged