Fix leak fd
ray-project/ray pull request #33311
Opened 2023-03-14 23:20 UTC by iycheng

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-03-15 15:01 UTC, rkooo567 approved these changes
LGTM. Btw, is a reason why CheckDeadSubscribers not enough because the timeout is too long (5m) right?

2023-03-15 15:01 UTC, rkooo567 commented on src/ray/pubsub/publisher.h
> +    PublishIfPossible(true);
nice catch!

2023-03-15 15:02 UTC, rkooo567 requested changes
(sorry let me approve after the answer of comments regarding the worker id ^)

2023-03-15 17:46 UTC, iycheng commented on python/ray/_private/worker.py
> +    worker_id = worker.worker_id
I think it comes from here: https://sourcegraph.com/github.com/ray-project/ray@master/-/blob/python/ray/_raylet.pyx?L1609:9

It's from core worker, so I think it should be the same?

2023-03-15 17:47 UTC, iycheng commented
Test failed. Rebase to master first.

2023-03-16 00:49 UTC, rkooo567 approved these changes

2023-03-16 00:49 UTC, rkooo567 commented on python/ray/_private/worker.py
> +    worker_id = worker.worker_id
I see. You are right. Maybe I was confused with the node id or sth...

2023-03-16 21:32 UTC, scv119 approved these changes
Thanks for the fix!

2023-03-16 22:24 UTC, merged

2023-03-16 22:24 UTC, iycheng commented
test failure not related.

2023-03-18 23:28 UTC, ArturNiederfahrenhorst commented
@iycheng I get some error I'm unable to parse since this commit:

> 
> /Users/artur/miniforge3/envs/ray/bin/python /Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm/_jb_pytest_runner.py --path /Users/artur/code/ray/python/ray/rllib/algorithms/ppo/tests/test_ppo_rl_module.py
> Testing started at 16:26 ...
> Launching pytest with arguments /Users/artur/code/ray/python/ray/rllib/algorithms/ppo/tests/test_ppo_rl_module.py --no-header --no-summary -q in /Users/artur/code/ray/python/ray/rllib/algorithms/ppo/tests
> 
> ============================= test session starts ==============================
> collecting ... collected 2 items
> 
> ../../../../python/ray/rllib/algorithms/ppo/tests/test_ppo_rl_module.py::TestPPO::test_forward_train ERROR [ 50%]2023-03-18 16:26:58,338	INFO worker.py:1559 -- Started a local Ray instance.
> 
> test setup failed
> message_descriptor = <google.protobuf.descriptor.Descriptor object at 0x17ced0b50>
> field_name = 'sender_id'
> 
>     def _GetFieldByName(message_descriptor, field_name):
>       """Returns a field descriptor by field name.
>     
>       Args:
>         message_descriptor: A Descriptor describing all fields in message.
>         field_name: The name of the field to retrieve.
>       Returns:
>         The field descriptor associated with the field name.
>       """
>       try:
> >       return message_descriptor.fields_by_name[field_name]
> E       KeyError: 'sender_id'
> 
> /Users/artur/miniforge3/envs/ray/lib/python3.10/site-packages/google/protobuf/internal/python_message.py:577: KeyError
> 
> During handling of the above exception, another exception occurred:
> 
> cls = <class 'test_ppo_rl_module.TestPPO'>
> 
>     @classmethod
>     def setUpClass(cls):
> >       ray.init()
> 
> ../../../../python/ray/rllib/algorithms/ppo/tests/test_ppo_rl_module.py:118: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> ../../../../python/ray/_private/client_mode_hook.py:105: in wrapper
>     return func(*args, **kwargs)
> ../../../../python/ray/_private/worker.py:1561: in init
>     connect(
> ../../../../python/ray/_private/worker.py:2147: in connect
>     worker.import_thread = import_thread.ImportThread(
> ../../../../python/ray/_private/import_thread.py:37: in __init__
>     self.subscriber.subscribe()
> ../../../../python/ray/_private/gcs_pubsub.py:238: in subscribe
>     req = self._subscribe_request(self._channel)
> ../../../../python/ray/_private/gcs_pubsub.py:87: in _subscribe_request
>     req = gcs_service_pb2.GcsSubscriberCommandBatchRequest(
> /Users/artur/miniforge3/envs/ray/lib/python3.10/site-packages/google/protobuf/internal/python_message.py:516: in init
>     field = _GetFieldByName(message_descriptor, field_name)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> message_descriptor = <google.protobuf.descriptor.Descriptor object at 0x17ced0b50>
> field_name = 'sender_id'
> 
>     def _GetFieldByName(message_descriptor, field_name):
>       """Returns a field descriptor by field name.
>     
>       Args:
>         message_descriptor: A Descriptor describing all fields in message.
>         field_name: The name of the field to retrieve.
>       Returns:
>         The field descriptor associated with the field name.
>       """
>       try:
>         return message_descriptor.fields_by_name[field_name]
>       except KeyError:
> >       raise ValueError('Protocol message %s has no "%s" field.' %
>                          (message_descriptor.name, field_name))
> E       ValueError: Protocol message GcsSubscriberCommandBatchRequest has no "sender_id" field.
> 
> /Users/artur/miniforge3/envs/ray/lib/python3.10/site-packages/google/protobuf/internal/python_message.py:579: ValueError
> ERROR [100%]
> test setup failed
> message_descriptor = <google.protobuf.descriptor.Descriptor object at 0x17ced0b50>
> field_name = 'sender_id'
> 
>     def _GetFieldByName(message_descriptor, field_name):
>       """Returns a field descriptor by field name.
>     
>       Args:
>         message_descriptor: A Descriptor describing all fields in message.
>         field_name: The name of the field to retrieve.
>       Returns:
>         The field descriptor associated with the field name.
>       """
>       try:
> >       return message_descriptor.fields_by_name[field_name]
> E       KeyError: 'sender_id'
> 
> /Users/artur/miniforge3/envs/ray/lib/python3.10/site-packages/google/protobuf/internal/python_message.py:577: KeyError
> 
> During handling of the above exception, another exception occurred:
> 
> cls = <class 'test_ppo_rl_module.TestPPO'>
> 
>     @classmethod
>     def setUpClass(cls):
> >       ray.init()
> 
> ../../../../python/ray/rllib/algorithms/ppo/tests/test_ppo_rl_module.py:118: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> ../../../../python/ray/_private/client_mode_hook.py:105: in wrapper
>     return func(*args, **kwargs)
> ../../../../python/ray/_private/worker.py:1561: in init
>     connect(
> ../../../../python/ray/_private/worker.py:2147: in connect
>     worker.import_thread = import_thread.ImportThread(
> ../../../../python/ray/_private/import_thread.py:37: in __init__
>     self.subscriber.subscribe()
> ../../../../python/ray/_private/gcs_pubsub.py:238: in subscribe
>     req = self._subscribe_request(self._channel)
> ../../../../python/ray/_private/gcs_pubsub.py:87: in _subscribe_request
>     req = gcs_service_pb2.GcsSubscriberCommandBatchRequest(
> /Users/artur/miniforge3/envs/ray/lib/python3.10/site-packages/google/protobuf/internal/python_message.py:516: in init
>     field = _GetFieldByName(message_descriptor, field_name)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> message_descriptor = <google.protobuf.descriptor.Descriptor object at 0x17ced0b50>
> field_name = 'sender_id'
> 
>     def _GetFieldByName(message_descriptor, field_name):
>       """Returns a field descriptor by field name.
>     
>       Args:
>         message_descriptor: A Descriptor describing all fields in message.
>         field_name: The name of the field to retrieve.
>       Returns:
>         The field descriptor associated with the field name.
>       """
>       try:
>         return message_descriptor.fields_by_name[field_name]
>       except KeyError:
> >       raise ValueError('Protocol message %s has no "%s" field.' %
>                          (message_descriptor.name, field_name))
> E       ValueError: Protocol message GcsSubscriberCommandBatchRequest has no "sender_id" field.
> 
> /Users/artur/miniforge3/envs/ray/lib/python3.10/site-packages/google/protobuf/internal/python_message.py:579: ValueError
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ../../../../python/ray/rllib/algorithms/ppo/tests/test_ppo_rl_module.py::TestPPO::test_rollouts 
> 
> ============================== 2 errors in 7.42s ===============================
> Exception ignored in atexit callback: <function shutdown at 0x289d9dc60>
> Traceback (most recent call last):
>   File "/Users/artur/code/ray/python/ray/_private/client_mode_hook.py", line 105, in wrapper
>     return func(*args, **kwargs)
>   File "/Users/artur/code/ray/python/ray/_private/worker.py", line 1624, in shutdown
>     disconnect(_exiting_interpreter)
>   File "/Users/artur/code/ray/python/ray/_private/worker.py", line 2220, in disconnect
>     worker.gcs_function_key_subscriber.close()
>   File "/Users/artur/code/ray/python/ray/_private/gcs_pubsub.py", line 288, in close
>     req = self._unsubscribe_request(channels=[self._channel])
>   File "/Users/artur/code/ray/python/ray/_private/gcs_pubsub.py", line 98, in _unsubscribe_request
>     req = gcs_service_pb2.GcsSubscriberCommandBatchRequest(
>   File "/Users/artur/miniforge3/envs/ray/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 516, in init
>     field = _GetFieldByName(message_descriptor, field_nam [...]

2023-03-20 22:30 UTC, rkooo567 commented
@ArturNiederfahrenhorst you need to do bazel build //:ray_pkg