Remove return_info from reset() in pettingzoo_env.py
ray-project/ray pull request #33470
Opened 2023-03-20 20:28 UTC by elliottower

## Why are these changes needed?

The `return_info` reset() parameter has been removed from the PettingZoo API for a few weeks: https://github.com/Farama-Foundation/PettingZoo/pull/890

Render() also has not taken the  render_mode argument since October of 2022: https://github.com/Farama-Foundation/PettingZoo/commit/a74a933237a73de84239b088dd16c3067a55e441

Motivation is that current pettingzoo version cannot run with RLlib without modifying these files locally to get rid of return_info (have tested with both parallel and aec envs, see https://github.com/Farama-Foundation/PettingZoo/pull/899/)

## Related issue number

Closes #32889 

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-03-20 22:22 UTC, elliottower commented
The DCO check failed due to commits being not signed, but I have 
`git config --global commit.gpgsign true` and it says all of my commits are verified. Followed the rebase instructions from the error message. Now I see there are some other error messages but I can't figure out what the problem could be. Can someone help figure these out? 

My only thought is that maybe the internal tests are using an older version of gymnasium/pettingzoo which still has return_info. Edit: I found this file for rllib with version 1.22.1, whereas 1.22.3 is the most widely used and 1.22.4 is the current release as of today.

2023-03-27 14:49 UTC, elliottower commented
@ArturNiederfahrenhorst any chance you could help look this over? I would like to use RLlib with the most recent PettingZoo release but this makes it impossible without locally modifying it

2023-03-27 17:13 UTC, sven1977 approved these changes
Thanks for the fix @elliottower !

2023-03-27 17:14 UTC, avnishn reviewed
This looks good to me. Can you pull ray/master into your pr that way we can see the latest tests run?

2023-03-27 17:14 UTC, avnishn commented on rllib/env/wrappers/pettingzoo_env.py
> +        return self.env.render()
in the newest petting zoo version, are render modes no longer configurable? 

if so the whole pr looks p much looks good to me

2023-03-27 17:15 UTC, avnishn commented
oh and please run the linter on your changes ./ci/lint/format.sh

2023-03-27 17:18 UTC, sven1977 requested changes
Awesome PR. Still some minor fixes to do before we can merge this. See my comments.
Thanks again! :)

2023-03-27 17:23 UTC, avnishn commented on python/requirements/ml/requirements_rllib.txt
> +pettingzoo==1.22.4; python_version >= '3.7'
we should actually be able to bump the gym version with no problems here. Can you please do so @elliottower. I'd be happy to assist you in the upgrade if any issues come up.

2023-03-27 17:29 UTC, elliottower commented on python/requirements/ml/requirements_rllib.txt
> +pettingzoo==1.22.4; python_version >= '3.7'
Okay I'll change it to the most recent versions of all of them. Gymnasium had a release 28 late last week and 28.1 a day or two later with hotfixes. The update made a slight change to the Spaces, such as Sequence action space, which led to an error in the PettingZoo CI, which I've now fixed (previous spaces.Sequence() calls need to specify spaces.Sequence(stack=True) to get the same behavior as before). I've fixed that issue and the PettingZoo CI tests there are now passing. I did a search and found no uses of spaces.Sequence in Ray's repo so I think that should be fine, but I can do the pytests and try to find other potential issues with gymnasium 28.1. 

We are finishing up a PettingZoo release to fix this gym 28.1, which we are hoping to get out by the end of this week. I can run the tests with the master branch of PettingZoo to ensure they pass and start debugging errors with them now, and then once the full release is out then I can change the requirements to list the new version of PettingZoo.

2023-03-27 21:02 UTC, elliottower commented
> Awesome PR. Still some minor fixes to do before we can merge this. See my comments. Thanks again! :)

Could you help me diagnose the problems with the tests which are failing? It says 100 successful and 11 failing. 

I'm running the pytest for pettingzoo locally to try and see if I can find any issue but can't see anything wrong, not sure why my change would affect things like ci-build-pr/java

2023-03-27 21:09 UTC, elliottower commented
Also I'm trying to install the repository locally and having issues, I ran `pip install -e . ` in the `/python/` directory, and it seemed to work at first but then had this error later 
```
 Analyzing: 2 targets (49 packages loaded, 1520 targets configured)
    ERROR: /private/var/tmp/_bazel_elliottower/fd84858c11d357b636f50f21ff877190/external/bazel_tools/platforms/BUILD:89:6: in alias rule @bazel_tools//platforms:windows: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.
    ERROR: /private/var/tmp/_bazel_elliottower/fd84858c11d357b636f50f21ff877190/external/bazel_tools/platforms/BUILD:89:6: Analysis of target '@bazel_tools//platforms:windows' failed
    ERROR: /Users/elliottower/Documents/GitHub/ray/cpp/BUILD.bazel:6:10: While resolving toolchains for target //cpp:libray_api.so: invalid registered toolchain '@bazel_skylib//toolchains/unittest:cmd_toolchain':
    ERROR: Analysis of target '//cpp:ray_cpp_pkg' failed; build aborted:
    INFO: Elapsed time: 211.165s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully (55 packages loaded, 1741 targets configured)
    /Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/Users/elliottower/Documents/GitHub/ray/python/setup.py", line 768, in <module>
        setuptools.setup(
      File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
        super().run_command(command)
      File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
        super().run_command(command)
      File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/Users/elliottower/Documents/GitHub/ray/python/setup.py", line 756, in run
        return pip_run(self)
      File "/Users/elliottower/Documents/GitHub/ray/python/setup.py", line 657, in pip_run
        build(True, BUILD_JAVA, True)
      File "/Users/elliottower/Documents/GitHub/ray/python/setup.py", line 605, in build
        return bazel_invoke(
      File "/Users/elliottower/Documents/GitHub/ray/python/setup.py", line 372, in bazel_invoke
        result = invoker([cmd] + cmdline, *args, **kwargs)
      File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['bazel', 'build', '--verbose_failures', '--', '//:ray_pkg', '//cpp:ray_cpp_pkg']' returned non-zero exit status 1.
    [end of output]

```

2023-03-28 15:22 UTC, elliottower commented
@sven1977 @avnishn any ideas about how to fix the failing tests? Re ran them and it’s the same ones failing but they don’t appear to be related to my changes as far as I can see at least

2023-03-29 09:42 UTC, sven1977 commented
I think the only two tests that are of relevance are those that are failing with this error here:
```
Traceback (most recent call last):

ImportError:
 cannot import name 'BaseParallelWraper' from 
'pettingzoo.utils.wrappers' 
(/opt/miniconda/lib/python3.7/site-packages/pettingzoo/utils/wrappers/__init__.py)
```
It does seem like a supersuit/pettingzoo mismatch issue. ??

2023-03-29 13:29 UTC, elliottower commented
> I think the only two tests that are of relevance are those that are failing with this error here:
> 
> ```
> Traceback (most recent call last):
> 
> ImportError:
>  cannot import name 'BaseParallelWraper' from 
> 'pettingzoo.utils.wrappers' 
> (/opt/miniconda/lib/python3.7/site-packages/pettingzoo/utils/wrappers/__init__.py)
> ```
> 
> It does seem like a supersuit/pettingzoo mismatch issue. ??

Ah yeah this was a typo which was fixed in the most recent pettingzoo update, thanks for pointing it out. I’ll work on getting those issues fixed. Going to wait to finalize this until we release the next major release though.

2023-04-22 22:38 UTC, elliottower commented
Going to do a new PR because this one seems to have gotten messed up from a re-signing issue

2023-04-22 22:38 UTC, closed without merging