[serve] Add log file path to replica details
ray-project/ray pull request #33640
Opened 2023-03-23 18:42 UTC by zcin

## Why are these changes needed?

Add absolute file path to log files for each replica.
https://github.com/ray-project/ray/pull/33503#discussion_r1142835813

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-03-23 19:22 UTC, edoakes requested changes

2023-03-23 19:22 UTC, edoakes commented on python/ray/serve/_private/replica.py
> +                    log_file_path = handler.baseFilename
this logic should live in `logging_utils` along with the logic that sets the file path

2023-03-23 19:34 UTC, edoakes approved these changes

2023-03-23 19:34 UTC, edoakes commented on python/ray/serve/_private/logging_utils.py
> +def get_logger_file_path() -> Optional[str]:
```suggestion
def get_component_logger_file_path() -> Optional[str]:
```
nit: match name below

2023-03-23 19:38 UTC, zcin commented
May need to change file path from absolute to relative file path per @alanwguo's request

2023-03-23 19:45 UTC, edoakes commented
I think this should definitely be an absolutely path, what's the purpose of making it relative? I don't know what it would even be relative to...

2023-05-08 15:33 UTC, edoakes requested changes

2023-05-08 15:33 UTC, edoakes commented on python/ray/serve/schema.py
> +    log_file_path_id: Optional[str] = Field(
```suggestion
    log_file_path: Optional[str] = Field(
```

2023-05-08 16:59 UTC, edoakes approved these changes

2023-05-08 23:40 UTC, zcin commented
@edoakes Tests look good, ready for merge

2023-05-09 15:38 UTC, merged