Improve the serialization error for tasks, actors and ray.put
ray-project/ray pull request #33660
Opened 2023-03-24 04:11 UTC by jjyao

## Why are these changes needed?
When ray.put, passing value as task/actor argument, task/actor definition have the serialization error, include the message from `ray.util.inspect_serializability` to help users debug the issue.

Example:

```
>>> ray.put(socket.socket())
Traceback (most recent call last):
  File "/Users/jjyao/Workspace/ray1/python/ray/_private/worker.py", line 667, in put_object
    serialized_value = self.get_serialization_context().serialize(value)
  File "/Users/jjyao/Workspace/ray1/python/ray/_private/serialization.py", line 450, in serialize
    return self._serialize_to_msgpack(value)
  File "/Users/jjyao/Workspace/ray1/python/ray/_private/serialization.py", line 428, in _serialize_to_msgpack
    pickle5_serialized_object = self._serialize_to_pickle5(
  File "/Users/jjyao/Workspace/ray1/python/ray/_private/serialization.py", line 390, in _serialize_to_pickle5
    raise e
  File "/Users/jjyao/Workspace/ray1/python/ray/_private/serialization.py", line 385, in _serialize_to_pickle5
    inband = pickle.dumps(
  File "/Users/jjyao/Workspace/ray1/python/ray/cloudpickle/cloudpickle_fast.py", line 88, in dumps
    cp.dump(obj)
  File "/Users/jjyao/Workspace/ray1/python/ray/cloudpickle/cloudpickle_fast.py", line 733, in dump
    return Pickler.dump(self, obj)
  File "/opt/anaconda3/envs/ray/lib/python3.8/socket.py", line 272, in __getstate__
    raise TypeError(f"cannot pickle {self.__class__.__name__!r} object")
TypeError: cannot pickle 'socket' object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jjyao/Workspace/ray1/python/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/jjyao/Workspace/ray1/python/ray/_private/worker.py", line 2561, in put
    object_ref = worker.put_object(value, owner_address=serialize_owner_address)
  File "/Users/jjyao/Workspace/ray1/python/ray/_private/worker.py", line 678, in put_object
    raise TypeError(msg) from e
TypeError: Could not serialize the put value <socket.socket fd=52, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>:
================================================================================
Checking Serializability of <socket.socket fd=52, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
================================================================================
!!! FAIL serialization: cannot pickle 'socket' object
    Serializing '_check_sendfile_params' <bound method socket._check_sendfile_params of <socket.socket fd=52, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>>...
    !!! FAIL serialization: cannot pickle 'socket' object
        Serializing '__func__' <function socket._check_sendfile_params at 0x7ff710359820>...
    WARNING: Did not find non-serializable object in <bound method socket._check_sendfile_params of <socket.socket fd=52, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>>. This may be an oversight.
================================================================================
Variable: 

	FailTuple(_check_sendfile_params [obj=<bound method socket._check_sendfile_params of <socket.socket fd=52, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>>, parent=<socket.socket fd=52, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>])

was found to be non-serializable. There may be multiple other undetected variables that were non-serializable. 
Consider either removing the instantiation/imports of these variables or moving the instantiation into the scope of the function/class. 
If you have any suggestions on how to improve this error message, please reach out to the Ray developers on github.com/ray-project/ray/issues/
================================================================================
Check https://docs.ray.io/en/master/ray-core/objects/serialization.html#troubleshooting for more information.
```

## Related issue number
Closes #31074

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-03-25 06:03 UTC, ericl commented on python/ray/tests/test_basic_5.py
> +        g.remote(s)
```suggestion
        g.remote()
```

2023-03-25 06:05 UTC, ericl requested changes
Nice! (from the issue): Could you also add tests for Tune (trainable func), Train (pytorch train func), Serve (deployment class), and Data (map_batches udf)? These libraries use custom serializers and may break the above error message.

2023-03-28 04:44 UTC, c21 commented on python/ray/data/tests/test_dataset_map.py
> +def test_nonserializable_map_batches(shutdown_only):
Data change looks good to me.

2023-03-28 04:47 UTC, ericl approved these changes

2023-03-28 04:57 UTC, sihanwang41 approved these changes
awesome

2023-03-29 19:17 UTC, zhe-thoughts approved these changes
Approved for merging to master

This PR changes many places, but looks like it's low risk (only touching error messages)

2023-03-29 19:20 UTC, merged