[Core] extend conda runtime_env to allow for using mamba as per PR 33596
ray-project/ray pull request #33758
Opened 2023-03-27 20:20 UTC by cosnicolaou

This is a starting point PR to find a means of allowing an alternative to conda to be used for creating environments. As per PR #33596 conda can be slow when building non-trivial environments. This PR allows for mamba to be used instead. It takes the form of extending the runtime_env's 'conda' dictionary to allow for an alternative executable to specified for creating environments:

```
runtime_env = {
        "conda": {"create_env_exe": "mamba", "dependencies": ["pip", {"pip": ["pip-install-test==0.5"]}]}
    }
```

The only functions that are altered are ```create_conda_env_if_needed``` to accept the name of exe to use rather than
hardcoding "conda" and CondaPlugin to obtain the executable name from the runtime_env.

## Why are these changes needed?

See PR #33596.

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-05-10 07:32 UTC, Dessix requested changes
I love this in concept but `micromamba` is probably a better move since the conda+mamba installation path is not recommended by the mamba project developers. Perhaps parameterizing `mamba_exists` is in order?

2023-05-10 15:57 UTC, cosnicolaou commented
My intention is to use mamba, or micromamba, instead of conda not in conjunction with it. With this change, the ray.init environment would specify which tool to use rather than having it be hardwired to conda as it is today.

2023-06-10 09:35 UTC, Dessix commented
This would be a rather nice improvement, considering how much faster Mamba runs; I would say this should be kept open for continuation.

2023-07-15 02:49 UTC, Dessix commented
This is still a worthwhile change; can any contributors take a look?

2023-09-17 06:48 UTC, Dessix commented
@jjyao So, about that...

2025-01-19 18:01 UTC, closed without merging