[core] Set OMP_NUM_THREADS to 1 if unset when starting python worker
ray-project/ray pull request #33902
Opened 2023-03-30 00:38 UTC by rickyyx

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-03-30 14:33 UTC, rkooo567 commented
We will try if we can lazy import numpy first. If we can do this, we may not need this change.

2023-03-30 14:35 UTC, rkooo567 commented
Based on the quick research, it seems like we can just not import numpy, and we will see if that approach will work before doing this.

Not importing numpy will also improve the worker startup time

2023-03-30 21:14 UTC, rickyyx commented on python/ray/_private/utils.py
> -def random_string():
removed this since I don't think we are using this anymore in the codebase.

2023-03-30 22:38 UTC, wuisawesome requested changes

2023-03-30 22:38 UTC, wuisawesome commented on python/ray/autoscaler/_private/load_metrics.py
> +        import numpy as np
Can you just remove the `np.` parts of these `np.mean`, `np.min`, and `np.max` so that we can just delete this instead?

2023-03-30 22:59 UTC, ericl approved these changes

2023-03-30 23:23 UTC, rkooo567 approved these changes
awesome! exiced to see this change :)

2023-03-30 23:58 UTC, pcmoritz commented
This is awesome!

2023-03-31 08:42 UTC, rkooo567 commented
Seems to be ready to be merged. I doubt java failure is actually related to this PR.

cc @zhe-thoughts this is the critical fix for V2 stack migration.
'
Also @rickyyx can you run the release test in V2 stack to see if the perf is recovered?

2023-03-31 16:45 UTC, rickyyx commented
Running into issues with running tests on v2.... asking help.

2023-03-31 16:58 UTC, zhe-thoughts commented
Will approve once @rickyyx resolves the above v2 issue

2023-03-31 18:50 UTC, rickyyx commented
I think running on v2 is still slow even with the PR ([cluster](https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_ajv7ks91hr9hdgfrj38i3miwpv)). And I was not able to start clusters on v1 to collect signals (I was trying to run the many_actors on v1 with OMP_NUM_THREADS not set in `ray start`) 

I did run the worker startup benchmark on v2 ( and I think when the file system is not the bottleneck (importing files), it does seem to improve the metrics). Highlighting things >= 10% change. 
<img width="971" alt="image" src="https://user-images.githubusercontent.com/11676094/229204491-34edb805-8c76-4f66-bf52-a1e2326a77c7.png">


The 90% regression seems to be just variance (the values are p50) and here are the values for master vs PR:
```
## Master
    "seconds_to_cold_start_64_tasks-no_import-without_gpu-single_node-without_runtime_env-64_CPU_64_GPU_cluster": {
        "measurements": [
            0.8435616493225098,
            0.8441426753997803,
            0.13407254219055176,
            0.09459686279296875,
            0.09999394416809082
        ],
        "p50": 0.13407254219055176
    },


## PR 
    "seconds_to_cold_start_64_tasks-no_import-without_gpu-single_node-without_runtime_env-64_CPU_64_GPU_cluster": {
        "measurements": [
            0.7273907661437988,
            0.26421618461608887,
            0.18021559715270996,
            0.33435678482055664,
            0.1224985122680664
        ],
        "p50": 0.26421618461608887
    },

```

I am still trying to see if I can run this & master on V1 stack w/o `OMP_NUM_THREADS` set, but we could probably merge it as well and see the result when v2 stack is fixed.

2023-03-31 19:07 UTC, wuisawesome approved these changes
Unsure why we sometimes use `statistics.mean` and other times do our own thing but lgtm.

2023-03-31 19:08 UTC, zhe-thoughts approved these changes

2023-03-31 20:05 UTC, rickyyx commented
Seems hard to verify this on V1 stack - (not easy to get a cluster with OMP_NUM_THREADS not set, which is the case this PR improves) 

Guess we could go ahead with the merge if the results above look good?

2023-03-31 20:50 UTC, rickyyx commented
> Unsure why we sometimes use `statistics.mean` and other times do our own thing but lgtm.

Ah, right. Fixed the nit.

2023-03-31 23:30 UTC, scv119 approved these changes
awesome!

2023-03-31 23:31 UTC, merged