Can ci errors
ray-project/ray pull request #34057
Opened 2023-04-04 18:19 UTC by can-anyscale

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-04-12 19:57 UTC, aslonnie approved these changes

2023-04-12 21:32 UTC, scv119 approved these changes

2023-04-13 07:42 UTC, krfricke requested changes
I'm not sure if we need most of the refactoring here.

We already expose exit codes that are much more descriptive than here, e.g.:

```
    # Hard infra errors (non-retryable)
    CLI_ERROR = 10
    CONFIG_ERROR = 11
    SETUP_ERROR = 12
    CLUSTER_RESOURCE_ERROR = 13
    CLUSTER_ENV_BUILD_ERROR = 14
    CLUSTER_STARTUP_ERROR = 15
    LOCAL_ENV_SETUP_ERROR = 16
    REMOTE_ENV_SETUP_ERROR = 17
    FETCH_RESULT_ERROR = 18
    ANYSCALE_ERROR = 19

    # Infra timeouts (retryable)
    RAY_WHEELS_TIMEOUT = 30
    CLUSTER_ENV_BUILD_TIMEOUT = 31
    CLUSTER_STARTUP_TIMEOUT = 32
    CLUSTER_WAIT_TIMEOUT = 33
```

Wouldn't it be enough to set 

```
- exit_status: 30
  limit: 3
- exit_status: 31
  limit: 3
```

etc?

I'd like to have clarity on this before merging so requesting changes for now

2023-04-13 07:42 UTC, krfricke commented on release/ray_release/buildkite/step.py
> +
Should this just be in `DEFAULT_STEP_TEMPLATE`?

2023-04-13 07:48 UTC, krfricke reviewed
Actually, I think the retry logic exists in a similar matter in `run_release_test.sh` - only that we we retry there in the same job and not in a repeated job.

Would it make sense to adjust that script to return a "retry" or "non-retry" exit code to buildkite? That way we can retain the existing exit codes in the python script and move buildkite-specific logic into the buildkite wrapper.

2023-04-13 14:26 UTC, can-anyscale commented
@krfricke ah nice, I didn't notice retry logic exists in the wrapper as well. I still kind of like a different result.status (currently timeout, error, infra_error, infra_timeout) for jobs that are retried, as they are stored in databricks, for further analysis and tracking purpose though. So  I can keep most of the logic to update result.status and result.last_logs (lot of refactoring here is to capture this for infra-error cases), keep the existing return code the same and move buildkite return code/retry to the wrapper. How do you like that? Or is it easier to understand to keep the retry logic in the same place as the computation of result.status.

2023-04-13 16:31 UTC, can-anyscale commented
@krfricke: awesome, I'll make sure to update the dashboard too!

2023-04-13 20:40 UTC, can-anyscale commented
Good for review now. Re-tested as well: https://buildkite.com/ray-project/release-tests-pr/builds/34922. Thanks for reviewing @krfricke

2023-04-13 23:41 UTC, ollie-iterators commented
The documentation test could be fixed by merging in recent changes.

2023-04-17 13:28 UTC, krfricke approved these changes
LG! Thanks for the revision.

Ping me to merge

2023-04-17 16:20 UTC, can-anyscale commented on release/run_release_test.sh
> +if [ "$REASON" == "infra error" ] || [ "$REASON" == "infra timeout" ]; then
they are without underscore; obtained from the reason() function on top of this file ;)

2023-04-17 17:37 UTC, merged