[Doc] [runtime env] Clarify conditions for local `pip` and `conda` requirements files
ray-project/ray pull request #34071
Opened 2023-04-04 21:15 UTC by architkulkarni

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-04-05 19:13 UTC, akshay-anyscale approved these changes

2023-04-05 20:04 UTC, sihanwang41 approved these changes

2023-04-11 22:13 UTC, architkulkarni commented
Hi @angelinalg, do you mind reviewing this on behalf of ray-docs when you get a chance?

2023-04-11 22:18 UTC, angelinalg commented on doc/source/ray-core/handling-dependencies.rst
> +  Furthermore, referencing local files `within` a `requirements.txt` file is not supported (e.g. ``-r ./my-laptop/more-requirements.txt``, ``./my-pkg.whl``).
```suggestion
  Furthermore, referencing local files `within` a `requirements.txt` file is not supported (e.g., ``-r ./my-laptop/more-requirements.txt``, ``./my-pkg.whl``).
```

2023-04-11 22:24 UTC, angelinalg requested changes
LGTM

2023-04-11 22:27 UTC, architkulkarni commented
@angelinalg thanks, updated!

2023-04-17 19:31 UTC, architkulkarni commented
@angelinalg would you mind approving this PR? It still has "changes requested"

2023-04-26 16:02 UTC, angelinalg approved these changes
LGTM

2023-04-28 21:35 UTC, merged