[docs] removed line numbers and fixed file name summary_model.py
ray-project/ray pull request #34617
Opened 2023-04-20 05:58 UTC by angelinalg

## Why are these changes needed?

Copy and paste button was including line numbers in 3 code examples, which is a bad user experience. 
Fixed error with filename. The command line instructions said `python model.py` but it should be `python summary_model.py`.

This addresses some issues in GH issue #34481, but not all of them.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-04-20 16:26 UTC, architkulkarni approved these changes

2023-04-20 16:31 UTC, architkulkarni requested changes
Actually it looks like this removes the line numbers altogether from the snippet altogether, rather than just making it so they aren't copied when the button is clicked. We refer to the line numbers in the snippet later on, so I think we either need the line numbers to be displayed or we need to remove the references to line numbers.

@shrekris-anyscale if I remember correctly, you had figured out some way of displaying the line numbers without them being copied, right?

2023-04-20 17:49 UTC, shrekris-anyscale commented
> @shrekris-anyscale if I remember correctly, you had figured out some way of displaying the line numbers without them being copied, right?

I don't think I found a way to make the clipboard stop copying line numbers. If you manually highlight the text, it doesn't copy the numbers.

2023-04-20 18:29 UTC, akshay-anyscale approved these changes

2023-04-20 18:49 UTC, angelinalg commented
Great catch, @architkulkarni! Thank you.

2023-04-20 19:11 UTC, angelinalg commented
@maxpumperla, does the Sphinx or plugin upgrades give us the ability to show the line numbers without compromising the copy-paste button functionality?

2023-04-21 16:29 UTC, architkulkarni approved these changes

2023-04-21 16:48 UTC, edoakes approved these changes

2023-04-21 16:48 UTC, merged