[Core] Remove multiple core workers in one process 2/n
ray-project/ray pull request #34942
Opened 2023-05-02 05:55 UTC by jjyao

## Why are these changes needed?
Remove some legacy code related to multiple core workers in one process since we now no longer support it.

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-05-02 06:43 UTC, cadedaniel approved these changes
this is awesome, makes my life easier :)

2023-05-02 06:43 UTC, cadedaniel commented on src/ray/raylet/worker_pool.cc
> -      // This is possible because a Java worker process may hold multiple workers.
nit: improve comment to say when this is possible? suggestion below which may not be correct
> This is possible if the idle_worker has been killed but hasn't been removed from the idle list yet.

2023-05-02 06:44 UTC, cadedaniel requested changes
ah meant to only comment. tests still running

2023-05-02 16:06 UTC, jjyao commented
Failed tests are unrelated.

2023-05-02 16:14 UTC, cadedaniel approved these changes

2023-05-02 16:24 UTC, merged

2023-05-06 03:04 UTC, jovany-wang commented
Nice PR!