[CI] Add env var suggestion for common call ray start fixture error on MacOS
ray-project/ray pull request #35226
Opened 2023-05-10 19:40 UTC by architkulkarni

## Why are these changes needed?
The `call_ray_start` fixture was not correctly returning the GCS address when run locally on MacOS, causing any tests with that fixture to fail.  

The reason is that the address is parsed from the `ray start --head` output, but the "`To add another node to this Ray cluster, run ray start --address=<GCS address>`" line is not printed on MacOS because multi-node clusters are disabled by default on MacOS.

To fix this, you need to enable multinode clusters before running the test.  This environment variable is set in Buildkite CI, but Mac developers might not have it set on their local machine.  This PR prints a suggestion to set the environment variable when this failure is encountered.

## Related issue number
Closes https://github.com/ray-project/ray/issues/35229

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-05-10 19:50 UTC, wuisawesome commented on python/ray/tests/conftest.py
> +    monkeypatch.setenv(ray_constants.ENABLE_RAY_CLUSTERS_ENV_VAR, "1")
Can we set the env var on line 482 instead of introducing a monkey patch here?

2023-05-10 19:50 UTC, wuisawesome requested changes
let's avoid monkeypatching if possible

2023-05-10 20:06 UTC, architkulkarni commented
@wuisawesome It's not a monkeypatch, it actually sets the env var for the lifetime of the fixture.  It's a pytest fixture that makes sure the global env is untouched.

2023-05-10 20:07 UTC, architkulkarni commented
Or do you mean to set it in the command only? like `ENABLE_CLUSTERS=1 ray start ...`

2023-05-10 23:03 UTC, jjyao commented
We have `    - export RAY_ENABLE_WINDOWS_OR_OSX_CLUSTER=1` in pipeline.macos.yaml, is it not working?

2023-05-10 23:08 UTC, architkulkarni commented
@jjyao It is working in Buildkite CI.  This PR only affects developers on Mac who are running tests locally.  Currently the error message is hard to debug.

2023-05-10 23:12 UTC, jjyao commented
Oh, I see. If you run the test locally via bazel, it should have the env var set. We have `test --test_env=RAY_ENABLE_WINDOWS_OR_OSX_CLUSTER="1"` in `.bazelrc`.

2023-05-10 23:35 UTC, architkulkarni commented
Sure.  I and others use `pytest -vs test_job_manager.py::my_specific_unit_test`, not sure if there's a convenient way to do that in bazel.

2023-05-10 23:37 UTC, jjyao commented
Yea, something like `bazel test //python/ray/tests:test_ray_init`. I think this is the preferred way since we used bazel in CI as well. If we use pytest directly then we lose whatever inside `.bazelrc`

2023-05-10 23:42 UTC, architkulkarni commented
Oh but how do you run a specific function or class within the `.py` test file?  

If bazel is the best way, I can update https://docs.ray.io/en/latest/ray-contribute/getting-involved.html#testing-for-python-development and get rid of the references to pytest

2023-05-10 23:55 UTC, jjyao commented
For that you can do `bazel test //python/ray/tests:test_ray_init --test_arg=-k "test_xxx"` but we also need to change the main function of the test script to 
```
if __name__ == "__main__":
    import pytest
    sys.exit(pytest.main(["-v", __file__] + sys.argv[1:]))
```

in order to pass through the `-k` stuff.

2023-05-11 14:32 UTC, wuisawesome commented
I'm saying `ray_context` has code like this 

```
    env = None
    if isinstance(parameter, dict):
        if "env" in parameter:
            env = {**os.environ, **parameter.get("env")}
```

Shouldn't we just make that 

    env = {"RAY_ENABLE_WINDOWS_OR_OSX_CLUSTER": 1}
    if isinstance(parameter, dict):
        if "env" in parameter:
            env = {**os.environ, **parameter.get("env")}.update(env)

2023-05-11 20:34 UTC, architkulkarni commented
Updated the PR to just print the warning.  It's a small one time cost for developers to enable the env var locally if they want to continue to use `pytest` directly with all of its CLI features instead of using `bazel`. This way we also don't have to worry about the CI env set in Buildkite being overwritten in a random fixture (could see it being hard to debug in the future).

2023-05-17 18:06 UTC, wuisawesome approved these changes

2023-05-24 18:54 UTC, wuisawesome approved these changes

2023-06-05 18:24 UTC, architkulkarni commented
`//python/ray/tune:test_controller_resources_integration                  FAILED in 3 out of 3 in 315.5s`
failure unrelated

Windows `test_scheduling*`, `test_basic_4*`, `test_task_events` unrelated

2023-06-05 18:25 UTC, merged

2023-06-06 02:05 UTC, vitsai commented
Unfortunately windows://python/ray/tests:test_basic_4_client_mode and windows://python/ray/tests:test_basic_4 both started failing with this commit, so reverting for now.