Separate runtime env agent from dashboard agent
ray-project/ray pull request #35292
Opened 2023-05-12 14:56 UTC by MisterLin1995

## Why are these changes needed?

These changes are part of the work to achieve the goal of separating runtime env agent from dashboard agent described in #30528. This PR does the following the things:
1. Move runtime env agent code files to ray/python/_private/runtime_env/runtime_env_agent
2. Add a runtime_env_agent_manager in raylet's node manager to start and monitor runtime env agent process.
3. Make raylet restart dashboard agent process when it dies
4. Keep raylet fate-share with runtime env agent process
5. UT changes to match the new behavior
6. Other works to start / stop runtime env agent processes when using ray cluster
7. Other works to pass runtime env agent grpc port to different part of ray (dashboard / state api / proxy server)

## Related issue number

 #30528

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-05-13 07:07 UTC, iycheng commented
Thanks @MisterLin1995 this PR is giant. I'll find some time next week reviewing this and might need to schedule a sync meeting for how to get it into the code base. Maybe we'll need to split it in someway.

2023-06-02 22:04 UTC, iycheng requested changes
Thanks for the work. I reviewed in high level and feel the goal of the work is clean, but just too big and we should think about how to deliver it incrementally.

Besides that, I do have some architecture questions.

- We should keep runtime env agent only visible to the raylet. Other module shouldn't see that. it might see other modules, though.
- Could the registration be more simple? If it's a module in raylet, maybe we should only pass the path of the main to raylet and raylet should be able to construct the cmd by itself to reduce redundant informations.

As for split, we probably can
- Refactor the agent manager and make it manage the dashboard agent.
- Move runtime env agent to the new place and make the old dashboard agent use that. In the mean time, make the runtime env agent able to start.
- Write runtime env agent manager in cpp and make it able to start the runtime env agent.
- Integrate it with raylet to replace the old ones and don't start runtime env agent in the old one by default.

2023-06-03 05:02 UTC, MisterLin1995 commented on dashboard/datacenter.py
> +                runtimeEnvGrpcPort=int(runtime_env_grpc_port),
Well, it's just the runtime env agent is directly called by other components other than Raylet, such as the client-server and state manager. Maybe we also need to provide RPC APIs in Raylet for these components to hide runtime env agent from them.

2023-06-05 02:53 UTC, MisterLin1995 commented
> * Refactor the agent manager and make it manage the dashboard agent.
I'm not quite sure about what's involved in this part, since it's already managing the dashboard agent.

> In the mean time, make the runtime env agent able to start.
Does this mean making the moved runtime env can be start both as module and as a separate process?

2023-06-05 21:49 UTC, iycheng commented on dashboard/datacenter.py
> +                runtimeEnvGrpcPort=int(runtime_env_grpc_port),
Hmmm, I see. This is pretty interesting. Do you know where is the entry point for that?

2023-06-05 21:53 UTC, iycheng commented
> > * Refactor the agent manager and make it manage the dashboard agent.
> 
> I'm not quite sure about what's involved in this part, since it's already managing the dashboard agent.
> 

I saw you update `class AgentManager : public rpc::AgentManagerServiceHandler {`. I think maybe we just have a PR make this manager more general? It's supposed to manage runtime env agent in the future I think?


> > In the mean time, make the runtime env agent able to start.
> 
> Does this mean making the moved runtime env can be start both as module and as a separate process?

I'm thinking that, the implementation is rpc unrelated, the dashboard agent's code is to expose the implementation and the new runtime env agent is also doing the same thing. This I mean the later one.

2023-06-08 23:43 UTC, iycheng commented on src/ray/raylet/agent_manager.cc
> +      delay_executor_([this]() { StartAgent(); }, /*ms*/ 10);
Please log here too.

2023-06-08 23:51 UTC, iycheng commented on src/ray/protobuf/runtime_env_agent_manager.proto
> +  int32 agent_port = 2;
Do we use 0 for the port?

2023-06-08 23:52 UTC, iycheng commented on src/ray/protobuf/runtime_env_agent_manager.proto
> +service RuntimeEnvAgentManagerService {
is it possible for the runtime env agent just use the same protobuf as the dashboard agent

2023-08-11 21:21 UTC, closed without merging