[Autoscaler] Add friendlier status message upon "No cluster status"
ray-project/ray pull request #35412
Opened 2023-05-16 22:52 UTC by architkulkarni

## Why are these changes needed?
The message "No cluster status" upon running `ray status` is likely due to a race condition where Ray starts before the autoscaler is started (see https://github.com/ray-project/ray/issues/35017#issuecomment-1535517998).  Until this is fixed, we make the error message a bit friendlier by adding `It may take a few seconds for the Ray autoscaler to start up.`. (If this is inaccurate, we shouldn't merge this PR)

## Related issue number
Related issue: #35017 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-05-17 18:09 UTC, wuisawesome requested changes
Let's avoid using the word "autoscaler" here since it's a confusing implementation detail (this feature also works for local and statically sized clusters). 

I think there's actually a very near term future with the implementation of this doesn't have to rely on the autoscaler.

2023-05-17 18:09 UTC, wuisawesome commented on python/ray/autoscaler/_private/commands.py
> +        status = "No cluster status. It may take a few seconds for the Ray autoscaler to start up."
```suggestion
        status = "No cluster status. It may take a few seconds for the Ray internal services to start up."
```

2023-05-17 18:09 UTC, wuisawesome requested changes
Let's avoid using the word "autoscaler" here since it's a confusing implementation detail (this feature also works for local and statically sized clusters). 

I think there's actually a very near term future with the implementation of this doesn't have to rely on the autoscaler.

2023-05-17 18:14 UTC, wuisawesome approved these changes

2023-06-08 22:16 UTC, architkulkarni commented
windows test_basic_4 was failing on master, unrelated
test_gcs_fault_tolerance unrelated
//doc:source/rllib/doc_code/catalog_guide  unrelated
//python/ray/data:doctest  unrelated
//rllib:learning_tests_two_step_game_qmix   unrelated

2023-06-08 22:16 UTC, merged