[core] GCS verison Auth
ray-project/ray pull request #36073
Opened 2023-06-05 15:47 UTC by vitsai

Add AuthType template parameter to authenticate against cluster token.

(Moved authentication logic over from #35014 to make the PR smaller.)

## Why are these changes needed?

## Related issue number

#34763

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-07-01 00:56 UTC, vitsai commented
cc: @bveeramani release-blocking PR

2023-07-03 17:20 UTC, scv119 requested changes
also the merge conflict need to be fixed.

2023-07-03 17:20 UTC, scv119 commented on src/ray/gcs/gcs_client/accessor.h
> +  NodeInfoAccessor(GcsClient *client_impl);
huh, why remove explicit?

2023-07-03 17:20 UTC, scv119 commented on src/ray/gcs/gcs_client/gcs_client.h
> +  /// \param cluster_id Optional cluster ID to provide to the client.
should we add comments somewhere on expected behavior of setting cluster_id to Nil?

2023-07-03 17:20 UTC, scv119 commented on src/ray/raylet/main.cc
> +  auto f = std::async(std::launch::async, [&]() {
any reason making this change?

2023-07-03 17:20 UTC, scv119 commented on src/ray/rpc/client_call.h
> +  template <class GrpcService, class Request, class Reply, bool Insecure>
super nit: Insecure -> VerifyClusterId

2023-07-10 20:54 UTC, closed without merging