[Data] fix `ray.data.from_huggingface` feature preprocessing
ray-project/ray pull request #36398
Opened 2023-06-14 00:08 UTC by Rohan138

## Why are these changes needed?

## Related issue number

Fixes #36296

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-06-14 22:37 UTC, bveeramani commented
Thanks! Think doctest is failing, but I'll fix it tomorrow.

2023-06-14 22:43 UTC, amogkam requested changes
Thanks @Rohan138. Looks like this is a bug that's coming from the Huggingface side. Accessing the dataset ( `hf_ds_arrow[:]`) should apply their transformations accordingly. 

Can you make a reproduction using HF Datasets directly and file a bug on `datasets` github?

2023-06-14 22:43 UTC, amogkam commented on python/ray/data/read_api.py
> +        ray_ds = ray_ds.map_batches(hf_ds_arrow.features.decode_batch)
do all Huggingface Datasets have a `features` attribute? Do the features always have a `decode_batch` attribute? If so, are they always guaranteed to be a function?

2023-07-18 19:14 UTC, bveeramani commented
Closing because I think we've found a workaround (?). Feel free to re-open

2023-07-18 19:14 UTC, closed without merging