[ci] remove is_automated_build in setup.py
ray-project/ray pull request #36547
Opened 2023-06-18 19:07 UTC by aslonnie

No place in our CI pipeline triggers that condition today.

2023-06-18 19:08 UTC, aslonnie commented
I directly throw an exception here in the code:
https://github.com/ray-project/ray/pull/36546/files

all wheel build/testing succeeds:
https://buildkite.com/ray-project/oss-ci-build-pr/builds/25877#_

I also searched over the code base and found no env var of saying `IS_AUTOMATED_BUILD`

2023-06-18 19:12 UTC, aslonnie commented
cc @vnlitvinov

2023-06-18 19:13 UTC, aslonnie commented
the flag is added in https://github.com/ray-project/ray/pull/17575 probably for upstreaming patches in https://github.com/krfricke/ray-packages-feedstock/tree/ray-1.5.1/recipe/patches 

but it is not tested anywhere on our own CI, and we have no idea if it is still working at all.

2023-06-18 19:25 UTC, aslonnie commented
and windows wheel building seems fine without it: https://buildkite.com/ray-project/oss-ci-build-pr/builds/25877#0188cfb5-2554-4192-85ea-dca2d837cd55/6885-8590

2023-06-18 19:26 UTC, aslonnie commented
cc @jovany-wang too

2023-06-20 16:52 UTC, can-anyscale reviewed
I'll wait a bit for the pinged folks to raise any concerns, otherwise I'll accept it tomorrow

2023-06-21 07:56 UTC, vnlitvinov commented
@aslonnie @can-anyscale `IS_AUTOMATED_BUILD` is used in conda-forge packaging Ray:
https://github.com/conda-forge/ray-packages-feedstock/blob/main/recipe/build-core.bat#L3

I think that if you remove that, it has high chance of breaking the build of conda package 😢 

cc @h-vetinari

2023-06-22 00:10 UTC, aslonnie commented
> it has high chance of breaking the build of conda package

we are making changes to our CI systems, and this `IS_AUTOMATED_BUILD` is not being tested anywhere. I fear that it will get broken on a future release anyways.

also it seems that it is only used in windows?

2023-06-22 00:52 UTC, h-vetinari commented
How many symlinks are we talking about here? If it's a small(-ish) number we can do this by hand (or carry a revert of this PR as a patch).

2023-06-22 02:31 UTC, aslonnie commented
> How many symlinks are we talking about here?

````
 35119148      0 lrwxrwxrwx   1 ubuntu   ubuntu         20 Mar 18 02:05 ./scripts/format.sh -> ../ci/lint/format.sh
 35095234      0 lrwxrwxrwx   1 ubuntu   ubuntu         24 Apr 10 16:53 ./release/workspace_templates -> ../doc/source/templates/
 35118750      4 lrwxrwxrwx   1 ubuntu   ubuntu         72 Jun  8 22:16 ./release/air_examples/opt_deepspeed_batch_inference/opt_deepspeed_batch_inference.ipynb -> ../../../doc/source/ray-air/examples/opt_deepspeed_batch_inference.ipynb
 35118753      0 lrwxrwxrwx   1 ubuntu   ubuntu         29 Jun  8 22:16 ./release/air_examples/opt_deepspeed_batch_inference/test_myst_doc.py -> ../../../doc/test_myst_doc.py
 35118724      4 lrwxrwxrwx   1 ubuntu   ubuntu         74 Jun  8 22:16 ./release/air_examples/dolly_v2_lightning_fsdp_finetuning/lightning-llm-finetuning-7b.ipynb -> ../../../doc/source/ray-air/examples/dolly_lightning_fsdp_finetuning.ipynb
 35118725      0 lrwxrwxrwx   1 ubuntu   ubuntu         29 Jun  8 22:16 ./release/air_examples/dolly_v2_lightning_fsdp_finetuning/test_myst_doc.py -> ../../../doc/test_myst_doc.py
 35116926      0 lrwxrwxrwx   1 ubuntu   ubuntu         43 Mar 18 02:05 ./release/air_examples/dreambooth/dreambooth -> ../../../python/ray/air/examples/dreambooth
 35116933      4 lrwxrwxrwx   1 ubuntu   ubuntu         69 Mar 18 02:05 ./release/air_examples/gptj_deepspeed_finetuning/gptj_deepspeed_fine_tuning.ipynb -> ../../../doc/source/ray-air/examples/gptj_deepspeed_fine_tuning.ipynb
 35114883      4 lrwxrwxrwx   1 ubuntu   ubuntu         64 Mar 18 02:05 ./python/ray/air/examples/rl_offline_example.ipynb -> ../../../../doc/source/ray-air/examples/rl_offline_example.ipynb
 35114882      4 lrwxrwxrwx   1 ubuntu   ubuntu         62 Mar 18 02:05 ./python/ray/air/examples/lightgbm_example.ipynb -> ../../../../doc/source/ray-air/examples/lightgbm_example.ipynb
 35114888      4 lrwxrwxrwx   1 ubuntu   ubuntu         61 Mar 18 02:05 ./python/ray/air/examples/upload_to_wandb.ipynb -> ../../../../doc/source/ray-air/examples/upload_to_wandb.ipynb
 35114885      4 lrwxrwxrwx   1 ubuntu   ubuntu         64 Mar 18 02:05 ./python/ray/air/examples/rl_serving_example.ipynb -> ../../../../doc/source/ray-air/examples/rl_serving_example.ipynb
 35114887      4 lrwxrwxrwx   1 ubuntu   ubuntu         64 Mar 18 02:05 ./python/ray/air/examples/upload_to_comet_ml.ipynb -> ../../../../doc/source/ray-air/examples/upload_to_comet_ml.ipynb
 35114884      4 lrwxrwxrwx   1 ubuntu   ubuntu         63 Mar 18 02:05 ./python/ray/air/examples/rl_online_example.ipynb -> ../../../../doc/source/ray-air/examples/rl_online_example.ipynb
 35114889      4 lrwxrwxrwx   1 ubuntu   ubuntu         61 Mar 18 02:05 ./python/ray/air/examples/xgboost_example.ipynb -> ../../../../doc/source/ray-air/examples/xgboost_example.ipynb
 35114886      4 lrwxrwxrwx   1 ubuntu   ubuntu         61 Mar 18 02:05 ./python/ray/air/examples/sklearn_example.ipynb -> ../../../../doc/source/ray-air/examples/sklearn_example.ipynb
 35115142      0 lrwxrwxrwx   1 ubuntu   ubuntu         15 Mar 18 02:05 ./python/ray/dashboard -> ../../dashboard
 35115500      0 lrwxrwxrwx   1 ubuntu   ubuntu         11 Mar 18 02:05 ./python/ray/rllib -> ../../rllib
 34836605      4 lrwxrwxrwx   1 root     root          120 Jun 18 19:25 ./bazel-bin -> /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/bin
 35113494      4 lrwxrwxrwx   1 ubuntu   ubuntu         79 Mar 18 02:05 ./doc/source/ray-air/examples/images/dreambooth_example.png -> ../../../../../python/ray/air/examples/dreambooth/images/dreambooth_example.png
 35113495      4 lrwxrwxrwx   1 ubuntu   ubuntu         80 Mar 18 02:05 ./doc/source/ray-air/examples/images/dreambooth_training.png -> ../../../../../python/ray/air/examples/dreambooth/images/dreambooth_training.png
````

2023-06-22 02:43 UTC, aslonnie commented
here are some ideas:

- for the bazel configs parts, they seem to be quite specific to conda build environment restrictions (?), maybe we can just drop them.
- instead of having these code in, I can leave two hook / injection places. like a `RAY_PREBUILD_CMD` env var to `subprocess.check_call()` , and a `RAY_BAZEL_CMD` env var as a json list or something to replace `["bazel"]` 

the general idea is to leave an injection place (and easier for us/me to test), where conda can still build ray with additional injected steps.

I can also ask my peers (at anyscale) if they are open to maybe move `dashboard` (and `rllib`) to `python/ray/dashboard` and reverse the symlink direction. I think those are the only two that are causing issues. maybe if the symlink directions are reversed, the problem of building on windows will just go away.

2023-06-22 07:37 UTC, h-vetinari commented
At a quick glance, the only two relevant symlinks (non-docs, non-example) seem to be:
```
./python/ray/dashboard -> ../../dashboard
./python/ray/rllib -> ../../rllib
```



> I can also ask my peers (at anyscale) if they are open to maybe move `dashboard` (and `rllib`) to `python/ray/dashboard` and reverse the symlink direction. I think those are the only two that are causing issues. maybe if the symlink directions are reversed, the problem of building on windows will just go away.

I don't know the build as intimately as @vnlitvinov, but if we're building both "sides" of the symlinks at different stages, then the direction doesn't actually matter, and we'll just have to replace it with a copy.

In any case, two folders seem manageable.

2023-06-23 21:11 UTC, vnlitvinov commented
Reversing two symlinks might help (cannot be sure without testing), as I don't think we're building stuff outside `python` directory (that said, I don't remember if conda build actually packages the client).

To get rid of this `automated` variable completely we'll need the bazel hook anyway, though.

2024-07-02 19:00 UTC, can-anyscale requested changes
push back to your queue since it's staled

2025-12-08 19:44 UTC, closed without merging