Add service deployment instructions to stable diffusion template
ray-project/ray pull request #37153
Opened 2023-07-06 18:44 UTC by akshay-anyscale

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-07-06 18:49 UTC, akshay-anyscale commented
Testing done using premerge: 

<img width="1441" alt="Screenshot 2023-07-06 at 11 47 31 AM" src="https://github.com/ray-project/ray/assets/122416226/a5ac53c0-8996-47ae-b1dd-c7e869fd410f">
<img width="1445" alt="Screenshot 2023-07-06 at 11 46 03 AM" src="https://github.com/ray-project/ray/assets/122416226/0c72e672-bf9c-428f-8cc4-bf95a5d9ef77">
<img width="1402" alt="Screenshot 2023-07-06 at 11 45 26 AM" src="https://github.com/ray-project/ray/assets/122416226/0551e688-fd80-4970-8fd3-51bd50afb45a">

2023-07-06 18:51 UTC, akshay-anyscale commented
<img width="1174" alt="Screenshot 2023-07-06 at 11 51 01 AM" src="https://github.com/ray-project/ray/assets/122416226/170e79b8-e801-4a7d-96b9-d8aa15bf0767">

2023-07-06 20:50 UTC, mjconnor approved these changes

2023-07-10 16:10 UTC, justinvyu reviewed
I think this generally looks good. A few suggestions:

- We can just remove the table at the start of the jupyter notebook, so that we don't need to update both.
- Could we also include the `serve run app:entrypoint && python query` in the test to make sure that at least works. I think testing the service is harder (is it possible to launch a service in a job?).

2023-07-10 16:17 UTC, akshay-anyscale commented
@justinvyu where can I update the tests? Since this requires GPU to run should it still be part of the testing pipeline?

2023-07-10 18:02 UTC, justinvyu commented
> @justinvyu where can I update the tests? Since this requires GPU to run should it still be part of the testing pipeline?

We can just add it at the end of the existing release test (which is setup with GPUs):

 https://github.com/ray-project/ray/blob/c67ebb45a7816e02273d7273edad74c77a9c600f/release/release_tests.yaml#L1003

2023-07-11 23:27 UTC, akshay-anyscale commented
Successful release tests- https://buildkite.com/ray-project/release-tests-pr/builds/45230#01894726-bc4a-4684-952e-641a6b3fbc79

2023-07-18 06:06 UTC, justinvyu requested changes
Looks like the release test failed - made a suggestion fix. After that, let's run the release test again, and should be good to merge once it passes.

2023-07-18 06:06 UTC, justinvyu commented on release/release_tests.yaml
> +    script: jupyter nbconvert --to script --output _test start.ipynb && ipython _test.py && python app.py
I think this needs to be:

```suggestion
    script: jupyter nbconvert --to script --output _test start.ipynb && ipython _test.py && serve run app:entrypoint && python query.py
```

2023-07-18 06:06 UTC, justinvyu commented on doc/source/templates/03_serving_stable_diffusion/app.py
> +    serve.run(entrypoint)
Don't think this block is needed since we go through `serve run`.

```suggestion
```

2023-07-19 06:51 UTC, justinvyu approved these changes
Thanks, LGTM.

Here was the passing release test for reference: https://buildkite.com/ray-project/release-tests-pr/builds/45812#01896c56-213c-4e4f-be52-f611eb96a03c

2023-07-19 15:13 UTC, merged