[release] fix torch lightning gpu tests.
ray-project/ray pull request #38039
Opened 2023-08-02 23:39 UTC by xwjiang2010

## Why are these changes needed?
Replace `validation_epoch_end ` with `on_ validation_epoch_end `.

## Related issue number
Closes #38036

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-08-02 23:41 UTC, woshiyyya commented on release/lightning_tests/workloads/lightning_test_utils.py
> +        ).mean()
```suggestion
        ).mean()
        self.validation_step_outputs.clear()
```

2023-08-02 23:43 UTC, woshiyyya requested changes
Thanks @xwjiang2010! LGTM. 

Just one minor change: clear the validation outputs at the end of validation epoch.

2023-08-02 23:45 UTC, xwjiang2010 commented
> Thanks @xwjiang2010! LGTM.
> 
> Just one minor change: clear the validation outputs at the end of validation epoch.

Ah right!
This is for correctness right? As the data structure is being used for validation that happens in different epochs. So we want to have a fresh start for another new epoch.

2023-08-02 23:51 UTC, woshiyyya commented
@xwjiang2010  Yes that's right:)

2023-08-03 16:21 UTC, woshiyyya approved these changes
Thank you @xwjiang2010 ~

2023-08-03 16:22 UTC, merged