[air] `pyarrow.fs` persistence: Don't automatically delete the local checkpoint
ray-project/ray pull request #38507
Opened 2023-08-16 18:24 UTC by justinvyu

## Why are these changes needed?

This PR updates the `persist_current_checkpoint` logic to not delete the user's input checkpoint upon uploading. This is instead the job of the user to clean up if they want to. This is in line with making things more explicit.

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-08-16 18:26 UTC, ericl approved these changes

2023-08-16 18:35 UTC, woshiyyya requested changes
I love this change. 

Previously, users had to create a tmpdir, copy existing ckpts to that tmp directory, and report it to Train. If the checkpoint is large, the copy step is unnecessary and takes a long time.

2023-08-16 18:35 UTC, woshiyyya commented on python/ray/train/tests/test_new_persistence.py
> +            )
Can we also check if the local checkpoint still exists after `train.report()` ?

2023-08-16 18:57 UTC, justinvyu commented
Ah yeah I didn't even think about that! Saves 1 copy step if they already have a dir created by some integration library.

2023-08-17 01:34 UTC, woshiyyya approved these changes
Thank you @justinvyu!

2023-08-17 01:41 UTC, merged