[docs] Add Nsight system docs on Ray
ray-project/ray pull request #40396
Opened 2023-10-17 06:14 UTC by jonathan-anyscale

## Why are these changes needed?
Add Ray documentation for new natively supported Nsight Profiler feature

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-10-18 21:54 UTC, emmyscode requested changes
Great doc and congrats on the Hackathon project!

To match the existing pattern of the Profiling page, can you add the information as a subsection in the ["Optimizing Performance"](https://docs.ray.io/en/latest/ray-observability/user-guides/debug-apps/optimize-performance.html#gpu-profiling-with-pytorch-profiler) page rather than adding another page to the side navigation?

I would make sure to make the section title something like "GPU profiling with Nsight Systems"

2023-10-18 21:54 UTC, emmyscode commented on doc/source/ray-observability/key-concepts.rst
> +- GPU profiling with :ref:`Pytorch Profiler <profiling-pytoch-profiler>` and :ref:`Nsight System <ray-profiling>`
Typo: `profiling-pytoch-profiler` -> `profiling-pytorch-profiler`

2023-10-18 21:54 UTC, emmyscode commented on doc/source/ray-observability/user-guides/profiling.md
>  (profiling-pytoch-profiler)=
Typo: `profiling-pytoch-profiler` -> `profiling-pytorch-profiler`

2023-10-18 21:54 UTC, emmyscode commented on doc/source/ray-observability/user-guides/ray-profiling.rst
> +
Regarding the main summary comment in favor of docs consolidation, I would remove this repeated information.

2023-10-18 21:54 UTC, emmyscode commented on doc/source/ray-observability/user-guides/ray-profiling.rst
> +Profiling results can be found under the `/tmp/ray/session_*/logs/{profiler_name}` directory. Alternatively, User can download the profiling reports from :ref:`Ray dashboard <dash-logs-view>`.
Rewrite: Alternatively, users can download the profiling reports from the Ray Dashboard.

2023-10-18 21:54 UTC, emmyscode commented on doc/source/ray-observability/user-guides/ray-profiling.rst
> +    While we don't prevent user from doing this, the best practice is to only specify filename in `-o, --output` option.
Rewrite: 
.. note::
The Nsight profiler `-o, --output` option allows you to set the path to a filename. Ray uses the logs directory as the base and appends the `-o, --output` option to it. As a best practice, only specify the filename in `o, --output` option.

2023-10-18 21:54 UTC, emmyscode commented on doc/source/ray-observability/user-guides/ray-profiling.rst
> +
I would remove this note in favor of just writing (Alpha) in the section header to be concise.

2023-10-18 21:54 UTC, emmyscode commented on doc/source/ray-observability/user-guides/ray-profiling.rst
> +
I would change this to the right subheading in the new page and rewrite as "GPU profiling with Nsight Systems"

2023-10-18 21:54 UTC, emmyscode commented on doc/source/ray-observability/user-guides/ray-profiling.rst
> +Confirm if Nsight System is installed by running:
Rewrite: Confirm Nsight is installed correctly:

2023-10-18 21:54 UTC, emmyscode commented on doc/source/ray-observability/user-guides/ray-profiling.rst
> +You can also add custom options for nsight profiler by specfying a dictionary of option values.
1. I would link the options: https://docs.nvidia.com/nsight-systems/UserGuide/index.html#cli-launch-command-switch-options
2. Capitalize "Nsight"

2023-10-18 21:54 UTC, emmyscode commented on doc/source/ray-observability/user-guides/profiling.md
> +- {ref}`NVIDIA Nsight System <ray-profiling>` is now natively supported
Add a sentence here to link to the new user guide.

2023-10-18 23:23 UTC, emmyscode commented
My suggestion is to remove the page `doc/source/ray-observability/user-guides/ray-profiling.rst` completely and absorb all of the information into the existing `doc/source/ray-observability/user-guides/debug-apps/optimize-performance.rst` This way, we can avoid having duplicate information and a longer side navigation.

2023-10-19 12:50 UTC, rkooo567 commented on doc/source/ray-observability/user-guides/debug-apps/optimize-performance.rst
> +* Setup the Ray tasks or actors which you want to profile by following this :ref:`user guide <ray-profiling>`.
Can you link to the specific section instead of this page (the section for GPU profiling)

2023-10-19 12:50 UTC, rkooo567 commented on doc/source/ray-observability/user-guides/debug-apps/optimize-performance.rst
> +Here are the steps to use Nsight Profiler with Ray Core:
I think all this info should be just inside the original section. You can simply add 

GPU profiling is critical for ML training and inference. Ray allows users to run Nsight profiler with Ray actors and tasks. See <direct link to the section> for details.

2023-10-19 12:50 UTC, rkooo567 commented on doc/source/ray-observability/user-guides/ray-profiling.rst
> +Profiling on Ray (Alpha)
I don't think we need a new page. Why don't we put this inside profiling.md?

2023-10-19 12:50 UTC, rkooo567 commented on doc/source/ray-observability/user-guides/ray-profiling.rst
> +There are several ways to perform profilling on Ray as desribed `here <https://docs.ray.io/en/master/ray-observability/user-guides/profiling.html>`_. For better experience, Ray is natively supporting
Not needed if we move this section to profiling.md

2023-10-19 12:50 UTC, rkooo567 commented on doc/source/ray-observability/user-guides/ray-profiling.rst
> +  @ray.remote(runtime_env={ "nsight": "default" })
```suggestion
  @ray.remote(runtime_env={ "nsight": "default" })
```

Is this correct? (I remember we used _nsight before)

2023-10-19 12:50 UTC, rkooo567 commented on doc/source/ray-observability/user-guides/ray-profiling.rst
> +  def ray_task():
Use actor as an example as most of ppl don't use task + gpu

2023-10-19 12:50 UTC, rkooo567 commented on doc/source/ray-observability/user-guides/ray-profiling.rst
> +  # run nsight with config: "nsys profile [default options] ..."
```suggestion
  # Actor/task process will run with : "nsys profile [default options] ..."
```

2023-10-19 12:50 UTC, rkooo567 commented on doc/source/ray-observability/user-guides/ray-profiling.rst
> +  @ray.remote(runtime_env={ "nsight": {
Can you clearly define this -o will only preserve and other default options will all removed when you specify any option? (it is not in-place update)

2023-10-19 12:50 UTC, rkooo567 commented on doc/source/ray-observability/user-guides/ray-profiling.rst
> +    "o": "task_1", # save report as task_1.nsys-rep
let's not write o option. I think 99.99% of users don't need it

2023-10-19 12:50 UTC, rkooo567 commented on doc/source/ray-observability/user-guides/ray-profiling.rst
> +  # run nsight with config:
`Ray actor/task process will launch with nsight command ...`

2023-10-19 12:50 UTC, rkooo567 commented on doc/source/ray-observability/user-guides/ray-profiling.rst
> +    The default report filename (`-o, --output`) is `worker_process_{pid}.nsys-rep`.
You should mention this is written to the log dir and that's subject to change

2023-10-19 12:50 UTC, rkooo567 commented on doc/source/ray-observability/user-guides/ray-profiling.rst
> +Profiling results can be found under the `/tmp/ray/session_*/logs/{profiler_name}` directory. Alternatively, users can download the profiling reports from the :ref:`Ray Dashboard <dash-logs-view>`.
```suggestion
Profiling results can be found under the `/tmp/ray/session_*/logs/{profiler_name}` directory. Users can download the profiling reports from the :ref:`Ray Dashboard <dash-logs-view>`.
```

2023-10-19 12:50 UTC, rkooo567 commented on doc/source/ray-observability/user-guides/ray-profiling.rst
> +Profiling results can be found under the `/tmp/ray/session_*/logs/{profiler_name}` directory. Alternatively, users can download the profiling reports from the :ref:`Ray Dashboard <dash-logs-view>`.
Can you add a specific screenshot (with an arrow to the profiling dir)?

2023-10-19 12:50 UTC, rkooo567 commented on doc/source/ray-observability/user-guides/ray-profiling.rst
> +    The Nsight profiler output (-o, --output) option allows you to set the path to a filename. Ray uses the logs directory as the base and appends the output option to it. As a best practice, only sp
Can you add an example?

```
--output <relative path> -> session_*/logs/profiling/<output>
--output <absolte_path> -> <absolute_path>
```

2023-10-19 12:50 UTC, rkooo567 commented on doc/source/ray-observability/user-guides/ray-profiling.rst
> +Profiling results can be found under the `/tmp/ray/session_*/logs/{profiler_name}` directory. Alternatively, users can download the profiling reports from the :ref:`Ray Dashboard <dash-logs-view>`.
Can you explain how to visualize the result?

2023-10-19 23:26 UTC, rkooo567 approved these changes
General doc structure LGTM. We should add a doc link to the API referece (synced offline for details). Can you lmk after @emmyscode gives the final sign off?

2023-10-19 23:43 UTC, emmyscode approved these changes
Looks great!

2023-10-20 17:55 UTC, angelinalg approved these changes

2023-10-20 17:55 UTC, angelinalg commented on doc/source/ray-core/handling-dependencies.rst
> +- ``nsight`` (Union[str, Dict[str, str]]): Nsight profiler config which either (1) "default" value refering to the `default config <https://github.com/ray-project/ray/blob/master/python/ray/_private/
```suggestion
- ``nsight`` (Union[str, Dict[str, str]]): specifies the config for the Nsight profiler. The value is either (1) "default", which refers to the `default config <https://github.com/ray-project/ray/blob/master/python/ray/_private/runtime_env/nsight.py#L20>`_, or (2) a dict of Nsight profiler options and their values.
```

2023-10-20 17:55 UTC, angelinalg commented on doc/source/ray-core/handling-dependencies.rst
> +  More detailed setup and usage can be found :ref:`here <profiling-nsight-profiler>`.
```suggestion
  See :ref:`here <profiling-nsight-profiler>` for more details on setup and usage.
```

2023-10-20 17:55 UTC, angelinalg commented on doc/source/ray-observability/user-guides/debug-apps/optimize-performance.rst
> +GPU Profiling with Nsight Profiler
```suggestion
GPU profiling with the Nsight Visual Profiler
```

2023-10-20 17:55 UTC, angelinalg commented on doc/source/ray-observability/user-guides/profiling.md
> +### Nsight Profiler
```suggestion
### Nsight Visual Profiler
```

2023-10-20 17:55 UTC, angelinalg commented on doc/source/ray-observability/user-guides/profiling.md
> +Confirm Nsight is installed correctly:
```suggestion
Confirm that you installed Nsight correctly:
```

2023-10-20 17:55 UTC, angelinalg commented on doc/source/ray-observability/user-guides/profiling.md
> +To enable GPU profiling, you can specify the config in `runtime_env` as follows:
```suggestion
To enable GPU profiling, specify the config in the `runtime_env` as follows:
```

2023-10-20 17:55 UTC, angelinalg commented on doc/source/ray-observability/user-guides/profiling.md
> +The `"default"` config can be found in [nsight.py](https://github.com/ray-project/ray/blob/master/python/ray/_private/runtime_env/nsight.py#L20).
```suggestion
You can find the `"default"` config in [nsight.py](https://github.com/ray-project/ray/blob/master/python/ray/_private/runtime_env/nsight.py#L20).
```

2023-10-20 17:55 UTC, angelinalg commented on doc/source/ray-observability/user-guides/profiling.md
> +#### Custom Options
```suggestion
#### Custom options
```

2023-10-20 17:55 UTC, angelinalg commented on doc/source/ray-observability/user-guides/profiling.md
> +You can also add [custom options](https://docs.nvidia.com/nsight-systems/UserGuide/index.html#cli-profile-command-switch-options) for Nsight profiler by specfying a dictionary of option values which
```suggestion
You can also add [custom options](https://docs.nvidia.com/nsight-systems/UserGuide/index.html#cli-profile-command-switch-options) for Nsight Visual Profiler by specifying a dictionary of option values, which overwrites the `default` config, however, Ray preserves the the `--output` option of the default config.
```

2023-10-20 17:55 UTC, angelinalg commented on doc/source/ray-observability/user-guides/profiling.md
> +# Actor/task process will run with :
```suggestion
# The Actor or Task process runs with :
```

2023-10-20 17:55 UTC, angelinalg commented on doc/source/ray-observability/user-guides/profiling.md
> +#### Profiling Result
```suggestion
#### Profiling result
```

2023-10-20 17:55 UTC, angelinalg commented on doc/source/ray-observability/user-guides/profiling.md
> +Profiling results can be found under the `/tmp/ray/session_*/logs/{profiler_name}` directory (subject to change). Users can download the profiling reports from the {ref}`Ray Dashboard <dash-logs-view
```suggestion
Find profiling results under the `/tmp/ray/session_*/logs/{profiler_name}` directory. This specific directory location may change in the future. You can download the profiling reports from the {ref}`Ray Dashboard <dash-logs-view>`.
```

2023-10-20 17:55 UTC, angelinalg commented on doc/source/ray-observability/user-guides/profiling.md
> +![Nsight profiler folder](../images/nsight-profiler-folder.png)
```suggestion
![Nsight Visual Profiler folder](../images/nsight-profiler-folder.png)
```

2023-10-20 17:55 UTC, angelinalg commented on doc/source/ray-observability/user-guides/profiling.md
> +To visualize the result, you need to install the [Nsight System GUI](https://developer.nvidia.com/nsight-systems/get-started#latest-Platforms) on your laptop. This is called the host. Then, transfer
```suggestion
To visualize the results, install the [Nsight System GUI](https://developer.nvidia.com/nsight-systems/get-started#latest-Platforms) on your laptop, which becomes the host. Transfer the .nsys-rep file to your host and open it using the GUI. You can now view the visual profiling info.
```

2023-10-20 17:55 UTC, angelinalg commented on doc/source/ray-observability/user-guides/profiling.md
> +**Note**: The Nsight profiler output (-o, --output) option allows you to set the path to a filename. Ray uses the logs directory as the base and appends the output option to it. For example:
```suggestion
**Note**: The Nsight Visual Profiler output (-o, --output) option allows you to set the path to a filename. Ray uses the logs directory as the base and appends the output option to it. For example: 
```

2023-10-20 17:55 UTC, angelinalg commented on doc/source/ray-observability/user-guides/profiling.md
> +As a best practice, only specify the filename in output option.
```suggestion
The best practice is to only specify the filename in output option.
```

2023-10-20 17:55 UTC, angelinalg commented on doc/source/ray-observability/user-guides/profiling.md
>  ## Ray Task / Actor timeline
```suggestion
## Ray Task or Actor timeline
```

2023-10-20 18:07 UTC, angelinalg commented
Very nice job, @jonathan-anyscale. I just had some nits. I assumed the proper name of the Nsight profiler is Nsight Visual Profiler. If not, please ignore those suggestions. You may also want to use Vale (go/vale) to get quicker feedback on typos and general style guidelines. Let me know if you have any questions.

2023-10-20 22:36 UTC, merged