[core] Fix broken runtime placement group test
ray-project/ray pull request #40507
Opened 2023-10-19 23:32 UTC by vitsai

Do not expose bundle as a resource to end user.

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-10-19 23:33 UTC, jjyao approved these changes

2023-10-19 23:39 UTC, jjyao requested changes

2023-10-19 23:39 UTC, jjyao commented on python/ray/runtime_context.py
> +        BUNDLE_RESOURCE_LABEL = "bundle"
I think the resource name is not just bundle

2023-10-20 20:27 UTC, vitsai commented
Can handle in #40517

2023-10-20 20:27 UTC, closed without merging