[data] log progress bar to data logs
ray-project/ray pull request #40814
Opened 2023-10-30 22:02 UTC by Zandew

## Why are these changes needed?

Log each operator's progress bar to `ray-data.log`

Example: `ray.data.range(100).map_batches(lambda x: x).materialize()`:
```
2023-10-30 14:59:36,342	INFO streaming_executor.py:310 -- Execution Progress Status:
Input                              100%|██████████| 20/20 [00:00<00:00, 359.94it/s]
ReadRange->MapBatches(<lambda>)      0%|          | 0/20 [00:00<?, ?it/s]

2023-10-30 14:59:36,344	INFO streaming_executor.py:323 -- Operator InputDataBuffer[Input] completed. Operator Metrics:
{'num_inputs_received': 20, 'bytes_inputs_received': 45900, 'num_outputs_taken': 20, 'bytes_outputs_taken': 45900, 'cpu_usage': 0, 'gpu_usage': 0}
2023-10-30 14:59:36,449	INFO streaming_executor.py:310 -- Execution Progress Status:
Input                              100%|██████████| 20/20 [00:00<00:00, 121.87it/s]
ReadRange->MapBatches(<lambda>)      5%|▌         | 1/20 [00:00<00:03,  6.09it/s]

2023-10-30 14:59:36,558	INFO streaming_executor.py:310 -- Execution Progress Status:
Input                              100%|██████████| 20/20 [00:00<00:00, 73.08it/s]
ReadRange->MapBatches(<lambda>)     10%|█         | 2/20 [00:00<00:02,  7.31it/s]

2023-10-30 14:59:36,662	INFO streaming_executor.py:310 -- Execution Progress Status:
Input                              100%|██████████| 20/20 [00:00<00:00, 52.99it/s]
ReadRange->MapBatches(<lambda>)     15%|█▌        | 3/20 [00:00<00:02,  7.95it/s]

2023-10-30 14:59:36,771	INFO streaming_executor.py:310 -- Execution Progress Status:
Input                              100%|██████████| 20/20 [00:00<00:00, 41.13it/s]
ReadRange->MapBatches(<lambda>)     20%|██        | 4/20 [00:00<00:01,  8.23it/s]

2023-10-30 14:59:36,877	INFO streaming_executor.py:310 -- Execution Progress Status:
Input                              100%|██████████| 20/20 [00:00<00:00, 33.78it/s]
ReadRange->MapBatches(<lambda>)     50%|█████     | 10/20 [00:00<00:00, 16.89it/s]

2023-10-30 14:59:36,900	INFO streaming_executor.py:310 -- Execution Progress Status:
Input                              100%|██████████| 20/20 [00:00<00:00, 32.52it/s]
ReadRange->MapBatches(<lambda>)    100%|██████████| 20/20 [00:00<00:00, 32.52it/s]
```

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-10-30 23:08 UTC, c21 approved these changes
cc @raulchen as well.

2023-10-30 23:08 UTC, c21 commented on python/ray/data/_internal/execution/streaming_executor.py
> -import tqdm
we can assume the `tqdm` package is always installed.

2023-10-31 17:20 UTC, raulchen requested changes

2023-10-31 17:20 UTC, raulchen commented on python/ray/data/_internal/execution/streaming_executor.py
> +                )
I think it's okay to not format with tqdm.  the graphics are not super useful. It is `state.summary_str()` that matters the most. (I'm not sure if `summary_str` already contains the `{op_state.num_completed_tasks}/{op.num_outputs_total()}` progress. If not, also log it).

I just found that we already have a similar function `_debug_dump_topology(topology)`. 
So I think we can considate them. By default, dump the info into data log here. If the flag is enabled, dump the info into both stdout and data log in the `while op is not None:` loop.

2023-10-31 22:09 UTC, c21 commented on python/ray/data/_internal/execution/streaming_executor.py
> +    logger.get_logger(log_to_stdout).info("vvv scheduling trace vvv")
this logging of `vvv scheduling trace vvv` and `^^^ scheduling trace ^^^` seems hard to read for me. Can we instead log an extra empty line at the end?

2023-10-31 23:25 UTC, raulchen commented on python/ray/data/_internal/execution/streaming_executor.py
> +    logger.get_logger(log_to_stdout).info("Scheduling Trace:")
nit, I think the previous log message (something like "execution progress") is more understandable.

2023-10-31 23:25 UTC, raulchen approved these changes

2023-11-01 18:16 UTC, merged