Optimize the doc about frozen VM expressions
ray-project/ray pull request #41233
Opened 2023-11-17 08:43 UTC by JingChen23

## Why are these changes needed?

Currently some expressions in our doc about how to prepare the frozen VM are inprecise, this change optimized the document. 

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2023-11-17 17:39 UTC, architkulkarni requested changes
One typo I think, otherwise looks good to me

2023-11-17 17:39 UTC, architkulkarni commented on doc/source/cluster/vms/user-guides/launching-clusters/vsphere.md
> +rage/experiment_results` as the `storage_path` for `RunConfig`.
```suggestion
Once a file share is created, you can mount it into the head and worker node and use the mount path as the `storage_path` for the `RunConfig` parameter in Ray Train and Tune. Please refer to [this example YAML](https://raw.githubusercontent.com/ray-project/ray/master/python/ray/autoscaler/vsphere/example-vsan-file-service.yaml) as a template on how to mount and configure the path. You will need to modify the NFS export path in the `initialization_commands` list and bind the mounted path within the Ray container. In this example, you will need to put `/mnt/shared_storage/experiment_results` as the `storage_path` for `RunConfig`.
```

2023-11-20 02:03 UTC, JingChen23 commented
> One typo I think, otherwise looks good to me

Thanks Archit for the review!

2023-11-20 16:34 UTC, architkulkarni approved these changes

2023-11-20 16:34 UTC, merged