[Core] Fix cgroup used memory calculation for Ray memory monitor
ray-project/ray pull request #43071
Opened 2024-02-09 06:04 UTC by jjyao

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2024-02-09 06:04 UTC, jjyao commented on src/ray/common/memory_monitor.cc
> +  return current_usage_bytes - inactive_file_bytes - active_file_bytes;
This is the key.

2024-02-09 06:07 UTC, WeichenXu123 approved these changes

2024-02-09 06:16 UTC, WeichenXu123 commented on src/ray/common/memory_monitor.cc
> +  return current_usage_bytes - inactive_file_bytes - active_file_bytes;
Let's comment why we need to substract `active_file_bytes`:

we can put the link as a good reference: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/resource_management_guide/sec-memory

and comment that 

`total_active_file + total_inactive_file == cache - shmem`

2024-02-09 06:17 UTC, WeichenXu123 commented on src/ray/common/memory_monitor.cc
> +  return current_usage_bytes - inactive_file_bytes - active_file_bytes;
and comment that cgroup v2 doesn't have `cache` and `shmem` fields, so we use `total_active_file, total_inactive_file` in formula to unify fomula across v1 / v2

2024-02-09 06:17 UTC, WeichenXu123 requested changes
You should update python side code too.

2024-02-09 08:23 UTC, WeichenXu123 approved these changes

2024-02-09 08:25 UTC, WeichenXu123 reviewed
Please refine comments before merging.
https://github.com/ray-project/ray/pull/43071/files#r1483902223

2024-02-10 01:02 UTC, rkooo567 approved these changes
Awesome. How do we plan to test it? Is it possible you run it with high IO workloads or are we just going to provide a wheel to users who have the problem?

2024-02-10 01:02 UTC, rkooo567 commented on python/ray/_private/utils.py
> +    memory_stat_filename, memory_usage_filename, inactive_file_key, active_file_key
Can you add type annotation?

2024-02-14 05:37 UTC, merged