[tune] Fix performance issue and fix reuse tests
ray-project/ray pull request #4379
Opened 2019-03-15 08:37 UTC by richardliaw

Pytest I think uses some multi-threaded importing, so
classes often fail to import, hence the hanging on Jenkins. This gets around that 
but using a constructor.

Performance issue reported earlier is also mitigated by only updating resources
once per TrialRunner step.

2019-03-15 17:08 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/92/
Test PASSed.

2019-03-15 20:10 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/12889/
Test FAILed.

2019-03-15 23:46 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/99/
Test PASSed.

2019-03-15 23:46 UTC, richardliaw commented on python/ray/tune/tests/test_actor_reuse.py
> +def create_resettable_class():
This is needed because pytest does not import classes correctly

2019-03-16 01:10 UTC, ericl requested changes

2019-03-16 01:10 UTC, ericl commented on python/ray/tune/ray_trial_executor.py
> +        if time.time() - self._last_resource_refresh > self._refresh_period:
Does this mean that if my trials run really fast (say 10ms) I won't be able to schedule more than 2 a second?

Why not refresh after each event processed?

2019-03-16 01:10 UTC, ericl commented on python/ray/tune/trial_runner.py
> +                _MEMORY_USAGE_WARNED = True
Please don't do this. The user can easily miss this warning otherwise since it's relatively unobtrusive.

2019-03-16 01:11 UTC, ericl commented on python/ray/tune/ray_trial_executor.py
> +        if time.time() - self._last_resource_refresh > self._refresh_period:
Oh, IIUC this is just for the "cluster resources", which are not expected to change dynamically often. If that's right then it seems ok, but I would document this.

2019-03-16 01:18 UTC, ericl commented on python/ray/tune/trial_runner.py
> +                _MEMORY_USAGE_WARNED = True
Consider reverting this change. The user can easily miss this warning otherwise since it's relatively unobtrusive.

2019-03-16 04:07 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/12909/
Test PASSed.

2019-03-16 05:57 UTC, ericl approved these changes

2019-03-16 17:44 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/105/
Test PASSed.

2019-03-16 20:46 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/12916/
Test FAILed.

2019-03-16 20:52 UTC, merged