Add generic item support for queue
ray-project/ray pull request #46849
Opened 2024-07-29 18:51 UTC by haarisr

## Why are these changes needed?

Add generic support for `queue`. This allows the `queue` to be templated over any type allowing for type checkers to work better.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

2024-08-26 17:32 UTC, rkooo567 reviewed
this is awesome! QQ; is it possible to add unit tests here? https://github.com/ray-project/ray/blob/master/python/ray/tests/test_typing.py

2024-08-26 17:32 UTC, rkooo567 commented
also there are some unit tests failures

2024-08-27 05:05 UTC, haarisr commented
The error has something to do with the docs not building.

Unfortunately I'm not super familiar with readthedocs, it's something to do with generic types.

```
ray/python/ray/util/queue.py:docstring of ray.util.queue.Queue:1: WARNING: py:obj reference target not found: ray.util.queue.T
```

2024-08-28 20:56 UTC, rkooo567 commented
can you first try adding a unit test? If it still fails, I can help resolving this

2024-09-26 17:57 UTC, haarisr commented
> can you first try adding a unit test? If it still fails, I can help resolving this

Hi bumping this

2025-05-29 20:27 UTC, codope requested changes
@haarisr Thanks for the contribution! Could you please rebase and address the comments?

2025-05-29 20:27 UTC, codope commented on python/ray/tests/typing_files/check_typing_bad.py
> +    int_queue.put(i)
what do the tests actually assert?
Also, can we add tests for the async variants (put_async / get_async) so you’re sure static checkers handle those too?

2025-06-02 18:47 UTC, haarisr commented on python/ray/tests/typing_files/check_typing_bad.py
> +    int_queue.put(i)
Theres a test in `python/ray/tests/test_typing.py` that runs the file and checks the error status of mypy on the entire file instead of each test (which is seperated by a comment right now)

I don't think that is the best way to go about it.

Sure I can add those tests too.

2025-06-02 18:47 UTC, haarisr commented on python/ray/util/queue.py
> +class Queue(Generic[T]):
Will do

2025-07-01 10:41 UTC, codope commented on python/ray/tests/typing_files/check_typing_bad.py
> +    int_queue.put(i)
@haarisr Could you also look into the test failures?

2025-07-08 17:55 UTC, edoakes commented
stale; @haarisr please re-open if you are still interested in contributing this!

2025-07-08 17:55 UTC, closed without merging