Fix webui
ray-project/ray pull request #4686
Opened 2019-04-23 16:18 UTC by suquark

## What do these changes do?

Fix the broken `get_webui_url()` API.

## Linter

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.

2019-04-23 16:20 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/570/
Test PASSed.

2019-04-23 16:22 UTC, robertnishihara commented on python/ray/tests/test_webui.py
> +    webui_url = addresses['webui_url']
```suggestion
    webui_url = addresses["webui_url"]
```

The linter will complain about this.

Also, will this test work? To work, it needs to have Python 3, psutil, and aiohttp installed in Travis.

2019-04-23 18:34 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/13935/
Test FAILed.

2019-04-24 09:53 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/580/
Test PASSed.

2019-04-24 10:36 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/581/
Test PASSed.

2019-04-24 12:26 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/13947/
Test FAILed.

2019-04-24 13:05 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/582/
Test PASSed.

2019-04-24 13:13 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/13948/
Test FAILed.

2019-04-24 13:34 UTC, jovany-wang requested changes

2019-04-24 13:34 UTC, jovany-wang commented on python/ray/tests/test_webui.py
> +            [sys.executable, "-m", "pip", "install", "aiohttp", "psutil"])
I don't think it's a good idea to install packages at runtime.
It's better to install them [here](https://github.com/ray-project/ray/blob/master/ci/travis/install-dependencies.sh#L51), like:
```shell
if is_python3:
pip install aiohttp==x.x.x psutil====x.x.x
fi
```

2019-04-24 15:09 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/13949/
Test FAILed.

2019-04-26 19:37 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/609/
Test PASSed.

2019-04-26 22:23 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/13983/
Test FAILed.

2019-04-27 07:11 UTC, jovany-wang approved these changes

2019-04-27 07:23 UTC, merged