[tune] Add Ax to Tune
ray-project/ray pull request #4731
Opened 2019-05-02 02:58 UTC by adizim

![image](https://user-images.githubusercontent.com/6635471/57054760-74d56580-6c4b-11e9-9c56-01333cec6c0d.png)

2019-05-02 03:02 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/652/
Test PASSed.

2019-05-02 04:14 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/14048/
Test FAILed.

2019-05-03 17:33 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/686/
Test PASSed.

2019-05-03 18:14 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/14090/
Test FAILed.

2019-05-03 18:55 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/687/
Test PASSed.

2019-05-03 21:02 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/14091/
Test FAILed.

2019-05-03 22:33 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/690/
Test PASSed.

2019-05-04 00:13 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/14094/
Test FAILed.

2019-05-04 01:23 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/691/
Test PASSed.

2019-05-04 03:22 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/14095/
Test FAILed.

2019-05-06 22:40 UTC, adizim commented
@AmplabJenkins retest this please

2019-05-06 22:43 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/718/
Test PASSed.

2019-05-06 23:53 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/14127/
Test FAILed.

2019-05-07 00:11 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/719/
Test PASSed.

2019-05-07 02:10 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/720/
Test PASSed.

2019-05-07 02:13 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/14128/
Test FAILed.

2019-05-07 02:40 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/721/
Test PASSed.

2019-05-07 03:48 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/723/
Test PASSed.

2019-05-07 04:20 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/14129/
Test FAILed.

2019-05-07 04:44 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/14130/
Test FAILed.

2019-05-07 05:29 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/14132/
Test FAILed.

2019-05-07 05:35 UTC, richardliaw commented on doc/source/tune-searchalg.rst
> -In order to use this search algorithm, you will need to install Scikit-Optimize via the following command:
wait we don't want to change this right :)

2019-05-07 05:38 UTC, richardliaw commented on doc/source/tune-searchalg.rst
> +The ``AxSearch`` is a SearchAlgorithm that is backed by `Ax <https://ax.dev/>`__ to perform sequential model-based hyperparameter optimization. Note that this class does not extend ``ray.tune.suggest
maybe also include a one-line comment about what is Ax. `Ax is a  platform for understanding, managing, deploying, and automating adaptive experiments. Ax provides an easy to use interface with BoTorch, a flexible, modern library for Bayesian optimization in PyTorch.`

2019-05-07 05:39 UTC, richardliaw commented on doc/source/tune-searchalg.rst
> +    $ conda install pytorch torchvision -c pytorch  # OSX only
I would consider just linking to the PyTorch Installation page here.

2019-05-07 05:39 UTC, richardliaw commented on doc/source/tune-searchalg.rst
> +This algorithm requires specifying a search space and objective. You can use AxSearch like follows:
```suggestion
This algorithm requires specifying a search space and objective. You can use `AxSearch` like follows:
```

2019-05-07 05:39 UTC, richardliaw commented on python/ray/tune/examples/ax_example.py
> +import numpy as np
the general style is to move this before the ray imports.

2019-05-07 05:41 UTC, richardliaw commented on python/ray/tune/suggest/ax.py
> +            to `log_data`.
This metric must also be present in the dict reported/returned by the Trainable.

2019-05-07 05:41 UTC, richardliaw commented on python/ray/tune/suggest/ax.py
> +        minimize (bool): Whether this experiment represents a minimization
Defaults to False.

2019-05-07 05:42 UTC, richardliaw commented on python/ray/tune/suggest/ax.py
> +            problem.
```suggestion
            problem. Defaults to False.
```

2019-05-07 05:42 UTC, richardliaw commented on python/ray/tune/suggest/ax.py
> +            equal number of outcome_constraints
```suggestion
            equal number of outcome_constraints.
```

2019-05-07 05:43 UTC, richardliaw commented on python/ray/tune/suggest/ax.py
> +        """Pass data back to Ax
```suggestion
        """Pass data back to Ax.
```

2019-05-07 05:43 UTC, richardliaw commented on doc/source/tune-searchalg.rst
> +    $ pip3 install ax-platform  # all systems
```suggestion
    $ pip install ax-platform  # all systems
```

2019-05-07 05:46 UTC, richardliaw commented on python/ray/tune/suggest/ax.py
> +                 parameter_constraints=[],
we should change this to `parameter_constraints=None` (along with any default kwarg that is `[]` or `{}`. There's a weird behavior with these lists being mutable and resulting in some hidden side effects if there are multiple instantiations.

For these defaults, the assignment should be like:
```
self._ax.create_experiment(
            name="ax",
            parameters=parameters,
            objective_name=objective_name,
            minimize=minimize,
            parameter_constraints=parameter_constraints or [],
            outcome_constraints=outcome_constraints or [],
...)
```

2019-05-07 05:47 UTC, richardliaw commented on doc/source/tune-searchalg.rst
> +The ``AxSearch`` is a SearchAlgorithm that is backed by `Ax <https://ax.dev/>`__ to perform sequential model-based hyperparameter optimization. Note that this class does not extend ``ray.tune.suggest
Also says SkOptSearch here.

2019-05-07 05:47 UTC, richardliaw requested changes
Left a few comments (be sure to request a review again when addressed).

2019-05-07 16:37 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/728/
Test PASSed.

2019-05-07 16:59 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/730/
Test PASSed.

2019-05-07 17:50 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/14136/
Test FAILed.

2019-05-07 18:06 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/14138/
Test FAILed.

2019-05-08 00:23 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/731/
Test PASSed.

2019-05-08 00:31 UTC, richardliaw commented on doc/source/tune-searchalg.rst
> +    $ pip install ax-platform
```suggestion
    $ pip install ax-platform sqlalchemy
```

2019-05-08 00:31 UTC, richardliaw commented on doc/source/tune-searchalg.rst
> +In order to use this search algorithm, you will need to install PyTorch and Ax. Instructions to install PyTorch locally can be found `here <https://pytorch.org/get-started/locally/>`__. You can insta
```suggestion
In order to use this search algorithm, you will need to install PyTorch, Ax, and sqlalchemy. Instructions to install PyTorch locally can be found `here <https://pytorch.org/get-started/locally/>`__. You can install Ax and sqlalchemy via the following command:
```

2019-05-08 00:37 UTC, richardliaw approved these changes
Pending last installation comments and this is good to go!

2019-05-08 00:38 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/732/
Test PASSed.

2019-05-08 00:45 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/733/
Test PASSed.

2019-05-08 02:20 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/14140/
Test FAILed.

2019-05-08 02:22 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/14139/
Test FAILed.

2019-05-08 22:54 UTC, merged

2019-05-08 22:54 UTC, richardliaw commented
Thanks @adizim!