Remove unnecessary string literal splits
ray-project/ray pull request #47360
Opened 2024-08-27 17:52 UTC by bryant1410

I found there were a bunch. Found them with:

```bash
find -name '*.py' -exec grep --color=always -HnIie '".*" ".*"' {} \; | less -r
```

2025-03-24 22:53 UTC, ruisearch42 commented
@bryant1410 can you rebase? many of these may already be fixed

2025-04-03 22:41 UTC, crypdick commented
@bryant1410 thank you for your contribution! can you please run the code formatter to make our linter checks pass, then we should be good to go!

2025-04-03 22:42 UTC, crypdick requested changes
please run code formatter

2025-04-07 17:27 UTC, bryant1410 commented
> @bryant1410 thank you for your contribution! can you please run the code formatter to make our linter checks pass, then we should be good to go!

done

2025-04-07 20:21 UTC, pcmoritz approved these changes

2025-04-08 01:04 UTC, pcmoritz commented
@bryant1410 Thanks a lot for your contribution!

2025-04-08 01:05 UTC, merged