RayServe Multi-Host TPU Example with vLLM
ray-project/ray pull request #47814
Opened 2024-09-25 00:48 UTC by ryanaoleary

## Why are these changes needed?

This PR adds a new guide to the Ray docs that details how to serve an LLM with vLLM and multi-host TPUs on GKE. This PR has been tested by running through the steps in the proposed guide and verifying correct output.

## Related issue number

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2024-09-25 00:52 UTC, ryanaoleary commented
cc: @andrewsykim

2024-09-27 07:38 UTC, ryanaoleary commented on doc/source/cluster/kubernetes/examples/tpu-multi-host-rayservice.md
> +docker push LOCATION-docker.pkg.dev/PROJECT-ID/REPOSITORY/IMAGE
Done in  15b4848.

2024-09-27 07:38 UTC, ryanaoleary commented on doc/source/cluster/kubernetes/examples/tpu-multi-host-rayservice.md
> +git https://github.com/vllm-project/vllm.git
Oh oops thanks for catching that, fixed in 70fbab0.

2025-02-04 02:29 UTC, ryanaoleary commented
I went through and updated this guide for the newer TPU Trillium so that it'll be more useful, it no longer requires multi-host since v6e can fit Llama 70B on a single node. I'll create a PR with a separate guide showcasing serving with Llama 405B and multi-host TPUs. cc: @andrewsykim @kevin85421

2025-02-10 21:25 UTC, andrewsykim commented on doc/source/cluster/kubernetes/examples/tpu-single-host-rayservice.md
> +git clone https://github.com/GoogleCloudPlatform/kubernetes-engine-samples.git
Could we host the example in KubeRay repo instead? I think that's consistent with other samples used in the Ray docs.

2025-02-10 23:48 UTC, ryanaoleary commented on doc/source/cluster/kubernetes/examples/tpu-single-host-rayservice.md
> +git clone https://github.com/GoogleCloudPlatform/kubernetes-engine-samples.git
Sounds good, added the manifest and script used to the KubeRay samples in https://github.com/ray-project/kuberay/pull/3000

2025-02-12 16:18 UTC, andrewsykim approved these changes

2025-02-19 00:38 UTC, andrewsykim commented
@angelinalg can you help us review this please?

2025-03-05 02:29 UTC, kouroshHakha requested changes
Hi @ryanaoleary , Thanks for the contribution. We just ossed our native ray serve LLM apis. Do you mind converting this tutorial to use that instead? 

https://docs.ray.io/en/latest/serve/llm/overview.html

Basically there is no need to reference a custom application code that is hosted in the kuberay code. Please use the latest apis from master. 


Also another question is if this tutorial is part of the ci/cd. For example what will happen if vllm / some api from ray changes?

2025-03-05 18:47 UTC, andrewsykim commented
@kouroshHakha thanks for letting us know!

There's actually some existing docs that use KubeRay + vLLM right now, for example see https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/vllm/ray-service.vllm.yaml. Would it be possible to merge Ryan's PR as-is and follow-up with a sweeping change that updates all the docs using vLLM for consistency?

2025-03-05 18:53 UTC, kouroshHakha commented
Yes we can merge this as it's a self-contained, and the code that most likely won't break in the future so this is a plus for this approach. But can we add a note on the very top (at the same level and visibility as where prerequisites are listed) in this tutorial that mentions there is a native serve LLM API with some pointers so that the reader does go under the impression that this is the only application code that works? In fact the new API is more recommended path for running LLMs through ray serve. The kubernetes deployment configs remain the same and only application code changes to use those APIs.

2025-03-05 20:21 UTC, ryanaoleary commented
> Yes we can merge this as it's a self-contained, and the code that most likely won't break in the future so this is a plus for this approach. But can we add a note on the very top to both new files in this PR and the existing kubernetes example (at the same level and visibility as where prerequisites are listed) in this tutorial that mentions there is a native serve LLM API with some pointers so that the reader does go under the impression that this is the only application code that works? In fact the new API is more recommended path for running LLMs through ray serve. The kubernetes deployment configs remain the same and only application code changes to use those APIs. If we do this then there is no need for a sweeping change now as it would be more clear to the reader.

Added a note in the vLLM examples in [466ad03](https://github.com/ray-project/ray/pull/47814/commits/466ad03a8d366dffd91b5eba65b9353bd1695329) about the new Ray Serve LLM API.

2025-03-05 20:36 UTC, kouroshHakha commented
> does the new LLM API support TPUs?

@andrewsykim

Right now users can call `config.get_serve_options()` to get the deployment options (including the placement group) That function currently does not support TPUs. But you can bypass that by providing your own placement group similar to how it's done currently in https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/vllm/serve_tpu.py#L102 and calling `.options` on the deployment object. Everything else remains the same similar to your example. 

It would be awesome if you / someone from your team could contribute and extend the current placement group creation within ray.serve.llm to support TPUs as well.

2025-03-05 20:36 UTC, kouroshHakha approved these changes
LGTM. Thanks. 🚀

2025-03-05 21:17 UTC, ryanaoleary commented
> LGTM. Thanks. 🚀 The doc build is failing tho. It might be the reference that is messed up. Once fixed we can merge.

Oh oops, I fixed the links. The build looks to be passing now.

2025-03-05 21:42 UTC, kouroshHakha approved these changes

2025-03-05 21:42 UTC, kouroshHakha commented
cc @angelinalg can you stamp this PR? It needs docs approval

2025-03-05 21:44 UTC, angelinalg approved these changes
stamp

2025-03-05 21:44 UTC, merged

2025-03-06 03:24 UTC, kevin85421 commented
Hi @ryanaoleary, I will revert this PR because my colleague merges this PR accidentally. We can discuss the next step of this PR in our 1:1 next time.