Updated link for slack
ray-project/ray pull request #47890
Opened 2024-10-03 20:45 UTC by bill-oconnor-anyscale

Removed old google form and updated to new landing page with new hubpsot form

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2024-10-03 20:46 UTC, angelinalg reviewed
LGTM

2024-10-04 16:05 UTC, saihaj requested changes

2024-10-04 16:05 UTC, saihaj commented on README.rst
> +.. _`Slack`: https://www.ray.io/join-slack
```suggestion
.. _`Slack`: https://www.ray.io/join-slack?utm_source=github&utm_medium=ray_readme&utm_campaign=getting_involved
```

2024-10-04 17:56 UTC, saihaj approved these changes

2024-10-04 18:17 UTC, merged