style: flake8 violation F401
ray-project/ray pull request #48185
Opened 2024-10-22 13:39 UTC by fscnick

## Why are these changes needed?

While running the pre-commit hook of flake8, the following error occurs if Python version is 3.12. It's because the version of flake8 is too old.

```
./python/ray/experimental/channel/nccl_group.py:13:5: F401 'cupy as cp' imported but unused
./python/ray/tests/autoscaler_test_utils.py:5:1: F401 'typing.Callable' imported but unused
./rllib/evaluation/sampler.py:58:5: F401 'gymnasium.envs.classic_control.rendering.SimpleImageViewer' imported but unused
```

However, there are another violation appeared after removing these unused import.
```
python/ray/experimental/channel/nccl_group.py:91:37: F821 undefined name 'cp'
python/ray/tests/autoscaler_test_utils.py:46:55: F821 undefined name 'Callable'
rllib/evaluation/sampler.py:343:35: F821 undefined name 'SimpleImageViewer'
```

After taking a look, 
[nccl_group.py:91](https://github.com/ray-project/ray/blob/8c28fe265a5457960bfc1b579687b6c1b632bbbc/python/ray/experimental/channel/nccl_group.py#L92) and [sampler.py:58](https://github.com/ray-project/ray/blob/8c28fe265a5457960bfc1b579687b6c1b632bbbc/rllib/evaluation/sampler.py#L345) are used in `Optional`
[autoscaler_test_utils.py:46](https://github.com/ray-project/ray/blob/8c28fe265a5457960bfc1b579687b6c1b632bbbc/python/ray/tests/autoscaler_test_utils.py#L46) `Callable` is used in type comment.

Thus, suppress F401.

## Related issue number

Closes https://github.com/ray-project/ray/issues/48062

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2024-10-22 13:39 UTC, fscnick commented
@MortalHappiness PTAL

2024-10-23 12:03 UTC, MortalHappiness requested changes

2024-10-24 15:44 UTC, Daraan commented on python/ray/tests/autoscaler_test_utils.py
> +        self.cmd_to_callback: Dict[str, Callable] = cmd_to_callback or {}
Disclaimer: I am just some random person showing up here.

As the minimum version is now 3.9 and [PEP 585](https://www.python.org/dev/peps/pep-0585) is available. `typing.Dict, typing.Callable` and similar are deprecated.

Now we can (and should rather) use `from collections.abc import Callable` and the builtins dict instead.

```suggestion
        self.cmd_to_callback: dict[str, Callable] = cmd_to_callback or {}
```

2025-01-13 06:35 UTC, MortalHappiness commented
Close this because we decide to migrate from `flake8` to `ruff` instead of upgrading `flake8`.

2025-01-13 06:35 UTC, closed without merging