Doc update #45339
ray-project/ray pull request #48626
Opened 2024-11-07 12:45 UTC by pinduzera

Extend explicitly on the documentation that the Python versions of client and server must match up to the Patch version.

This closes #45339

2025-02-01 01:04 UTC, richardliaw approved these changes

2025-03-06 21:02 UTC, crypdick approved these changes

2025-03-24 22:50 UTC, jjyao requested changes

2025-03-24 22:50 UTC, jjyao commented on doc/source/cluster/running-applications/job-submission/ray-client.rst
> +Similarly, the minor (e.g., 3.6 vs 3.7) and patch (e.g. 3.7.17 vs 3.7.16) Python versions must match between the client and server. An error will be raised if this is not the case.
For ray client I think we don't consider patch version:

```
def _check_versions(self, conn_info: Dict[str, Any], ignore_version: bool) -> None:
        # conn_info has "python_version" and "ray_version" so it can be used to compare.
        ignore_version = ignore_version or ("RAY_IGNORE_VERSION_MISMATCH" in os.environ)
        check_version_info(
            conn_info,
            "Ray Client",
            raise_on_mismatch=not ignore_version,
            python_version_match_level="minor",
        )
```

2025-03-24 23:48 UTC, pcmoritz commented on doc/source/cluster/running-applications/job-submission/ray-client.rst
> +Similarly, the minor (e.g., 3.6 vs 3.7) and patch (e.g. 3.7.17 vs 3.7.16) Python versions must match between the client and server. An error will be raised if this is not the case.
Can you dig into this a little deeper? I recently saw an error message
```
Call to `ray.init()` on the server failed with: Version mismatch: The cluster was started with:
    Ray: 2.44.0
    Python: 3.12.3
This process on node 127.0.0.1 was started with:
    Ray: 2.44.0
    Python: 3.12.8
```
which seems to indicate that's actually not the case -- there might be a bug :)

2025-06-01 04:49 UTC, jjyao commented on doc/source/cluster/running-applications/job-submission/ray-client.rst
> +Similarly, the minor (e.g., 3.6 vs 3.7) and patch (e.g. 3.7.17 vs 3.7.16) Python versions must match between the client and server. An error will be raised if this is not the case.
I checked. This is an warning message but not error message:

```
    if ray_matches and python_matches:
        if not python_full_matches:
            logger.warning(f"Python patch version mismatch: {mismatch_msg}")
    else:
        error_message = f"Version mismatch: {mismatch_msg}"
        if raise_on_mismatch:
            raise RuntimeError(error_message)
        else:
            logger.warning(error_message)
```

Maybe we shouldn't print out the warning message at all if we don't need to math patch version.

2025-06-01 04:50 UTC, jjyao commented
Closing this PR as the doc is right.

2025-06-01 04:50 UTC, closed without merging