[data] fix pandas type error while transfer from webdataset to lance
ray-project/ray pull request #48674
Opened 2024-11-09 08:37 UTC by Jay-ju

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2024-11-10 06:54 UTC, richardliaw commented
Thanks a bunch for this PR @Jay-ju -- could you make sure to add tests in test_webdataset?

2024-11-10 06:56 UTC, richardliaw requested changes
(need test)

2024-12-02 05:30 UTC, Jay-ju commented
> (need test)

done

2024-12-03 18:35 UTC, richardliaw approved these changes

2024-12-03 20:05 UTC, merged