refactor: kubernetes host abstracted as a helper function.
ray-project/ray pull request #48714
Opened 2024-11-13 01:30 UTC by ltbringer

## Why are these changes needed?

In #48541 `url_from_resource` was patched to use `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT_HTTPS`. Since `KubeRayNodeProvider` also has a `_url` method with a very similar implementation: https://github.com/ray-project/ray/blob/8ef918a390a521b4455d72c7b81b3785c066938b/python/ray/autoscaler/_private/kuberay/node_provider.py#L525-L542

which sets the host set as the default value. 

This PR refactors the changes made earlier and patches both `url_from_resource` and `KubeRayNodeProvider._url` to use the environment variables set by kubernetes. These changes are necessary to support multi-cluster environments where cluster's have custom DNS. Without this, the Kuberay autoscaler fails with a network error.

## Related issue number

NA

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [x] Release tests
   - [ ] This PR is not tested :(

2024-11-13 18:25 UTC, MortalHappiness requested changes

2024-11-15 00:59 UTC, MortalHappiness commented
Hi. Please sign-off all your commits for the DCO check to pass.

2024-11-15 05:16 UTC, MortalHappiness approved these changes
LGTM. Thanks!

2024-11-15 18:21 UTC, jjyao approved these changes

2024-11-15 18:21 UTC, merged