[data] add dataloader for lance datasource
ray-project/ray pull request #49459
Opened 2024-12-27 09:06 UTC by Jay-ju

Signed-off-by: jukejian <jukejian@bytedance.com>

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

2025-01-02 15:40 UTC, gvspraveen commented on python/ray/data/tests/test_lance.py
> +    dataloader = DataLoader(
ooc can you show example of how this work with `ray.train.torch. TorchTrainer`?. Currently it takes Ray `Dataset` as input and not Datasource.

2025-01-02 23:42 UTC, raulchen requested changes

2025-01-02 23:42 UTC, raulchen commented on python/ray/data/_internal/datasource/lance_datasource.py
> +        return self.LanceDataset(ds=self)
In Ray Data, a Datasource is to used to create a Ray Dataset, `ray.data.read_datasource(...)`.
Users are not supposed to directly use the Datasource class for training ingestion. 
If you want to do this, I think you can directly create a torch Dataset based on LanceDB without using Ray Data.

2025-01-03 02:45 UTC, Jay-ju commented on python/ray/data/_internal/datasource/lance_datasource.py
> +        return self.LanceDataset(ds=self)
From a theoretical perspective, directly creating a torch Dataset is also possible. it is inherited from Torch Dataset. The reason for placing it here is mainly that it can be directly converted into a dataset through the datasource, facilitating the implementation of the ray train + ray data mode.
WDYT？

2025-01-03 02:47 UTC, Jay-ju commented on python/ray/data/tests/test_lance.py
> +    dataloader = DataLoader(
It is indeed using Dataaset.

2025-01-08 03:06 UTC, raulchen commented on python/ray/data/_internal/datasource/lance_datasource.py
> +        return self.LanceDataset(ds=self)
sorry I still don't think this makes sense. 
because "Users are not supposed to directly use the Datasource class for training ingestion."

2025-02-27 11:52 UTC, closed without merging