Starting of ray head and worker is synchronized on GCS_READY flag in gcs
ray-project/ray pull request #4977
Opened 2019-06-13 13:34 UTC by WeipingQu

## What do these changes do?
This PR solve the problem of workers missing configs set by header in gcs when head and worker start concurrently.
The solution is to set a GCS_READY flag in GCS, which both head and workers synchronize on.

## Related issue number
Closes #4266

## Linter

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.

2019-06-13 16:38 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/14701/
Test FAILed.

2019-06-14 10:17 UTC, raulchen approved these changes
Thanks, LGTM.

2019-06-14 10:19 UTC, raulchen commented
CI is failing. But I don't see why that's related. Rerunning CI.

2019-06-14 10:42 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/1217/
Test FAILed.

2019-06-14 13:41 UTC, jovany-wang approved these changes

2019-06-16 03:45 UTC, raulchen commented
CI failure should be related. Can you take a look?

2019-07-07 14:42 UTC, jovany-wang commented
Any progress of this PR? 
NOTE: CI FAILED!

2019-10-08 19:21 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-10-10 03:41 UTC, jovany-wang requested changes

2019-10-10 03:41 UTC, jovany-wang commented on python/ray/services.py
> +        primary_redis_client.set("GCS_READY", 1)
Move this to node.py

2019-12-29 04:13 UTC, closed without merging