Reconstruct failed actors without sending tasks.
ray-project/ray pull request #5161
Opened 2019-07-10 14:00 UTC by raulchen

## What do these changes do?

Previously, we had to send a task to trigger the reconstruction of a failed actor. This has issues in some cases. For example, an actor that reading data from external DB will never receive tasks. This PR fixes this issue.

## Related issue number

## Linter

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.

2019-07-10 17:15 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/15279/
Test PASSed.

2019-07-10 20:38 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/1589/
Test FAILed.

2019-07-11 13:25 UTC, zhijunfu approved these changes
looks good to me. thanks

2019-07-11 18:16 UTC, stephanie-wang requested changes
Thanks, this looks good!

2019-07-11 18:16 UTC, stephanie-wang commented on python/ray/tests/utils.py
> +def wait_for_contition(condition_predictor,
```suggestion
def wait_for_condition(condition_predictor,
```

2019-07-11 18:16 UTC, stephanie-wang commented on python/ray/tests/utils.py
> +    """A helper function that wait until a conition is met.
```suggestion
    """A helper function that waits until a condition is met.
```

2019-07-12 04:03 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/1636/
Test FAILed.

2019-07-12 04:04 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/15328/
Test FAILed.

2019-07-12 06:50 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/15332/
Test FAILed.

2019-07-12 07:10 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/1640/
Test FAILed.

2019-07-12 07:38 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/1641/
Test FAILed.

2019-07-12 10:09 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/15333/
Test PASSed.

2019-07-12 18:55 UTC, stephanie-wang commented
Looks like the unit test that was added failed on one of the Travis runs: https://travis-ci.com/ray-project/ray/jobs/215417720. We should increase the timeout for that test.

2019-07-13 09:14 UTC, raulchen commented
thanks, increased to 5s

2019-07-13 11:55 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/15366/
Test PASSed.

2019-07-14 19:57 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-Perf-Integration-PRB/1670/
Test FAILed.

2019-07-15 05:07 UTC, raulchen commented
@stephanie-wang Tests have passed. Can you give a stamp?

2019-07-15 17:25 UTC, stephanie-wang approved these changes
Thanks! :)

2019-07-15 17:25 UTC, merged