Fixed link in tune that was not working
ray-project/ray pull request #5331
Opened 2019-07-31 11:27 UTC by lufol

## What do these changes do?
Fixed link leading to 404 page.

2019-07-31 14:23 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/15834/
Test PASSed.

2019-07-31 18:20 UTC, richardliaw approved these changes

2019-07-31 18:22 UTC, richardliaw commented on python/ray/tune/README.rst
> +To get started with Tune, try going through `our tutorial of using Tune with Keras <https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/tune_mnist_keras.py>`__.
```suggestion
To get started with Tune, try going through `our tutorial of using Tune with Keras <https://github.com/ray-project/tutorial/blob/master/tune_exercises/exercise_1_basics.ipynb>`__.
```

2019-07-31 18:22 UTC, richardliaw requested changes
Thanks for the fix! I think this is pointing to the wrong tutorial intended still.

2019-07-31 18:59 UTC, lufol commented
You are right!

2019-07-31 19:03 UTC, richardliaw approved these changes

2019-07-31 22:00 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/15843/
Test PASSed.

2019-07-31 22:13 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/15845/
Test PASSed.

2019-08-01 04:43 UTC, merged

2019-08-01 05:58 UTC, lufol commented
The error still persists on the doc page https://ray.readthedocs.io/en/latest/tune.html
Can someone also correct it there?