Refactor core worker context
ray-project/ray pull request #6034
Opened 2019-10-28 01:17 UTC by edoakes

## Why are these changes needed?

Simplifies the code.

## Related issue number

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

2019-10-28 01:18 UTC, edoakes commented
Depends on https://github.com/ray-project/ray/pull/6023.

2019-10-28 01:24 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-10-28 01:56 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/17956/
Test FAILed.

2019-10-28 22:58 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/17966/
Test FAILed.

2019-10-29 16:12 UTC, zhijunfu requested changes
Thanks. Currently `WorkerContext` is a relatively thin wrapper of `WorkerThreadContext`, while also maintains some information itself. While it's probably good to remove it, on the other side, the current changes make the various variables scattered in core worker, which makes it harder to maintain and more prone to errors. How about we have a `WorkerInfo` structure just to wrap the` job_id, actor_id` stuff and the logic to initialize & update them so they are still self contained? CoreWorker can still call the interface of `WorkerInfo` instead of embedding all the logic. What do you think?

2019-10-29 16:12 UTC, zhijunfu commented on src/ray/core_worker/core_worker.cc
> +      RAY_CHECK_OK(gcs_client_.Actors().AsyncUnsubscribe(handle.first, nullptr));
Could you please explain the logic here?

2019-10-29 16:12 UTC, zhijunfu commented on src/ray/core_worker/core_worker.cc
> +    RAY_CHECK(actor_id_ == task_spec.ActorId());
the if-else-if-else block above is getting a bit too complicated. Please consider extract them to a separate function?

2019-10-31 03:38 UTC, edoakes commented
@zhijunfu sorry this was a major WIP, should have labeled it. I am going to revisit this once a few outstanding PRs are in to avoid merge conflicts. Will consider the idea of a `WorkerInfo`, the logic for updating state is indeed getting a bit complex.

2019-10-31 12:51 UTC, zhijunfu commented
@edoakes I see, thanks for the clarifications

2019-11-14 22:58 UTC, closed without merging