Implement Persistent Actor
ray-project/ray pull request #6036
Opened 2019-10-28 19:06 UTC by simon-mo

This PR adds a new API for actor creation: `_remote(..., is_persistent=True`. This will make sure on a normal driver exit, the persistent actor will be kept alive.

2019-10-28 19:07 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-10-28 22:50 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/17963/
Test FAILed.

2019-10-28 23:14 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/17962/
Test FAILed.

2019-10-29 14:39 UTC, zhijunfu requested changes
seems to have a bug on variable initialization, others looks good. thanks.

2019-10-29 14:39 UTC, zhijunfu commented on src/ray/raylet/worker.h
> +  bool is_persistent_;
this is not initialized?

2019-10-30 22:58 UTC, pcmoritz commented on src/ray/raylet/worker.h
> +  bool is_detached_;
Let's call this `is_detached_actor_` and say in the documentation that this is only relevant for workers that are actors :)

2019-10-30 23:02 UTC, pcmoritz commented on src/ray/raylet/node_manager.cc
> +          // Then kill the worker process.
you should move this up one line again

2019-10-30 23:07 UTC, pcmoritz commented on python/ray/actor.py
> +            raise Exception("Detached actors must have associated name. "
How about `"Detached actors must be named. Please use..."`?

2019-10-30 23:07 UTC, pcmoritz commented on python/ray/actor.py
> +            detached: Whether the actor should be kept alive after driver exits
`.` at the end

2019-10-30 23:11 UTC, pcmoritz commented on python/ray/includes/common.pxd
> +            c_bool is_persistent)
`is_detached`?

2019-10-30 23:12 UTC, pcmoritz commented on python/ray/_raylet.pyx
> +                     is_persistent):
`is_detached`?

2019-10-30 23:13 UTC, pcmoritz commented on python/ray/_raylet.pyx
> +                     is_persistent):
You can actually say `c_bool is_detached` here and get rid of the `c_is_persistent` variable below.

2019-10-30 23:14 UTC, pcmoritz commented
This looks great, I left a few minor comments and can be merged after they are fixed :)

2019-10-30 23:41 UTC, simon-mo commented on src/ray/raylet/worker.h
> +  bool is_persistent_;
Resolved.

2019-10-31 00:24 UTC, pcmoritz approved these changes

2019-10-31 01:54 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/18000/
Test FAILed.

2019-10-31 02:38 UTC, zhijunfu approved these changes

2019-10-31 06:14 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/18012/
Test FAILed.

2019-10-31 06:15 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/18011/
Test FAILed.

2019-11-01 10:27 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/18048/
Test FAILed.

2019-11-01 14:22 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/18052/
Test FAILed.

2019-11-01 14:43 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/18051/
Test FAILed.

2019-11-01 17:28 UTC, merged

2019-11-15 09:27 UTC, raulchen commented
This feature is very useful. However, this API might have problems in some cases. 

Case 1:
```
# Driver code:
counter = Counter._remote(name="CounterActor", detached=True)
# Driver can't exit immediately here, because the actor creation task might not have been executed yet and could be cleaned up.
# Thus, we have to call a dummy method  to wait until the actor get created.
ray.get(counter.foo.remote())
```

Case 2:
```
counter = Counter._remote(name="CounterActor", detached=True)
ray.get(counter.foo.remote())
x = func.remote() # x is the return of a normal task.
counter.bar.remote(x) # `func` could get cleaned up as soon as driver exits. Then `counter.bar` will never run.
```

Thus, instead of making actors detached, I think it makes more sense simply **allow drivers to exit without cleanup**. Also, we need to expose an API to allow users to manually clean up the job afterwards. 

We've already implemented this in Ant's internal version. If you think this makes sense, we're glad to upstream this feature.

2019-11-15 22:31 UTC, simon-mo commented
@raulchen Detached actors are suppose to be used by libraries with extreme care. However, I agree that allowing drivers to exit without cleanup with also a valid option and I would be happy to see if it can be upstreamed. What would it look like? Would it be some parameters in `ray.init`? 

@stephanie-wang Would there be any object ownership concerns with a driver just exists without cleanup?

2019-11-18 22:31 UTC, stephanie-wang commented
We have control over the driver code, so why not just implement the driver so that it waits for detached actors/tasks to finish before exiting? Or, just use the detached flag for these tasks/actors to make sure that they don't get cleaned up while queued. I'm concerned about requiring applications to manually clean up their state; realistically applications are not going to do this correctly.

In the object ownership design, it should be okay, but it makes things much easier if we know at task/actor creation time that the task/actor is going to be "detached" (as @simon-mo did here for actors). Also, the first version would not have the ability to restart such tasks/actors.

2019-11-19 07:31 UTC, raulchen commented
> We have control over the driver code, so why not just implement the driver so that it waits for detached actors/tasks to finish before exiting? 

@stephanie-wang The problem is that not only the driver, actors could also submit normal tasks at any time. If the driver exits while the normal tasks are still being queued, those tasks will get lost. 

> Or, just use the detached flag for these tasks/actors to make sure that they don't get cleaned up while queued.

As mentioned above, sometimes it's uncertain when a normal task will be executed. That means, basically we need to add the "detached flag" to every normal task, which is inconvenient. Also, this will add extra complexities to scheduling queue code. 

@simon-mo Our current API for exiting driver without cleanup is `ray.shutdown(cleanup=False)`. We don't currently expose the API for manually killing a job yet, because all applications that need this feature are long running. So we simply shut down the cluster when the job is not needed. Does this also apply to ray serve? In the future, maybe we can allow users to kill their long running job by clicking a button on an admin web portal.