[tune] Stopgap for ray.get with timeout
ray-project/ray pull request #6097
Opened 2019-11-06 01:49 UTC by ujvl

## Why are these changes needed?

Reduce probability of slow `ray.get` from occurring during worker failures by waiting with a timeout first. If a failure occurs during the wait that's okay because we timeout.

This should be replaced by something like `ray.get(obj_id, timeout=timeout)`. 

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

2019-11-06 07:11 UTC, ericl commented
Instead of this how about we fix ray.get to include the timeout argument? This is already exposed in the C++ API.

cc @edoakes

2019-11-06 07:12 UTC, ericl requested changes
Please add the timeout parameter to the ray.get Python API instead of in tune. It's already supported in the core worker get interface.

2019-11-06 07:26 UTC, ericl commented
Actually why in the world is the get slow? I thought the timeout was on the order of 30 seconds...?

2019-11-06 09:52 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/18210/
Test PASSed.

2019-11-06 11:26 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/18212/
Test FAILed.

2019-11-06 12:19 UTC, ujvl commented
@ericl 

> Instead of this how about we fix ray.get to include the timeout argument? This is already exposed in the C++ API.

That was what we initially wanted to do but figured it would take longer to pass review. happy to have the timeout param exposed immediately instead

> Actually why in the world is the get slow? I thought the failure lease timeout was on the order of 30 seconds...?

this was just from empirical observation, took a "long" time but i could see it being ~30s. @richardliaw maybe we don't need to do this if thats the case since we want to set the timeout to 30s anyways?

in any case i think exposing the timeout param in ray.get would be useful.

2019-11-06 20:07 UTC, ujvl commented
Will create a PR later today that adds `timeout` to `ray.get`. This PR will be changed to use the new api

2019-11-14 20:15 UTC, ujvl commented
closing in favor of using `ray.get(id, timeout)` directly in #5877

2019-11-14 20:15 UTC, closed without merging