Build Docker Containers for Linux Wheels
ray-project/ray pull request #6233
Opened 2019-11-21 23:07 UTC by simon-mo

Note the limitation, we currently:
- Only build python 3.6 wheels
- CPU
- With a predefined set of requirements (mostly drawing from Tune's requirement)

2019-11-21 23:14 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-11-22 03:23 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/18703/
Test FAILed.

2019-11-24 09:42 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/18831/
Test FAILed.

2019-11-24 19:40 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/18839/
Test FAILed.

2019-11-24 23:16 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/18837/
Test PASSed.

2019-11-25 00:05 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/18844/
Test FAILed.

2019-11-25 04:49 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/18850/
Test PASSed.

2019-11-25 05:47 UTC, simon-mo commented
Example log here https://travis-ci.com/ray-project/ray/jobs/259983442#L241-L747

2019-11-25 07:41 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/18859/
Test FAILed.

2019-11-25 11:46 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/18867/
Test PASSed.

2019-11-25 20:12 UTC, edoakes requested changes
Can you make sure to run some tests using the autoscaler on k8s with an image you build using the script to make sure we have everything needed?

2019-11-25 20:12 UTC, edoakes commented on docker/autoscaler/requirements.txt
> +gym[atari]
+kubernetess, boto3

2019-11-25 20:12 UTC, edoakes commented on docker/autoscaler/Dockerfile
> +
let's also install curl, tmux, screen, rsync

2019-11-26 04:17 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/18898/
Test FAILed.

2019-11-26 21:37 UTC, edoakes approved these changes
LGTM please test as described above before merging

2019-11-28 01:05 UTC, simon-mo commented
Tested on autoscaler. With a minor fix (environment variable for click), it worked like a charm. Next step is to reduce the image size and support GPU, other version of python as well.

2019-11-28 01:05 UTC, merged