Consistent Name for Process Title
ray-project/ray pull request #6276
Opened 2019-11-25 20:47 UTC by simon-mo

Unify naming for process title to:
- `ray_worker::IDLE`
- `ray_worker::task_name()`
- `ray_actor::actor_name`
- `ray_actor::actor_name.method_name()`

This fix `ray stop` killing bazel processes because bazel test contains `ray_` in command line string.

2019-11-25 20:54 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-11-25 21:00 UTC, edoakes approved these changes
Let's wait to merge to be sure it fixes the tests

2019-11-25 21:13 UTC, ericl requested changes

2019-11-25 21:13 UTC, ericl commented on python/ray/_raylet.pyx
> +        next_title = "ray_actor::{}".format(class_name)
This unfortunately makes it too long to see in `top` most of the time. Can we keep it as just `ray_`?

2019-11-25 21:14 UTC, ericl commented on python/ray/_raylet.pyx
> +        title = "ray_worker::{}()".format(function_name)
Consider `ray::func()`

2019-11-25 21:14 UTC, ericl commented on python/ray/_raylet.pyx
> +        next_title = "ray_actor::{}".format(class_name)
Consider `ray::actor.method()`

2019-11-25 21:15 UTC, ericl commented on python/ray/worker.py
> +            setproctitle.setproctitle("ray_worker::IDLE")
By the way I think there are some unit tests that check the proc title that you have to fix.

2019-11-26 00:56 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/18903/
Test FAILed.

2019-11-26 02:12 UTC, ericl approved these changes
Lgtm if tests pass

2019-11-26 02:51 UTC, simon-mo commented
@ericl any clue why bazel is using python2.7 instead of conda here? /home/travis/miniconda/lib/python2.7/site-packages/_pytest/config/__init__.py:463: in _importconftest
350    raise ConftestImportFailure(conftestpath, sys.exc_info())
351E   ConftestImportFailure: (local('/home/travis/build/ray-project/ray/python/ray/tests/conftest.py'), (<class 'py._path.local.ImportMismatchError'>, ImportMismatchError('ray.tests.conftest', '/home/travis/.local/lib/python2.7/site-packages/ray-0.8.0.dev6-py2.7-linux-x86_64.egg/ray/tests/conftest.py', local('/home/travis/build/ray-project/ray/python/ray/tests/conftest.py')), <traceback object at 0x7f205efc4320>))

2019-11-26 03:03 UTC, ericl commented
Pull master, that was fixed recently.

2019-11-26 03:08 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/18897/
Test FAILed.

2019-11-26 12:25 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/18923/
Test PASSed.

2019-11-26 18:58 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/18936/
Test FAILed.

2019-11-26 19:56 UTC, merged