[tune] Added word-level language modeling RNN example on Wikitext-2.
ray-project/ray pull request #6352
Opened 2019-12-04 05:32 UTC by visatish

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

2019-12-04 05:32 UTC, visatish commented
@richardliaw

2019-12-04 05:37 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-12-04 06:33 UTC, richardliaw commented on python/ray/tune/examples/pbt_word_language_model_example.py
> +        **{
can you simplify this? (i.e., don't use the double asterisk)

2019-12-04 11:35 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19170/
Test FAILed.

2019-12-04 22:34 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19195/
Test PASSed.

2019-12-09 00:24 UTC, richardliaw requested changes
Can you see https://github.com/ray-project/ray/commit/9f2362041232df20110ed03c0d22ec51ef94edd8 as to how to add an example? 

A couple things to do:

1. add this to the documentation
2. add this to tests

2019-12-09 00:25 UTC, richardliaw commented on python/ray/tune/examples/pbt_word_language_model_example.py
> +        self.test = self.tokenize(os.path.join(path, 'test.txt'))
Also, can you make sure you do the linting?

https://ray.readthedocs.io/en/latest/tune-contrib.html

2020-09-21 23:33 UTC, closed without merging