[Java] Add java exception check in JNI
ray-project/ray pull request #6378
Opened 2019-12-06 08:09 UTC by kfstorm

## Why are these changes needed?

If `env->Call***Method(...)` throws any Java exception, we need to manually process it in JNI code. So we let it crash.
## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

2019-12-06 08:14 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-12-06 10:50 UTC, raulchen approved these changes

2019-12-06 10:51 UTC, raulchen requested changes
CI failure is related

2019-12-06 12:19 UTC, kfstorm commented
@raulchen I see Java test failed, but I can't repro at local. Maybe it's not caused by this PR. Let's see if it would still fail with my latest push.

2019-12-06 15:38 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19271/
Test PASSed.

2019-12-06 18:40 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19287/
Test PASSed.

2019-12-07 08:24 UTC, raulchen approved these changes

2019-12-07 08:25 UTC, merged