Fix bad checks and race condition from actor_deaths and node_failures tests
ray-project/ray pull request #6411
Opened 2019-12-10 03:26 UTC by ericl

## Why are these changes needed?

This ports bug fixes discovered while running the long-running ray ci tests.

2019-12-10 03:36 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-12-10 05:52 UTC, edoakes commented on src/ray/common/ray_config_def.h
> -RAY_CONFIG(int64_t, worker_heartbeat_timeout_milliseconds, 1000)
Actually we need these heartbeats even if we aren't sending any IDs to the raylet to ensure workers die when the raylet dies unexpectedly. See my change in https://github.com/ray-project/ray/pull/6412 instead.

2019-12-10 05:52 UTC, edoakes commented on src/ray/common/task/task.h
> +typedef std::function<void(const std::shared_ptr<void>, const std::string &, int, int,
This is getting complicated, can we add param names?

2019-12-10 05:52 UTC, edoakes commented on src/ray/core_worker/future_resolver.cc
> +        client_factory_({owner_address.ip_address(), owner_address.port(), -1}));
comment for the -1

2019-12-10 06:18 UTC, zhijunfu requested changes
We already support multiple workers in the same process (for java), and `pid` itself cannot identify a worker any more. 

How about we use `worker_id` instead of `pid`?

2019-12-10 06:19 UTC, zhijunfu commented on src/ray/protobuf/node_manager.proto
> +  int32 worker_pid = 2;
could we change to `worker_id` instead? since `pid` no longer identifies a worker with multi-threading.

2019-12-10 08:09 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19380/
Test PASSed.

2019-12-10 09:32 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19379/
Test FAILed.

2019-12-10 12:44 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19385/
Test FAILed.

2019-12-11 01:28 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19410/
Test FAILed.

2019-12-11 07:10 UTC, zhijunfu approved these changes
LGTM, thanks

2019-12-11 14:12 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19431/
Test FAILed.

2019-12-11 22:47 UTC, merged