[Serve] Added deadline awareness
ray-project/ray pull request #6442
Opened 2019-12-11 15:58 UTC by alindkhare

1. Added deadline awareness while enqueuing a query
2. Using Blist sorted-list implementation (ascending order) to get queries according to their specified deadlines. [buffer_queues]
3. Exposed slo_ms via handle/http request
4. Added slo example 
5. The queries in example will be executed in almost the opposite order of which they are fired
6. Added slo pytest
7. Added check for slo_ms to not be negative
8. Included the changes suggested

The reason for using Blist is - 

- pop operation should be O(1) (amortized) (helpful even for batched pop)
- There should not be significant overhead in maintaining the sorted list.
- The implementation is fast and uses C extensions. 

## Why are these changes needed?
Assigning deadline to every query is crucial from the client perspective 

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

2019-12-11 16:23 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-12-11 17:05 UTC, simon-mo commented
First iteration of the review done in https://github.com/alindkhare/ray/pull/2

2019-12-11 17:07 UTC, simon-mo commented
@alindkhare can you make sure to run `./scripts/format.sh` to pass the lint test.

2019-12-11 18:19 UTC, alindkhare commented
> @alindkhare can you make sure to run `./scripts/format.sh` to pass the lint test.

@simon-mo I have made the changes. The code seems to be passing the lint test

2019-12-11 20:50 UTC, simon-mo requested changes
Looks good. Few more comments and we can merge this.

2019-12-11 20:50 UTC, simon-mo commented on python/ray/experimental/serve/examples/echo_slo_reverse.py
> +Slo [reverse] example of ray.serve module
s/Slo/SLO

2019-12-11 20:50 UTC, simon-mo commented on python/ray/experimental/serve/queues.py
> +        # adding SLO (time taken to be completed)
```suggestion
        # Service level objective in milliseconds. This is expected to be the 
        # absolute time since unix epoch.
```

2019-12-11 20:50 UTC, simon-mo commented on python/ray/experimental/serve/queues.py
> +        # using blist sortedlist for deadline awareness
Can you add justification for blist here?

2019-12-11 20:52 UTC, simon-mo commented
The tests are failing because we forgot to install blist here https://github.com/ray-project/ray/blob/master/ci/travis/install-dependencies.sh

2019-12-11 22:01 UTC, alindkhare commented
> Looks good. Few more comments and we can merge this.

@simon-mo done!

2019-12-11 22:03 UTC, simon-mo approved these changes
Great work. Will merge when test passes.

2019-12-11 22:34 UTC, simon-mo commented
@alindkhare can you fix lint?
https://travis-ci.com/ray-project/ray/jobs/266238271

2019-12-11 23:20 UTC, simon-mo commented
🤦‍♂ need to add blist to https://github.com/ray-project/ray/blob/master/doc/requirements-doc.txt

2019-12-11 23:25 UTC, alindkhare commented
Done! 👍

2019-12-12 00:38 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19463/
Test FAILed.

2019-12-12 00:41 UTC, simon-mo commented
Lint+Serve tests passed. Merging.

2019-12-12 00:41 UTC, merged

2019-12-12 04:07 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19470/
Test FAILed.

2019-12-12 04:38 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19465/
Test PASSed.

2019-12-12 06:11 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19475/
Test FAILed.

2019-12-12 06:30 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19464/
Test FAILed.

2019-12-12 08:43 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19480/
Test FAILed.