[Serve] Adding BackendConfig
ray-project/ray pull request #6541
Opened 2019-12-19 06:52 UTC by alindkhare

1. Added BackendConfig
2. Added set_backend_config, get_backend_config
3. BackendConfig is saved in the persistent.
4. Router also has BackendConfig info
5. Added pytest and examples

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

2019-12-19 07:04 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2019-12-19 14:25 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19840/
Test PASSed.

2019-12-19 17:30 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19859/
Test FAILed.

2019-12-19 19:55 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19858/
Test PASSed.

2019-12-19 20:23 UTC, simon-mo requested changes

2019-12-19 20:23 UTC, simon-mo commented on python/ray/experimental/serve/api.py
> +    assert num_replicas >= 0, "Number of replicas must be greater than 1."
is this intentional? if so let's change the error message to say "greater than 0"

2019-12-19 20:23 UTC, simon-mo commented on python/ray/experimental/serve/context.py
> +batch_size = None
a new line is needed after this line

2019-12-19 20:23 UTC, simon-mo commented on python/ray/experimental/serve/context.py
> +# batch_size == `intval`  : the batch size of input list is equal to `intval`
batch_size (int): the batch...
https://sphinxcontrib-napoleon.readthedocs.io/

2019-12-19 20:23 UTC, simon-mo commented on python/ray/experimental/serve/global_state.py
> +    def start_actor_with_creator_kwargs(self, creator, kwargs, tag):
can you just modify `start_actor_with_creator` to accept kwargs

2019-12-19 20:23 UTC, simon-mo commented on python/ray/experimental/serve/queues.py
> +        logger.debug("Setting backend config for backend %s to %s", backend,
use "string".format(...)

2019-12-19 20:23 UTC, simon-mo commented on python/ray/experimental/serve/task_runner.py
> +        if type(work_item) is not list:
use `isinstance`

2019-12-19 20:23 UTC, simon-mo commented on python/ray/experimental/serve/task_runner.py
>  class TaskRunner:
I can see few ways to reduce the amount of repeated code in this section:
1. Move work_item -> args, kwargs transformation inside the work_item class. 
```python
args, kwargs = work_item.parse()
```
2. extract the invocation logic to separate function:
- `invoke_single`
- `invoke_batch`

3. raise error early. for example `Exception("Batched queries contain mixed context.")` can be raised earlier in the function.

2019-12-19 20:23 UTC, simon-mo commented on python/ray/experimental/serve/task_runner.py
> +                    raise Exception("Batched queries contain mixed context.")
Don't use bare exception, use RayServeException

2019-12-19 20:23 UTC, simon-mo commented on python/ray/experimental/serve/tests/test_api.py
> +    assert max(counter_result) < 20
how does this test batching?

2019-12-19 20:23 UTC, simon-mo commented on python/ray/experimental/serve/tests/test_api.py
> +    assert set(new_replica_tag_list) <= set(new_all_tag_list)
what does `<=` with `set` mean?

2019-12-19 20:31 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19866/
Test FAILed.

2019-12-19 21:41 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19863/
Test PASSed.

2019-12-19 23:57 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19868/
Test PASSed.

2019-12-20 00:21 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19867/
Test PASSed.

2019-12-20 02:33 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19882/
Test FAILed.

2019-12-20 21:08 UTC, simon-mo requested changes

2019-12-20 21:08 UTC, simon-mo commented on python/ray/experimental/serve/api.py
> +        creator = lambda x: TaskRunnerActor._remote(**x)  # noqa: E731
x -> kwargs

2019-12-20 21:08 UTC, simon-mo commented on python/ray/experimental/serve/api.py
> +    for serve_cfg in BackendConfig.serve_configs:
this should be a method inside BackendConfig like `def get_actor_creation_args`

2019-12-20 21:08 UTC, simon-mo commented on python/ray/experimental/serve/backend_config.py
> +        ret = "<{klass}({attrs})>".format(
this custom repr really necessary? can we just return the `str(self.__dict__())`?

2019-12-20 21:08 UTC, simon-mo commented on python/ray/experimental/serve/backend_config.py
> +        return json.dumps(self.__dict__)
do we really need custom `__str__` here?

2019-12-20 21:08 UTC, simon-mo commented on python/ray/experimental/serve/backend_config.py
> +    def _asdict(self):
`__dict__` should be sufficient right?

2019-12-20 21:08 UTC, simon-mo commented on python/ray/experimental/serve/backend_config.py
> +    def from_str(cls, json_string):
if this is for kv store can we put the logic inside kv store table?

2019-12-20 21:08 UTC, simon-mo commented on python/ray/experimental/serve/global_state.py
> +    def start_actor_with_creator(self, creator, kwargs, tag):
can we document what we expect the creator to do? before it was just a simple closure, now we actually need to be aware of its argument. 
```
Args:
    creator (Callable[Dict]): a closure that should return a newly crated actor handle when called with kwargs. The kwargs input is passed to `ActorCls_remote` method.
    ...
```

2019-12-21 03:12 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19923/
Test FAILed.

2019-12-21 03:30 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/19926/
Test FAILed.

2019-12-26 19:05 UTC, simon-mo reviewed
Great work we are almost there. One general comment I have is to add white space between code sections to make what each section does clearer. In particular `task_runner`.

2019-12-26 19:05 UTC, simon-mo commented on python/ray/experimental/serve/task_runner.py
> +            if not web_context:
Should we reverse this order of if else?
```
if is_web_context:
    ...
else: # python_context
    ...
```

2019-12-26 19:05 UTC, simon-mo commented on python/ray/experimental/serve/task_runner.py
> +        result_object_ids, context_list, arg_list = [], [], []
context_list -> context_flag_list

2019-12-26 19:05 UTC, simon-mo commented on python/ray/experimental/serve/task_runner.py
> +        result_object_ids, context_list, arg_list = [], [], []
flag indicate this is a list of boolean

2019-12-26 19:05 UTC, simon-mo commented on python/ray/experimental/serve/task_runner.py
> +            if not (all(context_list) or not any(context_list)):
`if set(context_list) != 1` is a bit clearer saying that we want unified context.

2019-12-26 19:05 UTC, simon-mo commented on python/ray/experimental/serve/task_runner.py
> +                                        "doesn't preserve batch-size.")
Great error message. Let's add one more sentence for actionable item:
> Please return a list of result with length equals to the batch size.

2019-12-26 20:42 UTC, alindkhare commented on python/ray/experimental/serve/queues.py
> +        self.backend_info = defaultdict()
It can be a normal dictionary!

2019-12-26 20:42 UTC, alindkhare commented on python/ray/experimental/serve/queues.py
> +                    max_batch_size = self.backend_info[backend][
Instead of 0,  it is assumed None.

2019-12-26 21:44 UTC, simon-mo commented on python/ray/experimental/serve/queues.py
> +        self.backend_info = defaultdict()
How about `defaultdict(lambda:dict(max_batch_size=None,...))` lambda so we are constructing new dictionary object each time.

2019-12-26 21:56 UTC, alindkhare commented on python/ray/experimental/serve/task_runner.py
> +                args = (FakeFlaskQuest(), )
Sure. Do you need  a list of FakeFlaskRequest() ?

2019-12-26 22:30 UTC, simon-mo commented on python/ray/experimental/serve/task_runner.py
> +                args = (FakeFlaskQuest(), )
Yes. For batching mode args need to be a list of FakeFlaskRequest consider the batch implementation. Even for args we should expect user to unpack them normally from a list.

2019-12-26 23:14 UTC, alindkhare commented on python/ray/experimental/serve/task_runner.py
> +                args = (FakeFlaskQuest(), )
If there is no web Context then flask request is useless right? why to create a list for that? When there is a web context, list of FlaskRequest is being send!

2019-12-26 23:15 UTC, alindkhare commented on python/ray/experimental/serve/queues.py
> +        self.backend_info = defaultdict()
Replaced it with a normal dict

2019-12-26 23:32 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/20062/
Test FAILed.

2019-12-26 23:43 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/20066/
Test FAILed.

2019-12-26 23:57 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/20068/
Test FAILed.

2019-12-27 00:02 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/20064/
Test FAILed.

2019-12-27 01:35 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/20074/
Test FAILed.

2019-12-27 01:46 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/20072/
Test FAILed.

2019-12-27 01:48 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/20071/
Test FAILed.

2019-12-27 01:48 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/20073/
Test FAILed.

2019-12-27 02:00 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/20076/
Test FAILed.

2019-12-27 06:02 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/20088/
Test FAILed.

2019-12-27 23:10 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/20103/
Test PASSed.

2019-12-28 05:33 UTC, simon-mo approved these changes

2019-12-28 05:34 UTC, merged

2019-12-28 08:42 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/20127/
Test PASSed.