[deploy][rps] models of resource provision service
ray-project/ray pull request #6714
Opened 2020-01-06 10:05 UTC by zeromem

## Why are these changes needed?

We plan to implement a Resource Provision Service (RPS) for Ray, you can read the design doc [here](https://docs.google.com/document/d/1Isx6I5dF2jRdNh9RVIRVmYb4Rd0QxOlAd_glq_l0eJo).

We have implemented a kubernetes operator for Ray (and has been merged #6328 ). As we know "Desired State Oriented" is an important core concept in Kubernetes, it means we need to interact with Kubernetes using declarative API, so we need a translator to translate user commands(from ray autoscaler or any other user client) to a desired ray cluster state.

In this plan, We will 
1. provide the abstraction / interface between Ray and different platforms like Kubernetes and Yarn. (This is what this Pull Request for).
2. provide a k8s-implementation.
3. adapt the ray-operator for the RPS.

## Related issue number

Merged #6328 
Merged #6501 

## Checks

- [*] I've run `scripts/format.sh` to lint the changes in this PR.
- [*] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

2020-01-06 10:13 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-01-06 10:27 UTC, caitengwei commented on deploy/java/ray-rps-k8s-impl/src/main/java/org/ray/deploy/rps/k8s/model/BaseCustomResource.java
> +    public static final String LABEL_POOL = "mandatory.k8s.alipay.com/app-logic-pool";
Is this label necessary?

2020-01-06 14:17 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/20437/
Test PASSed.

2020-01-06 14:28 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/20438/
Test FAILed.

2020-01-06 14:38 UTC, caitengwei requested changes
@zeromem Can you add a doc for RPS's API?

2020-01-06 14:38 UTC, caitengwei commented on deploy/java/ray-rps-model/src/main/java/org/ray/deploy/rps/model/Request.java
> + */
Pls remove these lines

2020-01-06 16:10 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/20440/
Test PASSed.

2020-01-07 11:24 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/20480/
Test PASSed.

2020-02-11 12:30 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/21735/
Test FAILed.

2020-06-24 06:59 UTC, richardliaw commented
OK I'm going to close this because there's no development activity. Others have mentioned to me that this would have been useful, but I think we need to resurface the discussion if we wanted to invest time on this.

2020-06-24 06:59 UTC, closed without merging

2020-06-24 06:59 UTC, richardliaw commented
Please open a new issue if you wish to discuss deployment.