Fix java bazel build
ray-project/ray pull request #6764
Opened 2020-01-10 09:49 UTC by chaokunyang

## Why are these changes needed?
* Make `bazel build //java:ray_java_pkg` generate maven deps so that users can develop java code using maven
* lint bazel

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

2020-01-10 09:53 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-01-10 10:22 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/20568/
Test FAILed.

2020-01-10 10:25 UTC, jovany-wang requested changes
Just add this line in `build.sh`:
```sh

 if [ "$RAY_BUILD_JAVA" == "YES" ]; then
   "$BAZEL_EXECUTABLE" build //java:ray_java_pkg --verbose_failures
+  "$BAZEL_EXECUTABLE" build //java:gen_maven_deps
 fi

 if [ "$RAY_BUILD_PYTHON" == "YES" ]; then
```

2020-01-10 10:48 UTC, chaokunyang commented
> Just add this line in `build.sh`:
> 
> ```shell
>  if [ "$RAY_BUILD_JAVA" == "YES" ]; then
>    "$BAZEL_EXECUTABLE" build //java:ray_java_pkg --verbose_failures
> +  "$BAZEL_EXECUTABLE" build //java:gen_maven_deps
>  fi
> 
>  if [ "$RAY_BUILD_PYTHON" == "YES" ]; then
> ```

`bazel build //java:ray_java_pkg ` is more consistent with `bazel build ray_pkg`.

2020-01-11 06:18 UTC, jovany-wang approved these changes
LGTM, Thanks.

2020-01-11 06:26 UTC, merged