[Java] Warp all exceptions in ObjectSerializer by ObjectDeserializingException
ray-project/ray pull request #7598
Opened 2020-03-13 12:05 UTC by lixin-wei

## Why are these changes needed?
When ray throw a RayWorkerException or RayActorException, it is hard to find which actor causing the problem. So I wrap a objectId to all exceptions in ObjectSerializer, it will help a lot for debuging.

## Related issue number

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

2020-03-13 12:06 UTC, lixin-wei commented
@jovany-wang @raulchen hi, could you please review this PR?

2020-03-13 12:07 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-03-13 12:12 UTC, raulchen commented on java/api/src/main/java/org/ray/api/exception/ObjectDeserializingException.java
> +public class ObjectDeserializingException extends RayException {
what about `ObjectDeserializationException`?

2020-03-13 12:15 UTC, lixin-wei commented on java/api/src/main/java/org/ray/api/exception/ObjectDeserializingException.java
> +public class ObjectDeserializingException extends RayException {
My mistake, fixed.

2020-03-13 12:22 UTC, raulchen approved these changes

2020-03-13 12:58 UTC, jovany-wang requested changes
The change you made in this PR is not correct.

We use `Arrays.equals(meta, TASK_EXECUTION_EXCEPTION_META)` to check if there's any exception instead of `throw`, so your `catch` would never be reached.

Let's return `new ObjectDeserializationException(objId, throwable)` directly:
```java
else if (Arrays.equals(meta, WORKER_EXCEPTION_META)) {
          return new ObjectDeserializationException(objId, new RayWorkerException());
}

```

2020-03-13 13:04 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/23146/
Test FAILed.

2020-03-13 13:15 UTC, lixin-wei commented
> The change you made in this PR is not correct.
> 
> We use `Arrays.equals(meta, TASK_EXECUTION_EXCEPTION_META)` to check if there's any exception instead of `throw`, so your `catch` would never be reached.
> 
> Let's return `new ObjectDeserializationException(objId, throwable)` directly:
> 
> ```java
> else if (Arrays.equals(meta, WORKER_EXCEPTION_META)) {
>           return new ObjectDeserializationException(objId, new RayWorkerException());
> }
> ```

I've fixed, thanks.

2020-03-13 13:27 UTC, jovany-wang commented on java/api/src/main/java/org/ray/api/exception/ObjectDeserializationException.java
> +public class ObjectDeserializationException extends RayException {
ObjectDeserializationException -> RayObjectDeserializationException

2020-03-13 13:32 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/23145/
Test PASSed.

2020-03-13 13:32 UTC, lixin-wei commented on java/api/src/main/java/org/ray/api/exception/ObjectDeserializationException.java
> +public class ObjectDeserializationException extends RayException {
done.

2020-03-13 13:50 UTC, jovany-wang approved these changes
LGTM

2020-03-13 14:31 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/23152/
Test PASSed.

2020-03-13 14:45 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/23153/
Test PASSed.

2020-03-14 06:56 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/23190/
Test FAILed.

2020-03-14 09:38 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/23192/
Test PASSed.

2020-03-14 10:42 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/23194/
Test PASSed.

2020-03-14 13:31 UTC, jovany-wang commented
Oops. It seems not reasonable to throw such exception when `get`.

Because if something went wrong of the task, `get` should throw the meaningful exception to indicate the reason instead of `DeserializationException`.

2020-03-14 13:33 UTC, jovany-wang commented
Maybe it's best to catch the exception and print the `objectId` on the user side.

2020-03-14 14:15 UTC, lixin-wei commented
> Oops. It seems not reasonable to throw such exception when `get`.
> 
> Because if something went wrong of the task, `get` should throw the meaningful exception to indicate the reason instead of `DeserializationException`.

DeserializationException do have a meaningful cause exception, user can see what exactly the root cause is. I don't think user will be confused.
@raulchen how do you think about this?

2020-03-14 14:34 UTC, jovany-wang commented
> > Oops. It seems not reasonable to throw such exception when `get`.
> > Because if something went wrong of the task, `get` should throw the meaningful exception to indicate the reason instead of `DeserializationException`.
> 
> DeserializationException do have a meaningful cause exception, user can see what exactly the root cause is. I don't think user will be confused.
> @raulchen how do you think about this?

After this PR, how do users write the following code?
```java

future = Ray.call();
try {
    future.get();
} catch (RayActorException e) {
    // handle actor dead case.
} catch (RayTaskException e) {
   // handle UDF failure case.
}
```

This is too weird I think:
```java
try {
    future.get();
} catch (RayObjectDeserializationException e) {
    if (e.getCauseException() instance of RayActorException) {
        // handle actor dead case.
    } else if (e.getCauseException() instance of RayTaskException) {
       // handle UDF failure case.    
    }
}
```

2020-03-25 04:33 UTC, raulchen commented
I think @jovany-wang's point makes sense. 
Let's just log the object id, and still throw the original exceptions.
@fryrestone is working on cross-language exception serialization. When that is done, we can put more meaningful information in the exception message.

2020-06-19 07:16 UTC, closed without merging