[docs] Add documentation for reference counting and 'ray memory'
ray-project/ray pull request #7661
Opened 2020-03-19 17:10 UTC by edoakes

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

2020-03-19 17:17 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-03-19 19:26 UTC, richardliaw commented on doc/source/memory-management.rst
> +
Getting the following errors - 

you should probably put this in a code-block.

```
/Users/rliaw/Research/riselab/ray/doc/source/memory-management.rst:33: WARNING: Title overline & underline mismatch.

-----------------------------------------------------------------------------------------------------
Object ID                                Reference Type       Object Size   Reference Creation Site
=====================================================================================================
/Users/rliaw/Research/riselab/ray/doc/source/memory-management.rst:62: WARNING: Title overline & underline mismatch.

-----------------------------------------------------------------------------------------------------
Object ID                                Reference Type       Object Size   Reference Creation Site
=====================================================================================================
/Users/rliaw/Research/riselab/ray/doc/source/memory-management.rst:86: WARNING: Title overline & underline mismatch.

-----------------------------------------------------------------------------------------------------
Object ID                                Reference Type       Object Size   Reference Creation Site
=====================================================================================================
/Users/rliaw/Research/riselab/ray/doc/source/memory-management.rst:112: WARNING: Title overline & underline mismatch.

-----------------------------------------------------------------------------------------------------
Object ID                                Reference Type       Object Size   Reference Creation Site
=====================================================================================================
/Users/rliaw/Research/riselab/ray/doc/source/memory-management.rst:133: WARNING: Title overline & underline mismatch.

-----------------------------------------------------------------------------------------------------
Object ID                                Reference Type       Object Size   Reference Creation Site
=====================================================================================================

2020-03-19 20:04 UTC, ericl approved these changes
Very nice.

2020-03-19 20:06 UTC, richardliaw requested changes
Can you fix rendering first?

2020-03-19 20:11 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/23385/
Test FAILed.

2020-03-20 15:25 UTC, edoakes commented on doc/source/memory-management.rst
> +In previous versions of Ray, there was no reference counting and instead objects in the object store were LRU evicted once the object store ran out of space. Some applications (e.g., applications tha
Good idea!

2020-03-20 18:01 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/23446/
Test PASSed.

2020-03-20 18:05 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/23444/
Test PASSed.

2020-03-20 19:43 UTC, richardliaw approved these changes
Pushed a lint fix - looks great!

Suspect the Jupyter notebook use case is going to be a big problem.

2020-03-20 20:47 UTC, merged

2020-03-20 21:26 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/23455/
Test PASSed.