[Parallel Iterators] Batching + Pipelining optimizations
ray-project/ray pull request #7931
Opened 2020-04-08 02:08 UTC by amogkam

## Why are these changes needed?
Adds optimizations to Parallel Iterators to improve throughput and.
* Adds internal batching for `gather_async`, `get_shard`, and `repartition` to reduce number of remote calls.
* Adds pipelining to `get_shard`.
* Fixes `StopIteration` error in `duplicate`
* Renames `async_queue_depth` in `gather_async` to `pipeline_queue_depth`

## Related issue number

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

2020-04-08 02:10 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-04-08 03:03 UTC, wuisawesome commented on python/ray/util/iter.py
> +                Increasing batch_time reduces latency but improves throughput.
I think you mean increases latency? 

Decreasing latency and improving throughput sounds great :)

2020-04-08 03:38 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/24376/
Test FAILed.

2020-04-08 07:51 UTC, ericl commented
Any benchmark results? Would be great to check in tests with reference results for future comparison.

2020-04-08 18:54 UTC, ericl requested changes

2020-04-08 18:54 UTC, ericl commented on python/ray/util/iter.py
> +                    batch_time: int = 10) -> "ParallelIterator[T]":
Consider `batch_ms`

2020-04-08 18:54 UTC, ericl commented on python/ray/util/iter.py
> +                     pipeline_queue_depth: int = 1) -> "LocalIterator[T]":
Consider `num_async_requests` instead of pipeline_queue_depth.

2020-04-08 18:54 UTC, ericl commented on python/ray/util/iter.py
> +                  pipeline_queue_depth: int = 1) -> "LocalIterator[T]":
Consider `num_async_requests`.

2020-05-20 21:45 UTC, ericl reviewed
I think we should go ahead and merge this, but with batching off by default (so no change to the existing code path). @amogkam can you make that change?

2020-05-20 21:54 UTC, amogkam commented
@ericl most recent commit sets `batch_ms` to 0 by default

2020-05-20 22:57 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/26156/
Test PASSed.

2020-05-20 23:55 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/26157/
Test PASSed.

2020-05-26 07:37 UTC, ericl approved these changes

2020-05-26 07:37 UTC, merged