[rllib] [RFC] Variable-length list space prototype
ray-project/ray pull request #8393
Opened 2020-05-10 23:28 UTC by ericl

## Why are these changes needed?

Support variable length struct spaces as an extra gym space. The decoding is handled similar to the batch format of tf.StructuredTensor:

![image](https://user-images.githubusercontent.com/14922/81513179-3a30ef00-92db-11ea-9cd9-dcd02c421f8b.png)

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

2020-05-10 23:34 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-05-11 00:41 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/25750/
Test PASSed.

2020-05-11 01:00 UTC, ericl commented on rllib/models/list_batch.py
> +
How to implement unbatch()?

2020-05-11 01:13 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/25751/
Test PASSed.

2020-05-11 02:07 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/25753/
Test PASSed.

2020-05-11 04:37 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/25752/
Test FAILed.

2020-05-11 05:07 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/25757/
Test PASSed.

2020-05-11 09:26 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/25755/
Test FAILed.

2020-05-11 19:56 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/25782/
Test PASSed.

2020-05-19 00:03 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/26066/
Test PASSed.

2020-05-19 01:36 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/26068/
Test PASSed.

2020-05-19 04:15 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/26075/
Test PASSed.

2020-05-27 09:19 UTC, sven1977 commented
@ericl is this ready for review?

2020-05-27 20:04 UTC, ericl commented
It needs some tests, I'll add that next week.

2020-06-02 05:06 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/26617/
Test PASSed.

2020-06-02 08:39 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/26616/
Test PASSed.

2020-06-02 18:54 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/26659/
Test FAILed.

2020-06-03 20:20 UTC, sven1977 requested changes

2020-06-03 20:35 UTC, ericl commented on doc/source/rllib-models.rst
> +RLlib supports complex and variable-length observation spaces, including ``gym.spaces.Tuple``, ``gym.spaces.Dict``, and ``rllib.models.extra_spaces.Repeated``. The handling of these spaces is transpa
Do you mean we should move it out of extra_spaces? I think we should stick with extra spaces for now since that's where the other extra ones are.

2020-06-03 20:35 UTC, ericl commented on rllib/examples/complex_struct_space.py
> +class SimpleRPG(gym.Env):
Done

2020-06-03 20:35 UTC, ericl commented on rllib/examples/complex_struct_space.py
> +class CustomTorchRPGModel(TorchModelV2, nn.Module):
Done

2020-06-03 23:43 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/26719/
Test PASSed.

2020-06-04 07:04 UTC, sven1977 commented on doc/source/rllib-models.rst
> +RLlib supports complex and variable-length observation spaces, including ``gym.spaces.Tuple``, ``gym.spaces.Dict``, and ``rllib.models.extra_spaces.Repeated``. The handling of these spaces is transpa
Yeah, I meant to move Repeated and Simplex into `utils.spaces.simplex/repeated.py`.
I thought, I did this already on a separate PR a week ago or so.
https://github.com/ray-project/ray/pull/8608

2020-06-04 07:06 UTC, sven1977 commented on doc/source/rllib-models.rst
> +RLlib supports complex and variable-length observation spaces, including ``gym.spaces.Tuple``, ``gym.spaces.Dict``, and ``rllib.models.extra_spaces.Repeated``. The handling of these spaces is transpa
There is only Simplex and it has been moved in this PR already to `utils/spaces/simplex.py`.
https://github.com/ray-project/ray/pull/8608

2020-06-05 20:07 UTC, ericl commented
Moved it.

2020-06-05 21:30 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/26810/
Test FAILed.

2020-06-06 02:22 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/26821/
Test PASSed.

2020-06-06 10:20 UTC, sven1977 approved these changes
:+1: Super cool to have this new Space. Thanks.

2020-06-06 10:22 UTC, merged