[rllib] Set framework to tf by default
ray-project/ray pull request #8748
Opened 2020-06-02 18:24 UTC by ericl

## Why are these changes needed?

Setting the framework to auto is making an important config option nondeterministic depending on the environment. This could harm reproducibility, so set the default to "tf" as it was before. We retain "auto" as an explicit opt-in.

2020-06-02 18:30 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-06-02 20:05 UTC, sven1977 requested changes

2020-06-02 20:05 UTC, sven1977 commented on rllib/agents/trainer.py
>      # auto: "torch" if only PyTorch installed, "tf" otherwise.
```suggestion
    # auto: "torch" if only PyTorch installed, "tf" if only TensorFlow installed, error otherwise.
```

2020-06-02 21:15 UTC, sven1977 approved these changes

2020-06-02 21:44 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/26671/
Test FAILed.

2020-06-02 23:22 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/26655/
Test PASSed.

2020-06-02 23:24 UTC, ericl commented
After thinking about it more, I think we should remove the checks entirely. There's no need to raise an import error since that will naturally arise anyways.

2020-06-03 01:22 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/26674/
Test PASSed.

2020-06-03 06:34 UTC, KristianHolsheimer commented on rllib/utils/test_utils.py
> +            Allowed are: "tf", "tfe", and "torch".
Are other frameworks disallowed? If not, perhaps we could rephrase this as
```python
# Supported options are: "tf", "tfe", and "torch"
```

2020-06-04 03:20 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/26730/
Test PASSed.

2020-06-04 22:42 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/26757/
Test PASSed.

2020-06-06 02:18 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/26820/
Test PASSed.

2020-06-09 06:04 UTC, merged