Add unsubscribe before re-subscribe when gcs server restarts
ray-project/ray pull request #8835
Opened 2020-06-08 12:42 UTC by ffbin

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

2020-06-08 12:42 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-06-08 14:25 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/26871/
Test PASSed.

2020-06-08 14:30 UTC, raulchen approved these changes

2020-06-08 15:16 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/26872/
Test PASSed.

2020-06-08 18:13 UTC, stephanie-wang requested changes
It's not going to work to call Unsubscribe directly when reconnecting to the GCS since this just adds the command to the queue. If there are other commands in the queue at the time, you could end up triggering the fatal check still, or you could mess up application logic.

I would suggest instead that we have an explicit Resubscribe/Reconnect method for the pubsub class that resets the state of all channels as necessary. I haven't thought through the logic much, but this should involve something like resetting the callback index to -1, sending another SUBSCRIBE command, etc.

Also, I cannot stress this enough: **this must have unit tests**. Especially for something like fault tolerance. The minimum for merging this PR is:
1. Mocking out Redis so that the unit test does not depend on the timing of when the Redis server is restarted.
2. Unit tests for restarting the Redis server at different times and under different scenarios. Minimum set for pubsub should cover a matrix of these cases:
- Restart when subscribed vs unsubscribed
- Restart when there is an in-flight command vs no in-flight command.
- Restart when there are no commands queued vs commands queued.

It's fine to keep the current tests that depend on Redis, but let's be clear that these are integration tests. **The purpose of the integration test is not to check our pubsub functionality**; it is only meant to confirm that Redis behaves according to the semantics mocked in the unit tests.

2020-06-09 02:53 UTC, ffbin commented
@stephanie-wang Thank you for your suggestion. Currently, GCS storage and pub sub use the same redis, so i need to separate them first, otherwise I can't test the scenario of restarting redis. If redis is restarted, we may need to create a new GcsPubSub, because it needs a new redis client. If it's just GCS server restart, I try not to subscribe anymore.

2020-06-19 02:03 UTC, closed without merging

2020-06-19 02:04 UTC, ffbin commented
This pr is not needed, because we have optimized the implementation of resubscribe.