[autoscaler] Run ray stop on cluster before tearing it down
ray-project/ray pull request #8922
Opened 2020-06-13 01:36 UTC by allenyin55

## Why are these changes needed?
This PR resolves a race condition when tearing down a cluster. While the cluster is stopping, Ray could still be running on the head node. It sees that the worker nodes are being shut down and create a new set of worker nodes, which will be leaked.

This PR runs `ray stop` on the cluster before the teardown so that ray will not be running when head node is stopping. 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

2020-06-13 01:43 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-06-13 03:38 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/27103/
Test PASSed.

2020-06-13 04:11 UTC, richardliaw requested changes
Hey @allenyin55  --

There are two use cases for ray down -- either you want to remove extraneous workers, or you want to teardown the entire cluster. 

In the case where you want to remove extraneous workers, this actually breaks existing behavior. In the case where you want to tear down the entire cluster, the head node is already terminated first, so this PR doesn't change the behavior.

What is the justification for this PR? Is there a reproducible script?

2020-06-16 02:41 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/27191/
Test FAILed.

2020-06-16 03:00 UTC, allenyin55 commented
Hi @richardliaw --

Got it. I made the change to only run `ray stop` when the user is trying to tear down the entire cluster.

The below shell script will reproduce the problem. The script creates a ray cluster and shuts it down soon after. The expected outcome of this script is that the whole cluster will be shut down. The actual outcome is that the original cluster will be shut down, but 2 new workers will be created.

```bash
ray up cluster.yaml -y
sleep 3
ray down cluster.yaml -y
```

cluster.yaml
```yaml
cluster_name: repro_cluster

min_workers: 2
max_workers: 2

provider:
    type: aws
    region: us-west-2
    availability_zone: us-west-2a

auth:
    ssh_user: ubuntu
```

2020-06-20 01:39 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/27359/
Test PASSed.

2020-06-20 02:05 UTC, richardliaw approved these changes

2020-06-21 00:02 UTC, merged