Refactor #8792 to integrate latest master
ray-project/ray pull request #8956
Opened 2020-06-16 00:56 UTC by jsuarez5341

This PR adds batched compute_actions for MA inference and the FlexDict extra space for complex observations/actions. Details provided in #8792; this PR simply refactors to base off of the latest master

@sven1977 Could you take a look at this?

2020-06-16 00:59 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-06-16 04:21 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/27190/
Test PASSed.

2020-06-16 06:26 UTC, sven1977 requested changes

2020-06-16 06:26 UTC, sven1977 commented on rllib/utils/spaces/space_utils.py
> +        elif isinstance(space_, Dict) or isinstance(space_, FlexDict):
```suggestion
        elif isinstance(space_, (Dict, FlexDict)):
```

2020-06-16 06:26 UTC, sven1977 commented on rllib/agents/trainer.py
> +    def compute_actions(self,
Could we also deprecate `compute_action` and rename it into `compute_single_action`. Just add a `deprecation_warning("compute_action", "compute_single_action")` call at the beginning of `compute_action` and then return the results of `compute_single_action` from within there.

2020-06-16 06:26 UTC, sven1977 commented on rllib/utils/spaces/flexdict.py
> +      err = 'Values of the dict should be instances of gym.Space'
This would make it impossible to have a `FlexDict` of `FlexDicts`, no?

2020-06-16 19:47 UTC, jsuarez5341 commented on rllib/utils/spaces/space_utils.py
> +        elif isinstance(space_, Dict) or isinstance(space_, FlexDict):
Didn't know isinstance could take a tuple -- thanks!@

2020-06-16 22:19 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/27225/
Test PASSed.

2020-06-17 06:34 UTC, sven1977 commented on rllib/agents/trainer.py
> +    def compute_actions(self,
Actually, this is fine. We can do this quickly in a separate PR.

2020-06-17 06:53 UTC, sven1977 approved these changes
Thanks for the PR @jsuarez5341 .
Looks all good!

2020-06-17 06:55 UTC, sven1977 commented on rllib/utils/spaces/flexdict.py
> +        return dict([(k, space.sample()) for k, space in self.spaces.items()])
```suggestion
        return {k: space.sample() for k, space in self.spaces.items()}
```

2020-06-17 06:58 UTC, jsuarez5341 commented on rllib/utils/spaces/flexdict.py
> +        return dict([(k, space.sample()) for k, space in self.spaces.items()])
Fixed

2020-06-17 08:36 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/27247/
Test PASSed.

2020-06-17 08:55 UTC, merged

2020-06-17 09:30 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/27248/
Test PASSed.