[RLLib] WindowStat bug fix
ray-project/ray pull request #9213
Opened 2020-06-30 17:08 UTC by 09wakharet

## Why are these changes needed?

## Related issue number

## Checks

- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [X] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

2020-06-30 17:11 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-06-30 17:26 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/27701/
Test FAILed.

2020-07-02 09:26 UTC, michaelzhiluo requested changes

2020-07-04 05:20 UTC, michaelzhiluo approved these changes

2020-07-06 02:57 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/27877/
Test PASSed.

2020-07-12 21:01 UTC, sven1977 approved these changes
lgtm

2020-07-12 21:01 UTC, merged