[rllib] AttentionNet fixes
ray-project/ray pull request #9406
Opened 2020-07-10 15:45 UTC by 09wakharet

## Why are these changes needed?

Fixes a batching error in Torch AttentionNet

## Related issue number

## Checks

- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [X] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [X] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

2020-07-10 15:52 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-07-10 21:50 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/28181/
Test FAILed.

2020-07-12 21:05 UTC, sven1977 approved these changes
lgtm.
Thanks for the fix.

2020-07-12 21:06 UTC, sven1977 requested changes
Sorry, one more thing. The test_attention_net test still seems to fail. Could you check?
Thanks.

2020-08-09 19:53 UTC, closed without merging

2020-09-03 02:21 UTC, zzcNEU commented
> ## 为什么需要这些更改？
> 修复了Torch AttentionNet中的批处理错误
> 
> ## 相关问题编号
> ## 支票
> * [x] 我已经`scripts/format.sh`设法使此公关中的更改不完整。
> * [x] 我已经包含了https://docs.ray.io/en/latest/所需的所有文档更改。
> * [ ] 我确保测试通过。请注意，可能会有一些不稳定的测试，请参阅[https://ray-travis-tracker.herokuapp.com/上](https://ray-travis-tracker.herokuapp.com/)的近期失败率。
> * 测试策略
>   
>   * [x]  单元测试
>   * [ ]  发布测试
>   * [ ]  此公关未经测试（请在下面说明）

Hello, I find you are the author of attention net. Can you teach me how use it? Maybe an examples?