[Core] enable put small object in memory store
ray-project/ray pull request #9452
Opened 2020-07-13 19:03 UTC by zhuohan123

## Why are these changes needed?

Previously we disabled putting small objects into the memory store by default. We turn this on by default in this PR.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

2020-07-13 19:06 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-07-13 19:06 UTC, rkooo567 commented
cc @raulchen

2020-07-13 19:13 UTC, suquark approved these changes
LGTM. We should merge after all related tests pass.

2020-07-13 21:23 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/28275/
Test FAILed.

2020-07-14 08:04 UTC, suquark commented
@zhuohan123 could you have a review that whether there are related CI failures?

2020-07-17 19:46 UTC, suquark commented
@zhuohan123 could you update this PR?

2020-07-17 21:22 UTC, suquark requested changes

2020-07-17 21:22 UTC, suquark commented on src/ray/common/ray_config_def.h
> +RAY_CONFIG(uint32_t, max_tasks_in_flight_per_worker, 1)
don't remove the last empty line

2020-07-17 21:27 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/28564/
Test FAILed.

2020-07-17 23:35 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/28567/
Test PASSed.

2020-07-20 06:35 UTC, raulchen commented
Hi @zhuohan123 @suquark , do you know what are missing in Java to turn this flag on?

2020-07-21 06:49 UTC, zhuohan123 commented
> Hi @zhuohan123 @suquark , do you know what are missing in Java to turn this flag on?

Some Java tests are failing when we turn this flag on, so we turn this off temporarily to pass the tests. I will take a look later to fix the Java tests.

In general, turning this flag on will cause some memory limits tests to fail. For example if we set the memory limit to 10M and put a 10M object. If now we put a very small object like a string "HI", previously there will be an OOM error, but now since the string will be put into the memory store, the OOM error will not exist anymore. I'm not sure whether there are these kinds of tests in Java for now but will check later.

2020-07-21 16:48 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/28693/
Test FAILed.

2020-07-28 18:48 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29057/
Test FAILed.

2020-07-29 20:53 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29132/
Test FAILed.

2020-09-21 23:36 UTC, closed without merging