Revert "Get rid of build shell scripts and move them to Python (#6082)"
ray-project/ray pull request #9599
Opened 2020-07-20 22:14 UTC by ericl

This reverts commit ac39e23145336fa7d450dd170e3e12ffc3d72d83.

I had to also reset setup.py manually to prior to that commit.

## Why are these changes needed?

The linux build is broken after this change
```
> sudo python setup.py develop
running build_ext
    error: [Errno 2] No such file or directory: 'bazel': 'bazel'
```
## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

2020-07-20 22:16 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-07-20 22:18 UTC, robertnishihara commented
Regarding

`    error: [Errno 2] No such file or directory: 'bazel': 'bazel'`

I've seen it on Mac as well.

2020-07-20 22:29 UTC, mehrdadn requested changes
I think this is already being handled in #9590. Please check to see if it's fixed there.

2020-07-20 22:42 UTC, edoakes approved these changes

2020-07-21 06:26 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/28672/
Test FAILed.

2020-07-22 01:52 UTC, closed without merging