[Core] Preliminary implementation of ownership-based object directory
ray-project/ray pull request #9735
Opened 2020-07-27 21:20 UTC by zhuohan123

## Why are these changes needed?

We move the object directory from the GCS to the owner's core_worker of an object, which is a bottleneck for Ray performance.

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

2020-07-27 21:26 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-07-28 03:24 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29016/
Test FAILed.

2020-07-28 04:55 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29018/
Test FAILed.

2020-07-28 15:25 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29047/
Test FAILed.

2020-07-28 18:09 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29055/
Test FAILed.

2020-07-29 01:59 UTC, ericl requested changes
A few comment on the directory implementation. Beyond that, we should make sure all tests pass with the flag off before merging.

2020-07-29 01:59 UTC, ericl commented on src/ray/common/ray_config_def.h
> +RAY_CONFIG(bool, ownership_based_object_directory_enabled, true)
Set this to False by default.

2020-07-29 01:59 UTC, ericl commented on src/ray/core_worker/reference_count.h
> +  void AddObjectLocation(const ObjectID &object_id, const ClientID &node_id);
Document these

2020-07-29 01:59 UTC, ericl commented on src/ray/object_manager/ownership_based_object_directory.h
> +  absl::flat_hash_map<WorkerID, std::pair<std::unique_ptr<rpc::CoreWorkerClient>, size_t>>
Add some comments for these.

2020-07-29 01:59 UTC, ericl commented on src/ray/object_manager/ownership_based_object_directory.cc
> +  RAY_CHECK_OK(worker_it->second.first->GetObjectLocationsOwner(
This is infinite polling right loop? Add a TODO to fix this.

2020-07-29 01:59 UTC, ericl commented on src/ray/object_manager/ownership_based_object_directory.cc
> +        if (--worker_rpc_clients_[worker_id].second == 0) {
Let's just keep the clients forever for now. This will be fixed with @barakmich 's connection pooling in the future.

2020-07-29 01:59 UTC, ericl commented on src/ray/object_manager/ownership_based_object_directory.cc
> +  }
Pull out this into a `GetClient()` utility method.

2020-07-29 01:59 UTC, ericl commented on src/ray/object_manager/ownership_based_object_directory.cc
> +/// object table entries up to but not including this notification.
Is it possible to inherit from the base object directory so we don't need to copy paste these methods?

2020-07-29 05:13 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29084/
Test FAILed.

2020-07-29 17:15 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29121/
Test FAILed.

2020-07-29 20:44 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29130/
Test FAILed.

2020-08-01 09:05 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29262/
Test FAILed.

2020-08-03 05:19 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29291/
Test FAILed.

2020-08-03 19:47 UTC, ericl commented
@zhuohan123 please make sure you address all the review comments.

2020-08-04 01:27 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29314/
Test FAILed.

2020-08-04 03:51 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29324/
Test FAILed.

2020-08-04 06:33 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29356/
Test FAILed.

2020-08-04 11:55 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29352/
Test FAILed.

2020-08-04 18:42 UTC, ericl approved these changes
Looks good. The only missing thing is unit tests for the ownership based object directory, but we can do that in another PR.

2020-08-04 18:44 UTC, ericl commented
It looks like tests are failing to compile here: https://travis-ci.com/github/ray-project/ray/jobs/368136571

Can you make sure Travis CI / LINT are ok?

2020-08-04 19:55 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29399/
Test FAILed.

2020-08-04 22:34 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29406/
Test FAILed.

2020-08-05 06:06 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29425/
Test FAILed.

2020-08-05 06:21 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29426/
Test FAILed.

2020-08-05 06:24 UTC, zhuohan123 commented
@ericl I believe all the tests are fixed now. If the latest travis result looks good, we can merge this PR to the master.

2020-08-05 23:24 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29468/
Test FAILed.

2020-08-06 01:08 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29476/
Test FAILed.

2020-08-06 01:23 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29478/
Test FAILed.

2020-08-06 06:30 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29487/
Test FAILed.

2020-08-07 01:32 UTC, ericl commented
More conflicts.

2020-08-07 20:29 UTC, ericl commented
@zhuohan123

2020-08-10 20:32 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29685/
Test FAILed.

2020-08-11 01:19 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29701/
Test FAILed.

2020-08-11 22:04 UTC, merged

2021-01-19 02:24 UTC, kfstorm commented
Hi guys, why does "object_manager" need to depend on "core_worker_lib"? It doesn't make sense to me.

2021-01-24 00:32 UTC, rkooo567 commented
^ +1 Based on the change, it seems unnecessary. @ericl do you know why? Can we remove it?