[Core] Fix test_logging_to_driver
ray-project/ray pull request #9829
Opened 2020-07-30 22:31 UTC by wuisawesome

## Why are these changes needed?

Fixes test_logging_to_driver

## Related issue number

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

2020-07-30 22:37 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2020-07-30 23:00 UTC, rkooo567 approved these changes

2020-07-31 00:31 UTC, ericl approved these changes

2020-07-31 00:32 UTC, ericl commented
This does'nt seem to be passing test_advanced_3: https://travis-ci.com/github/ray-project/ray/jobs/366875360

2020-07-31 00:32 UTC, ericl requested changes
::test_not_logging_to_driver FAILED                                      [ 19%]

2020-07-31 08:00 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29196/
Test FAILed.

2020-08-01 01:12 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/29240/
Test FAILed.

2020-08-03 19:52 UTC, ericl approved these changes

2020-08-03 19:52 UTC, merged